### ISSUE TITLE
[suggestion] remove gregtech from the pack

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/ATM-9#1002]
sure you can say "then just don't use it", but it seems (I'm not a mod developer) that gregtech has caused a lot of problems/inconveniences so far. be it ore generation or recipe conflicts. also from experience that everyone in the communities I'm in avoids modpacks with gregtech. iIn my opinion, this mod is too complex for a “kitchen sink” pack. endgame is all well and good, but how many create a star, which requires almost 18 hours of crafting time. especially those who have no opportunity to play the pack on a server and the process continues when you are not online.

maybe you could do a vote (discord). then you can see how the community thinks about it and whether the effort is even necessary or whether it will be appreciated.

**Comment by spacesailormarie** [comment]
lmfao

**Comment by planetme** [comment]
lmfao

**Comment by trainvoi** [comment]
rofl

**Comment by SuperObamaByte** [comment]
ungreggy

**Comment by ZombieZilla** [comment]
:trollface:
