### ISSUE TITLE
Curse Forge server pack dosn't have updated configs

### ISSUE THREAD

**Issue by CSMaybee** [AllTheMods/ATM-9#1007]
I am experiencing issues that have previously been fixed on my server that are not a problem in singleplayer. Notebly, the metal block recipies, and ore spawning. Some other posts have mentioned Gregtech configs being the culprit, but I am not absolutely sure.

**Comment by CSMaybee** [comment]
Copying my client's configs to my server fixed the issue, but now I need to retrogen all the vinella ores into the explored world. Any suggestions?

**Comment by Jessman5** [comment]
@CSMaybee would you be so kind and share your updated configs about the Greg Tech mod please?
I am experiencing the same issue that no vanilla ores are spawning in ATM9 v0.2.31

**Comment by CSMaybee** [comment]
> @CSMaybee would you be so kind and share your updated configs about the Greg Tech mod please?
> I am experiencing the same issue that no vanilla ores are spawning in ATM9 v0.2.31

I didn't manually edit any of the configs. I copied the configs directly from my playable instance to the server. I didn't delete the server configs. I let the existing files get overwritten so extra server specific configs didn't get deleted.
