### ISSUE TITLE
The game crashes while loading terrain

### ISSUE THREAD

**Issue by Sajns** [AllTheMods/ATM-9#1010]
The games get to loading terrain but then after a while the game crashes and this shows up: 
Error: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fluids.capability.IFluidHandler.getTanks()" because "this.handler" is null

Exit code: -1

Today I installed more RAM but that didn't seem to help in this case. 

Here is the crash report: 

[crash-2023-12-15_16.33.40-server.txt](https://github.com/AllTheMods/ATM-9/files/13686946/crash-2023-12-15_16.33.40-server.txt)

**Comment by Sajns** [comment]
I have tested a new world and that seems to work fine so something is wrong with the old world.

**Comment by abdullamu** [comment]
why did you close it reopen i have the same problem, after the latest update

**Comment by Sajns** [comment]
Okay, I reopened it... I have solved the problem after I get some help from the Discord server.

**Comment by abdullamu** [comment]
maybe share the fix ? so i can fix, thanks

**Comment by Sajns** [comment]
if you are crashing on the latest pack version with an error about "Ticking entity", edit world/serverconfig/forge-server.toml, find removeErroringEntities, and change that from false to true. This should let you back in.

Be sure to turn it back to false after that. 

For me it did crash again after this step but it was a second change that I need to do and it comes here: 

Then after set removeErroringBlockEntities to false and then start the game again, if it works now don't forget to turn removeErroringBlockEntities back to false. 

I hope this will work otherwise try discord ATM9 HELP.

**Comment by Sajns** [comment]
If you have discord will say.

**Comment by Sajns** [comment]
Then after set removeErroringBlockEntities to "True" and then start the game again, if it works now don't forget to turn removeErroringBlockEntities back to false.

"I wrote wrong, set it to true and then if it works back to false."

**Comment by abdullamu** [comment]
My crash error was due loading new chunk after updates, nothing helped except downloading new profile and moving my save data incase anyone having the same problem. You can close the issue both of us solved our problems.
