### ISSUE TITLE
I found a bug Whit the Black hole units and Cable tiers

### ISSUE THREAD

**Issue by Heromango1990** [AllTheMods/ATM-9#1011]
If you put a Cabled tier (any since) exporter onto a Black hole unit and then change dimension back and forth you can change the item inside the black hole unit to anything you like For Example You have 250k sand in the black hole unit then change dimension then it shows that it has 250k items inside but is NOT displaying which item it is meaning you can put in a (For example) ATM start and get 250k ATM stars instantly i recreated the bug and it only happens whit the Cable tiers Exporters (idk about importers) Normal exporters from refined storage work fine (so far)

**Comment by Kevin-Marsh** [comment]
This is an old bug for Industrial Foregoing that hasn't been fixed. It is suggested to not use Industrial Foregoing with Refined Storage or Applied Energistics.
