### ISSUE TITLE
Ars Nouveau incompatible sets

### ISSUE THREAD

**Issue by Bartek-Nalepa** [AllTheMods/ATM-9#1013]
Hey,

basically, Max Mana and mana regeneration in `%` from All The Wizard Gear is incompatible with Ars Nouveau mana. It doesn't count thus spells cant be used

![2023-12-16_01 41 07](https://github.com/AllTheMods/ATM-9/assets/43846005/3ee8bd87-a17f-4b06-a10e-e35b7b1fd753)
![2023-12-16_01 43 33](https://github.com/AllTheMods/ATM-9/assets/43846005/55d31b76-07fc-49aa-bd4c-02053eb733ca)

**Comment by Kevin-Marsh** [comment]
These are specially added Irons spells gear not Ars Nouveau.
