### ISSUE TITLE
[FULL][0.2.31] Offline, Single Player World not Loading

### ISSUE THREAD

**Issue by Skashur** [AllTheMods/ATM-9#1014]
I have tried multiple times to get my world to load. It just suddenly stopped wanting to continue after "Loading World files...", and would be stuck on the dirt back ground screen indefinitely. I have fully played a good 12 hours of this, and I'm not sure as to why it would suddenly stop working. I have tried saving a back up of my world and reinstalling the whole mod pack. It would load into a completely new world, but won't load into my world on the fresh install. I have double checked my graphics driver's, and everything is update to on that end. I have about 12gbs of ram allocated. This also started occurring after the 0.2.31 update from 0.2.30. Here is also the crash report after the program says it's "Not Responding".

link for crash log: https://mclo.gs/3AQMtgJ

Also, I have found someone with a similar issue that hasn't been resolved as well here: #476 

Here is 2 small screen shots of this occurring.  
![readingworlddata](https://github.com/AllTheMods/ATM-9/assets/154028030/029ae0ed-413b-4ba4-a036-82ad6a10f62b)
![andthenthis](https://github.com/AllTheMods/ATM-9/assets/154028030/0f45b288-2c88-4194-bade-4f5bf86c6b94)
 
It will just continue to load and load with nothing happening.

**Comment by Skashur** [comment]
Update on this issue! Successfully fixed it with some help on Mitchell52 (a dev) on the ATM9 discord. 

Here are the screenshots following the issue after updating my amd cpu drivers, and made sure my nvidia gpu is running the game and not my integrated gpu in my amd cpu. Along with the reccommended ARGs in the following order
![Screenshot1](https://github.com/AllTheMods/ATM-9/assets/154028030/b95dcc6e-ddc9-4b34-ac48-a02f346507ea)
![Screenshot2](https://github.com/AllTheMods/ATM-9/assets/154028030/be39027f-cd40-4d5a-810f-2baf3741cf75)
![screenshot3](https://github.com/AllTheMods/ATM-9/assets/154028030/eac2c36b-d83c-487c-8a3e-5c795aa78e26)

Along with the crash and Latest.logs in order from the screenshots.
https://mclo.gs/O2qS2Mk
https://mclo.gs/FYkvJK2
https://mclo.gs/rmCj1I5
https://mclo.gs/Qt43tBQ
https://mclo.gs/eeLskOh

If you have a similar issue consider going through this, but consider joining the discord! Everyone is very helpful, and I really appreciate the assistance.

**Comment by Thijspro24** [comment]
OMG THANKS it works yall are the best
