### ISSUE TITLE
ATM9 crash 

### ISSUE THREAD

**Issue by Loki21sa** [AllTheMods/ATM-9#1018]
My atm9 (singleplayer world) modpack crashes my game as soon as im in contact with the piglich using the invisibility cloak from reliquary is there any fix for this?
[crash-2023-12-18_02.15.59-server.txt](https://github.com/AllTheMods/ATM-9/files/13696633/crash-2023-12-18_02.15.59-server.txt)
this is my crash report

**Comment by KittyFloof** [comment]
seconded didn't know it was the cloak but looking here it makes sense. had to edit my player data using NBTExporer to place myself into the overworld to salvage my save.

**Comment by MrJesseD** [comment]
I had the same issue, but instead of putting myself in the overworld, I just set my gamemode to peaceful and that solved it for me.

**Comment by Loki21sa** [comment]
> I had the same issue, but instead of putting myself in the overworld, I just set my gamemode to peaceful, turned off the cloak and put it away and that solved it for me.

how did you manage to change the gamemode to peaceful?

**Comment by KittyFloof** [comment]
> > I had the same issue, but instead of putting myself in the overworld, I just set my gamemode to peaceful, turned off the cloak and put it away and that solved it for me.
> 
> how did you manage to change the gamemode to peaceful?

Probably edited the world settings file it would be in the world folder somewhere. I used NBTExporer to edit my player data to place me in another dimension away from the piglich I could have also removed the cloak from my inventory but didn't know where that section was located. Many ways to go about it.

**Comment by Loki21sa** [comment]
> > > I had the same issue, but instead of putting myself in the overworld, I just set my gamemode to peaceful, turned off the cloak and put it away and that solved it for me.
> > 
> > 
> > how did you manage to change the gamemode to peaceful?
> 
> Probably edited the world settings file it would be in the world folder somewhere. I used NBTExporer to edit my player data to place me in another dimension away from the piglich I could have also removed the cloak from my inventory but didn't know where that section was located. Many ways to go about it.

could you be so kind to walk me through it?

**Comment by KittyFloof** [comment]
> > > > I had the same issue, but instead of putting myself in the overworld, I just set my gamemode to peaceful, turned off the cloak and put it away and that solved it for me.
> > > 
> > > 
> > > how did you manage to change the gamemode to peaceful?
> > 
> > 
> > Probably edited the world settings file it would be in the world folder somewhere. I used NBTExporer to edit my player data to place me in another dimension away from the piglich I could have also removed the cloak from my inventory but didn't know where that section was located. Many ways to go about it.
> 
> could you be so kind to walk me through it?

Sorry but I'm quite busy today, I'm sure theirs tutorials on YouTube for NBTExporer and you would just need to look up the location for the world settings file.
