### ISSUE TITLE
Singleplayer world conversion and world gen transparent

### ISSUE THREAD

**Issue by piedrrum** [AllTheMods/ATM-9#1024]
When I updated my singleplayer world I got invisible chunks.
When I created a new single player one, I was able to see few chunk arounds but when coming to generation sometimes I got invisible but breakable chunks with no more update. I didnt reproduce with world gen for now. For world gen it could be:
Heavy ram load on my computer, particular biome / block, or something else...

**Comment by piedrrum** [comment]
I retried a new world gen and now I have no more bug... It may be due to a particular biome or generated block...
I dont have my old world to retry at the point where I was to see if texture were here again.

**Comment by shade1822226911** [comment]
Lost cities can put stress on the game, especially when the profile is custom made
