### ISSUE TITLE
[0.2.31] Crash - Exception in Server Tick Loop

### ISSUE THREAD

**Issue by perci100** [AllTheMods/ATM-9#1034]
https://mclo.gs/vwcctAa

Seems to affect certain areas of the world, perhaps a particular structure, unsure which as the server closes within secodns of nearing the area.

Currently affects 2 locations in the overworld.

**Comment by MegaPonyXD** [comment]
Hi, could you find a way to solve it?
I have the exact same problem i already tried to update my drivers, use more RAM and still crashed

**Comment by Rekalty** [comment]
Issue persists in 0.2.34, same crash log as OP. In my case it looks like it's a Dungeon Crawl structure that's causing it, though it could be something else underground.
