### ISSUE TITLE
Hydroponic bed recipe not showing in JEI but working

### ISSUE THREAD

**Issue by golost2202** [AllTheMods/ATM-9#1036]
Hello,

The recipes with the Hydroponid Bed is working but not showing in JEI

![2023-12-21_12 47 32](https://github.com/AllTheMods/ATM-9/assets/50000521/47d6c7f5-d042-4c94-a8c1-0464af4669cb)

For example Hydroponic Bed + every seed of Mystical is working, even the seed with a soil needed like all the modium seeds (You need to place the soil under the hydroponic bed)

![2023-12-21_12 45 21](https://github.com/AllTheMods/ATM-9/assets/50000521/267c1bae-b039-45e2-966f-8be3c99a96e4)
![2023-12-21_12 46 45](https://github.com/AllTheMods/ATM-9/assets/50000521/cef6ced9-ed44-4f64-830c-f4b89a0b6761)

I don't know if it's intended to work or if the recipe is just missing in JEI but it's kinda crazy with mystical seed and an hydroponic bed with full upgrade (can produce 1 essence of every seed every second)

**Comment by MarwenX3M** [comment]
Its a trade secret only the pros know ;)
