### ISSUE TITLE
Wrong tea recipe in cooking table

### ISSUE THREAD

**Issue by cykoticminds** [AllTheMods/ATM-9#1039]
There was an update not sure which one where it introduced new tea leaves and with it an updated tea recipe. The recipe went from being tea leaves and water side-to-side to tea above water. It seems like the cooking for blockheads cooking table didn't get the memo and kept the first recipe which doesn't craft anything anymore.

**Comment by Warlordhub** [comment]
Can confirm recipe does not work not even with a regular water bottle or the mods specific water bottle being available.

**Comment by chisgame** [comment]
still have this issue
also tofu to grounded pork has the same issues
position of items in crafting grid is wrong
