### ISSUE TITLE
Minecolonies - Disable spawning of empty/abandoned colonies

### ISSUE THREAD

**Issue by tekook** [AllTheMods/ATM-9#104]
Hi there,
I noticed minecolonies got added in one last update.
In ATM8 1.0.16 the changelog said "Disable empty minecolonies from spawning".

Can this be added to ATM9 as well?
Or does anyone know how the abandoned colonies got disabled im atm8? (Could it in the atm8 repository)

**Comment by Mitchell5200** [comment]
Planned, once Kubejs is updated to 1.20

**Comment by adkinss** [comment]
Out of curiosity, why do we want to prevent spawning of empty minecolonies?

**Comment by tekook** [comment]
> Out of curiosity, why do we want to prevent spawning of empty minecolonies? 

In atm8 they spawned more than normal villages. It was hell to find a normal village instead there were thousand of empty colonies.
