### ISSUE TITLE
Lag spikes when Shift+Click crafting a stack in AE2

### ISSUE THREAD

**Issue by Shimizoki** [AllTheMods/ATM-9#1040]
Spark: [Ticks > 100](https://spark.lucko.me/r4yCXtX7jd)

It appeared after updating from .28 to .32 on a locally hosted server.

Spark seems to imply that AE2 and FTBQuests are doing something funky together

**Comment by Atarashia** [comment]
I confirm that this also happens within the server I am playing on, which means the problem is present within the pack. If one crafts repeatedly while holding down shift+click, it can lead to a noticeable drop in TPS within the server. We did not test on a single-player environment; other users have also confirmed that they suffer from lag, even in different dimensions from our crafting actions. So, it's not a local performance drop, especially noticeable when crafting an empty inventory.

**Comment by Nordby9** [comment]
Im having the same issue on my server, don't really have anything to add.
Just wanted to add my voice to this issue. It's, sadly, almost making me switch over to RF, as we are still in early game.
Others have already switched because of this.
Forge version 15.0.15 on ATM9

**Comment by steven4547466** [comment]
Same issue. Makes crafting using AE2 almost impossible on a server as it will just end up kicking people that aren't doing the crafting while the server processes the crafting request.

Running on
- Ubuntu 20.04 (LTS)
- 128 GB DDR4 Memory
- Intel i9-9900k@5GHz

It's not a client sided issue either as it causes massive server lag.

My network is confined to 1 chunk and doesn't even have a controller, it's just an energy acceptor, 2 drive bays and a crafting terminal mainly:
![o240nn_18030 1](https://github.com/AllTheMods/ATM-9/assets/23726534/a9de5c67-26c9-4eab-8ec7-249ccdffb05b)

The chest just has an import bus on it, and when removed makes no difference in the lag produced from this.

**Comment by NachtRaben** [comment]
+1 experiencing the same issue but converted to AE towards the end of the pack. 
Issues is even worse when shift clicking items over wirieless.

**Comment by IssRey** [comment]
I'm having the same problem on ATM9 0.2.37. I'm no expert but Spark shows some funky shenanigans is going on between FTBQuests checking item crafts, AE2 processing the crafts, and oddly architectury is somehow involved. FTBQuests does use more thread % than any other process so I guess that's a clue. Smart people who know more, figure it out! lol
