### ISSUE TITLE
Extended AE2 - ME Tag Storage Bus/Export Bus not working

### ISSUE THREAD

**Issue by greatmonkey** [AllTheMods/ATM-9#1045]
mod pack version is 2.39 in single player

Using the ME Tag Storage Bus or Export Bus from Extended AE2 are not working.  Entering any tag with the Storage Bus will cause it to not put anything into the attach inventory, and the same thing happens with the Export Bus.

Tags I have tried:
forge:ores
forge:ores/*
forge:dyes
forge:dye/*
forge:dyes/* & !(forge:dyes/cyan)
forge:dyes/* && !(forge:dyes/cyan) - this is in the example in the in game guide.
forge:tools
forge:tools/*
minecraft:tools

I have also tried updating the mod to current version, 1.29 but it did not change anything.  Creating a new game and same issue was still there.

**Comment by Shimizoki** [comment]
I am running into the same issue.

I was able to get the ME Tag Storage Bus to work briefly (like for 10 seconds) using `forge:dusts`
But have been unable to make it work consistently or repeatedly.

The export bus has never once worked.

Version 0.2.32
Dedicated private server (self hosted)

**Comment by GlodBlock** [comment]
it has been fixed in 0.1.30
