### ISSUE TITLE
Massive lag caused by FTB quests

### ISSUE THREAD

**Issue by dos54** [AllTheMods/ATM-9#1048]
I've noticed a large amount of lag is being caused by FTB quests in version 0.2.32.

I play on a dedicated server that is hosted on a local machine. I played version 0.2.26 for a while, but recently started a new world with some friends and decided to update the modpack to the latest version. I noticed from the start that crafting, even in the inventory, is very slow. Today when compressing a large amount of cobblestone the server almost crashed (it was even worse than generating new chunks). So I decided to test things.

First, I looked at the Spark profiler. When looking at mods, the top 3 listed for causing lag were 
1.) architectury (4.98%,  2.62ms)
2.) jdk.proxy3 (4.82%, 2.58ms)
3.) ftbquests (4.02%, 2.15ms)

When inspecting these further I found that the #1 item in each list is something to do with crafting. And it's not by a small amount; in ftbquests, itemCrafted() takes 1.79ms compared to the next item's 0.34ms. That's more than 5x the time!

Second, I decided to check if this problem occurs in singleplayer as well. I created a new creative world, made an AE2 system with infinite cobblestone, and crafted an inventory full of 1x compressed cobblestone. My singleplayer world froze for several seconds (To be clear- I have a beefy PC)

Third, I disabled FTB quests and repeated the test in singleplayer. This time crafting took no time and resulted in no lag, even after several inventories full of compressed cobblestone. 

It seems that there is something wrong with the way that the questbook is handling crafting events. For the moment, I'm disabling FTB quests in my server.

Update: After disabling deleting the ftb-quests mod from my server, there are no longer any issues with lag when crafting.

**Comment by Shimizoki** [comment]
Your text was much more in depth than mine. But this seems to align with the ticket I opened a few days ago.

https://github.com/AllTheMods/ATM-9/issues/1040

**Comment by dos54** [comment]
> Your text was much more in depth than mine. But this seems to align with the ticket I opened a few days ago.
> 
> #1040

It looks like it. Sorry, I've never done one of these before. Should I have posted it on your ticket?

**Comment by alfredggttv** [comment]
This might be an issue related to the "checks" the mod does to see if you've acquired an item for one of the quests. I suggest on reporting the issue on the FTBQuests github as well while I look into it.

**Comment by Nordby9** [comment]
Just wanting to add, i have the same issue.
It's made half my server switch to RF. Which doesn't have the issue.
Personally i love AE too much, so ill stick by it, hoping it will get fixed.
We only notice an issue when doing it in AE2.

**Comment by biochemie** [comment]
Attempting to revert ftb-quests and ftb-xmod-compat back to their stable release versions in the 0.2.27 ATM9 update (`ftb-quests-forge-2001-1.2.1` and `ftb-xmod-compat-forge-2.0.4` before they were both updated to the beta releases in 0.2.28) appeared to alleviate some of the crafting lag in ATM9 0.2.32 (especially outside of AE2) but crafting lag withing the AE2 crafting interface was still obvious. Can also confirm that disabling ftb-quests on both the server and client eliminates the crafting lag present within the AE2 crafting interface.
