### ISSUE TITLE
Mythic Botany

### ISSUE THREAD

**Issue by Pengwyn-Aria** [AllTheMods/ATM-9#1051]
https://www.curseforge.com/minecraft/mc-mods/mythicbotany

Mythic Botany is an awesome add-on to the Botania mod pack that allows for more spells and rituals as well travel toAlfheim, by traversing through the portal once used solely for trading with the elves. I had an absolute blast with this addition in a previous server my friend hosted, and would love to see it added to ATM9.  Thank you for your consideration! ♥ =^.^= ♥

**Comment by Jupitor87** [comment]
its not 1.20.1

**Comment by Pengwyn-Aria** [comment]
> its not 1.20.1

Oh no... So it won't ever work for ATM 9 then?

**Comment by Mitchell5200** [comment]
Use #1 for mod suggestions, not new issues, mods also NEED to be forge mods and on the matching MC version that the pack is on
