### ISSUE TITLE
EndermanOverhaul lag.

### ISSUE THREAD

**Issue by SapleMyrup** [AllTheMods/ATM-9#1052]
Had to disable on .32 to get rid of some lag. removing the mod fixed it.

Server has 3 players

runs on 4 threads from a 8700k.

before removal : 70ms per tick

after removal : 45 ms per tick.

**Comment by GothBoyUK** [comment]
I have found that several species of Enderman are, somewhat, simpletons. They will teleport to a block that has something on it that prevents them from teleporting again. Sometimes hundreds can be on one block, usually the thing preventing teleportation also prevents entity cramming. I've never seen it happen to vanilla endermen but the modded ones are notorious for it. In addition, having Mushroom Fields Endermen was a very bad idea - I had to disable them specifically.

**Comment by SapleMyrup** [comment]
I didn't feel like this was the most appropriate way to report this, but I did a quick search first and didn't see anything about it. I knew it'd get lost on discord so there we are. Thank you for putting effort into this, whoever sorts this out.

**Comment by realstuffie** [comment]
had the same issue on my server 
![Capture](https://github.com/AllTheMods/ATM-9/assets/118485186/c08328d8-9f4c-46db-bf00-e302ce06247c)
