### ISSUE TITLE
Heavy Water isn't  working

### ISSUE THREAD

**Issue by Chingerlos** [AllTheMods/ATM-9#1057]
I did use a setup to produce Deuterium and was working, but since 0.2.32 heavy water isn't going in my Electrolytic Seperator.

I did try all what came in my mind all conf was right., but I doesn't accpet it anymore.

**Comment by Arnaen** [comment]
Unfortunately, I have the same problem and have been unable to find a solution.

**Comment by Chingerlos** [comment]
In 34 is it fixed
