### ISSUE TITLE
Every Docker Update the Server wont start

### ISSUE THREAD

**Issue by Mofarocker33** [AllTheMods/ATM-9#1060]
Hi,
i am using the Docker Image on my Unraid Server.
Every time i Upgrade to the actual Version it wont start with this Error:
`+ FORGE_VERSION=1.20.1-47.2.16
+ cd /data
+ [[ true = \f\a\l\s\e ]]
+ echo eula=true
+ [[ -f Server-Files-0.2.32.zip ]]
+ [[ -n -Xms2048m -Xmx16384m ]]
+ sed -i '/-Xm[s,x]/d' user_jvm_args.txt
+ for j in ${JVM_OPTS}
+ sed -i '$a\-Xms2048m' user_jvm_args.txt
+ for j in ${JVM_OPTS}
+ sed -i '$a\-Xmx16384m' user_jvm_args.txt
+ [[ -n '' ]]
+ [[ -n OP1, OP2 ]]
+ echo OP1, OP2
+ awk -v RS=, '{print}'
+ [[ -n '' ]]
+ sed -i 's/server-port.*/server-port=25565/g' server.properties
+ chmod 755 run.sh
+ ./run.sh
Error: could not open `libraries/net/minecraftforge/forge/1.20.1-47.2.16/unix_args.txt'`

Should this be fixed in the Image or is it kind of my bad in configuration?

Thanks in advance for Help.

**Comment by screret** [comment]
wrong java

**Comment by screret** [comment]
or bad path, unsure

**Comment by Mofarocker33** [comment]
So i should ask the Docker Maintainer?
https://hub.docker.com/r/goobaroo/allthemods9

**Comment by Mofarocker33** [comment]
Like it was commented on that Main Website from Docker:
`Deleting the downloaded server file in /data will restart the install/upgrade process.`
So i did `/mnt/cache_sys_docker/appdata/allthemods9-4# rm -rf Server-Files-*`
and it reloaded all necessary files.
Up and Running again.
