### ISSUE TITLE
Industrial foregoing block placer does not place blocks 0.2.32

### ISSUE THREAD

**Issue by gzcwnk** [AllTheMods/ATM-9#1061]
Block placer not placing wooden blocks for latex making

**Comment by anivlys** [comment]
Is this in a claimed chunk? The defaults do not allow the fake player for Industrial Foregoing to place blocks in claimed chunks.

**Comment by gzcwnk** [comment]
Yes, I have to allow fake accounts but it still didnt work until I removed and re-added the placer, then it placed fine.
