### ISSUE TITLE
[Feature Request] Periodic Table of the Elements

### ISSUE THREAD

**Issue by Pienapples** [AllTheMods/ATM-9#1062]
Create a questline surrounding Alchemistry to complete a Periodic Table of the Elements and give small XP rewards and Basic to Rare rewards depending on the difficulty of the Element and then some big fancy-ish reward for completing the Table.

**Comment by alfredggttv** [comment]
Is there an achievement for completing the Periodic Table of Elements? If so, this could be part of an Achievements tab!
