### ISSUE TITLE
Quest Book Empty & Recipes lost

### ISSUE THREAD

**Issue by skillvlzer0** [AllTheMods/ATM-9#1063]
![Screenshot 2023-12-26 060035](https://github.com/AllTheMods/ATM-9/assets/154891079/4e1981e2-5bed-4ac2-aa7f-d0f7829a6aca)

For context I am running a server through Creeper Host, I have downloaded the latest "All the Mods 9-0.2.33" update to the server as well as my personal client, straight downloads, zero modifications to mod list or configs. Yesterday on the previous release all was fine, but now today after the update the quest book and tab is completely empty of tabs or quest lines.

**Comment by Andrewki44** [comment]
Same issue here updating from 0.2.32 to 0.2.32

**Comment by skillvlzer0** [comment]
In addition to this, recipes have been removed, such as cooking sand in a furnace to make glass.

**Comment by Kevin-Marsh** [comment]
These issues would have been caused by incorrectly updating the pack. This was often caused by prism but should be resolved now.
