### ISSUE TITLE
Recipe overlap

### ISSUE THREAD

**Issue by RapsyJigo** [AllTheMods/ATM-9#1065]
There is a recipe overlap between `eidolon:candle` and `occultism:candle_white` making the occutlism candle impossible to craft.

**Comment by LightningManGTS** [comment]
Polymorph is in the pack to allow swapping between outputs when there's a conflict. This should be closed. 

![image](https://github.com/AllTheMods/ATM-9/assets/3919521/2b870f3f-af9a-4fd7-b2df-f21d91388b52)
