### ISSUE TITLE
Update v0.2.33 causes compatibility issues with Sinytra Connector, leads to broken 8x8 textures and increased performance issues.

### ISSUE THREAD

**Issue by PlayfulPiano** [AllTheMods/ATM-9#1068]
Unsure what could have caused this, as none of the blocks or mechanics seem to have broken? Just the textures, and restarting the instance doesn't fix it.
A previous backup of v0.2.32 works fine.

![image](https://github.com/AllTheMods/ATM-9/assets/3158887/847bbea4-d33b-43e8-ab53-bcb5fd48465d)
![image](https://github.com/AllTheMods/ATM-9/assets/3158887/6c88532a-c04d-467b-97c5-d02f2d379bd2)

**Comment by PlayfulPiano** [comment]
Can confirm it still breaks textures when updating from 32 to 34.
![image](https://github.com/AllTheMods/ATM-9/assets/3158887/1e113d1e-02e4-496f-ad20-4ff448995b76)
[debug.log](https://github.com/AllTheMods/ATM-9/files/13775761/debug.log)
[latest.log](https://github.com/AllTheMods/ATM-9/files/13775762/latest.log)

**Comment by PlayfulPiano** [comment]
Seems to be an issue with Sinytra Connector & ATM9 after the release of v33 of the modpack. Also noticed that I was using a somewhat outdated version of connector (v30 instead of v32), so I'll check if that fixes it first off.

**Comment by githubgarry73** [comment]
I had the same problem. Downgrading Embeddium to version 0.2.13 fixed it for me.

**Comment by PlayfulPiano** [comment]
> I had the same problem. Downgrading Embeddium to version 0.2.13 fixed it for me.

that is extremely good to know and thank you, talked with embeddedt and they can confirm the diff:
![image](https://github.com/AllTheMods/ATM-9/assets/3158887/468ad18e-4fd8-4014-8483-b31512a67065)

**Comment by githubgarry73** [comment]
Yeah, can confirm it's nvidium. Textures are bugged only with nvidium and embeddium 0.2.14+. Without nvidium the textures are fine.
