### ISSUE TITLE
LAN ERROR: Itemstack Cannot be created

### ISSUE THREAD

**Issue by Eyeveri** [AllTheMods/ATM-9#1070]
My wife and I are trying to do a lan world. We fixed the original java error of 0 in 0 out, but now we're getting "Internal Exception: Java.lang.IllegalArgumentException: Itemstack ingredients cannot be created using the empty ingredient."

**Comment by Eyeveri** [comment]
To be clear, we deleted the logprot mod as directed.

**Comment by Eyeveri** [comment]
Not sure what the issue is, but if you make a dedicated server following this - [AllTheGuides](https://alltheguides.pages.dev/help/server/#server-host-installation) - it works fine.

**Comment by creepercrack** [comment]
[latest.log](https://github.com/AllTheMods/ATM-9/files/14592821/latest.log)
