### ISSUE TITLE
Latex processor recipe missing for tiny dry rubber in 0.2.33

### ISSUE THREAD

**Issue by LightningManGTS** [AllTheMods/ATM-9#1071]
The latex processing recipe for tiny dry rubber is missing. Also labeled as depreciated?

Not sure what the idea here is, latex is still required for the dissolution chamber

**Comment by ModestTG** [comment]
I believe the latex processing unit now directly creates dry rubber instead of tiny dry rubber. So the tiny dry rubber item is deprecated.

**Comment by LightningManGTS** [comment]
In 0.2.33 there is no recipe for latex in the latex processor to produce anything.

**Comment by Queen4Eternity** [comment]
I'm playing on 0.2.34 and it uses the same recipe of just water and latex to make dry rubber instead of tiny dry rubber and you just put that directly into a furnace to make plastic. It is still missing the JEI recipe though.

**Comment by LightningManGTS** [comment]
Can confirm. Recipe is 750mb of Latex and 500 water. 

I double checked JEI and all that's listed is the dry rubber as the output with no input information.
