### ISSUE TITLE
[Suggestion]Add a second charm slot to allow magnet + something else

### ISSUE THREAD

**Issue by jinkhya** [AllTheMods/ATM-9#1074]
Hello,
I understand why having too many curios slots can make you very powerful, however it'd be nice to have 2 slots for charms as a good amount of players put the magnets there and then you can't have any other charm. 

Best regards,
jin

**Comment by TheOneLazyFox** [comment]
I just keep it in my inventory and use a keybind to turn it on and off, using the simple magnets mod one
