### ISSUE TITLE
Crash On loading

### ISSUE THREAD

**Issue by teriak47** [AllTheMods/ATM-9#1080]
Hello, I have a problem with ATM 9, I cannot launch the game, I have an exit error 1 and this log.

Could you help me please?

A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff2791233d, pid=15240, tid=17904

JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
C  [bitsperf.dll+0x233d]

[hs_err_pid16296.log](https://github.com/AllTheMods/ATM-9/files/13785854/hs_err_pid16296.log)

**Comment by gionekpro** [comment]
same

**Comment by TheBedrockMaster** [comment]
Still happening? Add crash label.
