### ISSUE TITLE
Zero MA seeds from harvesting since 0.0.26

### ISSUE THREAD

**Issue by loving2** [AllTheMods/ATM-9#109]
Hello, I believe there's a bug interacting between Harvest With Ease and Mystical Agriculture.

I'm using Harvester Pylons with supremium hoes to harvest various MA seeds and receiving exactly zero seeds from it. This seems to have been the case since updating to version 0.0.26 and beyond. My MA farms are all planted on the correct tier of essence farmland to increase secondary output to 20%, but I'm receiving no seeds at all. Placing the seed with farmland inside of a botany pot does result in seeds though.

Steps to reproduce:

1. Make any tier seed
2. (Optional) Use corresponding tier of essence on farmland
3. Plant seed
4. (Optional) Speed growth with mystical fertilizer
5. Harvest manually or with harvester pylon

**Comment by Dukisef012** [comment]
I think it's intended like this, it is the same in the ATM8 with Harvester Pylons, at least it is for me in my current playthrough of ATM8.

**Comment by loving2** [comment]
I think you're right, it looks like a config setting to disable secondary seed drops.
