### ISSUE TITLE
Game Keeps Freezing

### ISSUE THREAD

**Issue by StrickeNomad** [AllTheMods/ATM-9#1093]
My Game keeps freezing will still accept inputs but will stay on one frame

bellow is my latest log I could not put it in paste bin unfortunately

[latest.log](https://github.com/AllTheMods/ATM-9/files/13791881/latest.log)

**Comment by Xplodin** [comment]
what shader are you using (if any)?
Looks like a whole lotta GL ERROR spam in the logs
If not using shaders, remove oculus
