### ISSUE TITLE
[v0.2.34] Thermal Series - Random rewards (red die icon) not giving anything

### ISSUE THREAD

**Issue by UltraGameCoder** [AllTheMods/ATM-9#1096]
**What is the nature of the bug?**
Random Reward within Thermal Series section not giving any rewards

**Reproduce steps:**
- Look into the questbook section 'Thermal Series'
- Complete any: Tinker's Workbench, Alchemical Extender, Alchemical Amplifier, Decoctive Diffuser, Reinforced Integral Components, ...
- Claim rewards using the questbook's 'Click to collect all rewards'
- You only get 4x100 xp.  And the random reward gets checked off without giving you anything.

Proof: [https://youtu.be/49V_SErHX7I](https://youtu.be/49V_SErHX7I)

**Comment by willtarax** [comment]
Yeah I thought this would have been fixed by now, but it hasn't, issue is still occurring in the latest version of ATM9

**Comment by willtarax** [comment]
I think this is due to the loot table being loaded into the quest chapter and not the loot table folder. Silly mistake, but one that should have been corrected some time in the last 6 or so updates since Thermal quests were added...

**Comment by g0urra** [comment]
Bump, this is still an ongoing issue

**Comment by TheBedrockMaster** [comment]
Should be fixed?
