### ISSUE TITLE
[v0.2.34] Mechanical saw recipie conflict

### ISSUE THREAD

**Issue by TheFighter82** [AllTheMods/ATM-9#1097]
**What is the nature of the bug?**
Create mechanical saw alternates crafting stripped oak logs and hollow oak logs

**Reproduce Steps:**

- create mechanical saw & power it
- put oak logs into mechanical saw

proof: [https://drive.google.com/file/d/1FfIECjpWAykOphZaLzcPfcbpFBWt9Q8U/view?usp=sharing](url)

**Comment by Queen4Eternity** [comment]
Have you tried using the recipe filter?
![Create Mechanical Saw Recipe Filter](https://github.com/AllTheMods/ATM-9/assets/146783034/55c25884-167a-4559-81ee-e02a571bd2d3)

**Comment by Queen4Eternity** [comment]
p.s. I was not able to open your link properly but that might just be me/my computer.

**Comment by TheFighter82** [comment]
The filter worked for me. Thanks
