### ISSUE TITLE
I wanna See L_ender Cataclysm IN This Modpack 

### ISSUE THREAD

**Issue by TheRealEzufIII** [AllTheMods/ATM-9#110]
[L_Ender's Cataclysm](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm) Is a mod That Add many cool Boss With cool mechanic. And for the moment the Modpack doesn't have many bosses so :)

#1

**Comment by Mitchell5200** [comment]
Use #1 for mod suggestions please.

**Comment by TheRealEzufIII** [comment]
but i used it no? like in not in the title

**Comment by TheRealEzufIII** [comment]
i dont seem to understand lol

**Comment by Mitchell5200** [comment]
Use that > `https://github.com/AllTheMods/ATM-9/issues/1`
