### ISSUE TITLE
Mahou Margan : 5M dmg sword is a bit much isn't it?

### ISSUE THREAD

**Issue by jinkhya** [AllTheMods/ATM-9#1101]
Hello,

As much as one likes to get something really powerful I feel like this is going too far. Somebody on my server made this sword :
![image](https://github.com/AllTheMods/ATM-9/assets/10158963/12b6f3f4-ff32-4108-9d78-a30441874c64)

I know it's also enhanced by other mods than mahou but not by that much. No other sword from any other mod can reach 5 million damage. It's like being in creative mode at this point.
Shouldn't this be tweaked to a more reasonable number? 

Best regards,
Jin

**Comment by Burkino** [comment]
Nah it's fine. It's easy to get an overpowered weapon, and it's just as easy to become 99.9% unkillable, even with this weapon.
