### ISSUE TITLE
Falling lanterns + minecolonies = disaster

### ISSUE THREAD

**Issue by therodet** [AllTheMods/ATM-9#1104]
The Supplementaries mod default config option to cause lanterns to fall and burst into flames is problematic with minecolonists. The config is in the common config folder, so it currently has to be adjusted after every patch.

**Comment by Ciege666** [comment]
Can confirm, after partially burning down my smeltery, blacksmith, restaurant, university Tier 3 and university Tier 4

Old Line 508 of supplementaries-common.toml:
falling_lanterns = "ON"

Suggested Line 508 of supplementaries-common.toml:
falling_lanterns = "OFF"

Keeps everything except the fire from falling lanterns.

**Comment by Corbi84** [comment]
Since it has no tag yet: Can also confirm. Kept wondering why my buildings kept going up in flames when being upgraded, until I realized it's the lanterns...
