### ISSUE TITLE
(0.2.34) Lag because of crafting

### ISSUE THREAD

**Issue by Gronkelx** [AllTheMods/ATM-9#1111]
We have a Minecraft server with 4 people. The modpack is actually running quite well. But if someone is crafting something e.g. essences from mystical agricultare to a stack, then the server lags extremely and only when he has finished crafting it runs smoothly again.

**Comment by Entoarox** [comment]
We are a similar sized server with the same issue, it seems to mainly be manually crafting a stack with AE that amplifies the problem, lagging everyone as a result.

Given the high amount of boss mobs in the pack, these lag spikes can be incredibly detrimental, and I simply cannot expect everyone to stop crafting for however long such a boss fight takes.

**Comment by Moewen-dev** [comment]
Yup we have the same issue on a 2 man server...

**Comment by FallenPumpking** [comment]
Confirming this still exists in 0.2.37. Crafting a stack of items such as nuggets to ingots or MA Essence in a crafting terminal for AE2 lags entire server hard and has a delayed output.
