### ISSUE TITLE
No extra outputs for GregTech processes

### ISSUE THREAD

**Issue by kjukmar2** [AllTheMods/ATM-9#1113]
ATM 9, version 0.2.34
When using a macerator, the extra outputs that are produced depending on a percentage don't seem to be produced. Out of a stack of items not a single operation yelded the extra, which is quite unlikely as the operation has a 50% probability to at least double the output. It's reasonable to assume that the same is true for other processes and other machines that have a chance to produce additional output.

**Comment by kjukmar2** [comment]
I have incestigated this issue with other machines, and this issue is present for macerators until the HV tier, which make me think that this was intentional. I wonder who did this because it's stupid to invalidate early ore processing/duplication in this way. I also couldn't find any config files to fix this... issue.

**Comment by kurbar** [comment]
It is by design. GTCEu (and I think even original GT) macerator byproducts are unlocked at HV tier.

**Comment by screret** [comment]
completely intended and meant to make the player make more ore processing machines other than macerators (ore washers and the like).

**Comment by kjukmar2** [comment]
Hmmm, I remember that ore doubling, or even tripling (based on chance) used to work on an older version of the modpack, can't say on which unfortunately, even on the steam machines. Is anyone aware of a config file which would make it possible to fix this obersight?

**Comment by kjukmar2** [comment]
So, i tried replicating this issue without any other mods, and, unfortunately, succeeded.

**Comment by screret** [comment]
> Hmmm, I remember that ore doubling, or even tripling (based on chance) used to work on an older version of the modpack, can't say on which unfortunately, even on the steam machines. Is anyone aware of a config file which would make it possible to fix this oversight?

it got fixed about 1.5 months ago iirc
