### ISSUE TITLE
[FULL][0.2.34] Integreted dynamics crafting grid crash game !

### ISSUE THREAD

**Issue by Naegato** [AllTheMods/ATM-9#1115]
I play on server with my friend and when we connect the integretedterminals:part_terminal_storage to my network cause my game to crash 
![image_2024-01-02_220816655](https://github.com/AllTheMods/ATM-9/assets/84842519/05583da2-781c-4664-b2de-cab022ad1883)
![REPORT BUG](https://github.com/AllTheMods/ATM-9/assets/84842519/441f2d4f-9106-4c8e-b7a8-7f1b55d03a85)

**Comment by neotaoisttechnopagan** [comment]
Edit your config/integratedterminals-common.toml - look for the line under [core] that says "terminalStoragePacketMaxInstances" and change the value to 128.
