### ISSUE TITLE
I have no idea

### ISSUE THREAD

**Issue by Zreethan** [AllTheMods/ATM-9#1116]
![yoinks](https://github.com/AllTheMods/ATM-9/assets/155489138/822eb6ee-ec56-4276-a37a-1dda30a1d517)

The chucks that are loaded work just fine and if you leave them you still walk on the blocks that should be there. 
![image](https://github.com/AllTheMods/ATM-9/assets/155489138/8213e2c6-8e76-461e-aec6-709e7b2e2454)
 I have no idea, i reloaded the chucks and reloaded shaders. The world was working just fine until my friend noticed the nether was broken so i closed out and loaded back in and thats when the horror happened.

**Comment by Zreethan** [comment]
was quite strange, i put my render distance to 2 chunks and then it started loading the void. I then switched it back to 64 chunks and it reloaded it all. Very weird that reloading chucks didn't fix it then but o well.

**Comment by daviddomkar** [comment]
Also have this issue. Problem is, when running dedicated server, the chunk slider wont do anything.

**Comment by djnifos** [comment]
set it back to 32, restart the whole game.  For some reason setting it to 64 crashes the rendering thread.
