### ISSUE TITLE
Same items don't stack 9-0.2.34

### ISSUE THREAD

**Issue by clytemnestra** [AllTheMods/ATM-9#1119]
Hello, I have the exact same problem as here https://www.reddit.com/r/allthemods/comments/10i0bi7/same_items_dont_stack/

![image](https://github.com/AllTheMods/ATM-9/assets/7060048/a81434a5-2416-4779-bf85-89e46b8d3fac)

Items with that tag don't stack, seems like it's because a zombie picks them up

https://github.com/AllTheMods/ATM-9/issues/162 might be related

This happens in my mob grinder.

**Comment by Kevin-Marsh** [comment]
This should have been fixed with the removal of the Let Me Despawn mod.
