### ISSUE TITLE
Can't put fluids in refined storage (exporter/importer)

### ISSUE THREAD

**Issue by Kunandiir** [AllTheMods/ATM-9#1121]
I'm trying to automate latex from industrial foregoing and discovered that you cant put any fluid in exporter or importer as you can with items.
Here is screanshot, how it looks with items and I can't do this with fluids.
![photo_2024-01-03_18-57-10](https://github.com/AllTheMods/ATM-9/assets/85193924/ca7ffb5b-f6b5-423c-b57f-c9885eaea44e)
![photo_2024-01-03_18-57-54](https://github.com/AllTheMods/ATM-9/assets/85193924/e5469c4b-87df-44a8-8b39-1782f12fe042)

**Comment by Queen4Eternity** [comment]
You have to have a bucket of the liquid in your actual inventory and shift click it over.
