### ISSUE TITLE
Map 4 : reaching x cased crash

### ISSUE THREAD

**Issue by Grisabeller** [AllTheMods/ATM-9#1138]
i picked up a map  lable map 4 and followed to where the cross mark where the game crashed . and when trying to load that world again it crash as i stuck at that location

The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: Index -102 out of bounds for length 1024

[crash-2024-01-05_23.02.13-client.txt](https://github.com/AllTheMods/ATM-9/files/13847405/crash-2024-01-05_23.02.13-client.txt)

**Comment by AKlug1** [comment]
Same issue here, but with Map to the Ring of Gods. Error report looks the same but I'll throw it in anyway

[crash-2024-01-21_22.32.00-client.txt](https://github.com/AllTheMods/ATM-9/files/14004033/crash-2024-01-21_22.32.00-client.txt)
