### ISSUE TITLE
Occultism preview crash

### ISSUE THREAD

**Issue by K1kk0m4n** [AllTheMods/ATM-9#1139]
My game crashes to desktop on opening ritual preview from book dictionary of spirits. Game freezes for a bit and then crashes.

Crash report included. Playing All The Mods 9

[crash-2024-01-06_13.53.44-client.txt](https://github.com/AllTheMods/ATM-9/files/13849498/crash-2024-01-06_13.53.44-client.txt)

**Comment by K1kk0m4n** [comment]
Tried re-install modpack and in a new world, still crashes.

**Comment by K1kk0m4n** [comment]
Now my game crashes upon opening dictionary of spirits book from Occultism mod.

Crash log:

[crash-2024-01-10_14.18.05-client.txt](https://github.com/AllTheMods/ATM-9/files/13887497/crash-2024-01-10_14.18.05-client.txt)

**Comment by troughp** [comment]
I have also encountered this bug.  I was previewing the first ritual. Aviar's circle.  Repeated the crash once now am dropping this report here.
[crash-2024-01-11_14.40.54-client.txt](https://github.com/AllTheMods/ATM-9/files/13907690/crash-2024-01-11_14.40.54-client.txt)
[crash-2024-01-11_14.46.26-client.txt](https://github.com/AllTheMods/ATM-9/files/13907691/crash-2024-01-11_14.46.26-client.txt)
 these are the two crash reports the first and second time i triggered the crash.

**Comment by troughp** [comment]
And now I also can't open the dictionary of spirits.  I did open it a few times in between my last comment and this one.  But now it is crashing my world just to open it.
[crash-2024-01-11_15.08.47-client.txt](https://github.com/AllTheMods/ATM-9/files/13907880/crash-2024-01-11_15.08.47-client.txt)

**Comment by K1kk0m4n** [comment]
Posted this on Occultism issues here:
https://github.com/klikli-dev/occultism/issues/1025

Some answers on the matter
