### ISSUE TITLE
Mystical Agriculture seed duplication

### ISSUE THREAD

**Issue by Bultjer** [AllTheMods/ATM-9#1141]
<kbd>sneak (Shift)</kbd> + <kbd>use item (RMB)</kbd> on a grown Mystical Agriculture plant drops the seed and leaves the plant, leaving you with one extra seed. This works for unobtainium seeds in 1.20.1 - 0.2.35.

**Comment by Kevin-Marsh** [comment]
Configs were modified in order to fix this issue.

**Comment by DieAnotherDayTD** [comment]
is there a way for me to get the old version of the config file that will work in the atm9 to the sky pack or which config file do I have to edit to revert it back
