### ISSUE TITLE
Using stripped oak logs crafting 4 chests, you can make a bunch of chests

### ISSUE THREAD

**Issue by MooMcMooman** [AllTheMods/ATM-9#1145]
![image](https://github.com/AllTheMods/ATM-9/assets/131305003/bdee4966-8b85-49f6-add4-8816cf8d2f6d)

**Comment by Kanaede** [comment]
What is wrong? 1 Spindle contains 4 planks, it is just an alternative recipe if you need a lot of chests.,

**Comment by MooMcMooman** [comment]
It's not supposed to make different types of chest

**Comment by MihailBezukladnikovISiP201** [comment]
> It's not supposed to make different types of chest

Why so? I don't think that in this modpack that's a really huge issue with this. You need to craft bazzillion items, chest variation isn't that important

**Comment by neotaoisttechnopagan** [comment]
This works with regular oak logs as well. It's an alternative recipe and is enabled by default, not an issue/bug.

**Comment by RuhaiHu** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/11594515/b028de0f-dff9-4a60-bbab-962c70330851)
I not sure about it not being a problem ran into this a few minutes ago, and I don't see a way to scroll it. Also thats at 1440p. So lots of options to many to display.
