### ISSUE TITLE
[v0.2.33] Spark profiler shows EndermanOverhaul contributing to high tps

### ISSUE THREAD

**Issue by Brother-Blue** [AllTheMods/ATM-9#1148]
It's expected for mods to have different effects on tps of course, but in particular the Cave Enderman is contributing, on average, 16-18% tps usage with only 1 player online and nowhere near any caves. 
I put myself in a space station to verify and ran spark profile again at a 2 minute interval and received the same results.
![image](https://github.com/AllTheMods/ATM-9/assets/61142910/0fc748ba-2102-46ea-aec5-011b50af5953)

For some perspective, this is almost double than what mekanism is contributing with multiple bases chunk loaded.
![image](https://github.com/AllTheMods/ATM-9/assets/61142910/3916f91e-7a5f-44f1-b4fa-4a29bc295427)

Ideally I would like to disable this mod and investigate how this impacts performance, or if there is a config for this somewhere so I can tinker around with that. I checked in config and serverconfig but no luck there.

**Comment by dragongod100** [comment]
In my experience, the easiest fix was to disable mob griefing entirely on the server.

**Comment by GothBoyUK** [comment]
There is a config that can be edited. I am not at my laptop and can't remember where but it's definitely configurable. I think it was in the saves folder for the particular world. I was forced to disable Mushroom Endermen but may look into others as they are lag machines.

**Comment by Brother-Blue** [comment]
@dragongod100 unfortunately since it's not just me playing on the server that isn't a viable option.
Thank @GothBoyUK I'll dig around there and see if I can find it

**Comment by Kevin-Marsh** [comment]
Cave Endermen should now be turned off in atm9.
