### ISSUE TITLE
[v0.2.33] Server hosting issue

### ISSUE THREAD

**Issue by samololo** [AllTheMods/ATM-9#1149]
Hello. I have a problem while hosting my server.
I got the following log : http://pastebin.fr/135261
No apparent error.
But it stays stuck on GregTechCEu is initializing on platform: Forge
Using Verygames:
Java 17 - v0.2.35
If anyone had the same problem. I haven't found anything online.

**Comment by mdereus** [comment]
I have experienced this same thing. On a fresh Ubuntu 22.04 server and a fresh download of ATM9. I have tried every ATM9 version from 0.2.31 through 0.2.37 and the result is the same, gets to `GregTechCEu is initializing on platform: Forge` and hangs. Lack of CPU usage tells me it's not doing anything. I tried 0.2.37 with both OpenJDK 17 and 21 with no difference.

0.2.31 log: https://mclo.gs/d9eqfiw
0.2.37 log: https://mclo.gs/ahpG6BK

These are duplicate issues I've found with this same problem.
https://github.com/AllTheMods/ATM-9/issues/919
https://github.com/AllTheMods/ATM-9/issues/679

I have ATM9 0.2.31 running on Unraid in a Docker container using [this repo](https://github.com/Goobaroo/docker-allthemods9). I copied that entire installation to the Ubuntu server and it hangs at the same ` GregTechCEu is initializing on platform: Forge` log entry.
Logs for the 0.2.31 Docker copy: https://mclo.gs/ZM903kc

I decided to try another clean Ubuntu install. Installed OpenJDK 17 headless, and ATM9 0.2.37. It started without issue. Copied my 0.2.31 world in and still working.

**Comment by BlairStewart** [comment]
ATM9 `v0.2.39` with `itzg/minecraft-server:2024.2.0` Also having this issue.
