### ISSUE TITLE
[v0.2.36] Allthemodium gears multiservo press recipe is bugged

### ISSUE THREAD

**Issue by RealRainbuu** [AllTheMods/ATM-9#1151]
The recipes for gears in the multiservo press are broken, as they have no input and output the gear.
![image](https://github.com/AllTheMods/ATM-9/assets/77862418/eb9d10f3-d6d9-4dfe-8f2e-677ba7861b79)
![image](https://github.com/AllTheMods/ATM-9/assets/77862418/485d516c-1ea8-4120-8094-c8c0d82fb60e)
![image](https://github.com/AllTheMods/ATM-9/assets/77862418/ba1d5c93-eb59-4e6b-b017-df78cdf66d63)

**Comment by Schrimpes** [comment]
I apologize immediately if this comes across as rude, but the search bar is not just a decoration. ^^

[fifth post under this one](https://github.com/AllTheMods/ATM-9/issues/1143)
