### ISSUE TITLE
[v0.2.36] Diamond Gear Recipe is buggy inside the Multiservo Press

### ISSUE THREAD

**Issue by LuziferSenpai** [AllTheMods/ATM-9#1156]
Hey,

when you look at the Recipe for a Diamond Gear, you see that the Gear is made out of nothing inside the Multiservo Press, it should be 4 Diamonds.

**Comment by g0urra** [comment]
I would like to say that this issue is still ongoing as of v0.2.54

**Comment by Kevin-Marsh** [comment]
This is caused by an issue in the script that unifies the recipes and adds the gears etc into the multiservo press.  We are working on a fix if we can.
