### ISSUE TITLE
Request for mod addition

### ISSUE THREAD

**Issue by ExemplarDraco** [AllTheMods/ATM-9#116]
LittleTiles looks like it is updating and I've missed the smaller blocks (like chisels and bits) for a while now. Feels like most modpacks I've played recently don't have either
Edit: I thought 1.20 LittleTiles was out but it was just 1.12 I'm not sure why I thought 1.12 was the newest one..

**Comment by Mitchell5200** [comment]
use issue #1 for mod suggestions, not new posts
