### ISSUE TITLE
[ ATM9 - No Frills ] Bringing back Advanced Generators would be beneficial.

### ISSUE THREAD

**Issue by Henrique143** [AllTheMods/ATM-9#1161]
In the latest version of ATM9 - No Frills (0.0.4), Advanced Generators was removed, and I don't quite understand the reason behind it.

It's a small mod that doesn't introduce any world generation, yet it serves as an excellent power option for the early to mid-game stages.

Since the nerf of Mekanism's ethylene, many other power alternatives have become viable. One example is Advanced Generators, paired with the production of biodiesel from Immersive Engineering. This served as a great option for transitioning to mid-game power with a reasonable resource investment, complexity, and a rewarding payoff.

Considering that the mod doesn't significantly impact performance and positively expands gameplay options, I ask the developer team to reconsider adding back Advanced Generators to ATM9 - No Frills.

Thanks!

**Comment by whatthedrunk** [comment]
its very possible it will come back. No Frills is still in early days and we are working things out.
