### ISSUE TITLE
Crash while opening inventory in creative on server

### ISSUE THREAD

**Issue by avatarfreak345** [AllTheMods/ATM-9#1162]
Bug produced by joining a server, going to creative and trying to open the inventory.
[Crash report.txt](https://github.com/AllTheMods/ATM-9/files/13891378/Crash.report.txt)

**Comment by ShikuTeshi** [comment]
I can confirm the same. Updated to 0.23.7 today from 0.23.6 and nobody on my server can open their inventories in creative mode without crashing.
