### ISSUE TITLE
Occultism crashes when clicking preview button in book

### ISSUE THREAD

**Issue by bossempoleon** [AllTheMods/ATM-9#1168]
when i go to preview an occultism ritual it crashes the game almost immediately

**Comment by jpruitt2297** [comment]
same here. only difference is that the game still seems to be running, not crashing itself to desktop, and removes any and all visuals and inputs.

**Comment by Kevin-Marsh** [comment]
This is an issue caused by incompatibility between occultism and shaders specifically. There isn't really a method to fix it other than to turn off shaders at the moment.
