### ISSUE TITLE
Version 0.2.36 - Crash on startup

### ISSUE THREAD

**Issue by juleklO** [AllTheMods/ATM-9#1169]
After installing ATM9 from the ATLauncher and manually downloading the suggested files, launching the instance crashes during splash-screen loading.

I've tried both 8Gb and 16Gb RAM allocation. Issue persists.

[crash-2024-01-12_10.01.04-client.txt](https://github.com/AllTheMods/ATM-9/files/13917603/crash-2024-01-12_10.01.04-client.txt)

**Comment by Mitchell5200** [comment]
The crash report tells you the exact issue in this case, navigate to https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible , and read the documentation there please
