### ISSUE TITLE
Iron's Spellbooks dont use Apotheosis upgrades when in offhand

### ISSUE THREAD

**Issue by NovaOreo** [AllTheMods/ATM-9#1171]
Holding the Apotheosis enhanced Iron's spellbook in my offhand does not apply its base Cast time reduction, max mana increase or added cooldown reduction. 
![2024-01-13_00 35 15](https://github.com/AllTheMods/ATM-9/assets/113480291/9dda0695-007a-4426-a6ce-2a53122e4092)
![2024-01-13_00 35 17](https://github.com/AllTheMods/ATM-9/assets/113480291/1e2ae26f-2afd-44c2-8b1c-8045443d4735)

**Comment by Executorder** [comment]
"when in Mainhand"

**Comment by NovaOreo** [comment]
Ah yes...... im stupid. Thanks
