### ISSUE TITLE
[v0.2.36]Create doesn't apear in JEI search 

### ISSUE THREAD

**Issue by 0xDaniel** [AllTheMods/ATM-9#1172]
Did update from 0.2.32 straight to 0.2.36 and some of create items aren't showing in search. This applies to @ create or just searching the item.
Also playing on server.
![image](https://github.com/AllTheMods/ATM-9/assets/16672167/a4509853-b531-41ea-8136-3cbb4cc9b02f)
![image](https://github.com/AllTheMods/ATM-9/assets/16672167/291dc67d-08bb-4a25-8ee7-502b37b076e3)

**Comment by REsaY01451** [comment]
I'm on current version, 0.2.37, and numerous base Create items aren't showing up in the search. Cogwheels, water wheels, to name a few. I don't have an exhaustive list. The recipes are IN JEI, and if I click on them from the result of other searches (like right clicking on andesite shafts and finding cogwheels that way), the recipe is there and I can even quick-craft.
