### ISSUE TITLE
ATM9 Server Crashing and timing out unexpectedly.

### ISSUE THREAD

**Issue by HaileyMimi** [AllTheMods/ATM-9#1174]
When Playing on the server it seems to randomly at some points when entering certain locations on the map, timeout then proceed to crash. Can't seem to see any issues myself as to why. I will attatch the crash log. 
[crash-2024-01-13_11.51.21-server.txt](https://github.com/AllTheMods/ATM-9/files/13929327/crash-2024-01-13_11.51.21-server.txt)
Thanks for your time,

**Comment by LynBean** [comment]
I think it is related to this issue.
https://github.com/iron431/irons-spells-n-spellbooks/issues/284

**Comment by StijnOnline** [comment]
I was also having this issue and can confirm that version 2.2.1 resolved the issue for me.
