### ISSUE TITLE
Hostile Expansion Mods!

### ISSUE THREAD

**Issue by DarkFlames999** [AllTheMods/ATM-9#1176]
This mod pack should have a new variety of new challenges in the form of your nightly mobs and variety in each vast biome you encounter, so I will introduce a couple of mods I have just in mind to give that excitement.

The Mutant Monsters mod is a mod that takes an old concept of a stronger variation of your typical mobs in the caves and at night, and puts it in the most recent version of Minecraft, this is a fun and challenging mod for you early-game players.
 Mutant Monsters Mod: https://www.curseforge.com/minecraft/mc-mods/mutant-monsters
 
 The Enemy Expansion mod adds a variety of completely new mobs both in the daytime and at night for a couple of biomes, some of these mobs are a little tougher than your typical everyday mobs, but come with rewards if slain
 Enemy Expansion Mod:https://www.curseforge.com/minecraft/mc-mods/enemy-expansion
 
 The Born in Chaos mod adds new challenges and monsters to face at night in the form of new undead mobs, new spirit mobs, new terrifying beasts, and even aquatic dangers, giving all sorts of challenges to the player, with rewards that will make it worth the trouble of fighting these beasts
 Born in Chaos Mod:https://www.curseforge.com/minecraft/mc-mods/enemy-expansion

**Comment by Mitchell5200** [comment]
Use #1 for mod suggestions, not a new issue post
