### ISSUE TITLE
Dimensional Card not working

### ISSUE THREAD

**Issue by lwgabo** [AllTheMods/ATM-9#1179]
![2024-01-15_03 07 12](https://github.com/AllTheMods/ATM-9/assets/156643260/89447fde-5be3-4248-b7ce-a9c7c73badf1)
Hello, I am having a problem with the dimensions and global mod with the range improvements the number changes but with these it remains like this

**Comment by mixednutts** [comment]
Try using the normal wireless transmitter instead of the advanced.

**Comment by lwgabo** [comment]
> Try using the normal wireless transmitter instead of the advanced.

not working I tried with all versions of wireless, both grid and others, but a certain number of blocks away from the warehouse never works, even with global or dimensional cards.

**Comment by lwgabo** [comment]
Thank you very much, I used the normal transmitter and not the improved one and putting the improvement there worked, thank you
