### ISSUE TITLE
JEI recipe registry takes too long

### ISSUE THREAD

**Issue by Splarkszter** [AllTheMods/ATM-9#1186]
Hello, good day y'all.

So i have a PC with 8GB of RAM and i have been struggling to run the modpack because of the nature of it, i know, just bear with me.

I have the problem that JEI is taking forever to build(?) recipes so i can never join a server

``[00:00:00] [pool-27-thread-1/ERROR] [me.je.li.lo.PluginCallerTimerRunnable/]: Registering recipes: jei:minecraft is running and has taken 2.426 minutes so far``

CPU is constantly at 100% so I don't know if it's building the recipes or something else.

I tried removing JEI but for some dumb reason the modpacks makes it required by the server (there is no reason for JEI to be required by the server):
``[20:11:23] [Netty Client IO #1/ERROR] [ne.mi.ne.NetworkRegistry/NETREGISTRY]: The server is likely to require channel [[jearchaeology:jea]] to be present, yet we don't have it``

**Comment by Splarkszter** [comment]
Anyway the issue of JEI being so dumb that it can't load the recipe libraries is solved by using the actually well made REI... gosh why people keep using JEI.

**Comment by The1goit-Dev** [comment]
experiencing the same problem here, and my PC has 16GB ram, replacing JEI with REI caused a problem with more overlays, and deleting that solved it. but now the game freezes when the world loads.
