### ISSUE TITLE
game crash a few second later

### ISSUE THREAD

**Issue by Hal0gen3s** [AllTheMods/ATM-9#1188]
Some time after entering the world, the screen freezes and the game shuts down, and I get this 

[crash-2024-01-17_17.46.46-server.txt](https://github.com/AllTheMods/ATM-9/files/13966740/crash-2024-01-17_17.46.46-server.txt)

**Comment by XxNukeclearxX** [comment]
After looking at your crash log via using mclo.gs to find a solution for you, it looks like you have a bee that is causing a ticking entity error. 
![Screenshot 2024-01-17 232557](https://github.com/AllTheMods/ATM-9/assets/27360129/0b324027-9bbd-416b-a654-1a8960b8f600)

If possible, I would try to kill the bee. A method to do this would be going down a version of the modpack, killing said bee in the listed cords, and then trying to update again to see if that issue persists.

**Comment by Hal0gen3s** [comment]
Thanks for the help, I'll get back to you if it works, and I'll get back to you if it doesn't work :D

**Comment by Hal0gen3s** [comment]
Also, there are 10 bees in a 3x3x3 area, and there are 10 of these areas. Would having too many bees in this 3x3x3 area cause a problem?

**Comment by Hal0gen3s** [comment]
I'm just asking out of curiosity, if I'm not mistaken, there is no "not enough crash" mod in the modpack. This mod can be added and it would be better for both players. Just a suggestion, you can ignore it

**Comment by Hal0gen3s** [comment]
Btw problem solved I kill all bees

**Comment by XxNukeclearxX** [comment]
Glad to honestly hear the problem was resolved. I definitely will look into the "not enough crashes" mod as well for my own personal benefit. Thanks for that! :D
