### ISSUE TITLE
Recipes not working(single player world) need help 

### ISSUE THREAD

**Issue by Usamamqsood** [AllTheMods/ATM-9#1191]
It's been a month since I downloaded ATM9 multiple times. Everything downloads and installs perfectly, and it runs well. However, I'm having issues crafting ingots from nuggets, turning coal into coal blocks, and converting iron ingots into iron blocks. Additionally, I can't make glass by smelting sand. Please help if anyone knows how to fix these issues. Thank you.

**Comment by Kevin-Marsh** [comment]
These issues are caused by a corrupted install that didn't get the proper gregtech config file in the download.
