### ISSUE TITLE
Create Hose Pulley not botmoless with biodiesel

### ISSUE THREAD

**Issue by Nidaelie** [AllTheMods/ATM-9#1196]
Create pump filling an inw rold tank (10k buckets) for botmless hose pulley and making the fluid source infinite is destroying excess fluid in the filling when it should stop filling.
Then the pulley dont recognize the blocks.

Even when detecting the pump dont pump out anything. but if u revert the pump ot fill the pulley, it admits more buckets but destroys them if the 10k goal has been reached

Expecting: botomless biodiesel and pump pumping out infinite fluid

**Comment by Nidaelie** [comment]
![2024-01-18_16 53 24](https://github.com/AllTheMods/ATM-9/assets/31002746/d8d049e2-c38a-4242-a75c-60bd5b9b2e3d)

**Comment by Nidaelie** [comment]
have tried sinking more blocks, 1 to the bottom and nothing works

If asked, have removed all fluids and i have more than 10k buckets. Did 2 times..

With the pool filled with lava works perfectly

**Comment by screret** [comment]
Only water & lava can be bottomless in base create iirc.

**Comment by Nidaelie** [comment]
as u can see in the screenshot it says bottomless with biodiesel...

**Comment by screret** [comment]
Gonna guess that's a bug as it really shouldn't be bottomless AFAIK.
Do tell me if i'm just wrong.

**Comment by Nidaelie** [comment]
i guess if the pulley shows bottomless then it is configured to allow all in the config...

**Comment by Jmpp2909** [comment]
In the Create config, fluids that are allowed to be extracted as infinite are Whitelisted, meaning it would need a manual change to add another. Afaik, Create can consider something Bottomless, but not pull infinite, as those 2 are different things.

This is the source for the bottomless config
[allow.json](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/tags/fluids/bottomless/allow.json)

and this is the default value for the "allow.json"
{ "replace": false, "values": [ "minecraft:water", "minecraft:lava" ] }

So yeah, unless its manually changed, only water and lava work.
