### ISSUE TITLE
Main menu scales up to mutch on x3

### ISSUE THREAD

**Issue by Goten87** [AllTheMods/ATM-9#12]
when i set my GuiScale to 3 this happens
im gaming on 1080P screens
when i go to the ingame menu its fine again
<img alt="Windowed" src="https://cdn.discordapp.com/attachments/432318605238075403/1120336330912698378/image.png">
<img alt="Fullscreen" src="https://cdn.discordapp.com/attachments/432318605238075403/1120336672282910772/image.png">

**Comment by GordonHollow** [comment]
Can confirm it, has the sam issue
scale of 3 - do exactly this
i also on 1080p

**Comment by whatthedrunk** [comment]
i might have made it better with the new update but if not disable fancy menu. Pack Menu should be added in the next day or two.

**Comment by Goten87** [comment]
i can see it all now but its still way to big xD but i can click all the buttons now

**Comment by whatthedrunk** [comment]
Fixed thanks
