### ISSUE TITLE
Server Crashing on startup - 0.2.37

### ISSUE THREAD

**Issue by RileyOard** [AllTheMods/ATM-9#1202]
Hi,

For some reason a few days ago my server started crashing on startup. I attempted to update to the newest version (2.37) and didn't seem to help the issue.

[crash-2024-01-19_18.20.02-fml.txt](https://github.com/AllTheMods/ATM-9/files/13995510/crash-2024-01-19_18.20.02-fml.txt)

**Comment by JAKAMI99** [comment]
Try the following:

    Locate the supplementaries-common.toml file in your server's mod folder (in this case, /C:/Users/roard/Desktop/Server-Files-0.2.37/Server-Files-0.2.37/mods/).

    Delete the supplementaries-common.toml file.

    Restart your Minecraft server.

**Comment by RileyOard** [comment]
Dude that worked thank you so much

**Comment by JAKAMI99** [comment]
Glad I was able to help :) Have fun
