### ISSUE TITLE
NBT related Duplication glitch

### ISSUE THREAD

**Issue by Pipeline929** [AllTheMods/ATM-9#1203]
As much as I have enjoyed messing with it, I feel it's time I report it. Granted my server is running 0.2.35, but I don't see this mentioned anywhere. There seems to be a duplication glitch between the cable tiers mod, refined storage, and dank storage. Any item that seems to have similar NBT data can be duplicated within a dank using refined storage and a dank in a dock. This works with Apotheosis Gems and enchanted books, as well as certain containers like bundles or thermal series satchels. 

Using any of the 3 tiers of exporters from Cable Tiers, connected to a refined storage system, and pointed to a dank in a dock. Set the exporter's filter to the item you want to dupe (the filter is not super specific as long as it interacts with the item, so any Apoth gem works for all the Apoth gems) and set the exact mode to off. Have the exporter target the dank in a dock and be sure to have a Refined Storage External Storage attached to the dank. When you have the loop of the external storage and exporter set up on the Dank, drop the item you want to dupe into the Dank first, then the item to be converted into the Dank second, the result should be a duplication of the first item. This does not seem to work "remotely" by adding it into the Refined Storage system using a Grid, it needs to be done manually into the Dank. 

I have added a link to a short video showing the glitch in action, if you would like any more information please let me know, or if my link is not allowed I can change it into a GIF or something. I had someone in the ATM discord attempt the process with an AE2 system but they did not have the same result. Granted they used the base exporter from AE2 (of which I don't know if there is a mod adding improved ones like Cable Tiers for RS).

https://imgur.com/a/tcWmVBp

**Comment by Pipeline929** [comment]
Wanted to add, that I just tested it and it works with Danks themselves as well, so a Dank holding items can be duped using an empty one. They have to be the same tier as one another but it does dupe the contents inside.

**Comment by Bossxer** [comment]
> Wanted to add, that I just tested it and it works with Danks themselves as well, so a Dank holding items can be duped using an empty one. They have to be the same tier as one another but it does dupe the contents inside.

how do you do this?

**Comment by Pipeline929** [comment]
the dank dupe works the same as the gem dupe, set the export filter to whatever tier dank, put the dank with items in FIRST, then add a second empty (or full if you want to overwrite the items) inside the dank placed in world. Your initial dank with items should now show there are 2 inside the in-world dank and they should have the same items. This also works with the immersive satchels (I think that's what they are called).

**Comment by Pipeline929** [comment]
> > Wanted to add, that I just tested it and it works with Danks themselves as well, so a Dank holding items can be duped using an empty one. They have to be the same tier as one another but it does dupe the contents inside.
> 
> how do you do this?

the dank dupe works the same as the gem dupe, set the export filter to whatever tier dank, put the dank with items in FIRST, then add a second empty (or full if you want to overwrite the items) inside the dank placed in world. Your initial dank with items should now show there are 2 inside the in-world dank and they should have the same items. This also works with the immersive satchels (I think that's what they are called), in the same way, just change the export filter.

**Comment by Pipeline929** [comment]
UPDATE:

This dupe seems to work with just about any container, not just a dank storage. Tested it with Soph backpacks, Supplementary Sacks, as well as a normal vanilla chest. The only factors to the dupe seem to be a Refined Storage "External Storage" with default settings, a Cable Tiers "Exporter" of any tier set with the filter of the item you wish to dupe, and Exact Mode set to OFF. Other than that, a basic/simple RS setup I assume is all that is needed besides the specified things above. Using a controller, Grid (non-crafting one), and a 1k storage block for my testing, but when I found this glitch I had an RS setup with drives and multiple grids (crafting, fluid, etc.)

**Comment by Bossxer** [comment]
> UPDATE:
> 
> This dupe seems to work with just about any container, not just a dank storage. Tested it with Soph backpacks, Supplementary Sacks, as well as a normal vanilla chest. The only factors to the dupe seem to be a Refined Storage "External Storage" with default settings, a Cable Tiers "Exporter" of any tier set with the filter of the item you wish to dupe, and Exact Mode set to OFF. Other than that, a basic/simple RS setup I assume is all that is needed besides the specified things above. Using a controller, Grid (non-crafting one), and a 1k storage block for my testing, but when I found this glitch I had an RS setup with drives and multiple grids (crafting, fluid, etc.)

i can not seem to re create it on 2.0.39

**Comment by starforcraft** [comment]
This bug is now fixed with Cable Tiers version 1.2.2
