### ISSUE TITLE
Blackhole unit dup glitch

### ISSUE THREAD

**Issue by MrXkrules** [AllTheMods/ATM-9#1204]
Hi. I'm using AE2 with industrial foregoing blachhole units in controllers. For some reason sometimes blackhole units loose perception what items are in them. So when you try to add different item into them, those inside the unit gets trasformed into that item. I had unit with 100k redstone and now it is glowstone. And my quartz is now 32k swords from silent gear (I really don't like silent gear. Hope Tinker will come back). It looked like problem with extended AE but now i'm not sure cause it happened again even though i removed them from my base.

**Comment by juliuskolosnjaji** [comment]
Hi there! Do you have any new information about this glitch. Any procedure you know to replicate this glitch?

**Comment by MrXkrules** [comment]
Not right now. My computer blew up recently so it's in warranty service. As soon as I get my computer back I'll test out multiple scenarios and give more findings about this.

**Comment by Kevin-Marsh** [comment]
This is a known bug that has existed in Industrial Foregoing for at least three years. It can't be fixed from our end. I would suggest not using IF storage with applied energistics or refined storage.
