### ISSUE TITLE
Low FPS on Linux

### ISSUE THREAD

**Issue by JAKAMI99** [AllTheMods/ATM-9#1205]
I have pretty bad performance on Linux, even without a Shader.
The GPU is almost idling, while one CPU core is at 100%.

Decreasing the RAM Setting doesn't helped

**Comment by ProjectSynchro** [comment]
Which drivers do you run? What are your system specs?

**Comment by JAKAMI99** [comment]
Hey, thanks for your answer.

My Specs are:
OS: Ubuntu 22.04.3 LTS x86_64 
Kernel: 6.5.0-15-generic 
CPU: Intel i7-9700K (8) @ 5.000GHz 
GPU: NVIDIA GeForce RTX 2070 Rev. A 
Memory: 47975MiB (DDR4)

My Driver Version of the RTX2070 is "535.154.05"


When enabling a shader, even with mid-settings, I get around 30–60 fps ob a QHD Monitor

**Comment by ProjectSynchro** [comment]
I don't personally have NVIDIA hardware anymore, but I do know the 535 series driver is really bad, especially in Vulkan applications (performance across everything is also effected). You can try and roll back to an older driver (the 525 series seems to be a good pick). You can also try the 545 drivers as well. 

If you're using Wayland, you should also try playing in X11 and see if you get better performance there.
