### ISSUE TITLE
Ridiculite bee conversion doesnt work - latest 0.2.37

### ISSUE THREAD

**Issue by kevin-meyers** [AllTheMods/ATM-9#1208]
This happened previously https://github.com/AllTheMods/ATM-9/issues/992#issue-2038271037

Item converstion for ridiculite egg should become insanite but becomes inanite instead.

It also happens with only a ridiculite bee in the hive and most importantly - It wont convert to insanite with only the inanite bee in the hive!! So as of right now I have been unable to create one

I also tried without simulation upgrades of course, same outcome

![image](https://github.com/AllTheMods/ATM-9/assets/37648386/a5e0b39a-7cae-42c2-a017-e60d31125ada)

![image](https://github.com/AllTheMods/ATM-9/assets/37648386/e0ca9d88-ca11-4567-8f4f-cb0413cb5b06)

![image](https://github.com/AllTheMods/ATM-9/assets/37648386/65ce7b84-5795-4b05-9920-599c92af40e1)

**Comment by d4yy** [comment]
Issue still present on 0.2.59 - Ridiculite egg does not convert to insanite and if you have a ridiculite bee in the hive or an adjacent hive it will incorrectly convert it to an inanite egg

**Comment by bashamahmoud** [comment]
Same problem here on 1.1.1 the current last update. I try to separate the hive to somewhere else yet it doesn't want to convert. Also, if there is a radioactive bee or a ludicrite bee, it will convert to blutonium bee and inatite bee respectivly.
