### ISSUE TITLE
[0.2.38] datapack change on existing world

### ISSUE THREAD

**Issue by jpruitt2297** [AllTheMods/ATM-9#1217]
When loading a single player world from pre-0.2.38, game tells me due to datapack change that it can't load said world unless I load in "safe mode" or install datapack manually. Any fix or am I fine to load into "safe mode"? And if I do need to install datapack manually, where might I find it in the installed files?
![datapack safe mode screen](https://github.com/AllTheMods/ATM-9/assets/49281856/2adda172-6f2e-49ae-8d74-66ea13b42a4a)

edit 1: log for info
https://paste.atlauncher.com/view/19f15ad4-31ff-408d-a698-48187154b7d0

edit 2: downgraded back to 0.2.37, world loads just fine

**Comment by Mitchell5200** [comment]
Please check the config `serverconfigupdater-common.toml` in the configs folder and compare to https://github.com/AllTheMods/ATM-9/blob/main/config/serverconfigupdater-common.toml, if it does Not match, copy the config contents from Github and replace the local config,

OR, Path to `/kubejs/data/sgjourney/` and delete `worldgen`

**Comment by deccer** [comment]
Hey ho,

just wanted to let you know that I also stumbled upon this very error, same setup.

`serverconfigupdater-common.toml` was identical, deleting `worldgen` in `...sgjourney` made it work again.

**Comment by jpruitt2297** [comment]
serverconfigupdater-common.toml is correct and sgjourney worldgen has been deleted, this worked. Thanks
