### ISSUE TITLE
[Crash] "java.lang.NullPointerException: Registry Object not present: cataclysm:sticky_gloves"

### ISSUE THREAD

**Issue by ArsiTheFox** [AllTheMods/ATM-9#1219]
Getting a massive crash when opening Creative inventory:

Exception: "java.lang.NullPointerException: Registry Object not present: cataclysm:sticky_gloves"

 

CrashLog: https://pastebin.com/e7bYTPLx
[crash-2024-01-23_19.36.02-client.txt](https://github.com/AllTheMods/ATM-9/files/14031650/crash-2024-01-23_19.36.02-client.txt)

**Comment by IvySong73** [comment]
I had this issue, found out I hadn't done the server upgrade properly and there were duplicate versions of mods.  
My fix was to recreate the server using the updated files, move my world file over, and adjust the server properties.

**Comment by ArsiTheFox** [comment]
> I had this issue, found out I hadn't done the server upgrade properly and there were duplicate versions of mods. My fix was to recreate the server using the updated files, move my world file over, and adjust the server properties.

That was it xD, my bad.....

**Comment by ArsiTheFox** [comment]
Thank you <3
