### ISSUE TITLE
Bad Server Performance - Low TPS 

### ISSUE THREAD

**Issue by JAKAMI99** [AllTheMods/ATM-9#1220]
Hey, I have a pretty decent server, and I am running the newest ATM9.
I still experience awful performance, lags etc. (I am running this server in my local LAN so no network lag)
I ran a spark report, but I really don't know how to properly interpret the information.

 https://spark.lucko.me/KQWw37pMfn

**Comment by JAKAMI99** [comment]
Another report, recorded while the red moon was active, so there were lots of entities :)
CPU usage is pretty low, RAM is set to min 10G, max 20G. Spark seems to report it wrong, or I am missing something

https://spark.lucko.me/t6LPzd5nbR

**Comment by HeroYui** [comment]
I am having the same Issue.
From what I am reading the brunt of the performance hits are Mob Entities like Sheep and Spiders and the like.
Is there a way to reduce the lag besides of adding a mod regarding mobs (and their AI?)
Or how should this be approached?

https://spark.lucko.me/I7aT6yupEK

**Comment by Kevin-Marsh** [comment]
Enhanced celestials was removed from the pack which should alleviate the issue.
