### ISSUE TITLE
Debug menu breaks when pressing Alt + F3 to open it

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-9#1226]
In All the Mods 9 version 0.2.39, using Alt+F3 to open the debug menu breaks it, causing the game to think the debug menu is open even though none of it is rendering. No errors are logged to the console during this.

If Better F3 is enabled, pressing Alt+F3 to close the debug menu will not work unless the mod is disabled via its config option. Even then, the vanilla debug menu can render when opened with F3, but not if opened with Alt+F3.

This is most likely caused by something breaking the rendering of the FPS and TPS graphs in such a way so as to make the entire debug screen nonfunctional when these graphs should be visible.

(The exact issue was found in an instance where Journeymap was replaced with Xaero's World Map and Minimap, but that shouldn't affect reproducibility.)

**Comment by agaring** [comment]
To give more info, this happen even with a fresh 0.2.39 install.
When pressing `Alt + F3`, something in the rendering pipeline break hard enough that you need to restart Minecraft.
This also cause other HUD element such as **Jade** to be broken.

Will update this post as I learn more.
