### ISSUE TITLE
[0.2.39] Game Crashes to Desktop upon pondering the Conductor Cap in Create: Steam 'n' Rails

### ISSUE THREAD

**Issue by MikuLittle** [AllTheMods/ATM-9#1229]
https://pastebin.com/1iZtGAkE

Forge 47.2.19
MCP 202301612.114412
ModernFix 5.12.1+mc1.20.1
MC 1.20.1
ATM 0.2.39

Upon pondering the Conductor Cap, and moving to the second scene, the game hard crashes when I click through the scenes chapters.  The crash log is uploaded above.

**Comment by myLogic207** [comment]
Hm, maybe check your files or for other mods. This does not happen to me, pondering and clicking through the scenes works just fine
