### ISSUE TITLE
[0.2.39] Creative Jetpack is not craftable

### ISSUE THREAD

**Issue by gsmith2885** [AllTheMods/ATM-9#1231]
The Creative jetpack has a recipe but it is not craftable. I have tried both my existing unobtainium pack and created a new one to rule out NBT being the issue. I have also tried RS, AE2, backpack crafting, and a vanilla crafting table.

![image](https://github.com/AllTheMods/ATM-9/assets/16124897/df68f327-ecd3-43af-8902-2151e2215d35)

**Comment by Burkino** [comment]
The issue is with the jetpack, it can't be charged what so ever since this adds new NBT data. So disable any wireless charging, and make a new one
