### ISSUE TITLE
Refined storage Crashing when I access it any ideas

### ISSUE THREAD

**Issue by jfox166** [AllTheMods/ATM-9#1234]
[crash-2024-01-26_13.16.59-client.txt](https://github.com/AllTheMods/ATM-9/files/14069448/crash-2024-01-26_13.16.59-client.txt)

**Comment by jfox166** [comment]
https://mclo.gs/x1xcXr3

**Comment by Ash-Nuke** [comment]
Did you by any chance attempt to autocraft or anything like that? I know I ran into an issue with getting a Java error when trying to craft a cover from JEI itself when in a grid from RS.

**Comment by shade1822226911** [comment]
Maybe you had tons of items with nbt? I lost a world because of that
