### ISSUE TITLE
Single player world crashes on new update 

### ISSUE THREAD

**Issue by Un1dent1f1ed** [AllTheMods/ATM-9#1235]
Can someone tell me what has happened to the world 
[crash-2024-01-23_23.38.42-server.txt](https://github.com/AllTheMods/ATM-9/files/14070401/crash-2024-01-23_23.38.42-server.txt)

**Comment by XxNukeclearxX** [comment]
After reviewing the crash log itself, it looks like your client is unable to read this config file: "jumbofurnace-server.toml" which is odd as that could mean it may not have access to do so OR something was corrupt during the first install of this update or even the modpack itself. Did you by any chance update from a previous version? Have you also attempted to do a clean install? Is this world from a previous version as well?
