### ISSUE TITLE
Unable to craft breaker module from modular routers

### ISSUE THREAD

**Issue by SimonSoby** [AllTheMods/ATM-9#1236]
Hello.

Currently trying to craft som breaker modules from modular routers. But no matter what pickaxe i use, wooden or diamond, the breaker module only comes out as the level of an iron pickaxe. Also not able to craft the module with any enchants on it

![Screenshot_2](https://github.com/AllTheMods/ATM-9/assets/25232087/6a61cbfe-1286-4e71-9862-71df001cf232)

**Comment by Meepsauce** [comment]
Have had the same issue, it's a bug with Modular Routers. They've fixed this in 12.1.1 MC-1.20.1 on the 24th Jan but the pack needs to update it.
https://www.curseforge.com/minecraft/mc-mods/modular-routers/files/5056687
