### ISSUE TITLE
[Recipe] ATM Star in Star Forge requires 9x fewer nether stars

### ISSUE THREAD

**Issue by contra1337** [AllTheMods/ATM-9#1238]
Recipe in Star Forge for ATM Star states 1,574,640 mB liquid nether stars. Each nether star creates 144 mB

1574640 / 144 = 10,935 nether stars

Crafting the ATM star using create requires 9\*9\*9\*15 = 10,935 nether star **Blocks**

Correct requirement should be 14,171,760 mB liquid nether stars

Its possible this is intentional or fine since the star forge is so far down the gt progress line. It is mainly just an inconsistency imo

**Comment by Burkino** [comment]
If you want to make the star forge you need an atm star block, at which point you'll probably already have starry bees producing more atm stars than you'll ever need

**Comment by contra1337** [comment]
> If you want to make the star forge you need an atm star block, at which point you'll probably already have starry bees producing more atm stars than you'll ever need

Sure, you probably have all the materials in abundance. Should every other part of the recipe also be cheaper then instead?

Like I said, not a big deal, it's just inconsistent
