### ISSUE TITLE
Allthemodium Alloy Paxel got consumed crafting a Traveler's Backpack

### ISSUE THREAD

**Issue by ralphocdol** [AllTheMods/ATM-9#1241]
One of the crafting recipe for getting a Standard Traveler's Backpack is using shears and an existing backpack variation, like a Cow Traveler's Backpack. With shears, the shear will lose some of its durability but will not be consumed.

The paxel is included in the crafting recipe as a shear replacement, but the problem is it is consumed, which should not be the case as it is pretty expensive and tedious to make.
![Crafting Recipe](https://github.com/AllTheMods/ATM-9/assets/31056871/a7dc7cc4-836f-4494-9409-1f8780581644)

**Comment by terminatorbs** [comment]
Same issue when crafting advanced beehives - it consumes the alloy paxel. lost mine not even half a day after getting it. this is on 0.2.40.

**Comment by James103** [comment]
The Allthemodium Alloy Paxel is coded not to have durability. For almost all intents and purposes, this is equivalent to having infinite durability, but the crafting recipes mentioned treat these items as if they were single-use, and completely break them in the process.

**Comment by Kevin-Marsh** [comment]
This is an issue  caused by the compatibility for the Paxel to be used as a pair of shears. It can't be fixed unless the ability is removed. We can only suggest to be careful to verify the correct item usage when making recipes that use shears.
