### ISSUE TITLE
Various Quest issues

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/ATM-9#1244]
So I've been waiting for a few versions now for a couple of quest issues to be fixed,  I am hoping this can be a pinned list for others to use perhaps? A reference for AlfredGG or whomever takes up his mantle.

Gregtech Getting started > Handy tools > Wrenches, Scythes & Butchery Knives.
Half a dozen or so of them in the list look to have enchants that do not come with the actual item when made.

Evilcraft > Blood Brooms
I have no idea why the bare rod is not triggering however it is also happening to the final product at any blood level.

I think there's a few more but people are late logging in today and can't confirm before submitting..

**Comment by myLogic207** [comment]
Adding to the list: some Applied Energistics Quests (the interfaces one and another one in the autocrafting section)
