### ISSUE TITLE
Color Applicator Quest

### ISSUE THREAD

**Issue by Trev57** [AllTheMods/ATM-9#1245]
AE2 Color Applicator Quest Issue

Similar to https://github.com/AllTheMods/ATM-8/issues/647 similar to this post, having issues with the color applicator quest. Made a color applicator, the color applicator quest is not completing.

I initially made one, and it didn't complete, but then I saw the other dependencies, and completed Energy Cell. 

Even after completing this dependency the quest has a checkmark but is greyed out?
It even says 100 percent complete, and I've tried to make more applicators, but nothing seems to work.

![image](https://github.com/AllTheMods/ATM-9/assets/51894945/dd9443d7-5b69-470f-9bfa-22347df54ef9)

**Comment by Furious1964** [comment]
Getting the same thing, but quest is stuck at 0%.

**Comment by Ego8316** [comment]
We had the same issue, we solved it by reseting the quest with the command /ftbquests change_progress @a reset 03E6FA4DCB71162E
After that, once both 4K ME Storage Component and Energy Cell are completed, take the Color Applicator in the inventory and the quest should complete. At least that worked for us

**Comment by TheBedrockMaster** [comment]
Still a problem?

**Comment by TheBedrockMaster** [comment]
Works fine for me, make sure you have all the dependencies complete. Add quest bug label.

**Comment by snsm-uptime** [comment]
This is failing for me too with the same conditions. I was unable to run that command on the current version.

**Comment by ryantheleach** [comment]
Color Applicator has prerequisites that do not match the graphic / it's position.

4k ME Storage Componet, Energy Cell, and Basic Cabling.

It's pretty confusing.

<img width="1038" height="537" alt="Image" src="https://github.com/user-attachments/assets/b7568014-3739-4270-9578-a0179aacd040" />

<img width="865" height="833" alt="Image" src="https://github.com/user-attachments/assets/58696602-0ea8-42d8-bc26-4eb1cd4c935b" />

**Comment by ReHWolution** [comment]
Same thing happening to me. I thought it was because of the dimensional card charging the applicator. Turned it off, completed everything else, it doesn't get ticked as completed despite completing the dependencies :\
