### ISSUE TITLE
Error: java.lang.NullPointerException: Registry Object not 

### ISSUE THREAD

**Issue by BMag108** [AllTheMods/ATM-9#1246]
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Registry Object not present: cataclysm:curse_of_desert

[crash-2024-01-29_14.11.05-client.txt](https://github.com/AllTheMods/ATM-9/files/14085290/crash-2024-01-29_14.11.05-client.txt)

]
fresh installation of ATM9, connecting to my private server after updating version

**Comment by djnifos** [comment]
Redo your server update using one of the methods on the guide.  This crash means that somehow two versions of cataclysm loaded.

https://alltheguides.pages.dev/help/server/#updating
