### ISSUE TITLE
[0.0.40] Using certain FramedBlocks on Create trains crashes the client on assembely and renders the world unjoinable

### ISSUE THREAD

**Issue by rinyafii** [AllTheMods/ATM-9#125]
When using some "Double" FramedBlocks on a Create train, they tend to crash the client when attempting to assemble the train. The world this was done at now become permanently inaccessible because the train is still assembled with the bugged block.

[crash log](https://mclo.gs/FGp2klw)
[full log](https://mclo.gs/zRX4Mfj)

**Comment by XFactHD** [comment]
A new version of FramedBlocks with a fix for this has just been approved on CurseForge.
