### ISSUE TITLE
Brass Gear Missing Recipe

### ISSUE THREAD

**Issue by Ash-Nuke** [AllTheMods/ATM-9#1250]
Hi there! 

I've discovered that the brass gear from AllTheOres does not have a recipe for the Multiservo Press at all. (See attached photo below)

I expected to be able to throw 4 brass ingots into the machine with the gear mold, but instead have discovered that it's blank. 
To recreate this:
1. Open JEI
2. Search "brass gear" (or brass and find the gear itself)
3. Look at the recipe that shows the Multiservo Press machine from Thermal Expansion.
4. The missing recipe will appear right there.

My game's version is outdated. However, after looking through the GitHub in both open and closed tickets, there was none to be found about the missing recipe for this error.

All the Mods 9 Version: 0.2.34 is the version of this error being discovered. I've not checked other versions of the pack to identify this issue yet or not but will be doing so shortly after posting this. 

**EDIT:** I forgot to put the screenshot originally. Here it is.
![Brass Gear Recipe in Multiservo Press](https://github.com/AllTheMods/ATM-9/assets/27360129/b2f3e854-74b7-496d-8527-a8f8c6a93790)

**Comment by shade1822226911** [comment]
can confirm with unobtainium gears in 0.2.40

**Comment by Ash-Nuke** [comment]
Can also confirm with allthemodium gears and vibrainium gears too. Only way around it is making a metal press from Immersive Engineering but even then.
