### ISSUE TITLE
Allthemodium ore is lame

### ISSUE THREAD

**Issue by Magesticles** [AllTheMods/ATM-9#1255]
So I need help understanding how this adds a fun gameplay element to the pack. Is it beneficial to the modpack to have "Allthemodium ore" thats so rare to find its borderline completely not fun to play the pack? My answer is, no, allthemodium ore is not beneficial whatsoever. 

Oh yay, on my brand new world I have to find the Deep dark, and search endlessly along the walls for a item just so I can continue progressing. 
I've tried the legit way, using the nature compass and looking. Once there at the deep dark, I simply never find it. Even cheated in the allthemodium sight, and could not find it. Please tell me, how is this any kind of fun when I NEED this one stupid ore to progress the pack?
Ok fine, I kill the warden that finally spawned, got a allthemodium ingot from the questbook. That helps a little, but its only one. I need more. So I go to the mining dimension, start looking at y20 to -y59. No dice. Ok fine, cheat in the allthemodium sight. Still nothing! I was using a hammer in creative mode destroying miles of blocks underground, and found nothing. 

WTF is the point here. Please for the love that all is holy, change this. This progression halter just tightens my butthole.

**Comment by CoalSephos** [comment]
use a rftools miner in the mining dimension then just mine the allthemodium ore it leaves behind

**Comment by TrickyTz** [comment]
You only need two AllTheModium to easily get more. Use one to make a teleport for the mining dimension. Use the other one to make 3 AllTheModium Sight Potions and then Charm of AllTheModium Sight.

Go in the Mining Dimension, get down on DeepSlate height and activate the charm. You can easily geht a couple of hundred AllTheModium Ores
