### ISSUE TITLE
The Beyond???

### ISSUE THREAD

**Issue by RaxtL** [AllTheMods/ATM-9#1256]
I have gone to the beyond and I am faced with this
![2024-02-01_13 57 59](https://github.com/AllTheMods/ATM-9/assets/150716463/ed6cb597-11f5-4d80-851b-d17e6e791db2)

Any ideas how to regen? I've flown 2,000 in all directions and no land.
![2024-02-01_13 58 11](https://github.com/AllTheMods/ATM-9/assets/150716463/4f11b464-d0a7-4fa4-aa63-ac29cb2c70ac)

please help.

**Comment by djnifos** [comment]
It is a void, it's meant to be, you can base there for more FPS if you want.

**Comment by RaxtL** [comment]
But its like that 1,000 in all directions and I went down until I dies and up to y:100 and its all like this, I thought I had to find and mine stuff from there?

**Comment by Mitchell5200** [comment]
nope, just build out from your teleport pad

**Comment by Mrlucifer71** [comment]
love it
