### ISSUE TITLE
[0.2.40] Elytra "Boost" on Orthogonal and Diagonal lines every 300 blocks

### ISSUE THREAD

**Issue by RobynIsi** [AllTheMods/ATM-9#1257]
I noticed that at certain spots around my base, whenever I used the Elytra straight up, I would fly infinitely upwards, this also has the affect of boosting the player towards the direction they look in.
https://github.com/AllTheMods/ATM-9/assets/145802553/584af941-449f-4ff4-bd94-29b1e8030eef
(Video of proof of this event happening, it is consistent, at the very end I F3 if that info is required)

I went into a creative world and tested where this happens. I noticed that at every 300 block intersection (0, 0; 0, 300; -300, 0; etc.) straight lines in every orthogonal and diagonal direction has this attribute. (-inf to inf, 0; 0, -inf to inf; 1, 1; 2, 2; etc. as well as 300 + any of the coordinates)
![2024-02-02_00 36 03](https://github.com/AllTheMods/ATM-9/assets/145802553/8af46889-948b-40d0-9867-0ab175da7d2e)

I did not expect this when I started to use the elytra, I assumed it would work the same way it has in previous versions of unmodded minecraft, where there is no boost whatsoever.

This issue was found in 0.2.37 and confirmed to happen in 0.2.40

**Comment by Jaydenpoyser4** [comment]
could it be laylines from Mahou Tsukai you cant see them unless you use magic but if you use and elytra it gives you a boost and lets you go forever as long as you follow the line or on it cause every line has a center at some point

**Comment by RobynIsi** [comment]
Looking through some Reddit posts, this seems to be exactly it. Is there any way to disable the boost? The mod menu doesn't show the config for Mahou Tsukai.

**Comment by RobynIsi** [comment]
Forgot to close, thanks for the help, let me know if there is a way to disable this feature!

**Comment by Jaydenpoyser4** [comment]
> Forgot to close, thanks for the help, let me know if there is a way to disable this feature!

maybe if you check conifgs i can check for you if you need me to

**Comment by Jaydenpoyser4** [comment]
> Forgot to close, thanks for the help, let me know if there is a way to disable this feature!

but also laylines are important for mahou
