### ISSUE TITLE
it wont let me update my server 

### ISSUE THREAD

**Issue by Jaydenpoyser4** [AllTheMods/ATM-9#1262]
i asked the people who run my server hosting pebble host and they said it was a modpack issue so i am here to get help when i update the pack on my server it says 02.02 21:38:49 [Server] main/[WARN] [minecraft/Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode i took it to a staff member from pebble host and this is what was said 
![image](https://github.com/AllTheMods/ATM-9/assets/105961470/8a8275b6-18a4-42ea-a193-064a7a200065)

**Comment by Mitchell5200** [comment]
Probably related to https://github.com/AllTheMods/ATM-9/issues/1225#issuecomment-1907855315
