### ISSUE TITLE
[0.0.40] Game crashes when hovering over the filter buttons on Trash Can mod trash cans

### ISSUE THREAD

**Issue by rinyafii** [AllTheMods/ATM-9#127]
[crash log](https://mclo.gs/X3Kp3j4)
[full log](https://mclo.gs/V6PVX3J)

**Comment by DiggityMan420** [comment]
same i am tried this with the  super can (all three) crashed when hovering over the X icon
log https://paste.atlauncher.com/view/92cbfe57-aa40-4663-8a41-4d09e086b19d

**Comment by DiggityMan420** [comment]
comment deleted Fixed when updated to remove legendry tooltips

**Comment by TheBedrockMaster** [comment]
Add crash label. Is this still an issue?
