### ISSUE TITLE
some greg tech recipes lag when i look at them while in my storage 

### ISSUE THREAD

**Issue by Jaydenpoyser4** [AllTheMods/ATM-9#1270]
i go into my me storage and it lags my game to a crawl when im looking at certain greg tech recipes in jei while in my storage 

https://github.com/AllTheMods/ATM-9/assets/105961470/59b79df3-a8b7-4a1e-8d43-1f86894b2a57

**Comment by MineCracked** [comment]
This is driving me nuts. My frames drop even lower when doing the same thing. Are you running shaders? Did you find a solution?
