### ISSUE TITLE
Apotheotic Boss Gate Pearl (Gateways To Eternity)

### ISSUE THREAD

**Issue by Solego** [AllTheMods/ATM-9#1273]
All The Mods 9, v2.41
Client Side issue, Server Side unaffected
Severity: JEI is mostly useless until client restart. 

Problem with the Gateways To Eternity Apotheotic Boss Gateway Pearl.  When scrolling through waves on this specific pearl, JEI Tooltips crash until client restart.  All tooltips on all items handled by JEI are replaced with (Tooltip Error, See Logs). See attached log excerpt.
[pearl_snippet.txt](https://github.com/AllTheMods/ATM-9/files/14155489/pearl_snippet.txt)

I am not sure if this pearl is an ATM9 custom, or provided by the mod author.  Issue was also submitted to Gateways To Eternity github.  https://github.com/Shadows-of-Fire/GatewaysToEternity/issues/47

**Comment by Kevin-Marsh** [comment]
This appears to be fixed.

**Comment by Ianthasys** [comment]
This seems to still be an issue as of pack version 0.2.53
