### ISSUE TITLE
[0.2.41] Enchantment Books can no longer be combined

### ISSUE THREAD

**Issue by slowthgt** [AllTheMods/ATM-9#1274]
Instance version: 0.2.41
No configs modified.

Disabling Quark fixes the issue.

**Comment by jpruitt2297** [comment]
Noticed this as well. Example, from experience, being Apotheosis enchant Boon of the Earth, used 2 IV books to try and make a V book, gave IV no matter what I did (enchant onto pick and combine or combine 2 books). Also upon retrieving IV book from my enchantment library, the Quark advancement for upgrading an enchant book with an ancient tome popped.

**Comment by Kevin-Marsh** [comment]
We disabled quark ancient tomes to fix this issue.
