### ISSUE TITLE
[version 0.2.39] Server shutdown W/ no crash report and no indicator in logs

### ISSUE THREAD

**Issue by MacaroniBot5** [AllTheMods/ATM-9#1280]
ATM 9 version 0.2.39

For the past two or so weeks(Starting at the creation of the server), the server has been shutting down suddenly without warning almost like a crash. It has not been leaving crash reports either. I tried looking through the server logs leading up to each shut down and can't seem to find anything to indicate what is happening. I am hosting through PebbleHost with 10gb of ram for the pack. 

I attempted to get assistance through pebblehost and they said that they were getting reports similar to mine and that they suspected a memory caused by something in the modpack. 

mcpaste link to the log is attached. https://mcpaste.io/26c676bb622ed565

**Comment by tumultkersplode** [comment]
I'm experiencing the same issue. Also on Pebblehost. I'm running 0.2.43. I'm wondering if there's a setting that Pebblehost could be setting incorrectly? I set allow-flight=true from false and the crashes seemed to go down, but I'm still getting random crashes. 

https://mcpaste.io/ca6bb14f4277c2f7
