### ISSUE TITLE
Item's keep getting a single NBT tag that makes them unstackable.

### ISSUE THREAD

**Issue by ClickErrorxD** [AllTheMods/ATM-9#1282]
Issue: The issue is that something is adding the NBT Tag "**{Picked:1b}**" to a lot of items, making them not stack with the vanilla unmodified item. For example, if I have ender pearls, from the base game, and put them into the storage, and then something in the pack applies the data to the enderpearl, it will not stack with the vanilla ones in my drawer. I am using Spawners and Cursed Earth dirt to spawn mobs in.

It's not just Ender Pearls, it's a variety of items. I have items coming in from a fortune clearing quarry, and the mob farm mentioned above.

Pack Version: 0.2.40

Media:
The NBT Data on the Enderpearl is shown with the clip.
https://imgur.com/a/JX52bAh
https://imgur.com/a/Wglu3Wk

**Comment by ClickErrorxD** [comment]
I just don't understand... I just had two different slime pearl items, same lore, same name, no nbt data, but they refused to stack, and then when I manually took the item out of the drawer, and put them back in, they stacked. However, my slime balls, same deal, no nbt data, but refused to go into my drawer of slime balls (with a available space).

I made this post with this exact issue in discord:
`Has anyone ever had issues with function storage? My items are not going into my drawers while im piping them into the controller, or when I right-click it to manually store it, it wont go in until I take the item out to add it to the stack in my inventory and then I can right-click again for it to deposit?

https://imgur.com/a/d0p1YVR

Here's the clip --- and I just realized, i think its the same issue i posted about before... items are getting a weird nbt data which makes them not stack, despite being the exact same item. If I put two of the same items (that don't stack) inside a pipz filter, one of them has no data, one has the data "{Picked:1b}". https://imgur.com/a/JX52bAh the clip of linked drawers and the nbt data picture`

**Comment by ClickErrorxD** [comment]
> I have this issue as well and found that if I pull one time out of the draw, it will then stack with the rest of the items. Seems like having it go into a stack in the player's inventory will remove any nbt data on the item itself.

 Yea, that's the same for me, which is manual. The whole point of having the pipe into the drawer system is to not have to go and search for the drawer yourself. Imma have to just quit playing for awhile, it's honestly annoying that i afk for 5 minutes and come back to stuff that's refusing to go into existing drawers.

**Comment by Kevin-Marsh** [comment]
This sounds like an issue that was caused by the let me despawn mod. It was supposed to be fixed back in October. Is your modpack up to date and it is still occurring?

**Comment by ClickErrorxD** [comment]
> This sounds like an issue that was caused by the let me despawn mod. It was supposed to be fixed back in October. Is your modpack up to date and it is still occurring?

I was using Pack Version: 0.2.40 at the time, i thought it was the most recent pack version.

**Comment by Kevin-Marsh** [comment]
I just needed to verify that it was still occuring before sending it back over to them. Thanks for letting me know.

**Comment by Flameshocker** [comment]
I am having the same issue I have to empty my drawers from time to time to get items to stack I am on the latest version of ATM. I am using refined storage with an external storage attached to an drawer controller.

**Comment by ClickErrorxD** [comment]
It's still occuring using:
![image](https://github.com/AllTheMods/ATM-9/assets/87890013/ff20fbc5-948a-495e-8f90-49cd00c8223f)
Using drawers is horrible if i gotta manually takes stuff out and put it back in just to store stuff.

**Comment by Kevin-Marsh** [comment]
The let me despawn mod was removed from the pack. Please let us know if this issue occurs again.
