### ISSUE TITLE
Ars Nouveau Scroll's (allow/deny)

### ISSUE THREAD

**Issue by MarobsKoco** [AllTheMods/ATM-9#1283]
version: 0.2.41.zip

It seems that the scrolls dont work at all. I can't filter item's be course i can't click the block's or item's on to the scroll as it should through the scribers table. so i cant work with starbuncle's.

**Comment by Kevin-Marsh** [comment]
This is a known bug  for Ars Nouveau. All we can do is wait for them to fix it.
