### ISSUE TITLE
Gregtech version mismatch??

### ISSUE THREAD

**Issue by xWaller0119** [AllTheMods/ATM-9#1285]
I am trying to join my local server. Says server has gregtech 1.1.2.a and I have 1.1.2.a or whatever. But it won't let me join... How does this make any sense???

![javaw_gg5vDGEmIf](https://github.com/AllTheMods/ATM-9/assets/10786761/1936d96a-ea97-428f-a243-c0745b6c4c65)

**Comment by MavriYdra** [comment]
Got the same issue w/ the newest version

![image](https://github.com/AllTheMods/ATM-9/assets/78053489/c3085a42-6204-40c4-ba04-6c9ea15eea41)

**Comment by innerlurken** [comment]
Hi, Had the same issue, turns out I copied the config folder over too. All i had to do to fix it was delete the GregTech config file

**Comment by Kevin-Marsh** [comment]
Mismatches like these are often caused by incorrect configs between the server and the client. Checking the configs and potentially repairing the installation should fix it for anyone who finds this in the future.
