### ISSUE TITLE
Disconnected and unable to Log in again

### ISSUE THREAD

**Issue by Borailuce99** [AllTheMods/ATM-9#1290]
Me and some friends are currently playing ATM9 - 0.2.41 modpack on my own server. The first days there wasn't any problem, but after a couple of days, all of us (except only one friend, not the op) are getting randomly disconnected by the server. After that, we are completely unable to log in because we are still logged in on the server (I've tried kicking from terminal but nothing works) so we need to restart the server completely to be able to log in again. 
After a couple of minutes, without making anything special or laggy, we get disconnected again.
We tried restarting all the computers, the server, the computer where the server is running... nothing solves it.

**Comment by sjs262** [comment]
I am having the same problem on an Akliz server. Literally softlocked out of the server unless I restart it. It literally takes like 15 minutes for the server to realize I got disconnected.
