### ISSUE TITLE
AIOT Botania Recipe Issue 

### ISSUE THREAD

**Issue by leadwolf32** [AllTheMods/ATM-9#1292]
The Alfsteel Hoe and Shovel require themselves and an Alfsteel ingot to make, which makes them impossible to make.

It should be the Terra Hoe and Terra Spade, respectively

**Comment by FireFrost76** [comment]
the alfsteel  upgrade template also requires its self to make

**Comment by Kevin-Marsh** [comment]
You need to get the alfsteel template by killing a witch or evoker with an elementium sword.
