### ISSUE TITLE
Cannot craft chests out of most modded wood

### ISSUE THREAD

**Issue by tauras129** [AllTheMods/ATM-9#1298]
In the latest version you can no longer craft chests out of the wood tag meaning that you cannot craft a chest out of modded wood unless the mod defines a recipe for a chest, you can still craft chests out of vanilla wood because of the quark recipes.

**Comment by spiderkitten** [comment]
I too have this issue.Also cannot craft a vanilla chest unless you use skyroot planks from The Aether mod as that is the only recipe. Trying to use any other vanilla wood will only make Quark Chests which you can convert, but thats an extra unnecessary step imo.  I don't want to have to use two patterns in Refined Storage when just one should suffice.

**Comment by Kevin-Marsh** [comment]
This should be resolved next update. The quark config has been amended to disable the quark chests.

**Comment by zckss** [comment]
The Quark chests are used in the FairyTale MineColonies style (from StyleColonies), which makes some buildings impossible to complete.  Perhaps there should be a specific recipe added for the Quark chests so they don't block that style.
