### ISSUE TITLE
[FULL][0.0.4] EMI Recipe Left Click

### ISSUE THREAD

**Issue by quikenb** [AllTheMods/ATM-9#13]
Typed Certus Quartz
Pressed left click or "r" to see the recipe 
Presse left click on the "In-World" tab
Game crashed
[crash-2023-06-19_14.48.26-client.txt](https://github.com/AllTheMods/ATM-9/files/11788804/crash-2023-06-19_14.48.26-client.txt)

**Update Any "In-World" EMI recipes crash the game

**Comment by emilyploszaj** [comment]
Since this was not reported on my repo I'll mention it here, this crash was fixed in EMI 1.0.5

**Comment by quikenb** [comment]
I love your work EMI looks amazing BTW. However, it appears on v0.0.4 we were using EMI 1.0.4. I would love to see EMI as a main stream instead of JEI or REI. Let's hope ATM team update v0.0.8 to EMI 1.0.5 :)

**Comment by quikenb** [comment]
Confirmed 1.0.5 EMI has fixed the issue.
For now EMI is removed. Closing down issue
