### ISSUE TITLE
[0.2.43] GregTech still broken from 0.2.42

### ISSUE THREAD

**Issue by prejas3** [AllTheMods/ATM-9#1302]
Just after update i tried to create khantaal rod as well as some ingot with use of soldifier. Nothing works no matter I use ae2 or do it manually. 
![image](https://github.com/AllTheMods/ATM-9/assets/62844653/e37e4fef-68d6-4a7c-9b15-38f1135a45fa)

**Comment by whatthedrunk** [comment]
This recipe worked just fine for me. Anyone else having this issue or any other issues on 0.2.43?

**Comment by fatbadpig** [comment]
Updated to 0.2.43 from 0.2.41. Most GregTech recipes seem fine. However “LV Electric Pump” cant be crafter in Assembler

**Comment by Mrminesheeps** [comment]
It's worth nothing that (at least for me) the EBF is broken as well. 
![image](https://github.com/AllTheMods/ATM-9/assets/15947037/207ca372-5077-456f-aae3-cbf399814dfc)
It has sat in this state for well over two hours. It also ate some of the resources I had put into it, and the muffler looks as if it's still active.

**Comment by whatthedrunk** [comment]
> It's worth nothing that (at least for me) the EBF is broken as well. ![image](https://private-user-images.githubusercontent.com/15947037/303466866-207ca372-5077-456f-aae3-cbf399814dfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0Mzg2MzEsIm5iZiI6MTcwNzQzODMzMSwicGF0aCI6Ii8xNTk0NzAzNy8zMDM0NjY4NjYtMjA3Y2EzNzItNTA3Ny00NTZmLWFhZTMtY2JmMzk5ODE0ZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDAwMjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MGQwMjFhODJjNGQ4OGQ2NWZiZjVmNzQxODNlYTVhNzQ1MTJkMmY3ODZiOGJjMDBjYTFhMWZjZTk0ODM3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EwMM0SwDBTN_uhKBDmLpoQeqECyqU3Aaix-7vGIcrAo) It has sat in this state for well over two hours. It also ate some of the resources I had put into it, and the muffler looks as if it's still active.

what are you trying to process so I can test it out?

**Comment by whatthedrunk** [comment]
I was also asked to ask if you have enough power in the machine before you tried to process it?

**Comment by Mrminesheeps** [comment]
> I was also asked to ask if you have enough power in the machine before you tried to process it?

I definitely have enough, I'm running a Mek fusion and converting power. This screenshot happening while making Vanadium Gallium (The blue ingots) but has also happened with Kanthal and a couple others I can't remember off the top of my head.

**Comment by Mrminesheeps** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/15947037/074307d3-1d7e-484f-8877-ad8d625afcdc)
This depicts my EBF shortly after successfully cooking one of the two niobium titanium ingots I requested. It just... ate the other dust and gas I provided.

**Comment by whatthedrunk** [comment]
While I am waiting on feedback from the team do you have time to test this file? https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3-build_485

**Comment by Mrminesheeps** [comment]
> While I am waiting on feedback from the team do you have time to test this file? https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3-build_485

From my (admittedly minimal) testing, it seems this version did at least fix the EBF. It seems to be working exactly as intended, every time. Compared against the same setup in the older version, which did consume some of the spent ingredients. (I tested in a singleplayer world)

**Comment by prejas3** [comment]
> While I am waiting on feedback from the team do you have time to test this file? https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3-build_485

I've tried with this file on my server but still got problems
![image](https://github.com/AllTheMods/ATM-9/assets/62844653/734bd2e1-0f43-4fa2-bca8-2ad4a115cac8)
Chemical reactor starts running, make couple batches and that's it. It has all ingredients, power and circuit and still I need to disable and enable it.

Could it be still a build issue or world it's corrupted?

**Comment by prejas3** [comment]
After further testing with Chemical Reactor, Assembler and EBF I can tell that
- it hapens after recipe change, for example assembler is doing one type of cable, then other one, assembler creates one and then nothing (I've got blocking mode enabled)
- EBF it's working kinda okay but it's probably voiding some items, for example, I batch crafted 10 ingots of Tungsten as well as Tungsten steel and in autocrafitng I've got message that only 6 out of 10 were made, and there is nothing in input hatch

**Comment by Mrminesheeps** [comment]
> > While I am waiting on feedback from the team do you have time to test this file? https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3-build_485
> 
> From my (admittedly minimal) testing, it seems this version did at least fix the EBF. It seems to be working exactly as intended, every time. Compared against the same setup in the older version, which did consume some of the spent ingredients. (I tested in a singleplayer world) Did further testing, the EBF is certainly in a better state, but still not fixed fully. I ran some test crafts in batches of 128 ingots, and sometimes lost one ingot. Tested with: Kanthal, Vanadium Gallium, Tungstensteel, Tungsten, and Trinium. It seems the EBF, at some indeterminate time, takes a "sacrificial ingot" before it cooks without incident.

Just gonna make this comment more visible since I just made some edits with new info.
