### ISSUE TITLE
Please fix bug for eternal stella + hammer

### ISSUE THREAD

**Issue by CengizhanOemuer** [AllTheMods/ATM-9#1303]
Whenever u combine an etnernal stella with an hammer to give it unlimited durability it becomes undestructable, but when u use the hammer it returns to beeing a normal hammer and uses durabilty.

**Comment by kevin-meyers** [comment]
it still has unlimited "durability" but is stuck on the 30 "uses".

**Comment by Kevin-Marsh** [comment]
This is due to mod interactions and unable to be fixed on our end.
