### ISSUE TITLE
ATM9 [0.2.43] "Ad Astra" Steel/Iron Plates Bugged

### ISSUE THREAD

**Issue by StarHunter36016** [AllTheMods/ATM-9#1306]
As of update 0.2.43, the steel and iron plate blocks from Ad Astra can no longer be placed in framed blocks from the "FramedBlocks" mod. Also, the steel plate block from Ad Astra can no longer be placed on Create Mod contraptions, otherwise it'll say the contraption can't be moved.

**Comment by djnifos** [comment]
Fixed in 0.2.49 by the AdAstra update to 1.15.18
