### ISSUE TITLE
GregTech circuits not working

### ISSUE THREAD

**Issue by Beltrano42** [AllTheMods/ATM-9#1307]
None of the circuits from greg, from lv to luv I can't craft with the assembler ( yes, I'm using the right tier ), seem to wait for a circuit number, IDK

**Comment by OrangeCreamsicle3** [comment]
Yeah, after I updated the server to the latest version. The circuit assembler won't craft the circuits. Broke my entire auto-crafting and can't progress at all.

**Comment by cokeacolaking** [comment]
Has there been a fix? Still having this issue in 0.2.51

**Comment by Snakedon** [comment]
> Has there been a fix? Still having this issue in 0.2.51

try this
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/11229335-c2da-426a-a756-ce107f64eb00)

**Comment by OrangeCreamsicle3** [comment]
> Has there been a fix? Still having this issue in 0.2.51

I have updated the modpack to 0.2.51 and never had an issue since then.

**Comment by Rykon00** [comment]
So yeah, a Friend of mine and I are just stepping into GregTech, on the version 0.2.56. We do have the exact same problem with passive Crafting circuits. The assembler even did some yesterday, but won't do anything this evening. We only got around to MV-Good Circuits, which can be crafted in the Crafting Field but won't work in the SINGLE block Circuit Assembler. The LV-Circuit does still work without any issues.

**Comment by AlgarDev** [comment]
I'm still having the same issue in 0.3
First image is my setup, second one is the JEI recipe
![image](https://github.com/user-attachments/assets/bdad8a40-7748-452a-8b21-85ede7905278)
![image](https://github.com/user-attachments/assets/1cd224aa-1d1b-42d7-b216-d151623a9db8)
