### ISSUE TITLE
Automated farms stop working

### ISSUE THREAD

**Issue by tekook** [AllTheMods/ATM-9#131]
So I have this really wierd bug that most of my automated (vanilla) farms simple stop "growing".
Like a sugarcane farm, bamboo farm, kelp farm, etc.
They all work when I build them, but most of the items stop growing after a while.

I have the chunks force loaded (via FTBChunks).
Even after restarting the server, or unloading the chunks, the items don't grow.

Anyone else having this issue?

**Comment by Alucard1313** [comment]
Same in my world

**Comment by shikyo13** [comment]
Yes my crop farms stop producing after a while.
