### ISSUE TITLE
GT Canning machine not working

### ISSUE THREAD

**Issue by Zenthae** [AllTheMods/ATM-9#1310]
The gregtech canning machine is not working for battery recipes other than cadmium ones.
![image](https://github.com/AllTheMods/ATM-9/assets/32647899/e22e48ec-f780-4121-953a-b692b15dff68)
ATM 9 .42

**Comment by thepauljs** [comment]
I'm on 0.2.43, and this exact setup (Small Battery Hull and Sodium Dust in MV Canner) worked fine
