### ISSUE TITLE
Gregtech Bugs

### ISSUE THREAD

**Issue by jungshinyung5** [AllTheMods/ATM-9#1311]
![2024-02-10_00 51 30](https://github.com/AllTheMods/ATM-9/assets/43872929/76e61e1a-a6c9-444c-893a-6ea845929f35)

[1. Advanced Laser Engraver] Not Make ULPIC Wafer
= Tech progress is no longer possible.

[2. Advanced Laser Engraver] Not Make ILC Wafer
= Tech progress is no longer possible.

[3. Advanced Cutter] Not Make Silicon Wafer with water and Lubricant
only Make Distilled Water
[4. Advanced Assembler] Not Make MV Electirc Pump

[5. any] Last Version RS Crafter Patten not Reading Gregtech's Machine

I'm doing Gregtech 16 hours a day, but I can't proceed anymore. I'd really appreciate it if you could fix it quickly.

**Comment by jungshinyung5** [comment]
1~4 errors : [0.2.42]
5 error : [0.2.43]

The 0.2.43 version cannot proceed with Greggs at all.
And version 0.2.42 cannot proceed from the middle due to a fatal error.

**Comment by jungshinyung5** [comment]
![2024-02-10_11 21 31](https://github.com/AllTheMods/ATM-9/assets/43872929/58ed31fe-1b65-42cc-bbcd-ba19767ec407)
[0.2.43]
[Advanced Assembler] Not Make 1x Copper Cable

**Comment by jungshinyung5** [comment]
![2024-02-10_11 23 08](https://github.com/AllTheMods/ATM-9/assets/43872929/b6b15dae-02ab-431c-9b78-5f0f0e5e3a60)
[0.2.43]
[Advanced Cutter] ULPIC CHIP

**Comment by forsakendaemon** [comment]
I'll add here that in 0.2.43 the Advanced Macerator won't process many of the ores, including those that have a Macerator recipe in JEI.

So far I've tested with:
- Cobaltite Ore *
- Pentlandite Ore *
- Nether Tetrahedrite Ore *
- End Sheldonite Ore *
- Nether Bornite Ore *
- Nether Chalcocite Ore *
- Deepslate Pyrolusite Ore
- Deepslate Tantalite Ore

All ores appear in the Ore Processing Diagram as available to be Macerated; those marked with * also have a Macerator recipe visible.

**Comment by kjukmar2** [comment]
> I'll add here that in 0.2.43 the Advanced Macerator won't process many of the ores, including those that have a Macerator recipe in JEI.
> 
> So far I've tested with:
> 
>     * Cobaltite Ore *
> 
>     * Pentlandite Ore *
> 
>     * Nether Tetrahedrite Ore *
> 
>     * End Sheldonite Ore *
> 
>     * Nether Bornite Ore *
> 
>     * Nether Chalcocite Ore *
> 
>     * Deepslate Pyrolusite Ore
> 
>     * Deepslate Tantalite Ore
> 
> 
> All ores appear in the Ore Processing Diagram as available to be Macerated; those marked with * also have a Macerator recipe visible.

I tried putting oilsands and copper block ores in macerators up to and including HV, as well as IV, and there was no result. Taking into account your information I think it's safe to assume that none of block ores are proccesable in any gregtech macerator.

**Comment by forsakendaemon** [comment]
Yup, I just ran up against the Oilsands Ore issue myself. That one at least I can work around with the Pyrolyse Oven and a near-infinite supply of wood.

**Comment by jungshinyung5** [comment]
![2024-02-10_21 41 19](https://github.com/AllTheMods/ATM-9/assets/43872929/622ab387-7b40-4853-a624-a7b5c9420aca)
[0.2.43]
[Advanced Laser Engraver] Not Make RAM Wafer

It's not working, but I really wanted to do it, so I found a way.

Change the version from [0.2.43] to [0.2.42] and [0.2.42] to [0.2.43].
If you repeat it seven times, you succeed in making RAM Wafer just once.

**Comment by prejas3** [comment]
I'm also waiting for new version but for the time being I was asked to use this https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3-build_485
It helps with couple of problems - for example multiblock macerator and ore washer are working but sometimes they just stop (I bypassed it by using controller module and inverted redstone signal with timer set to 5k ticks 
For a fact with this build of the GT most of recipes works fine but machines just stops working just right after making one batch of a new recipe.
For example: you're making coper cables and assembler is working fine, then autocrafing starts making osmium cable and after one cable it stops. You need to go from machine to machine one by one and disbale/enable them to start working.
I think that controller and redstone with timer should also work but it's ugly af

**Comment by kjukmar2** [comment]
So, I tried the latest GT build, which is 489. It seems to me that the majority of recepies works: blank wafers wafer and ores macerate. The problem is that recepies for GT machines in JEI are broken and don't show up :")

**Comment by kjukmar2** [comment]
> The problem is that recepies for GT machines in JEI are broken and don't show up :")
Though I now think about that it MAY be because this version of GT is kind of... external mod? One that wasn't supplied by the pack. Guess one will have to wait for the next mainline version of GT to be incorporated into ATM.

**Comment by jungshinyung5** [comment]
[0.2.43]
![2024-02-11_10 20 24](https://github.com/AllTheMods/ATM-9/assets/43872929/33190345-8470-4dc8-86ee-cc32f7ea417c)
[Advanced Laser Engraver] Not Make CPU Wafer

![2024-02-11_11 06 17](https://github.com/AllTheMods/ATM-9/assets/43872929/ac1b39e2-0953-4d6d-9a53-e55d82ad8f04)
[Advanced Cutter 2] Not Make Phosphorus-doped Wafer
I try Lubricant, Distilled Water, water but, It's all not working.

**Comment by jungshinyung5** [comment]
[0.2.43]
![2024-02-11_13 05 44](https://github.com/AllTheMods/ATM-9/assets/43872929/5cb72e18-005a-4fa6-9f10-877426648e95)
[Advanced Canner 2] Not Make Small Sodium Battery

**Comment by StripedMonkey** [comment]
At least one of the recipes for Microprocessors is now broken, at least using liquid soldering alloy.
![image](https://github.com/AllTheMods/ATM-9/assets/8009284/3ffebf18-6cf5-4ea3-bbd4-b281dcb4cbf0)
Gregtech progression is definitely completely broken in 0.2.43

**Comment by StripedMonkey** [comment]
Installing GregTech 1.1.13.a-build_491 seems to have fixed the issue, so it seems to just be a waiting game for GT to push something upstream.

**Comment by IISkullsII** [comment]
I've looked up the Gregtech Version used in the ATM9 0.2.42, wich is "[1.1.3-build_485](https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3-build_485)" and it seems to works just fine and the JEI seems to be working too. But there might be another issue, use this with care. I still would recommend to wait for an official ATM9 patch, to fix this issue.

**Comment by StripedMonkey** [comment]
build 485 does work wrt the circuits, but it appears that some of the ore processing recipes are broken, specifically magnenite and lapis are the two I have seen so far, and the ores are clogging my ore processing. 

I have not encountered any truly progression-breaking bugs with build 485 of GT (yet!) but, I'm gonna be honest, there needs to be some serious QA/CI work to make sure that progression isn't actually completely broken. Whether that's on the ATM-9 side or on the Gregtech side I don't know, but this is a bit absurd.

The current release of ATM9 is completely broken progression wise, and you can't actually get anything done in gregtech, and thus much of the endgame, because of this.

**Comment by jungshinyung5** [comment]
Thank you to everyone who left comments.
Just in case you don't know, I'm leaving a comment here as well.
[0.2.45] When updating the version, all the errors posted above will be resolved.
However, please note that all Gregtech JEI recipes have disappeared due to the current error.
Only the recipe is gone, but the production is working normally.

**Comment by StripedMonkey** [comment]
Build 500 (more probably 499, but I tested 500) seems to have fixed recipes being missing from JEI, however Non-GregTech ores (including vanilla ores like Iron and Redstone) are not able to be macerated. That might be due to some mod other interactions but I've not tested much further than that.
