### ISSUE TITLE
AdAstra and framed blocks broken after update

### ISSUE THREAD

**Issue by Whitei520** [AllTheMods/ATM-9#1313]
I updated today to ATM9 v0.2.43 and all AdAstra decorative blocks are no longer compatible with framed blocks. I had to load the server as a single player world just to be able to join without errors.

I understand this update included a large rewrite of AdAstra with lots of block IDs changing.
I assume this is the fault of the AdAstra devs forgetting to add compatibility back after the changes.

I think it would be a good idea for ATM devs to add the block tag `framedblocks:frameable` back to the AdAstra blocks to prevent buildings from breaking.

I have not tested all the AdAstra blocks, but the ones I have checked all have this issue. e.g. Iron Plating, Pillars, etc.

**Comment by djnifos** [comment]
Fixed in 0.2.49 by the AdAstra update to 1.15.18
