### ISSUE TITLE
packing tape from sophisticated storage not working with eternal stella

### ISSUE THREAD

**Issue by sh4ni** [AllTheMods/ATM-9#1315]
making the packing tape from sophisticated storage indestructible does not work.
the nbt data still shows the damage tag and it gets used up without you seeing how many uses it has left.

**Comment by Vany** [comment]
Yep, it not works with unbreaking too.
but it's not atm bug, ask @P3pp3rF1y for fix. (if he want's it)

**Comment by P3pp3rF1y** [comment]
I guess I could add showing the remaining uses and potentially give it a few more uses than 4, but definitely don't want unbreaking, mending or eternal stella working on that.
