### ISSUE TITLE
Ad Astra Hammer Missing Cannot Progress through Quest Book

### ISSUE THREAD

**Issue by BassManSteve1** [AllTheMods/ATM-9#1317]
As written in Title 0.2.43

**Comment by whatthedrunk** [comment]
I got a fix in for the next update thanks.

**Comment by ellelapsus** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/139272614/8b15c010-c0f8-4b3d-9abb-647d33390f08)
![image](https://github.com/AllTheMods/ATM-9/assets/139272614/dd043bb5-83cb-4298-b940-fa62618c70ae)
unsure if 0.2.46 counted for the "next update" but still seeing an issue.

**Comment by contra1337** [comment]
looks like the Oxygen Tank also has this missing item issue too from quest 'Preparing Some Oxygen'
