### ISSUE TITLE
[0.0.42] Corail graves cannot be collected on others Minecolonies

### ISSUE THREAD

**Issue by MiniHerc** [AllTheMods/ATM-9#132]
On the ATM9 server I play on, a player died on another player's Minecolony and they could not collect their grave until the other player gave them permissions.

**Comment by 727Enjoyer** [comment]
makes sense as it kinda behaves as claimed c hunks - which also need perms from the owner to interact with your grave

**Comment by Corail31** [comment]
Hi, you can probably sneak over the grave to open it. The next release will allow to interact directly.
