### ISSUE TITLE
Reforge mjolnir game crash

### ISSUE THREAD

**Issue by Alejandro0905** [AllTheMods/ATM-9#1320]
If you try to reforge the mjolnir from the botania in the Aphoteosis table the game will close

**Comment by FireFrost76** [comment]
they fixed it , its on latest update for apotheosis

**Comment by FireFrost76** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/1157#issuecomment-1936489741

**Comment by Ari-W123** [comment]
@

> [Shadows-of-Fire/Apotheosis#1157 (comment)](https://github.com/Shadows-of-Fire/Apotheosis/issues/1157#issuecomment-1936489741)

Could you give me a guide on how to do that as I am unfamiliar with coding
