### ISSUE TITLE
Trying to add Project E to Modpack.

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-9#1321]
I'm trying to add Project E to the ATM9 Modpack, but it only seems to work on version 0.2.41 as the other 2 newest versions of ATM9 makes the Transmutation Tablet empty and unusable and items in JEI have no EMC values.  Can anyone help me with this. I've provided the log for 0.2.41.

https://mclo.gs/p2tvjpk

Thanks in advance.

Here is the Latest Log for Version 0.2.43, I hope this helps.:

https://mclo.gs/H6Ryqh9

**Comment by Mitchell5200** [comment]
You have a heap of duplicate mods, just of different versions in your mods folder, a reinstall or cleanout will be needed

ignore below as that was my first thought before reading other things, unless the above does not fix
~https://mclo.gs/H6Ryqh9#L6212 Project E intergration and Chipped error, go speak to the PE integration dev~

**Comment by Furious1964** [comment]
Deleted ATM9 Folder and reinstalled the Modpack. Reinstalled Project E and still the same thing, no Item EMC Values and Transmutation Tablet is empty and won't accept anything.

https://mclo.gs/x6G9AZH

**Comment by Mitchell5200** [comment]
okay, now the error is the part i had crossed out before, https://mclo.gs/x6G9AZH#L10679 error between Chipped and Project E Integration

**Comment by Furious1964** [comment]
Asking guys at Github/Chipped for some help. Thanks for your help.
