### ISSUE TITLE
massiv dupe bug

### ISSUE THREAD

**Issue by ferrium42** [AllTheMods/ATM-9#1332]
After the new update i regonized dupe items .
i had witherskull shards for 4 skulls and ended with a lot more.
i crafted ender eyes in my inventory and get 17 more than the 11 i expected. 
please look into that

**Comment by Mitchell5200** [comment]
Duplicate of #1327, #1331, #1332, #1333, 1334
Cause is FastWorkbench, hotfix releasing soon
