### ISSUE TITLE
Crafting items duplicates ingredients (0.2.45)

### ISSUE THREAD

**Issue by Dkapka** [AllTheMods/ATM-9#1333]
Crafting items duplicates ingredients, both vanilla and modded recipes affected. See below. Issue persists in new worlds and post reinstall.

https://github.com/AllTheMods/ATM-9/assets/97832276/677cef6a-14dc-4ede-bf7c-ee007e25f568

**Comment by Mitchell5200** [comment]
Duplicate of #1327, #1331, #1332, #1333, 1334
Cause is FastWorkbench, hotfix releasing soon
