### ISSUE TITLE
[0.2.46] GregTech Macerator Unable to Process Vanilla Silktouched Ores

### ISSUE THREAD

**Issue by vitharr137** [AllTheMods/ATM-9#1339]
Currently tested and failed: Copper Ore (Minecraft) block, Redstone Ore (Minecraft) block
Tested in Steam Macerator and Basic Macerator
Raw ores and ingots work however

**Comment by kjukmar2** [comment]
I confirm, also would like to add that this issue is present with the block ores from the AllTheOres mod
