### ISSUE TITLE
GregTech Broken Quests

### ISSUE THREAD

**Issue by GhostSpooky** [AllTheMods/ATM-9#1340]
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/ee67f0e2-b76b-4ffc-a7aa-05713929deff)
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/b068cf12-33aa-4ed5-8036-df12f7520550)
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/32c11852-2ecf-4633-8550-04f835362865)
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/1eaee369-32a3-40a3-b8ad-013b851c9d79)
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/bc24f401-dd0b-4b3a-97f9-8da85d31bc6a)

Some GregTech items required by quests and some quest rewards have the wrong item IDs

**Comment by GhostSpooky** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/f037a36c-a635-4ad9-9543-d3443a1099fa)
![image](https://github.com/AllTheMods/ATM-9/assets/53067263/40dd1c6e-8536-4bed-bb60-c6bc12620767)

**Comment by TheBedrockMaster** [comment]
Add quest bug label. Are these all fixed?

**Comment by TheBedrockMaster** [comment]
Can this be closed?
