### ISSUE TITLE
Dupe glitch bug

### ISSUE THREAD

**Issue by Frostthejack** [AllTheMods/ATM-9#1342]
Would it be possible to make it so that the bins from mekanism can not be registered as storage for ars Nouveau storage lecturn. It can see their contents but but can not pull from or place into however it sees it as available inventory when attempting to craft and will craft as long as you have 1 of each item needed for the recipe in the crafting grid. Discovered this when making coal blocks. I had exactly 9 in the crafting grid and all other coal was in a connected bin. Shift click to create a stack and my available coal did not decrease. Was able to do this multiple times with no loss of coal.

**Comment by Kevin-Marsh** [comment]
This doesn't happen to me in testing. It simply doesn't work with the bin but there is no duping.
