### ISSUE TITLE
Enchantment Descriptions should not be removed!

### ISSUE THREAD

**Issue by Tuganace** [AllTheMods/ATM-9#1344]
Hi, I saw in one of your latest versions, that u deemed Enchantment Descriptions unnecessary because Cofh could do the same, but that is most definitely not the case, Cofh can only handle it if an item or book has a single enchantment on it, but as soon as u have a book/tool/armour with more than one enchantment, it shows nothing, so can u plz bring back Enchantment Descriptions? :)

**Comment by ArcTrooper210** [comment]
Can confirm it shows nothing

**Comment by Kevin-Marsh** [comment]
This was removed to clean up the item displays. You can still find an explainer on the books of the enchants in JEI.
