### ISSUE TITLE
Start up Error - DefaultSettings encountered an error during the complete event phase. Version 0.2.46

### ISSUE THREAD

**Issue by theprodigy4** [AllTheMods/ATM-9#1347]
After update client will not complete start up due to:  DefaultSettings encountered an error during the complete event phase.

Crash Report: https://mclo.gs/jPt8qhP

**Comment by darrenh2** [comment]
Just updated this morning and getting the same error

**Comment by darrenh2** [comment]
Still getting same error when updating to 0.2.51

**Comment by LukasComK** [comment]
you can fix?

**Comment by LukasComK** [comment]
it worked by deleting quack-common and options.txt
