### ISSUE TITLE
Miltiblock consumes double resources on first operation

### ISSUE THREAD

**Issue by kjukmar2** [AllTheMods/ATM-9#1349]
Modpack version - 0.2.46
Multiblock structures (or at least blast furnace with lv input hatch) consume double resources when they start a production cycle.
Will update if this issue persists after reloads and if other multiblocks and input hatches are affected.

**Comment by Mrminesheeps** [comment]
Is this issue repeatable? And would it be possible for you to re-create this bug under "ideal conditions" (By that I mean set it up in a creative world closely resembling your setup, but with guaranteed power)? There's a few factors that could've done this, including a brief lapse in power, or improper maintenance (Though I doubt this is the case here, since your EBF is still LV.)

**Comment by kjukmar2** [comment]
Maintenance, huh... That never occured to me. Didn't have any time to deal with it yesterday, will try to check it out in a creative world later today (it's 7 am where i live) and maybe record a video.

> Is this issue repeatable? And would it be possible for you to re-create this bug under "ideal conditions" (By that I mean set it up in a creative world closely resembling your setup, but with guaranteed power)? There's a few factors that could've done this, including a brief lapse in power, or improper maintenance (Though I doubt this is the case here, since your EBF is still LV.)

**Comment by forsakendaemon** [comment]
This appears to be a common problem with the EBF - I lose an ingot on pretty much every batch as well. It's been mentioned in other issues, no joy yet though.

**Comment by kjukmar2** [comment]
https://github.com/AllTheMods/ATM-9/assets/101963516/add56bb5-570a-4cf6-bbf4-be5e0e412e2b

So, i have discovered that fps may be, in fact, the thing to blame for this, because the bug was gone when I unloaded the cpu from unwanted processes, and it would return when cpu was under load. I have to note, that I didn't observe any of this behaviour on older versions of the modpack, e.g. 0.2.39.
