### ISSUE TITLE
Crashing.. Not entirely sure what's causing it

### ISSUE THREAD

**Issue by Mariieez** [AllTheMods/ATM-9#1351]
I just started a hosted modded server on Apex Hosting with ATM 9, however when I try to open my inventory in creative it automatically crashes me regarding a Nether Star Bucket. "The game crashed whilst unexpected error Error: java.lang.NullPointerException: Registry entry not present: gtceu:nether_star_bucket" I'm not entirely sure what mod it could be from I have uninstalled and reinstalled multiple times with no additional mods. I was directed here by the discord support team, any and all help would be appreciated! This is my latest log https://mclo.gs/bTAB5er

**Comment by cowardlycamper32** [comment]
Bump, can confirm on version 0.2.59. Here's my latest.log -
[latest.log](https://github.com/AllTheMods/ATM-9/files/15490305/latest.log)

**Comment by TheBedrockMaster** [comment]
Add crash label.

**Comment by huntyh** [comment]
Still happening as of 0.3.2
https://mclo.gs/3COmpVy

**Comment by cowardlycamper32** [comment]
All the logs reference the GregTech CuE nether star bucket

**Comment by huntyh** [comment]
https://mclo.gs/HQHV87E
Also happening to players NOT in creative mode. Players opening and closing Lootr Loot barrels experience crashes regarding Nether star bucket.
