### ISSUE TITLE
Block of brass

### ISSUE THREAD

**Issue by Ellrik** [AllTheMods/ATM-9#1356]
currently with the FairyTale minecolony pack you are unable to make the glass frames required for higher tiers. All because one of the material components require the 'Block Of Brass' from the create mod specifically, which I cant find a way to make

![Capture](https://github.com/AllTheMods/ATM-9/assets/160074917/66c56aa7-2872-4ac9-937c-218d51d635aa)

**Comment by Ellrik** [comment]
anyone have a work around?  I am stuck on this since .45

**Comment by Noes4** [comment]
Still not fixed, can't work around this. There is only a block of brass from allthemods itself, while the recipe requires a block of brass from create. Won't work with the allthemods brass block, unfortunately

**Comment by TheCommensuratePup** [comment]
If you use the command to give yourself the block of brass from create it does work. So it does appear to just be a compatibility issue. Note, it appears that the glass needed is quark's framed glass not create's framed glass, not important but for future reference.

**Comment by Mitchell5200** [comment]
I have not yet found a proper way to fix this yet, However, i have found a workaround
Use the mekanism "oredictionificator", and set `'forge:storage_blocks/brass'` (or /zinc, or anyother material) as the filter, and click the arrows until the create brass shows up, then toss in ATO brass. ***(as pictured)***
![2024-08-13_21 53 33](https://github.com/user-attachments/assets/cd9f2e22-9468-4cd5-a594-eb08645d412f)
![2024-08-13_21 53 50](https://github.com/user-attachments/assets/4952261f-c977-4f89-b3fe-5b9c25e87dad)

Duplicate issues, #1431, #1356

**Comment by V-res** [comment]
I fixed this by adding custom recipes via kubejs witch is a possibility in allthemods 9. Create custom_recipes.js file in {your atm9 folder}/kubejs/server_scripts directory. Attaching my custom_recipes.js file. I also added andesite encased shaft block which is needed for FairyTale minecolony farm, and which you cant craft or collcet as one block normally, and quark feeding trough which is needed for some animal farms in FairyTale pack. Andesite Encased shaft is crafted from Shaft and Andesite Casing and Feeding Trough is crafted with 2 fence gates of any type and 3 planks of any type.

P.S. Note that for FairyTale library Framed Framed Glass block(the one that also requires 'Block of Brass' block) you need to use quark:framed glass not create:framed glass. 

<img width="281" height="116" alt="Image" src="https://github.com/user-attachments/assets/6c7e2203-5e6a-4efa-9043-c029f20f885b" />

<img width="271" height="115" alt="Image" src="https://github.com/user-attachments/assets/64552995-9260-4418-8d62-edf4b78a051a" />

<img width="284" height="120" alt="Image" src="https://github.com/user-attachments/assets/f2d27a34-24bb-4413-861b-62b93b68c1ac" />

[custom_recipes.js](https://github.com/user-attachments/files/24526129/custom_recipes.js)
