### ISSUE TITLE
Trouble with Electric Blast furnace (Gregtech)

### ISSUE THREAD

**Issue by MCCatboyTV** [AllTheMods/ATM-9#1359]
Okay so i tried to use the Electric blast furnace to create Vanadium. Did not wokr and even after switching recepis and plaing the mutliblock structure at another place and repairing it it is still not doing as it is supposed to and the Machine does this.
![Bild_2024-02-15_124535660](https://github.com/AllTheMods/ATM-9/assets/44748848/b237c91b-7270-4372-9669-9efe51993faa)

even if it eventually starts working the progressbar does not move at all.

**Comment by CloWnicide** [comment]
It seems the machines now have to warm up to start working, but the machines are failing certain recipes it seems. Neodymium is also failing to progress in the EBFs

**Comment by tkoopman** [comment]
I also have been having issues on previous working machine. Mostly when having AE2 queue multiple crafts even with it configured to wait for 1 craft to finish before sending the next. I have checked all in single chunk and even removed any wall sharing. It will always start the craft and coils light up but will get stuck often at the starting 0 seconds even if previous craft went smoothly.

It also not chunk loading / unloading as it happens that often that I now just stand in front of it waiting for it to fail. What makes it worse, all the ways I found to fix it so it starts crafting again, also makes it void the current ingredients. Pausing/unpausing the machine being the easiest way to get it unstuck.

@CloWnicide I don't think it is "warming up" as it often not the 1st craft that fails but the 2nd or 3rd. I also have left it at 0 seconds for a while and nothing changes.

I am running the latest version 0.2.46.

**Comment by CloWnicide** [comment]
The machines warm up, that's the coils lighting up one by one, and then it starts the recipe. At least on my end is what its doing.

**Comment by tkoopman** [comment]
Oh. Might be slightly different issue then. I had something similar to that a couple of versions ago but what I am seeing now is all the coils light up immediately but the timer never leaves 0 seconds.

**Comment by MCCatboyTV** [comment]
i have all your problems at the same time and i get no output of it

**Comment by MCCatboyTV** [comment]
also using .46

**Comment by twhickey** [comment]
I'm having the same (or a very similar issue) - I have EBFs that seem to have warmed up (all coils lit up), and the interface says "Running Perfectly", but the progress stays at 0%

**Comment by MCCatboyTV** [comment]
okay soo now something changed now, every second recepy gets lost...

**Comment by jebjoya** [comment]
Hey folks, just a note - this is a known issue in the latest GT - there _is_ a workaround though - if you set the configuration option in GregTech of `asyncRecipeSearching` to `false` (can be found either in the GT config file in the `gtceu.yaml` file in the `config` folder, or can be done through the mods menu -> Gregtech -> machines for local single player worlds).  For what it's worth, the other known issue at the moment is in using distinct buses mode - you need to use physical circuits instead of the virtual circuits from the UI.  Both these issues are scheduled to be fixed in newer updates of GTCEu modern as I understand.
