### ISSUE TITLE
ATM9 Crashing due to block rats:garbage_pile

### ISSUE THREAD

**Issue by mferry1** [AllTheMods/ATM-9#1361]
The crash seems to be happening because of terrain generation on a village. The crash report says the error came from rats:garbage_pile. The Rats mod is not mod pack however, so I'm not sure why it's trying to generate that anyway. Regardless, installing the Rats mod on top of ATM9 mod pack fixes the issue.

**Comment by alessiorapisarda** [comment]
+1, having the same issue

**Comment by Nakeol** [comment]
+1 same

**Comment by djnifos** [comment]
I'm working on fixing this mod, where is this village generating?

**Comment by alessiorapisarda** [comment]
> I'm working on fixing this mod, where is this village generating?

I think it generates in vanilla and custom biomes, try to generate a new world and use the locate command to locate ctov villages, medium sized often has this problem. Mine were dark forest and swamp type of villages but I think most are affected by this issue

**Comment by Mitchell5200** [comment]
https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/issues/91
