### ISSUE TITLE
Gregtech Scheelite Veins Not Generating In ATM Mining Dimension

### ISSUE THREAD

**Issue by Mrminesheeps** [AllTheMods/ATM-9#1364]
Exactly as the title says, just about every valid vein type spawns here except for Scheelite, which makes gathering Tungsten a bit more of a chore than I'd like. Furthermore, said Scheelite veins in The End are quite small, which only exacerbates this issue. It would be amazing if these could be generated in the ATM Mining Dim as well!

**Comment by Mrminesheeps** [comment]
bump

**Comment by Mrminesheeps** [comment]
Would just like to mention this is STILL an issue post-update. Brand new mining dimension generated STILL has no scheelite veins.

**Comment by BlueHero233** [comment]
Scheelite and Tungstate veins still spawn on the End Islands, albeit even more rare than naquadah, but yeah it is misleading to say oregen was moved to the mining dimension

I might also add that fluorite doesnt spawn either which, requiring a minimun of 900,000,000 buckets of fissile fuel to get the antimatter necessary to beat the game, its a little tiresome

**Comment by loving2** [comment]
This should be resolved in the latest version, including the fluorite spawning in the mining dimension, but please let me know if there are still issues!
