### ISSUE TITLE
Failed to load mods

### ISSUE THREAD

**Issue by Dordoux** [AllTheMods/ATM-9#1365]
when I try to start atm9 this happens:

[crash-2024-02-17_15.32.58-fml.txt](https://github.com/AllTheMods/ATM-9/files/14319171/crash-2024-02-17_15.32.58-fml.txt)

[latest.log](https://github.com/AllTheMods/ATM-9/files/14319172/latest.log)

I tried the newest modpack and repairing both, the installation and the modpack und got the newest GPU driver.

**Comment by rueckl** [comment]
I am also having this issue.
If I backup the world and uninstall/reinstall, it works, but only once
[crash-2024-02-17_12.04.35-fml.txt](https://github.com/AllTheMods/ATM-9/files/14319218/crash-2024-02-17_12.04.35-fml.txt)
[latest.log](https://github.com/AllTheMods/ATM-9/files/14319220/latest.log)
![image](https://github.com/AllTheMods/ATM-9/assets/9300021/aa4b2f39-5b3b-4615-bc5b-ecfca5338496)

**Comment by Dordoux** [comment]
My problem is gone after restarting the pc. Sometimes it is that easy.

**Comment by rueckl** [comment]
I am still having the same problem =/

**Comment by rueckl** [comment]
The issue solved itself on the new version
