### ISSUE TITLE
Item Duplication and Dissaperances

### ISSUE THREAD

**Issue by ryanjrman** [AllTheMods/ATM-9#1367]
I am playing on a 4 person server with my friends and we are having major issues with item duplication and disappearances. When crafting, ghost items will stay in the crafted part of the grid. Crafting wood into planks yields a random amount of planks, not four stacks. Same with a lot of other recipes. For some reason, compressed stacks will sometimes turn into infinite wells of items, filling up backpack and inventory space. The only solution has been to get the item pile to go into a pit and compressing the inventory items. This is becoming very problematic. I just had a crash when crafting warped stem into planks. Really hoping this gets fixed in the next major update.

An unrelated issue that is likely unable to be fixed. Opening the AE2 inventory with the "search tooltips" enabled creates five seconds of lag before continuing. Could be an AE2 issue. Might also be a database issue.

**Comment by Kevin-Marsh** [comment]
This was a bug caused by fastworkbench in a single version of the pack. Please update your server and clients if you are still experiencing this issue.

**Comment by ryanjrman** [comment]
> This was a bug caused by fastworkbench in a single version of the pack. Please update your server and clients if you are still experiencing this issue.

I have gone through several versions and it has followed me through. I have not updated to the most recent version but will try it out and edit this post if its still a problem.

**Comment by ryanjrman** [comment]
This issue appears to be fixed! Thank you!
