### ISSUE TITLE
Create: Steam 'n' Rails won't allow retrieval of certain tracks

### ISSUE THREAD

**Issue by ethan-w-foshee** [AllTheMods/ATM-9#1368]
**ATM9 Version**: 0.2.37
**Create: SNR Version**: 1.5.3+forge-mc1.20.1
**Create Version**: 0.5.1.f

Hi all! So when working with the Create Train Tracks, any train track that uses modded materials, when broken, won't drop itself, whether using a wrench, a pickaxe/axe, or a tool with silk touch.

### Recreate the issue:
> Create a train track using modded materials
> Place down the train track
> Break the train track
> Nothing drops

I personally tested Umbran wood from `Biomes O' Plenty`, Lunar Wood from `Blue Skies`, and Jacaranda Wood from `Biomes O' Plenty` again. I then tested with Vanilla Birch, as well as the Phantom Train Tracks (using Phantom Membrane), and these were dropped perfectly normally, using a wrench and/or pickaxe.

**Comment by ethan-w-foshee** [comment]
We updated our server to the current latest version of ATM9 [0.2.48], and this issue is still occurring.

**Comment by IThundxr** [comment]
This is being tracked at https://github.com/Layers-of-Railways/Railway/issues/282
