### ISSUE TITLE
RS infinite storage parts 

### ISSUE THREAD

**Issue by LPC2000** [AllTheMods/ATM-9#1370]
Both RS infinite storage parts have no recipe anymore after the last update

**Comment by GothBoyUK** [comment]
It was most likely an intentional change because they were removed (as per the commits).

**Comment by LPC2000** [comment]
> It was most likely an intentional change because they were removed (as per the commits).

Weird because there is a whole questline specifically for infinite storage

**Comment by slowthgt** [comment]
it was removed in https://github.com/AllTheMods/ATM-9/pull/1341 . I did ask why that happened on the pull request, because, as you correctly said, its still a quest and this change did not show up on the changelog at all.
