### ISSUE TITLE
AE2 quests does not detect the created item

### ISSUE THREAD

**Issue by ooichir0oo** [AllTheMods/ATM-9#1371]
I'm trying to complete two AE2 quests, "Auto-Crafting" and "The IO", and both have the same problem, it doesn't detect that I created the items, in this case one of the quests would be the ME Interface and the other the ME Pattern Provider.

I even tried to create it on a vanilla crafting table but it still doesn't work, it's not possible to submit the item because it says that the items will be auto-detected

![Screenshot 2024-02-18 110732](https://github.com/AllTheMods/ATM-9/assets/92395570/0681e0b6-c1f8-4d63-908e-ff991dc5962d)

As you can see in the screenshot above, it is possible to see the ME Patter Provider in my hand and the quest without completing it.

**Comment by TheBedrockMaster** [comment]
Add quest bug label.

**Comment by TheBedrockMaster** [comment]
"My quest is stuck/grey"
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

"I want the reward from the quest though"
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.
