### ISSUE TITLE
Regarding the issue of "Cytological Isolator" producing "Nether Star"

### ISSUE THREAD

**Issue by YoulQey** [AllTheMods/ATM-9#1376]
![{39B81789-5292-4f5b-A384-6B9BF9C55979}](https://github.com/AllTheMods/ATM-9/assets/53635729/a5e13e4e-a54c-4108-98ee-3cbae91f93a3)
Is it a balancing issue to use "Nether Star Seeds" to produce "Nether Star" in "Phytogenic Isolator" without the need for a corresponding core to operate?

**Comment by James103** [comment]
The same issue exists for Allthemodium, Vibranium, and Unobtainium, all of which should need Magical Soil to grow.

**Comment by YoulQey** [comment]
> The same issue exists for Allthemodium, Vibranium, and Unobtainium, all of which should need Magical Soil to grow.

Yes, it is easy to produce and highly efficient. I think it disrupts balance like the previous watermelon generator.

**Comment by YoulQey** [comment]
> > The same issue exists for Allthemodium, Vibranium, and Unobtainium, all of which should need Magical Soil to grow.
> 
> Yes, it is easy to produce and highly efficient. I think it disrupts balance like the previous watermelon generator.

The key issue is that it does not require magical soil or core

**Comment by Kevin-Marsh** [comment]
It isn't possible to add soils to an Insolator. This is behaving as expected.
