### ISSUE TITLE
[0.2.48] Can't Make Small HSS-S Gear with LEM MultiBlock

### ISSUE THREAD

**Issue by jungshinyung5** [AllTheMods/ATM-9#1378]
![2024-02-19_17 22 14](https://github.com/AllTheMods/ATM-9/assets/43872929/04411152-7e10-47cd-a2ee-957595932d25)
![2024-02-19_17 17 00](https://github.com/AllTheMods/ATM-9/assets/43872929/88e1d3f8-a016-4b01-8f7b-9d91501a7ffa)
![2024-02-19_17 17 09](https://github.com/AllTheMods/ATM-9/assets/43872929/00943f8b-6e35-4c8a-bd18-a9c7c579bbba)
![2024-02-19_17 18 15](https://github.com/AllTheMods/ATM-9/assets/43872929/54bf6618-8adf-4b77-b7dd-246d32d7fb15)
![2024-02-19_17 18 29](https://github.com/AllTheMods/ATM-9/assets/43872929/80e5bb87-d1d6-4851-a9b7-8f0f79c33c6c)

I'm using a translator.

Small HSS-S Gear should be made as above in LEM multi-block, but HSS-S Plate is being made

I didn't take a picture, but when I give programming of 1 and 10 to the 2 input buses in the LMP multi-block,

Recognizing the last set of 10, the result is only a recipe for programming 10.

I think it's probably the same error.

**Comment by swee356** [comment]
Is the "Distinct Buses" of each Input Bus set to Yes?

**Comment by jungshinyung5** [comment]
> 각 입력 버스의 "고유 버스"가 예로 설정되어 있습니까?

I've seen this comment and tried it, but it still doesn't work. Is there a set maximum number of Input Buses for one multiblock?

**Comment by swee356** [comment]
Wait, you seem to be using the wrong mold.
"Casting Mold" is the Mold for Fluid Solidifier, Extruder needs "Extruder Mold".

> I've seen this comment and tried it, but it still doesn't work. Is there a set maximum number of Input Buses for one multiblock?
As indicated in JEI's Multiblock Info, there is an upper limit to the total number of buses and hatches, because a minimum number of casings for each.
However, that upper limit is high and is not an immediate obstacle.
In fact, my LEM has 11 input busses, and I have no problem with their operation, and each one creates the correct item.

**Comment by jungshinyung5** [comment]
> Wait, you seem to be using the wrong mold. "Casting Mold" is the Mold for Fluid Solidifier, Extruder needs "Extruder Mold".
> 
> > I've seen this comment and tried it, but it still doesn't work. Is there a set maximum number of Input Buses for one multiblock?
> 
> As indicated in JEI's Multiblock Info, there is an upper limit to the total number of buses and hatches, because a minimum number of casings for each. However, that upper limit is high and is not an immediate obstacle. In fact, my LEM has 11 input busses, and I have no problem with their operation, and each one creates the correct item.

I'm sorry. Small Tungstensteel Gear and Small Stainless Steel Geer have been produced before, so I didn't notice it at all.
