### ISSUE TITLE
[0.2.48] Immersive Engineering causes crash upon entering village 

### ISSUE THREAD

**Issue by dekejr** [AllTheMods/ATM-9#1383]
When I enter a village with an Immersive Engineering hut it causes the server to crash and corrupt the chunk. Requiring me to delete player data for server to work again

Mods added: squat grow

crash report: 
https://pastebin.com/xCLEkMLV

**Comment by brisingraerowing** [comment]
If this pack uses the CTOV IE datapack, it's broken due to conveyors not liking being broken by worldgen. I have a modified version that removes the conveyors from the Jungle Tree Village hut, which seems to be the only one with them. It can probably also be removed with KubeJS and (IIRC) MoreJS.

**Comment by djnifos** [comment]
Would be interested in seeing the datapack, would you care to PR it?

**Comment by Kevin-Marsh** [comment]
This should be resolved in 0.2.55
