### ISSUE TITLE
TNT replication failure

### ISSUE THREAD

**Issue by Achiyun** [AllTheMods/ATM-9#1385]
All the Mods 9-0.2.49TNT replication failure，
but All the Mods 9-0.2.37.zip is ok

**Comment by Mitchell5200** [comment]
Expand please, what do you mean by `"TNT replication failure"` do you mean item dupes? if so, good, we dont' want any item dupes

**Comment by Achiyun** [comment]
> Expand please, what do you mean by `"TNT replication failure"` do you mean item dupes? if so, good, we dont' want any item dupes

I made a machine using redstone ，I used the bug of copying TNT, but it is now invalid. However, in the All the Mods 9-0.2.37.zip version, this bug is useful
