### ISSUE TITLE
Workbench recipe book disappears

### ISSUE THREAD

**Issue by Achiyun** [AllTheMods/ATM-9#1386]
All the Mods 9-0.2.49

**Comment by Mitchell5200** [comment]
the vanilla recipe book? always gets disabled in our packs, JEI exists for that reason

**Comment by Achiyun** [comment]
> 香草食谱书？在我们的包中总是被禁用，JEI 就是因为这个原因而存在的

ok, I remember it was opened before. Did I make a mistake? How can I enable it
