### ISSUE TITLE
Chipped Mod Workbenches

### ISSUE THREAD

**Issue by Mndarrr** [AllTheMods/ATM-9#1388]
After updating our server and client to the latest update (0.2.49) for ATM9, none of the Chipped workbenches allow item or search input and have a different UI from the older versions of ATM9. This includes all the work benches like Mason, Alchemy, Botanist, Glassblower etc for the mod and all the backpack/chest upgrades that use the mod Chipped. The block types still show in JEI and previously placed blocks made using the mod still appear in world, just unable to use the workbenches to create more. 

This is the UI from the mod showcase video (for glassblower table), and how the UI appeared prior to this latest update:
![mod showcase](https://github.com/AllTheMods/ATM-9/assets/19742210/47058ae5-71e2-4f9c-815d-5dfe89e9133a)

This is the UI for the Mason Table on the latest version of ATM9:
![Mason Table](https://github.com/AllTheMods/ATM-9/assets/19742210/e771a22f-7b31-4f9c-bbae-8ac283340078)

And the backpack upgrade UI for Mason Table not allowing item creation:
![Mason Backpack Upgrade](https://github.com/AllTheMods/ATM-9/assets/19742210/e392920a-34d6-488d-aa43-76e6c72deaa4)

**Comment by Thomulus** [comment]
Same issue for me

**Comment by Mitchell5200** [comment]
Gold blocks are in the alchemy bench, Raw gold ore storage blocks are the mason table
