### ISSUE TITLE
Can't ultimine Allthemodium ores

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-9#1391]
As of All the Mods 9 version 0.2.36, all Allthemodium ores are unable to be mined using FTB Ultimine.

Allthemodium ores were able to me mined using FTB Ultimine in previous All the Mods modpacks.

If this is a newly intended change, the following line in the tooltips for Allthemodium ores should be changed:
```
PLAYER MINEABLE ONLY. NOT QUARRYABLE
```
should be
```
PLAYER MINEABLE ONLY. NOT QUARRYABLE OR VEINMINABLE.
```

**Comment by Mrminesheeps** [comment]
I thought it was kind of obvious. And for those who didn't think so, they'd find out pretty quickly.
