### ISSUE TITLE
Added the use of Gregtech to handle five-fold ore generation for ATM9.

### ISSUE THREAD

**Issue by tangzixiang-hash** [AllTheMods/ATM-9#1397]
I was tired of using mek for mineral multiplication (because of TPS), so I wrote a script where gregtech could replace mek for all minerals.
[GTM-MEK-5bei.zip](https://github.com/AllTheMods/ATM-9/files/14361646/GTM-MEK-5bei.zip)

**Comment by Fjoaorossi** [comment]
On which folder of kubejs I can add this script to use it too?
