### ISSUE TITLE
Some GregTech Multiblock Quests Won't Complete

### ISSUE THREAD

**Issue by twhickey** [AllTheMods/ATM-9#1399]
I'm working on the LuV Tier quests for GT, and some of the multiblock quests around the Alloy Blast Smelter group of quests won't complete (but some of them will).  All of the tasks except for the "Observe {X} complete"  I have not made it to the point of trying all of them yet, but here's what I've found so far. For all of the ones that will not complete, I've completed the prerequisites, and all of the tasks on the quest except observing the multiblock are complete. For the ones that won't complete, I've tried completely tearing down and rebuilding the multiblock, and also just removing and replacing the controller block, neither one works.

Completed Successfully:
* Large Maceration Tower
* Large Sifting Funnel
* Large Chemical Bath

Will Not Complete:
* Alloy Blast Smelter
* Large Centrifugal Unit

**Comment by TheBedrockMaster** [comment]
Add quest bug label.

**Comment by TheBedrockMaster** [comment]
Add quest bug label. Are these still broken?
