### ISSUE TITLE
It keeps crashing because of Ad Astra mod

### ISSUE THREAD

**Issue by aerowand** [AllTheMods/ATM-9#1401]
If somebody uses or (maybe have) the Ad-Astra block/item the server crashes. And when I go somewhere near there, the server crashes.

this is the log : https://mclo.gs/U8qjDpE
and this is the crash log : https://mclo.gs/he8adzC

[222월2024 14:03:57.763] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
--
8176 | net.minecraft.ReportedException: Ticking block entity
8177 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8178 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8179 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8180 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8181 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8182 | at java.lang.Thread.run(Thread.java:1583) ~[?:?]
8183 | Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
8184 | at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
8185 | at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
8186 | at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
8187 | at java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
8188 | at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
8189 | at earth.terrarium.adastra.common.utils.TransferUtils.pullFluidNearby(TransferUtils.java:89) ~[ad_astra-forge-1.20.1-1.15.17.jar%23503!/:?]
8190 | at earth.terrarium.adastra.common.blockentities.machines.OxygenLoaderBlockEntity.tickSideInteractions(OxygenLoaderBlockEntity.java:88) ~[ad_astra-forge-1.20.1-1.15.17.jar%23503!/:?]
8191 | at earth.terrarium.adastra.common.blockentities.base.ContainerMachineBlockEntity.internalServerTick(ContainerMachineBlockEntity.java:51) ~[ad_astra-forge-1.20.1-1.15.17.jar%23503!/:?]
8192 | at earth.terrarium.adastra.common.blockentities.base.EnergyContainerMachineBlockEntity.internalServerTick(EnergyContainerMachineBlockEntity.java:26) ~[ad_astra-forge-1.20.1-1.15.17.jar%23503!/:?]
8193 | at earth.terrarium.adastra.common.blockentities.base.RecipeMachineBlockEntity.internalServerTick(RecipeMachineBlockEntity.java:31) ~[ad_astra-forge-1.20.1-1.15.17.jar%23503!/:?]
8194 | at earth.terrarium.adastra.common.blocks.base.BasicEntityBlock.lambda$getTicker$2(BasicEntityBlock.java:65) ~[ad_astra-forge-1.20.1-1.15.17.jar%23503!/:?]
8195 | at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8196 | at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8197 | at net.minecraft.world.level.Level.redirect$bhh000$observable$redirectTick(Level.java:4040) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8198 | at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8199 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8200 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?]
8201 | ... 5 more
8202 | [222월2024 14:03:57.795] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 76b04f78-4028-42fd-9164-10709ab195b9
8203 | [222월2024 14:03:57.795] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: E:\ATM9\Server-Files-0.2.51\.\crash-reports\crash-2024-02-22_14.03.57-server.txt

**Comment by TheBedrockMaster** [comment]
Add crash label. Did you figure it out?
