### ISSUE TITLE
Stuck on preparing for world creation 

### ISSUE THREAD

**Issue by Dobanek** [AllTheMods/ATM-9#1405]
Hello i have been having a issue that when i create a new singleplayer world it just won't load and its stuck on preparing for world creation screen can someone help me?

**Comment by jaideepheer** [comment]
I'm facing the same issue.
Many JEI plugins seem to take a very long time to register recipes.
![image](https://github.com/AllTheMods/ATM-9/assets/15523937/b0c89692-a830-46f0-b960-637be96815b7)

I'll post the full `latest.log` file once my game starts.

**Comment by jaideepheer** [comment]
In my case, JVM ran out of memory. I had allocated `5408MB` and the Java process was taking upwards of `7.9GB`.
Here is my latest log file: [latest.log](https://github.com/AllTheMods/ATM-9/files/14396070/latest.log)

You can see in the log that it ran out of memory while registering recipes
![image](https://github.com/AllTheMods/ATM-9/assets/15523937/d6ac223a-3577-4ceb-b6b2-4fd163bb7f05)

**Comment by Dobanek** [comment]
Okay its working now thanks for the help

**Comment by jaideepheer** [comment]
> Do you have at least 16 GB of RAM on your computer? If so, try allocating at least 8 GB (8192 MB) to the game. If not, you won't be able to run the full pack.

Thanks, Dobanek, raising memory fixed the issue.
