### ISSUE TITLE
Weird sound + darkening screen after being at bedrock level for >1 min

### ISSUE THREAD

**Issue by James103** [AllTheMods/ATM-9#1411]
As of All the Mods 9 version 0.2.46, when going to bedrock level and staying there for >1 min, I hear some weird sounds, then the screen goes dark as a pattern of pitch black covers my view. What mod causes this effect and how can it be disabled?

**Comment by Mitchell5200** [comment]
Voidscape, and yes

**Comment by James103** [comment]
Thank you for letting me know. To disable this effect, a player (in singleplayer) or server admin can go into the Voidscape config (voidscape-common.toml) and change this line to an empty list `[]`:
https://github.com/AllTheMods/ATM-9/blob/17d759af40abb4b46138d2e432bcd5dc643a6195/config/voidscape-common.toml#L4

Also make sure `bedrockTeleportationDimensionWhitelist` is set to true. This combination should disable players being teleported into the Voidscape dimension from standing on bedrock.

If Voidscape access is desired, alternative means are necessary; e.g. a custom recipe for the blocks making up the Void Portal (if one hasn't been built already) or running the command to teleport the player there.
