### ISSUE TITLE
Soul Enchanter not working with Charm of Allthemodiumsight

### ISSUE THREAD

**Issue by g0urra** [AllTheMods/ATM-9#1412]
Trying to enchant Charm of Allthemodiumsight with the Soul Enchanter does not bring up any enchants. Other similar charms such as Charm of NetheriteSight does not have the same issue.
![bild](https://github.com/AllTheMods/ATM-9/assets/12349921/cc5183c4-7840-4716-8b4b-0d1104f42f53)
![bild](https://github.com/AllTheMods/ATM-9/assets/12349921/06a5c37e-6b44-4bb3-a79f-609855ea647b)

**Comment by Kevin-Marsh** [comment]
This is a feature added by apotheosis. It doesn't work in third party enchanters.
