### ISSUE TITLE
Problem entangling blocks

### ISSUE THREAD

**Issue by MushuPlatypus** [AllTheMods/ATM-9#1413]
In version 0.2.51 I cannot entangle blocks in the hyperbox.

// Downgrading to Entangled 1.3.16 for Forge 1.20 fixes the issue

**Comment by Infarcactus** [comment]
an issue like this already existed : 
https://github.com/AllTheMods/ATM-9/assets/149241321/ffccf36d-2ca0-44e9-bc2f-0d0cee1087c6

**Comment by Infarcactus** [comment]
An issue like this alread yexisted : https://github.com/AllTheMods/ATM-9/issues/1395
