### ISSUE TITLE
[Feature-Request] Make so the pearls from the enderman overhauled can be converted to vanilla ones

### ISSUE THREAD

**Issue by ToastWithCheeze** [AllTheMods/ATM-9#1420]
As in the title. It is kind of annoying to find normal endermans because of enderman overhauled and with them dropped custom pearls with some recipes dont like, for example the potion master mod need normal ender pearls and i cant seem to easily convert the warped pearls to vanilla pearls

**Comment by Mrminesheeps** [comment]
Since the pearls share the entry forge:ender_pearls with vanilla pearls, you may be able to use Mekanism's Unifier/Dictionificator/whatever to auto-convert the pearls.

**Comment by ToastWithCheeze** [comment]
> Since the pearls share the entry forge:ender_pearls with vanilla pearls, you may be able to use Mekanism's Unifier/Dictionificator/whatever to auto-convert the pearls.

I guess it would work but it is kind of annoying early game getting ender pearls

**Comment by Mrminesheeps** [comment]
> > Since the pearls share the entry forge:ender_pearls with vanilla pearls, you may be able to use Mekanism's Unifier/Dictionificator/whatever to auto-convert the pearls.
> 
> I guess it would work but it is kind of annoying early game getting ender pearls

Another method I noticed was you can use them to make pearl blocks, which will convert back into vanilla pearls.
