### ISSUE TITLE
ExtremeReactors turbine power output limited by its own internal buffer

### ISSUE THREAD

**Issue by TheLastPaladin** [AllTheMods/ATM-9#1424]
Extreme Reactor's turbine is easily capable of producing millions of FE/t. I've just build a turbine that should generate somewhat over 15M FE/t. After connecting everything I've noticed the turbines only outputs 9.06M FE/t . This only makes sense, since this is exactly the size of its internal energy buffer. I've taken some screenshots to visualize this problem.

CURRENT BEHAVIOUR:
The power generation is limited by the turbines internal energy buffer.

EXPECTED  BEHAVIOUR:
The turbines internal energy buffer should always be several times higher than the maximum power that can be generated.

I don't know if its possible to modify the internal energy buffer of Extreme Reactor Multiblocks(maybe kubejs or sth?), however I didn't find anything in the configs. If this is not an issue on your side but rather a problem with the mod itself please let me know so I can report it to the extreme reactors git issue board.

Thanks!

![2024-02-26_01 19 50](https://github.com/AllTheMods/ATM-9/assets/52897035/4cb9d528-8c17-450d-aeb0-fa719a966208)
![2024-02-26_01 20 02](https://github.com/AllTheMods/ATM-9/assets/52897035/f527feab-582f-4a56-b294-6e519185341d)
![2024-02-26_01 20 12](https://github.com/AllTheMods/ATM-9/assets/52897035/087a90ac-9ed0-44a7-9969-447d88607beb)

**Comment by James103** [comment]
What version of Extreme Reactors are you running?

**Comment by TheLastPaladin** [comment]
ExtremeReactors2 - 2.0.77

**Comment by James103** [comment]
What version of ZeroCore are you running?

**Comment by Kevin-Marsh** [comment]
Turbines are buffed in ATM9 by 3 times the energy production. This means that it is running into the cap of what the turbine can store. There isn't really a method to fix on either our end or extreme reactors unless we wanted to simply cut the power back down and nerf the turbines.
