### ISSUE TITLE
Spatial distortions are way too rare

### ISSUE THREAD

**Issue by sjs262** [AllTheMods/ATM-9#1425]
Like many other players on atm9, I have spent a considerable number of hours searching through the demon realm for a spatial distortion with no luck. I'm on my 6th hour and I think there is no reason for it to be this rare, especially because you need to find 2 to get to the miners dimension. Is there any way to tweak the rarity? At the very least, there should be a config option for it.

**Comment by GothBoyUK** [comment]
Be aware that I never got any spatial distortion 'warnings' at all during my playthrough. However, I randomly found the doors when deciding to go back to the start and scout every single room again and eventually got into the mines. Still can't find anywhere near enough Hellforged items though.

**Comment by Kevin-Marsh** [comment]
We added 2 methods to obtain intricate hellforged parts after you obtain your first parts. You can use either the hellforged bee or the meteor ritual from blood magic to obtain more. We will forward your thoughts on the rarity to the blood magic devs.
