### ISSUE TITLE
Missing Block [0.2.51]

### ISSUE THREAD

**Issue by MitchellZahn** [AllTheMods/ATM-9#1431]
While upgrading the Minecolonies Town Hall from level 2 to level 3 using the FairyTale colony pack, it requres a Block of Zinc from the Create mod and won't accept the Zinc Block from AllTheOres. However, the Block of Zinc from Create doesn't exist within the mod pack

Edit; Block of Brass is also missing to create the "Framed Framed Glass" for the level 2 to level 3 upgrade for the university

**Comment by ddotthomas** [comment]
Still an issue on 0.2.60

**Comment by Noes4** [comment]
Also goes for a guard tower from 2 -> 3, not able to craft framed windows with a block of brass in the architect cutter . cause were missing the create block of brass

**Comment by Mitchell5200** [comment]
I have not yet found a proper way to fix this yet, However, i have found a workaround
Use the mekanism "oredictionificator", and set `'forge:storage_blocks/brass'` (or /zinc, or anyother material) as the filter, and click the arrows until the create brass shows up, then toss in ATO brass. ***(as pictured)***
![2024-08-13_21 53 33](https://github.com/user-attachments/assets/cd9f2e22-9468-4cd5-a594-eb08645d412f)
![2024-08-13_21 53 50](https://github.com/user-attachments/assets/4952261f-c977-4f89-b3fe-5b9c25e87dad)

Duplicate issues, #1431, #1356
