### ISSUE TITLE
Star matter plasma Issue & missing recipe for UHV 64a substation energy hatch

### ISSUE THREAD

**Issue by Moustik2002** [AllTheMods/ATM-9#1432]
Hi i've tried multiple way to inject Helium plasma, iron plasme and oxygen plasma in my fusion reactor but multiblock seems not to accept them. I've tried through dedicated input hatch or within nonuple ones.

And as mention in title the recipe for UHV 6A substation energy hatch doesn't exist then the dedicated quest cannot be achieved?

**Comment by Moustik2002** [comment]
Star compression module recipe is not working either in the star forge

**Comment by Aeiiry** [comment]
I'm also experiencing this, I noticed the recipe for star matter plasma is the only one in the fusion reactor that has an empty slot in the first fluid input, could be nothing but wanted to note a discrepancy.
![image](https://github.com/AllTheMods/ATM-9/assets/19582161/07bc7604-5687-4fbf-b3d9-8197271ce698)

**Comment by BrandonJ98** [comment]
UHV 64A Substation Energy Hatch is still missing a recipe. Is this an ATM thing, or GregTech thing?

**Comment by loving2** [comment]
I cannot replicate these issues on a fresh install of ATM9 v0.3.5.
