### ISSUE TITLE
[0.2.51] not complete multi block quests

### ISSUE THREAD

**Issue by jungshinyung5** [AllTheMods/ATM-9#1436]
I'm using a translator.

Some multi-block quests in the newly added GregTech quest line are not cleared.

I'm playing single and I'm not even using cheat.

I would appreciate it if you could improve it.

![2024-02-28_18 40 50](https://github.com/AllTheMods/ATM-9/assets/43872929/9c6139b0-1c70-48d1-bf7e-fdc0f072890a)
![2024-02-28_18 40 53](https://github.com/AllTheMods/ATM-9/assets/43872929/1ac156ff-fd02-4b6c-8fe4-e8a47f79eac5)
![2024-02-28_18 41 07](https://github.com/AllTheMods/ATM-9/assets/43872929/e7474e8b-1abb-4191-b8fb-f84d342cdaf1)
![2024-02-28_18 41 09](https://github.com/AllTheMods/ATM-9/assets/43872929/f59aa730-1c77-4ef2-bb50-022d25936cc8)
![2024-02-28_18 41 13](https://github.com/AllTheMods/ATM-9/assets/43872929/5635f7b5-8c21-4a11-b68c-46ae15d05ae4)
![2024-02-28_18 41 15](https://github.com/AllTheMods/ATM-9/assets/43872929/901e7896-0ff7-4b1b-aa38-4c389a914b49)
![2024-02-28_18 41 16](https://github.com/AllTheMods/ATM-9/assets/43872929/e1ca27ee-4bad-432e-8845-c5bdd7c16b81)
![2024-02-28_18 41 19](https://github.com/AllTheMods/ATM-9/assets/43872929/f0b7cf19-6068-4bfd-ad60-2881ef2a0c00)
![2024-02-28_18 41 21](https://github.com/AllTheMods/ATM-9/assets/43872929/268caff0-75be-4cc5-9da6-2406e83ae94f)
![2024-02-28_18 41 23](https://github.com/AllTheMods/ATM-9/assets/43872929/a93803d7-350e-47ab-852d-985deef546be)
![2024-02-28_18 41 24](https://github.com/AllTheMods/ATM-9/assets/43872929/059de4ca-a84e-4959-9d68-07e6898b0314)
![2024-02-28_18 41 26](https://github.com/AllTheMods/ATM-9/assets/43872929/64bbd4aa-7680-443a-b898-8313d4c1e124)
![2024-02-28_18 41 28](https://github.com/AllTheMods/ATM-9/assets/43872929/37909048-62fb-4199-a476-0d72aec438a5)
![2024-02-28_18 41 36](https://github.com/AllTheMods/ATM-9/assets/43872929/342ae349-8bc2-423c-8507-f3b75bc0ec76)

**Comment by jungshinyung5** [comment]
f it's difficult, could you at least delete it from the quest line?

I've been playing ATM9 for more than 700 hours, but I'm so sorry for this part

For those who are challenging all the questions, please take quick action.

**Comment by loving2** [comment]
Thank you for reporting this issue! I've managed to fix this in my testing world, and I added the fix to a Pull Request so it should be fixed in the next update.
