### ISSUE TITLE
My  Unobtainium Pickaxe and atomic disassembler turned to stone pickaxes

### ISSUE THREAD

**Issue by MutedInvisible** [AllTheMods/ATM-9#1437]
I think i might have come across a bug that has been encountered while i was doing Botania (making alfsteel). I just made a time in a bottle to use it on the mana spreader and while i did that my  Unobtainium Pickaxe and atomic disassembler turned to stone pickaxes.
& my other tools did not,like my allthemodium alloy paxel.I would like to know if this is a feature or a unlucky bug i just have discovered by accident.

Thank you

**Comment by thevortex** [comment]
this is not a behaviour introduced by the Allthemodium mod itself, and i do not believe this is an addition at the pack level either

**Comment by MutedInvisible** [comment]
could you Elaborate a bit more mate?

**Comment by thevortex** [comment]
i don't have any more information at this time, only that this is not an intended behaviour from Allthemodium or a recipe/interaction we added specifically at the pack level, and thus we need to do more investigating

**Comment by Kevin-Marsh** [comment]
Do you use refined storage for your autocrafting?
