### ISSUE TITLE
[0.2.37]Error when updating to latest version

### ISSUE THREAD

**Issue by antoineok** [AllTheMods/ATM-9#1438]
Hi. I'm trying to update my server from 0.2.37 to 0.2.51.

However, it always crashes at the same time (The problem comes from the Stargate mod, according to the crash report):

Here is the crash report:
https://pastebin.com/evYqsZ61

**Comment by humanehj** [comment]
+1

**Comment by antoineok** [comment]
I want to add that i have the same error if i try to update to 0.2.38. Any version above 0.2.38 just give me this crash report

**Comment by djnifos** [comment]
https://allthemods.github.io/alltheguides/help/server/#updating

That mod changed how it saves it's data.  We have a datapack to make stargates generate more than 1 per world.  The newer versions have an additional mod that will fix the datapacks for you, but you have to have done the update correctly.  The link I've shared is our basic guide on updating a server.  I usually do that 1st method in the Manually section personally, but there's no reason to prefer it necessarily over the other.

**Comment by antoineok** [comment]
That's what i did. Manual update, second method. I have no modified kubejs folder, i copied the world, local, server.properties and eula.txt

**Comment by antoineok** [comment]
No matter how many times i try to setup the server, copying the eula, the server.properties, the world, local and journeymap folders in a new server instance, i always get the error.
Here is, once again, the error (this time on mclo.gs because it's a bit more appropriate for this kind of problems:
https://mclo.gs/b0sb4hH
And the latest.log (that i haven't sent):
https://mclo.gs/4auCYXu

**Comment by antoineok** [comment]
serverconfigupdater-server:
https://mclo.gs/mIUtW8Q
serverconfigupdater-common:
https://mclo.gs/IvQZ9Bh

**Comment by djnifos** [comment]
and if you chase down the paths mentioned in the second one, have they been deleted? server>kubejs>data>sgjourney>worldgen and server>kubejs>data>sgjourney>tags>worldgen ?

**Comment by antoineok** [comment]
server>kubejs>data>sgjourney>tags>worldgen exists it contains a structure folder, which contains 2 json files
server>kubejs>data>sgjourney>tags>worldgen>structure>cartouche.json:
https://mclo.gs/asuji1f
server>kubejs>data>sgjourney>tags>worldgen>structure>has_stargate.json:
https://mclo.gs/IAJIAza

server>kubejs>data>sgjourney>worldgen doesn't exists

**Comment by djnifos** [comment]
Yes, on my working server, kubejs>data>sgjourney contains only an empty tags folder.  Make it like that and try to boot again.

**Comment by djnifos** [comment]
weird, are those worldgen folders recreated?

**Comment by antoineok** [comment]
no

**Comment by djnifos** [comment]
Did you have any stargates opened prior to trying to update?

**Comment by antoineok** [comment]
No, but maybe someone in the other team did. I'm waiting for their response

**Comment by antoineok** [comment]
No one touched the stargate mod

**Comment by djnifos** [comment]
If you do that, there are three folders in that Kubejs>data folder that will have to go for it to boot : Sgjourney, common_stargates, and overworld_cartouches

**Comment by antoineok** [comment]
so if i move the sg mod outside of the mods folder, and do the same with those three folders, the server will start normally, and then i can put them back and it won't cause troubles?

**Comment by djnifos** [comment]
That should work, yes, but I'm not 100% sure if it won't just crash again when you put them back.  It's not clear what the problem actually is.  Seems like something is missing from Vanilla that it's trying to use.

**Comment by antoineok** [comment]
yeah no, it crashes when put back, which is wierd because i don't recall it crashing when creating a new map

**Comment by antoineok** [comment]
Yeah, it doesn't crash when creating a new map.
