### ISSUE TITLE
[Question] Would there be any interest in Alchemistry/Mekanism/GregTech compatibility?

### ISSUE THREAD

**Issue by sciguyryan** [AllTheMods/ATM-9#1442]
Just a quick question before I start to implement it, would there be any interest in some additional Alchemistry, Mekanism and GregTech intercompatability?

I've been thinking about implementing some recipes to allow various chemicals from Alchemistry to be used by Mekanism and GregTech (and vice versa).

If this is something you think may be useful, let me know and I'll see what I can sort out.

**Comment by Mrminesheeps** [comment]
Absolutely. This would be nice to see.

**Comment by sciguyryan** [comment]
> Absolutely. This would be nice to see.

It's actually a fairly large amount of work since GT is a huge mod and covers a vast area.

I was planning on doing things such as making sure the GT dusts, gems, etc. can be dissolved via the Dissolver and ensuring that the chemical formulae used by GT to determine its outputs are the same as the Alchemistry outputs. I've written a tool to help with this, but it's still a largely manual process.

The process also includes reconfiguring things like redstone to produce the same outputs as would be produced with GT. By aligning them in this way I can also add compatibility between Alchemistry, Mekanism and GT fluids too, in certain instances. For example, Alchemistry ethylene into Mekanism ethylene can then be done as follows:

`{
  "type": "mekanism:rotary",
  "fluidInput": {
    "amount": 1,
    "fluid": "chemlib:ethylene_fluid"
  },
  "fluidOutput": {
    "amount": 1,
    "fluid": "mekanism:ethylene"
  },
  "gasInput": {
    "amount": 1,
    "gas": "mekanism:ethylene"
  },
  "gasOutput": {
    "amount": 1,
    "gas": "mekanism:ethylene"
  }
}`

Where is the equivalent of Almost Unified for fluids? Bleh. I'm doing this for my own personal version of the pack, even if it ends up not being something that's wanted for the pack as a whole.

**Comment by Mrminesheeps** [comment]
Yeah im trying to get a modification to Wasted bees pushed so we don't have to Chernobyl our worlds/bases for the sake of a bee, without it breaking progression. See Pull Requests if interested, I have the files there.

**Comment by StrwbryPanda** [comment]
I was just thinking today about how neat it would be if there were ways for these mods to have compatible items! (I made the polonium bees only to realize they only make the chemlib polonium)

**Comment by sciguyryan** [comment]
> I was just thinking today about how neat it would be if there were ways for these mods to have compatible items! (I made the polonium bees only to realize they only make the chemlib polonium)

I'm working on it here: http://github.com/sciguyryan/ATM-Mod-Integration/

It's a fairly large process though. At the moment I'm working through the dissolution recipes. I've had to make a bunch of tweaks and I've tried to make it so that the GT process isn't sidelined either. I want the mods to be able to interact, not for one to replace the other.

**Comment by Kevin-Marsh** [comment]
A lot of alchemistry compatability has been specifically turned off in atm9.

**Comment by Daimonfire1** [comment]
> > Absolutely. This would be nice to see.
> 
> It's actually a fairly large amount of work since GT is a huge mod and covers a vast area.
> 
> I was planning on doing things such as making sure the GT dusts, gems, etc. can be dissolved via the Dissolver and ensuring that the chemical formulae used by GT to determine its outputs are the same as the Alchemistry outputs. I've written a tool to help with this, but it's still a largely manual process.
> 
> The process also includes reconfiguring things like redstone to produce the same outputs as would be produced with GT. By aligning them in this way I can also add compatibility between Alchemistry, Mekanism and GT fluids too, in certain instances. For example, Alchemistry ethylene into Mekanism ethylene can then be done as follows:
> 
> `{ "type": "mekanism:rotary", "fluidInput": { "amount": 1, "fluid": "chemlib:ethylene_fluid" }, "fluidOutput": { "amount": 1, "fluid": "mekanism:ethylene" }, "gasInput": { "amount": 1, "gas": "mekanism:ethylene" }, "gasOutput": { "amount": 1, "gas": "mekanism:ethylene" } }`
> 
> Where is the equivalent of Almost Unified for fluids? Bleh... yeah... I know that's a difficult one.
> 
> I'm doing this for my own personal version of the pack, even if it ends up not being something that's wanted for the pack as a whole.

I am actually working on an equivalent of Almost Unified for fluids, planning to finish it in the next few days

**Comment by BrandonJ98** [comment]
> A lot of alchemistry compatability has been specifically turned off in atm9.

Why?? Some of these resources are super low chance drop and take forever to get, or are a rare ore that only spawns in small veins every 50 or so chunks. When things with progression like late game GregTech take thousands of the material, are you really expecting people to sit and sift for a chance drop for 5 hours just to get a fraction of what they need??

 I'm all for having players put in the work to get the first chunk (which I have done), but after that I'd rather be able to generate it reliably and automatically versus the current "sift, hope, and try not to fill all of the storages" method that we have to do.
