### ISSUE TITLE
mage armor for ars and iron

### ISSUE THREAD

**Issue by Tinodon** [AllTheMods/ATM-9#1444]
Hello, ars nouveau and iron spell books are too insane magic mod but if we can have the unobtainium armor only for iron spell, that's bad. 
I think make the armor works for both mod can be significantly.
Thx for your works Dev <3

**Comment by Kevin-Marsh** [comment]
This was made for the pack by the dev of Irons spells. We would support adding something for ars if another community member were to create something but we can't add a mod that doesn't exist.
