### ISSUE TITLE
Missing Recipe for Slurry

### ISSUE THREAD

**Issue by KarmaTsukigami** [AllTheMods/ATM-9#1445]
Whilst setting up the mekanism ore processing system, I found that there was no recipe for Dirty Osmium Slurry to be cleaned to Clean Osmium Slurry in the Chemical Washer, but it's also the only recipe missing for me.

**Comment by Krotu** [comment]
I had this exact issue today running the game in single player. The chemical dissolution chamber was backed up with dirty osmium slurry and the washer was not accepting it, jei had no recipe for dirty osmium slurry -> clean osmium slurry but the rest of the recipes for processing clean osmium slurry into ingots were present, only the washer recipe was missing.

A client restart fixed the issue in my case.
