### ISSUE TITLE
Can't use GT Macerator on AllTheOres Ruby Ore

### ISSUE THREAD

**Issue by cokeacolaking** [AllTheMods/ATM-9#1456]
https://imgur.com/a/083D6kT

Asked around, it worked in previous patches (0.2.40) and it shows up on JEI but doesn't process anything.

**Comment by thepauljs** [comment]
I can confirm this doesn't work, though it is worth noting that the deepslate variant does work

**Comment by MKr4zy** [comment]
new Modpack Version (0.2.55) Ruby ore is now working, sort of.
Now theres two recepies, 
![Bild_2024-03-30_203432993](https://github.com/AllTheMods/ATM-9/assets/33859570/d881367c-1e4e-4a64-bcfb-2d48f6fbd460)
The top one is the expected Output with "2x Crushed Ruby Ore; chance for Chromium Dust and  Chance for Stone dust".
The bottom one is the one that works in the macerator, and it produces 2 crushed tin Ore with the rest...

**Comment by battle00333** [comment]
I am running into this issue as well with some of the vanilla deepslate ores. 
But this is with the basic macerator. from memory all the macerators pull from the same recipe list.
So far i have not found any deepslate ore that works.
