### ISSUE TITLE
[0.2.51] Corail Tombstone Flight Scroll effects do not wear off

### ISSUE THREAD

**Issue by d-avery** [AllTheMods/ATM-9#1457]
My friend use a Flight Scroll from Corail Tombstone while in the Voidscape dimension. He fell into the void, so he got sent back to the overworld (but didn't die). The Flight Scroll wore off in the overworld, but its effects did not, and now he can fly indefinitely.

Expected behavior: Flight effect should've stopped when the scroll wore off.

Latest server and client at time of writing (0.2.51)

**Comment by TheBedrockMaster** [comment]
Add bug label. Is this still an issue?

**Comment by d-avery** [comment]
I'm unsure. The server in question is not active anymore, it's been a while. I don't have the pack installed anymore either.

**Comment by TheBedrockMaster** [comment]
So this can be closed?

**Comment by d-avery** [comment]
I can't confirm if it's still an issue in the latest version. I would say close it for now, and if I encounter it again in the future, I will make sure to file a new report.

**Comment by d-avery** [comment]
Oops. Closing now

**Comment by d-avery** [comment]
Closing issue
