### ISSUE TITLE
craft star compresion module is broken

### ISSUE THREAD

**Issue by Snakedon** [AllTheMods/ATM-9#1460]
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/2441a2aa-ecc1-4bee-bfe8-b72cb3e494c3)
craft star compresion module in star forge not working

**Comment by Snakedon** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/495fe716-8a51-41d0-a916-df8b3e536b69)
the rest of the crafts that I tested for GregStor work.

**Comment by loving2** [comment]
Thank you for reporting this! I have managed to fix this in my develeopment environment and added it to a pull request, so it should be fixed in the next update

**Comment by Snakedon** [comment]
Thank you for your quick response)
