### ISSUE TITLE
Modular Routers Breaker module not working

### ISSUE THREAD

**Issue by TheMasterTM69** [AllTheMods/ATM-9#1461]
For some reason when I made the breaker module to use as a method to farm Certus quartz for AE2 i put the module in and.. nothing happens.
Added power upgrade, still not working. (Redstone mode is off, should always work on its own)
Changed item to cobble stone instead, still not working and breaking the block.
Filters are all off so it should basically break anything and the correct side is selected.
![2024-03-04_23 20 01](https://github.com/AllTheMods/ATM-9/assets/75620187/d14ef671-aaa9-468b-b86b-2ac46863308b)
![2024-03-04_23 20 13](https://github.com/AllTheMods/ATM-9/assets/75620187/48247807-31db-414c-8a7d-d7008df3af60)
Is there something wrong with the mod or config perhaps? anyway to get it working again?

**Comment by Schrimpes** [comment]
Did you allow fake players on your team? is not allowed by default.

**Comment by GothBoyUK** [comment]
Are you also putting a Security Module in the router? You need one that has been set to the user who owns the chunk the router is in (most likely you). To set the owner you shift right click it in the air when you have it in your hand.

**Comment by TheMasterTM69** [comment]
OK i got it working.. 
Fake players was the issue ;-; i feel so dumb.
I feel like the Security module could work too @GothBoyUK
