### ISSUE TITLE
Polonium

### ISSUE THREAD

**Issue by Grant-K** [AllTheMods/ATM-9#1466]
I can Polonium to go into the Pressurized Reaction chamber doubled and triple checked inputs and im using pressurized pipes that have polonium in then but no luck!

**Comment by ArcTrooper210** [comment]
JEI should tell you where Polonium can be inputted

**Comment by TheBedrockMaster** [comment]
Any luck since?

**Comment by TheBedrockMaster** [comment]
You can Polonium?
