### ISSUE TITLE
Crash with functional storage

### ISSUE THREAD

**Issue by weeaudi** [AllTheMods/ATM-9#1467]
[crash-2024-03-07_04.22.57-server.txt](https://github.com/AllTheMods/ATM-9/files/14524021/crash-2024-03-07_04.22.57-server.txt)

i dont know what exactly is causing this but our server is completely unplayable.

**Comment by weeaudi** [comment]
After about 6 hours we were able to remove the offending block and get our server running again but this still is an issue that shouldn’t have happened.

**Comment by ArcTrooper210** [comment]
Next time if you want to send a crash log, use https://mclo.gs

**Comment by nickheyer** [comment]
Same thing just happened to me. My log matches OP's exactly
