### ISSUE TITLE
Vanilla Ingot to Block Recipe no longer working

### ISSUE THREAD

**Issue by Kaldoron** [AllTheMods/ATM-9#147]
Since the new Update 9-0.0.43 there are no more Recipes for Crafting Gold Block, Iron Block, Lapis Block, Redstone Block and so on.

**Comment by aAndrew3030** [comment]
It is the GregTech mod causing the issue, as it seems to implement its own (very unique) way of processing ore. Not sure if it is a error or intentional

**Comment by Kaldoron** [comment]
Since Gregtech doesn't have recipes for this blocks either i don't think its intended

**Comment by chady33** [comment]
you cant make glass as well Gregtech is messing everything up

**Comment by aAndrew3030** [comment]
Just disabled GregTech to confirm it is the mod, recipes back to normal. Probably best to stick to .42 till this is fixed

**Comment by chady33** [comment]
yes i roll back to 42

**Comment by aAndrew3030** [comment]
GregTech has been updated with a fix for this issue (version 1.0.8.a)

**Comment by R3dB3ard90** [comment]
I just updated to ATM9 0.62 and the missing glass recipe is happening to me. the Gtech version is gtceu-forge-1.20.1-1.0.11.a.jar

Does anyone know if this is fixed in 0.63? or is the solution to still just disable?
