### ISSUE TITLE
Game Crashes when using the occultism multiblock preview

### ISSUE THREAD

**Issue by Feedini** [AllTheMods/ATM-9#1471]
Title sums it up. This is the error message i get:

The game crashed whilst tesselating block model
Error: java.lang.IndexOutOfBoundsException: null

Exit code: -1

any and all help is appreciated

**Comment by Kevin-Marsh** [comment]
This is a bug that occurs when using shaders. The devs are aware of this issue but you should disable your shaders if you are still struggling with this issue.

**Comment by KragZer** [comment]
Same crash for me but not same problem !
[crash-2024-04-27_11.38.05-client.txt](https://github.com/AllTheMods/ATM-9/files/15137769/crash-2024-04-27_11.38.05-client.txt)
