### ISSUE TITLE
quest Micro Universe Orb

### ISSUE THREAD

**Issue by Snakedon** [AllTheMods/ATM-9#1473]
in quest Micro Universe Orb (MU) (GregTech) they require 28 MU Energy transmitter and 160 MU focus lens, but in the JEI  it’s 160 MU Energy transmitter and 28 MU focus lens, which is correct? 
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/6f3eea60-d5f4-4ba2-88bb-47f40e9f5950)
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/e88403c2-4af7-434d-a3ab-24d6c1f3815d)

**Comment by loving2** [comment]
JEI is correct, this must have been a typo, thank you for catching it!
