### ISSUE TITLE
Multiple Server Crashes/Server Failing to Start.

### ISSUE THREAD

**Issue by Fliptop023** [AllTheMods/ATM-9#1475]
Server is failing to start. Happens multiple times in fairly quick succession (maybe it is just looping).
Server is running latest version of the pack
[crash-2024-03-09_20.47.50-server.txt](https://github.com/AllTheMods/ATM-9/files/14548676/crash-2024-03-09_20.47.50-server.txt)
[crash-2024-03-09_20.36.39-server.txt](https://github.com/AllTheMods/ATM-9/files/14548677/crash-2024-03-09_20.36.39-server.txt)
[crash-2024-03-09_20.31.17-server.txt](https://github.com/AllTheMods/ATM-9/files/14548678/crash-2024-03-09_20.31.17-server.txt)
[crash-2024-03-09_20.26.17-server.txt](https://github.com/AllTheMods/ATM-9/files/14548679/crash-2024-03-09_20.26.17-server.txt)
[crash-2024-03-09_20.21.27-server.txt](https://github.com/AllTheMods/ATM-9/files/14548680/crash-2024-03-09_20.21.27-server.txt)
[crash-2024-03-09_20.16.39-server.txt](https://github.com/AllTheMods/ATM-9/files/14548681/crash-2024-03-09_20.16.39-server.txt)
[crash-2024-03-09_20.03.58-server.txt](https://github.com/AllTheMods/ATM-9/files/14548682/crash-2024-03-09_20.03.58-server.txt)
[crash-2024-03-09_20.00.38-server.txt](https://github.com/AllTheMods/ATM-9/files/14548683/crash-2024-03-09_20.00.38-server.txt)
[crash-2024-03-09_19.55.52-server.txt](https://github.com/AllTheMods/ATM-9/files/14548684/crash-2024-03-09_19.55.52-server.txt)
[crash-2024-03-09_19.39.02-server.txt](https://github.com/AllTheMods/ATM-9/files/14548685/crash-2024-03-09_19.39.02-server.txt)
[crash-2024-03-09_19.30.23-server.txt](https://github.com/AllTheMods/ATM-9/files/14548686/crash-2024-03-09_19.30.23-server.txt)
Can provide more info on request

**Comment by djnifos** [comment]
try setting max-tick-time to -1 in server.properties.  That may let your server get past the startup
