### ISSUE TITLE
Issues with ATM9 

### ISSUE THREAD

**Issue by trykio1** [AllTheMods/ATM-9#1477]
hello! I downloaded the atm9 modpack and I added a couple more mods for extra fun, but for some reason, it isnt working. Can anyone help please?
[latest.log](https://github.com/AllTheMods/ATM-7/files/14549963/latest.log)

**Comment by Mitchell5200** [comment]
as for this crash, "a couple more mods", an extra 200, plus fabric mods and connector, not something i'd suggest doing, but looking at the log, cause seems to be related to `aoa3` whatever that mod does.
