### ISSUE TITLE
[0.2.51] Memory leak

### ISSUE THREAD

**Issue by Captn138** [AllTheMods/ATM-9#1482]
Hello there !

I am reporting an issue that I have faced playing the modpack.
The amount of memory used by the game keeps getting bigger and bigger until eventually I run out of memory and my computer crashes.

Here are the specs of my setup :
JAVA : 17.0.10 from OpenJDK
MODPACK VERSION : 0.2.51
LAUNCHER : GDLauncher
MEMORY ASSIGNED : 16GB
OS : Arch Linux

I haven't tried to launch the game from another launcher, bu I highly doubt this is in cause.
I play on a server with a friend on Windows, and he doesn't seem to have any memory problem.

I don't know if I can do anything to check which mod is causing the leak, but I'll be happy to do it if anyone knows how.

I'll be trying AdoptOpenJDK to see if it has anything to do with the Java package and I'll keep this post updated.

**Comment by djnifos** [comment]
I wouldn't assign more than 12 for this pack.  Definitely also make sure you leave some for linux to use.    What GPU and gpu driver are you using?

**Comment by Captn138** [comment]
I'm actually rocking a 32GB setup so Likux has no issue running with the 16GB remaining.
I have a RX 6750XT with the Mesa driver

**Comment by ReKon64** [comment]
Still a thing. Any news?

**Comment by Captn138** [comment]
Hello.
I've been inspecting and trying to swap out things to find out what was responsible. In the end it's "the modpack" (not sure what in the modpack exactly).
I've tried updating it but on the server on which I play, every update possible broke everything.
Eventually I decided to stick to that version, even thought I have to restart the game every 4-6 hours.
I guess you'll close this because I don't think it is relevant anymore.

**Comment by ashzure-github** [comment]
Manjaro also has memory issues with atm9. my machine has 30 gigs, i allocate 12. Over time, it just keeps piling on memory beyond that allocation.

**Comment by Jonnhis** [comment]
There is a memory leak in Oculus when you change dimensions: https://github.com/Asek3/Oculus/issues/631
If you're not using shaders you can safely disable Oculus and prevent some of the memory leakage

**Comment by Captn138** [comment]
> There is a memory leak in Oculus when you change dimensions: [Asek3/Oculus#631](https://github.com/Asek3/Oculus/issues/631) If you're not using shaders you can safely disable Oculus and prevent some of the memory leakage

Ah thank you.
Even thought I have finished the pack in the mean time, it might help me as I plan to do the to the sky version, I'll check for this problem
