### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by RaxtL** [AllTheMods/ATM-9#1486]
I have tried installing ReplyMod so I can record speed builds, like Sips and other youtubers but it just crashes the game, any ideas?

**Comment by Mitchell5200** [comment]
Can’t help without logs, best guess, incompatible forge/mc versions, or some incompatibilities between other mods

**Comment by Mitchell5200** [comment]
Looking at the "Replay mod" on curseforge, it only has a fabric 1.20 release, not  forge, [This Reddit post](https://www.reddit.com/r/ModdedMinecraft/comments/16lcgbo/replay_mod_fabric_alternative_for_forge_1201/) details how you can use [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector) to use the fabric version on forge.

**Comment by RaxtL** [comment]
OMG OMG OMG!!!   it works thank you very very very very much you are more awesome than an awesome possum.
