### ISSUE TITLE
loses the key bindings

### ISSUE THREAD

**Issue by EyeGazeGirl** [AllTheMods/ATM-9#149]
Every time Minecraft starts, it loses the key bindings. I play Minecraft with my eyes using this mod: https://github.com/SpecialEffect/EyeMineMods 

I have to change my keys to make sure it works. Don't think this mod is the issue. It is very frustrating to change the keys every time.

**Comment by TheBedrockMaster** [comment]
Is this still an issue?

**Comment by EyeGazeGirl** [comment]
Yes but we have worked it out. It is the EyeMine mod not the mod pack

**Comment by TheBedrockMaster** [comment]
So this can be closed?

**Comment by EyeGazeGirl** [comment]
Yes

**Comment by TheBedrockMaster** [comment]
Can you close it then?
