### ISSUE TITLE
I need help please

### ISSUE THREAD

**Issue by trykio1** [AllTheMods/ATM-9#1494]
### Possible Fixes

Yes

### Modpack Version

1.20.1

### What happened?

It is not ATM9, but I need help with it, so please tell me what I should do.
[latest.log](https://github.com/AllTheMods/ATM-9/files/14612191/latest.log)

### Crash Log

[latest.log](https://github.com/AllTheMods/ATM-9/files/14612191/latest.log)

**Comment by Mitchell5200** [comment]
In this case, it looks like quark's Lib Zeta is outdated, update it, if that does not solve it, start removing and updating things until it works.
