### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Musteer** [AllTheMods/ATM-9#1495]
### Possible Fixes

Yes

### Modpack Version

0.2.51

### What happened?

Every time I try to create a new world, my game crashes.

### Crash Log

https://gist.github.com/Musteer/948038dd0fb4fa80769194345a601381

**Comment by djnifos** [comment]
Allocate at least 8gb in your launcher for the pack.  Make sure you have 8gb free on your system to give it.

**Comment by Musteer** [comment]
how do i do this?

**Comment by djnifos** [comment]
Depends on your launcher, but they all will have a way to do it.  In curse, you can do it per pack or globally for all packs.  Globally is via the gear icon in the bottom left, then inside the minecraft section.  Just remember to leave yourself some ram for your OS to run.

**Comment by djnifos** [comment]
Reopen this or visit us in discord if you can't manage to fix it.
