### ISSUE TITLE
ATM9 Loading [Crash]: 

### ISSUE THREAD

**Issue by WB1130** [AllTheMods/ATM-9#1496]
### Possible Fixes

Yes

### Modpack Version

ATM9-0.2.52

### What happened?

Updated to the newest pack and now I get this crash.  I don't have anything extra or changed anything. 

### Crash Log

https://gist.github.com/WB1130/7fbb552acb38ff2b2a6c520581f16c79

### Latest.Log

https://gist.github.com/WB1130/e60c1d11ae4aeb18f4501c43c218891f

**Comment by Mitchell5200** [comment]
looks like Steam and Rails failed to load, logs say a corrupted config, locate and delete the mod's configs

**Comment by WB1130** [comment]
I can't find the config file for this mod. The mod is called Steam Rails but I cannot find a config file named that

**Comment by Mitchell5200** [comment]
ah, that mod calls it's configs `railways-client`, and `railways-common`

**Comment by WB1130** [comment]
I found it but deleting it created more issues. I tried deleting the mod but that created more issues. I don't know why all the sudden this is happening.

**Comment by WB1130** [comment]
For anyone having this same issue, I ended up deleting the entire pack and starting over. 
I did copy my saves folder and backup folder over so everything is good except all my settings/keybinds are messed up.
