### ISSUE TITLE
[Crash]: Worldgen crash

### ISSUE THREAD

**Issue by alessiorapisarda** [AllTheMods/ATM-9#1497]
### Possible Fixes

Yes

### Modpack Version

0.2.52

### What happened?

World generation (and the game, of course) crashes, it seems related to ChoiceTheorem's Overhauled Villages

java.lang.RuntimeException: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'rats:garbage_pile' at position 0: <--[HERE]

### Crash Log

https://gist.github.com/alessiorapisarda/cd979f95b977d0f63b9afc6732d260b9

**Comment by Mitchell5200** [comment]
Related to https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/issues/91

**Comment by ChoiceTheorem** [comment]
Fixed from my end! Update to CTOV 3.4.3 will solve this issue.
