### ISSUE TITLE
[Bug]: AE Search

### ISSUE THREAD

**Issue by DarkGeoSword** [AllTheMods/ATM-9#1498]
### Possible Fixes

Yes

### Modpack Version

0.2.52

### What happened?

Sync with JEI does not work anymore. Refined Storage works with JEI, but AE2 does not anymore.

### latest.log

https://gist.github.com/DarkGeoSword/bdc93478b9d55c75cf326380d24bc599

**Comment by mentimjojo** [comment]
After testing it seems the newly added mod "ae2insertexportcard-1.20.1-1.0.3" broke this feature. Removing this mod fixes the problem.

**Comment by Mitchell5200** [comment]
https://github.com/starforcraft/AE2-Insert-Export-Card/issues/1

**Comment by mentimjojo** [comment]
This issue should be fixed in the latest AE2 Insert/Export card update. 

[Latest update AE2 Insert/Export Card](https://legacy.curseforge.com/minecraft/mc-mods/ae2-insert-export-card/files/5189115)

**Comment by Mitchell5200** [comment]
Fixed in 0.2.53
