### ISSUE TITLE
server pack trojan?

### ISSUE THREAD

**Issue by AdinQu** [AllTheMods/ATM-9#15]

**Comment by AdinQu** [comment]
![unknown_2023 06 19-18 15](https://github.com/AllTheMods/ATM-9/assets/93778364/baf3f258-ab9a-47ee-b441-d267137072c7)

**Comment by AdinQu** [comment]
![Capture](https://github.com/AllTheMods/ATM-9/assets/93778364/a937629f-9cfd-4906-9255-d069af296551)

**Comment by whatthedrunk** [comment]
false positive thanks
