### ISSUE TITLE
0.44 Recipe Conflict: Sleeping Bag and Wool Slabs

### ISSUE THREAD

**Issue by sleepp-dev** [AllTheMods/ATM-9#150]
Unable to craft a Sleeping Bag as it shares a recipe with Wool Slabs and I'm not seeing polymorph or any other recipe conflict mod unless I'm just overlooking it.

**Comment by Neywiny** [comment]
I just ran into this. To solve, click the two arrows above the crafting output. That allows you to select the recipe.
