### ISSUE TITLE
[Bug]: duplication bee upgrade

### ISSUE THREAD

**Issue by lylian007** [AllTheMods/ATM-9#1501]
### Possible Fixes

Yes

### Modpack Version

0.2.52

### What happened?

when I shift + click on an advanced bee hive + extension box, with stack upgrades in my hand, those are all transferred to the hive but only 1 upgrade is consumed in my hand, so I can recover the stacker upgrades that aren't a display bug (so there's duplication).

**Comment by JaisDK** [comment]
it's fixed, just need to update the mod
