### ISSUE TITLE
[Bug]: Immersive engineering gun turrets have no GUI

### ISSUE THREAD

**Issue by AndritaLucianGabriel** [AllTheMods/ATM-9#1502]
### Possible Fixes

Yes

### Modpack Version

0.2.51

### What happened?

Gun turrets from IE have no input box (it's not clickable), also if you press in the area that's supposed to store the names, you can hear a button being pressed)
![image](https://github.com/AllTheMods/ATM-9/assets/63100651/f05568ab-d1c9-4830-8a2e-fd623136c018)

**Comment by mentimjojo** [comment]
This is not an issue with ATM9, but rather an issue on IE side. You should report on their git repo 👍
