### ISSUE TITLE
[Bug]: Inventory Sorting needs to be disabled on RS Crafter Manager window

### ISSUE THREAD

**Issue by VorpalLemur** [AllTheMods/ATM-9#1503]
### Possible Fixes

Yes

### Modpack Version

0.2.51

### What happened?

Accidentally hitting the middle mouse button while the Refined Storage crafter manager is open will ruin your day... taking all patterns across all the crafters in your whole network and reassigning them where they certainly won't work.   When you have hundreds of patterns defined, this can be a nightmare to sort out.

I currently have Quark Inventory's 'Sort Player Inventory' and 'Sort Target Inventory' functions unbound.  I have middle click bound to Sophisticated Backpacks 'sort backpack' and Sophisticated Storage 'sort  storage'  as well as minecraft's 'pick block' and JEI's 'cheat 1 stack' functions.   That's the complete list of what I have middle mouse click bound to.   Looking at this configuration, I have no idea why middle mouse button tries to sort the crafter manager screen, but I'm able to reproduce it at will.

**Comment by Kevin-Marsh** [comment]
Sorting in atm9 is performed with Inventory Profiles Next. It doesn't record the keybinds in the keybind menu but rather has its own menu which can be opened by pressing the 'rc' keys.
