### ISSUE TITLE
[Bug]: The tag forge:cheeses is empty so you can't craft anything that requires cheese

### ISSUE THREAD

**Issue by RippAlex** [AllTheMods/ATM-9#1504]
### Possible Fixes

Yes

### Modpack Version

0.2.52

### What happened?

The tag forge:cheeses is empty so you can't craft anything that requires cheese[https://imgur.com/a/aDsUXT4](url)

**Comment by isavegas** [comment]
It looks like removing or commenting out this line fixes the issue, at least on my end: [kubejs/server_scripts/tags.js#L85](https://github.com/AllTheMods/ATM-9/blob/875132eae6e021375e4563b1dfc1109a7f39b854/kubejs/server_scripts/tags.js#L85).
