### ISSUE TITLE
[Bug]: Sophisticated Storage Controller randomly refuses to link to chests and barrels

### ISSUE THREAD

**Issue by FoxtrotUniformRomeoYankee** [AllTheMods/ATM-9#1506]
### Possible Fixes

Yes

### Modpack Version

0.2.53/0.2.52

### What happened?

Linking storages from Sophisticated Storage mod, such as chests and barrels to the Storage Controller from that mod doesn't seem to be working properly since the version 0.2.52. 
When placing a bunch of chests in a world and trying to link them to a Storage Controller Some chests are refusing to link. Unlinking those chests that were able to link makes it possible to link chests that were unable to link previously. 
[Video demonstrating the issue](https://www.youtube.com/watch?v=p4nsAWlCSpo)
Aside from that, those chests that were linked before update remained linked, but didn't function correctly. Their inventory is visible through AE2 terminal, but some items don't end up in the chests they should be routed to according to installed filter (which was working perfectly prior to 0.2.52). 

Things I've tried:
- Reinstalling Instance (including uninstalling completely and installing)
- Updating java

Rolling back to 0.2.51 fixes the issue

**Comment by James103** [comment]
How many chests and barrels do you have linked to the controller when attempting to link another chest/barrel fails even if within range?

**Comment by FoxtrotUniformRomeoYankee** [comment]
Can't really say. It seems random. It's not like you can't link more than a certain number. Some chests can still be linked after some of them have already refused to. You can see it on the video.
Either way. I was able to also repro it with a clean instance with just Sophisticated Storage installed, so I've opened an issue in Sophisticated Storage repo as well. Mod dev have marked it as a bug, so i think he's on it.

**Comment by James103** [comment]
See also https://github.com/P3pp3rF1y/SophisticatedStorage/issues/385.

**Comment by FoxtrotUniformRomeoYankee** [comment]
fixed by dev
