### ISSUE TITLE
[Quests issues]: Ars nouveau

### ISSUE THREAD

**Issue by jelliedpanda** [AllTheMods/ATM-9#1507]
### Modpack Version

0.2.51

### Describe the issue

Ars nouveau quest line doesnt accept the archwood logs. i have tried collecting all of the logs, stripped and full logs of every tree but the quest does not complete even though it says its at 100% completion. i of course have collected 2 planks as well. it is fully complete but i cant claim the reward.

**Comment by TheBedrockMaster** [comment]
Is this still an issue, if so screenshot?

**Comment by ToshibaEC0Microwave** [comment]
This works with current version and may just be either a bug or a problem with not completing previous quests. Will be closed
