### ISSUE TITLE
[Bug]: Chunk Destroyer enchanted with Boon of the Earth

### ISSUE THREAD

**Issue by Kami-no-Shi** [AllTheMods/ATM-9#1509]
### Possible Fixes

Yes

### Modpack Version

2.53

### What happened?

So doing some testing with the Chunk destroyer from the Quarry plus mod enchanted with Efficiency, Unbreaking, Fortune and Boon of the Earth in the mining dimension. It seems to not pick up the multiplied items from boon after the initial boon proc resulting in massive amounts of ores on bedrock floor. The chunk destroyer was enchanted with max level enchants on it from the apotheosis mod with creative mode means.

**Comment by James103** [comment]
Have you tried reporting this to the Quarry Plus mod developers (https://github.com/Kotori316/QuarryPlus/issues)?
