### ISSUE TITLE
[0.0.44] [EnderIO] using the Primitive Alloy smelter crashes the game/server

### ISSUE THREAD

**Issue by ArcadeArchie** [AllTheMods/ATM-9#151]
Currently trying to use the Primitive Alloy smelter crashes the game/server
and even after restarting it still crashes, we should probably rollback to a previous version of EnderIO until upstream is fixed

Modpack version: 0.0.44
EnderIO version: 6.0.6-alpha

i've already made an issue upstream in EnderIO's repo
https://github.com/Team-EnderIO/EnderIO/issues/342

**Comment by Alucard1313** [comment]
Known issue, a mod update will be released soon to fix it.

**Comment by ArcadeArchie** [comment]
> Known issue, a mod update will be released soon to fix it.

yep they've just released v6.0.7-alpha

**Comment by ArcadeArchie** [comment]
fixed in 0.0.45
