### ISSUE TITLE
[Suggestion] Blacklist AE2 facades from JEI

### ISSUE THREAD

**Issue by Peri-42** [AllTheMods/ATM-9#1511]
AE2 facades take up a LUDICROUS amount of space and clog up every JEI search because a separate recipe is generated for each and every block in the game. I end up blacklisting them from JEI myself, but that gets reset every time the modpack updates.

I don't know if it would be possible to add some sort of dummy recipe to show up just to teach people how to make the facades or if it would have to be documented elsewhere, but the way they show up in JEI now is frankly kinda ridiculous, especially for something you'll likely only need to learn one time and can extrapolate to any other block.

![image](https://github.com/AllTheMods/ATM-9/assets/15340096/dc0351f1-92f0-4244-bae3-2552dede2f3f)

**Comment by mentimjojo** [comment]
Which launcher are you using that resets configs on each update? Do your keybinds reset every time as well?

On the topic, personally i like to have the facade recipes in JEI. Perhaps a button to turn them on/off would be nice, but i dont think thats something that belongs here, maybe a good idea to suggest the idea to the JEI devteam?

**Comment by Peri-42** [comment]
oh, i didn't even consider that it could be a launcher issue, i use Prism Launcher. keybinds don't get reset, but a good chunk of my configs get overwritten, i always assumed that was just part of the update lol.

**Comment by Lilu-VA** [comment]
I second this, as it seems that JEI preloading is the biggest culprit when it comes to loading times. Blacklisting these or at least having an option to do so would likely improve it immensely.

**Comment by Kevin-Marsh** [comment]
This was implemented in the latest version.
