### ISSUE TITLE
[Bug]: Cable Tiers importers not accepting stack upgrades

### ISSUE THREAD

**Issue by lolo528491** [AllTheMods/ATM-9#1516]
### Possible Fixes

Yes

### Modpack Version

ATM 9-0.2.51

### What happened?

As the title says, the importers for Refined Storage won't accept stack upgrades, only speed upgrades. Only the basic Tier importer from the Refined Storage mod itself does accept stack upgrades. Speed upgrades work on all importers

**Comment by Kevin-Marsh** [comment]
Cable tiers processes stacks by default and as such can't accept stack upgrades.
