### ISSUE TITLE
Compacting drawer - glowstone issues

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-9#152]
GregTech is causing an issue on a compacting drawer. If you put glowstone on it, you get glowstone dust, glowstone block and tiny pile of glowstone dust (gregtech).

But at some point, without touching the drawer, everything gets converted to tiny pile of glowstone dust and there are no other items in the drawer.

Also, if you put tiny pile of glowstone dust in the drawer, you only get that item, like if it was not compacting anything. Compacting only works if you put glowstone block or glowstone dust inside of it.

**Comment by aAndrew3030** [comment]
Use the simple compacting drawer? (two slot version instead of three)

**Comment by M4RC0Sx** [comment]
Thank you! Didn't know that block existed!
