### ISSUE TITLE
[Crash]: 0.2.53 - Crashing on startup, exit code -805306369

### ISSUE THREAD

**Issue by freeman7946** [AllTheMods/ATM-9#1521]
### Possible Fixes

Yes

### Modpack Version

0.2.53

### What happened?

I was playing a private server with my friends yesterday (I'm not host, server is working perfectly for all other players) when the game crashed and has not let me back in since. I can usually get to the main menu (sometimes crashes even before then), but can't load a new or existing world, nor can I join my server. The first time it crashed, I was looking at my graphics settings and I accidentally opened the resource packs tab and when I clicked the back button (without changing anything), it crashed. Now it crashes when I try to load into any world/server. It finishes encrypting, then crashes when it says 'joining world'.

I had 8gb of ram allocated at the time, tried up to 13gb. The highest I've seen it go is around 11gb, I have 16 total. I'm running the most recent version of Minecraft (optifine 1.20.4). I have my Nvidia drivers completely up to date. There was an update released for my drivers two days ago, but was able to launch and play until last night. 

Vanilla minecraft still works without issue. I launch ATM9 through Curseforge. I don't have any shaders. The only resource packs I have are from ATM9.

Any help would be appreciated!

### Crash Log

https://gist.github.com/freeman7946/c593279ecbf133e3016df530a5e0b395

### Latest.Log

https://gist.github.com/freeman7946/86dccb96d55ecf2cd748858ec34718c2

**Comment by wolfieboy09** [comment]
Uninstall Optifine, and that should fix it.
Also, there's a GSON (JSON) error with wares mod, and that's the issue
