### ISSUE TITLE
Refined Storage system not working Cross Dimensionally

### ISSUE THREAD

**Issue by VocaFabulas** [AllTheMods/ATM-9#1523]
I've made the wireless transmitter NOT THE ADVANCED WIRELESS. I Have plenty of power to the system. I have a wireless crafting grid. I have the storage area chunk loaded. For some reason when I go to another dimension I can open the wireless crafting grid and see my storage system but I can in no way interact with it. I can't move things in or out or craft from it at all.

Showing that I do have the wireless setup done right.
![Screenshot 2024-03-22 114130](https://github.com/AllTheMods/ATM-9/assets/164540321/e64a27f0-d3f6-4537-9aac-ec872f4ac8ae)
Showing the inventory appearing in the other dimension though I cannot add, take, or craft from it.
![Screenshot 2024-03-22 114235](https://github.com/AllTheMods/ATM-9/assets/164540321/916dadd2-3950-45d4-9acb-7336542def9c)

**Comment by VocaFabulas** [comment]
It now works for some reason. I didn't even reset the game. I didn't adjust chunk loads either. I cannot currently replicate this bug.

**Comment by TheLastPaladin** [comment]
Since this is most likely a low-priority bug from either RS or RSInfinityBooster I highly recomment closing this issue here and moving it to the RSInfinityBooster Git

**Comment by Grant-K** [comment]
This might be related to https://github.com/Hexeption/RSInfinityBooster/issues/29
where the advanced wireless transmitter wont work with dimension card.
