### ISSUE TITLE
[Bug]: Iron Spells' apotheosis gems errored

### ISSUE THREAD

**Issue by Sylvaerin** [AllTheMods/ATM-9#1525]
### Possible Fixes

Yes

### Modpack Version

9-0.2.54

### What happened?

After updating the modpack, I noticed that my gems for iron spells were gone from my spellbook/armor, and my stockpiled gems were errored out.

**Comment by Kevin-Marsh** [comment]
This was caused by edits that irons spells made and should be fixed in the current version.
