### ISSUE TITLE
[Bug]: Iesnium Comb doesn't have Centrifuge recipes

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [AllTheMods/ATM-9#1528]
### Possible Fixes

Yes

### Modpack Version

0.2.54

### What happened?

Iesnium Comb can only be processed in Mixer from Create. This shouldn't happen, as all combs must be able to be processed in Productive Bees's centrifuges.

Iesnium Comb Blocks cannot be processed at all.

**Comment by Kevin-Marsh** [comment]
This shows up for me just fine on 0.2.54. This could be a JEI bug. Try adding the comb to the centrifuge anyway to test if it works.

**Comment by pPkMnh4to8994h** [comment]
Did full reinstall of the pack, now it works. Another reminder to me and everyone else - **do not update on existing instance**, even if done through launcher (Prism Launcher in my case).
