### ISSUE TITLE
Flux points don't connect to ender io Energy conduits

### ISSUE THREAD

**Issue by Pelkenator** [AllTheMods/ATM-9#153]
I know I know you are very busy with other things however im letting you guys know now so that when somebody gets around to it there will be a fix for Atm 21

**Comment by taj1994** [comment]
I just tested this in an instance with just EnderIO and Flux Networks, and it also doesn't seem to work there, so it's not an All the Mods issue. Have you reported it to EnderIO and/or Flux Networks yet?

**Comment by taj1994** [comment]
Reported to [Flux Networks](https://github.com/SonarSonic/Flux-Networks/issues/518) and [Ender IO](https://github.com/Team-EnderIO/EnderIO/issues/360)
