### ISSUE TITLE
[Bug]: Using the external storage from Refined Storage on a chest with stack upgrades allows for crazy duping.

### ISSUE THREAD

**Issue by NeoTheJackal** [AllTheMods/ATM-9#1530]
### Possible Fixes

Yes

### Modpack Version

0.2.53

### What happened?

When connecting a chest with stack upgrades to a Refined Storage grid and then using said grid to craft high quantities of an item makes it craft way more than it's supposed to. I was packing sand and from 2k sand ended up with around 30 8x compressed blocks.

**Comment by Kevin-Marsh** [comment]
Yeah. We are trying to find a fix. This has been reported to Refined storage in January but we aren't sure how to proceed from our side. Thanks for informing us. We will keep monitoring it.
