### ISSUE TITLE
[Crash]: Chunks not loading then crash

### ISSUE THREAD

**Issue by DenisKoether** [AllTheMods/ATM-9#1533]
### Possible Fixes

Yes

### Modpack Version

9-0.2.53

### What happened?

Every time one of my friends wants to explore the world with the jetpack, he gets a few chunks far and then he has to wait 3-10 minutes until the chunks are loaded. If he is not careful and flies into the unloaded chunk, the server crashes immediately.

The server has a Ryzen 7 3700X and enough RAM, but that can't be the problem as other Minecraft servers also run on it without any problems.

At the beginning of ATM9 I also created a server that ran without any problems.

### Crash Log

https://gist.github.com/DenisKoether/2600dd48ae48f38bd6258d71618e8516

**Comment by DenisKoether** [comment]
I set "Max tick time=-1" now the server no longer crashes but you are kicked out of the server until the chunks are loaded...

**Comment by FreshDumbldore** [comment]
I see you have the same problem as i have... 
[Here](https://github.com/AllTheMods/ATM-9/issues/1769)
It is annoying waitung for the world to load every like 5-10 minutes due to this bug.

**Comment by DenisKoether** [comment]
I use AMP and the fix was to disable "Use Synchronous IO".
