### ISSUE TITLE
[Bug]: Eternal water block from Evil craft turns to ice when in an oxygenated space in an Ad Astra space station 

### ISSUE THREAD

**Issue by Pelkenator** [AllTheMods/ATM-9#1534]
### Possible Fixes

Yes

### Modpack Version

9-0.2.54

### What happened?

Eternal water block turns to ice I have tried placing torches next to the block to prevent this but it fails to help.

**Comment by Kevin-Marsh** [comment]
Bug was also reported to the evilcraft team. Closing here.
