### ISSUE TITLE
0.0.44 Evil Craft weather bottles crash.

### ISSUE THREAD

**Issue by PBnJs87** [AllTheMods/ATM-9#154]
When messing with weather bottles or the weather beacons, game will crash some require a back up restore to get back into your world.

[crash-2023-07-26_08.35.09-server.txt](https://github.com/AllTheMods/ATM-9/files/12168494/crash-2023-07-26_08.35.09-server.txt)
[crash-2023-07-26_11.50.32-server.txt](https://github.com/AllTheMods/ATM-9/files/12168495/crash-2023-07-26_11.50.32-server.txt)
[crash-2023-07-26_11.52.57-server.txt](https://github.com/AllTheMods/ATM-9/files/12168496/crash-2023-07-26_11.52.57-server.txt)

**Comment by mendiettak** [comment]
can confirm; server running 0.0.42

**Comment by darklotus781** [comment]
Confirmed on 0.0.45, not sure this is an ATM issue though, should report to EvilCraft instead.
