### ISSUE TITLE
[Bug]: Search sync feature broke again between AE2 and JEI.

### ISSUE THREAD

**Issue by mentimjojo** [AllTheMods/ATM-9#1554]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

As the title describes the search sync feature broke again between AE2 and JEI. Once again the issue seems to be with the addon mod: ae2insertexportcard-1.20.1-1.1.2.

Rolling this mod back to version 1.1.1 resolves the issue.

Also reported to the mod dev.
https://github.com/starforcraft/AE2-Insert-Export-Card/issues/3

### Developer reports

https://github.com/starforcraft/AE2-Insert-Export-Card/issues/3

**Comment by Kevin-Marsh** [comment]
Thank you for the note. We have talked to the dev and there is now a new version of the mod which will be in the next version that fixes this.
