### ISSUE TITLE
[Bug]: Server download contains a broken version of forge

### ISSUE THREAD

**Issue by XxTRAINEExX** [AllTheMods/ATM-9#1555]
### Possible Fixes

Yes

### Modpack Version

Server-Files-0.1.0

### What happened?

Server-Files-0.1.0 contains a forge version that is outdated and does not launch due to a change in mojangs domain names.  Downloaded a newer version of forge corrects this issue.  Specifically I pulled down forge 47.2.21 and the install works properly.

**Comment by Kevin-Marsh** [comment]
That server version is severely outdated and there was a bg regarding the domain change a while back. This won't be modified.

**Comment by XxTRAINEExX** [comment]
@Kevin-Marsh first time posting so apologize if this is a dumb question.  Does that mean we can no longer run ATM9 servers because the server file will not be updated?  I was trying to start a new ATM9 server and that is the only downloadable file I could find on the website.

**Comment by Kevin-Marsh** [comment]
It is all good. When you open curseforge you can click on the version and then click on additional files to get the server files. I have provided a link to 0.2.54. There will be an update to 0.2.55 but it is stuck waiting to be reviewed so it will be a few days. [Here is the link.](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5200590/additional-files)

**Comment by XxTRAINEExX** [comment]
ooof.. I can't believe I missed that.  Sorry for the bug report.  And thank you!
