### ISSUE TITLE
[Crash]: Update 0.2.55 causing crash on "Joining World..."

### ISSUE THREAD

**Issue by BrainReader** [AllTheMods/ATM-9#1557]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

Any existing or new world crashes at the end of "Joining World..." phase. This does not happen on any of the older updates. The crash report gets created in the base folder of the modpack, and not in the "crash-reports" folder.

I am running the modpack from ATLauncher.

### Crash Log

https://gist.github.com/BrainReader/deb6b44b7cdf4f82846acd7bae73006f

### Latest.Log

https://gist.github.com/BrainReader/28cb3fa4f9d17fa409c519f388d6655c

**Comment by Mitchell5200** [comment]
Known, being fixed in GT, awaiting on a CF release their side before we can do a pack update, maybe 24-48 hours

**Comment by Sudoasroot** [comment]
according to changelog, fixed in GregTechCEu 1.20.1-1.1.4.a
