### ISSUE TITLE
[Bug]: Wrong recipes

### ISSUE THREAD

**Issue by LorenzoW112** [AllTheMods/ATM-9#1559]
### Possible Fixes

Yes

### Modpack Version

0.2.48

### What happened?

I tried to craft Sweeping Edge III books but i discovered that they have the same crafting recipe as Impaling III 
![Screenshot 2024-03-30 133234](https://github.com/AllTheMods/ATM-9/assets/58951406/fa58543a-790e-4cbc-b035-68b4a23be8ff)
![Screenshot 2024-03-30 133257](https://github.com/AllTheMods/ATM-9/assets/58951406/e4e7d822-9f91-4988-b4a0-432ff5208101)

**Comment by Kevin-Marsh** [comment]
This was fixed in the latest enderio which is in pack version 0.2.55.
