### ISSUE TITLE
EnderIO soul binder issue

### ISSUE THREAD

**Issue by Bradderz65** [AllTheMods/ATM-9#156]
I cannot change the type of spawner using the soul binder, no matter what spawner of vial i use, also cant pipe any form of xp into it using the mods own pipes or any other.

**Comment by aAndrew3030** [comment]
I was able to pipe xp in using the EnderIO tank and a fluid pipe from the Pipez mod.

**Comment by beamer91** [comment]
I had to use the Experience rod from Ender IO and shift right click the soul binder. It is very slow though.

**Comment by tyler489** [comment]
@Bradderz65 @beamer91 
Im assuming you guys are on a server 

@aAndrew3030 
you are on singleplayer im guessing?

**Comment by beamer91** [comment]
yes I am

**Comment by Rover656** [comment]
These issues should have been resolved in Ender IO v6.0.8-alpha and up. If not, please @ me with further details. Thanks.
