### ISSUE TITLE
[Bug]: Version 0.2.55 Missing server version

### ISSUE THREAD

**Issue by SamuelColacchia** [AllTheMods/ATM-9#1561]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

Looks like the release of 0.2.55 on curse forge did not include the server files.

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5220241/additional-files

**Comment by FrankenBobbo** [comment]
Awaiting CurseForge review, as mentioned [here](https://github.com/AllTheMods/ATM-9/issues/1555#issuecomment-2027846237)
Also this line of text under every update.
![image](https://github.com/AllTheMods/ATM-9/assets/64887834/8a1c694e-72b4-40b0-979f-e55a99818ebb)
