### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AsianMcRasin** [AllTheMods/ATM-9#1562]
### Possible Fixes

Yes

### Modpack Version

AlltheMods9

### What happened?

Me and my friend are playing on an atm9 server and we cant put a sharpness 9 book on a sword through a anvil.
![Screenshot 2024-03-30 212254](https://github.com/AllTheMods/ATM-9/assets/163957418/b7e78d3b-9e92-4e57-80f8-0527a1da495a)
![Screenshot 2024-03-30 212353](https://github.com/AllTheMods/ATM-9/assets/163957418/f178fb5a-97b3-40de-9f31-10715c824a81)

**Comment by AsianMcRasin** [comment]
What one of the apotheosis mod dev said
"issue tends to be caused by other mods that fiddle with the anvil. I can fix it if the offending mod can be sourced, but I will not lint an entire modpack to do so.

Please report this issue to the modpack and have them get back to me with more details."

**Comment by Mitchell5200** [comment]
> ### Modpack Version
> AlltheMods9

The Modpack version needs to be the exact pack version, not "atm9"

**Comment by AsianMcRasin** [comment]
Version 0.2.51

**Comment by Kevin-Marsh** [comment]
Does the server have any additional mods or things like the ancient tomes enabled?

**Comment by AsianMcRasin** [comment]
only other mod i added was world edit and I dont know where to look if ancient tomes are enabled

**Comment by Kevin-Marsh** [comment]
Open up jei, type ancient and see if they show up.

**Comment by AsianMcRasin** [comment]
![Screenshot 2024-03-30 212353](https://github.com/AllTheMods/ATM-9/assets/163957418/211cb13e-ce42-4b78-b894-ec31422beb8c)
This is what pops up

**Comment by AsianMcRasin** [comment]
![Screenshot 2024-03-30 233222](https://github.com/AllTheMods/ATM-9/assets/163957418/9e4e3177-0371-40b8-9204-a6f04d118c04)

**Comment by AsianMcRasin** [comment]
this is what pops up

**Comment by Kevin-Marsh** [comment]
I am not sure what to suggest. I can't replicate this on my end with the version or on the latest. I would suggest that the server operator updates to 0.2.55 and see if that fixes it as a side effect.

**Comment by AsianMcRasin** [comment]
alright thank you anyways
