### ISSUE TITLE
[Bug]: placing ancient vine causes to spawn ancient vine with ancient soul berry

### ISSUE THREAD

**Issue by MihailBezukladnikovISiP201** [AllTheMods/ATM-9#1563]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

So i make my way to the Other dimension without food source, and decide to set up small farm with vines for berries, but with placing down on ancient stone makes them already grown up to harvest. It could be actually easy farm for food (this thing is important for manually gathering ores in mining dimension), works on nether and overworld as well.

**Comment by Kevin-Marsh** [comment]
This is a minor bug. You can already infinitely duplicate the berries with bonemeal or an allthemodium hoe with natures blessing far more effectively than placing and breaking.
