### ISSUE TITLE
[Bug]: Duplication/Infinite Resources Bug

### ISSUE THREAD

**Issue by DarkHope1988** [AllTheMods/ATM-9#1564]
### Possible Fixes

No

### Modpack Version

0.2.53

### What happened?

After some testing and troubleshooting, I couldn't figure it out on my own, so I'm hoping you can help me out.

Here's the deal: There seems to be a bug that lets players duplicate items or have infinite resources. No matter what I tried—logging out and back in, restarting the server, or even starting fresh with a new instance—the problem stuck around.

After some digging, I found that the bug kicks in when I have the Universal Terminal from ae2wtlib mod along with the Wireless Pattern Encoding and Wireless Crafting Grid features in my inventory. When I try to use items like Mystical Fertilizer on seeds with the Universal Terminal in my inventory, the amount in my hand magically jumps to 32, even if I had less to start with. And weirdly enough, I can keep using the item indefinitely. I also suspect there might be a similar issue with functional Storage Drawers, where stacks get halved when I take items out, but I haven't tested this thoroughly yet.

I'm pretty sure it has something to do with the Universal Terminal, but I'm stumped as to how these features are interacting to cause this. Anyway, I thought it was important to bring this to your attention so we can keep improving the modpack.

> wanted to provide you with some additional information regarding the infinite resources bug I previously reported. Upon further testing, I discovered that the issue only occurs when the Universal Terminal from ae2wtlib mod is bound to the ME system via the wireless antenna, and only when the antenna is within range. If the antenna is out of range, everything behaves normally.

I hope this information helps in diagnosing and resolving the issue.

**Comment by Kevin-Marsh** [comment]
Could you please check your me system after using the essence. The Wireless universal terminal has a restock feature that can be enabled by hitting the restock key set in the applied energistics keybind category. This pulls items out of your me system and keeps the items stocked in your inventory.

**Comment by DarkHope1988** [comment]
thx ... I seem to have stumbled upon the keybind for it... terrible ^^ sry

**Comment by Kevin-Marsh** [comment]
No problem. I am glad we got that sorted.
