### ISSUE TITLE
[Quests issues]: Typo on ATM mod for Vibranium Templates

### ISSUE THREAD

**Issue by samtarplee** [AllTheMods/ATM-9#1566]
### Modpack Version

0.2.54

### Describe the issue

Small typo on https://github.com/AllTheMods/ATM-9/blob/8fa82f5b1dbf3a4f60d05452ac36efd731107a8e/kubejs/assets/kubejs/lang/en_us.json#L330, should be `Suspicious` not `Suspecious`, was really bugging me

**Comment by Mitchell5200** [comment]
Fixed, thanks for the spot
