### ISSUE TITLE
[Bug]: 0.2.55 dedicated server no one can join

### ISSUE THREAD

**Issue by fkempf78** [AllTheMods/ATM-9#1567]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

After update of dedicated server, joining to server is no longer possible. -> either "Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 26 out of bounds for length 5" or timeout.
Restoring Server to 0.2.54 and also client, login possible with no issues. Again Update -> Same Problem
[latest.log](https://github.com/AllTheMods/ATM-9/files/14817494/latest.log)
[server.latest.log](https://github.com/AllTheMods/ATM-9/files/14817534/server.latest.log)

**Comment by Micaxs** [comment]
Wondering about this one as well.

**Comment by Kevin-Marsh** [comment]
Could you please update to 0.2.56 and see if this fixes your issue? There was apparently an issue with Gtceu that should be fixed.

**Comment by fkempf78** [comment]
Yes, that has fixed the problem, Thank You very much and thanks for the great mod!
