### ISSUE TITLE
[0.0.45] Missing Vanilla TNT Recipie 

### ISSUE THREAD

**Issue by Sudoasroot** [AllTheMods/ATM-9#157]
The Vanilla recipie of TNT is not craftable and not listed in JEI anymore

**Comment by Alucard1313** [comment]
Listed in Jei for me, but only can crafted via GregTech mod

**Comment by serenibyss** [comment]
GregTech removes the vanilla TNT recipe in favor of its own, and its not configurable (this is the only recipe treated this way iirc). So it would need to be added back somewhere else

**Comment by tekook** [comment]
just stumbled upon this. This needs to be added back again...
I guess this required kubejs to add back receipes.
Gregtech should be removed due to this imho.

**Comment by screret** [comment]
> this

There **is** a config option to add it back.
Nobody's toggled it on.

**Comment by tekook** [comment]
> > this
> 
> There **is** a config option to add it back.
> Nobody's toggled it on.

Do u have link on how to toggle this option? All I found was that is has **no** toggle...

**Comment by tekook** [comment]
for anyone wondering on how to bring back the vanilla tnt reciepe:
open gtceu.yaml on /config folder and set
removeVanillaTNTRecipe to false.
