### ISSUE TITLE
[Bug]: Essence of Knowldedge bucket missing

### ISSUE THREAD

**Issue by waggz81** [AllTheMods/ATM-9#1571]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

With the addition of the experience droplet -> essence of knowledge recipe from the centrifugal separator, this is giving essence of knowledge but there's no bucket recipe in order to place the fluid in RS exporters etc.

**Comment by Kevin-Marsh** [comment]
I would advise piping it directly into an experience crystal from the centrifuge. Cofh doesn't provide a bucket recipe and the essence is unified between the bottle ' o' enchanting and the droplet.

**Comment by waggz81** [comment]
That doesn't fix the very bug-like behavior of being able to pipe it in to storage system but not out and the fluid grid providing empty buckets when you click it while it deletes the fluid from storage. Honestly you are probably better off removing the recipe again or making it provide a different xp fluid that does work as intended.

**Comment by Kevin-Marsh** [comment]
I should make a stipulation that this doesn't fix Refined Storage's bugged handling of fluids. The fluid is fine. RS isn't.
