### ISSUE TITLE
[Bug]: AE2 Terminal/JEI Search synchronizasion broken

### ISSUE THREAD

**Issue by TheLastPaladin** [AllTheMods/ATM-9#1573]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

I've updated my server to 0.2.55 and right after joining I noticed that the AE2 Terminal search synchronization was disabled. This is very confusing to me as I have Search Sync enabled.
All terminals are affected, so default AE2 but also Wireless (Universal) Terminals.
This issue appears in any scenario, so switchting search mode JEI or AE2 doesn't help either.

**Comment by Kevin-Marsh** [comment]
Updating your server to 0.2.56 will fix this. There was a bug in Ae2 import export card.
