### ISSUE TITLE
[Bug]: Productive Bees upgrades duplication

### ISSUE THREAD

**Issue by MarioRogue** [AllTheMods/ATM-9#1574]
### Possible Fixes

No

### Modpack Version

0.2.53

### What happened?

I shift clicked the omega upgrade into the bee hive and it removed one from my inventory while in the hive it added the full stack into the slot which I could take back to my inventory and keep doing to get more of those.

![image](https://github.com/AllTheMods/ATM-9/assets/34819886/ce8d414f-3ec7-44f6-8cd9-135d5c79b180)

**Comment by Kevin-Marsh** [comment]
I can't replicate this in 0.2.56. Could you update your pack and tell me if the issue persists for you?

**Comment by SethaWetha** [comment]
> I can't replicate this in 0.2.56. Could you update your pack and tell me if the issue persists for you?

It seems it's mostly patched in 0.2.56 but the issue still persists. If you're quickly shift + right-clicking the end of a stack and your hand gets auto refilled by a different stack, sometimes a full stack of upgrades will end up in the bee hive.

**Comment by JaisDK** [comment]
> > I can't replicate this in 0.2.56. Could you update your pack and tell me if the issue persists for you?
> 
> It seems it's mostly patched in 0.2.56 but the issue still persists. If you're quickly shift + right-clicking the end of a stack and your hand gets auto refilled by a different stack, sometimes a full stack of upgrades will end up in the bee hive.

Can you give some more details on how you manage this? Which stacks of upgrades are already in the hive and which are you moving from the inventory (also stack size). A video of it would be idea.

**Comment by MarioRogue** [comment]
> I can't replicate this in 0.2.56. Could you update your pack and tell me if the issue persists for you?

Yeah seems like its fixed on the 0.2.56, I can't do it anymore
