### ISSUE TITLE
[Bug]: Supplementaries Mod not displaying items correctly

### ISSUE THREAD

**Issue by LargeSmile45** [AllTheMods/ATM-9#1575]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

I have several different mod items on display at my base using the Supplementaries Mod's Pedestals & Items Shelf. Before I updated to the lastest version (0.2.56). Everthing displayed on these pedestals showed the correct texture. Now everything that is displayed is either showing up as Dirt or Raw Salmon, as shown in the attached screenshots.

![Before Updating to Latest](https://github.com/AllTheMods/ATM-9/assets/75589590/190bfb3b-41b5-4e50-a755-e6c527760fe5)

Now aftering updating to the latest
![After-Updating](https://github.com/AllTheMods/ATM-9/assets/75589590/1fd4ef53-c0bd-424a-9aeb-698ded15f2f9)

This also seem to be effecting items displayed on Items Shelf and a couple of other placeable items from Supplementaries as well. 
![Supplimentaries-Displaying-Items-Mismatch](https://github.com/AllTheMods/ATM-9/assets/75589590/5e264677-c4a1-4922-8301-722fe9cb471a)

![Supplimentaries-Texture-bug](https://github.com/AllTheMods/ATM-9/assets/75589590/0f0ae7c5-4926-44b5-bb4f-9490dfb8c582)

**Comment by Kevin-Marsh** [comment]
This is supplementaries april fools prank.
