### ISSUE TITLE
ATM9 V0.0.45 Netherite crafter from refined storage interface bug

### ISSUE THREAD

**Issue by phunderr** [AllTheMods/ATM-9#158]
When opening the netherite crafter there is a visual bug

![2023-07-27 07_45_54-Minecraft Forge_ 1 20 1 - Multiplayer (3rd-party Server)](https://github.com/AllTheMods/ATM-9/assets/44674338/84340dee-fc35-4bc7-9efa-98c6a45b529e)

**Comment by aAndrew3030** [comment]
This was fixed in version 4.0.1 of ExtraStorage, but hasn't been updated in the pack yet.
