### ISSUE TITLE
[Bug]: upgrade chest/barril item bug

### ISSUE THREAD

**Issue by Frosztgelado** [AllTheMods/ATM-9#1592]
### Possible Fixes

Yes

### Modpack Version

0.2.56 lastest

### What happened?

There is a bug that I noticed in the most recent .56, that the items to upgrade barrels/chests, when they are upgraded from the initial level (chest or normal barrel) to the item level, example (iron, gold, etc... ) the item has infinite use (I only tested it on the barrel) so you can create one made of diamond or netherite, and create barrels, and upgrade several with just one item

### latest.log

https://gist.github.com/Frosztgelado/a567aa9a2854cac6aabdec6087554d67

**Comment by Kevin-Marsh** [comment]
This should be fixed next update.
