### ISSUE TITLE
[Quests issues]: Chapter 1: The Beginning "We've Struck Diamonds"

### ISSUE THREAD

**Issue by binarywaddle** [AllTheMods/ATM-9#1595]
### Modpack Version

0.2.56

### Describe the issue

Hello, I am stuck unable to complete the quest "We've Struck Diamonds" in Chapter 1. It shows checked off but I'm unable to proceed any further due to it not completing. Am I missing anything obvious? As you can see I've already been to the Twilight Forest and the Nether as well which are checked off.

Thank you for the awesome modpack!
![image](https://github.com/AllTheMods/ATM-9/assets/1279202/d3fdf575-aa2f-4b81-b04e-25e0b0cb0050)

Also completely unrelated but is there a reason that Curseforge no longer shows a list of mods in the pack?
![image](https://github.com/AllTheMods/ATM-9/assets/1279202/3b7cbd77-ee69-490b-894d-ed4e55e11070)

**Comment by luxidoptera** [comment]
This is a very common and very weird issue; everyone who encounters it seems to have it on different quests. Me and my boyfriend are encountering it on "The Stone Age".

ATM devs, if you can figure out what's causing this problem and fix it, it would be GREATLY appreciated.

**Comment by TheBedrockMaster** [comment]
Might just have to use editing mode if possible

**Comment by ToshibaEC0Microwave** [comment]
This might just be a bug needing editing mode to complete. Just incase I've changed it so it accepts any forge diamonds. Hopefully should be fixed
