### ISSUE TITLE
[Bug]: GregTech Assembly Line doesn't accept PneumaticCraft Lubricant in its recipes

### ISSUE THREAD

**Issue by SethaWetha** [AllTheMods/ATM-9#1596]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

PneumaticCraft Lubricant does not work in the GregTech Assembly Line when calling for Lubricant in a recipe. Assuming this is unintended because it works for all the other GregTech recipes I've tried.

**Comment by loving2** [comment]
Cannot recreate on latest ATM9 v0.3.5
