### ISSUE TITLE
[Quests issues]: Best Enchaniting set-up, multiple issues

### ISSUE THREAD

**Issue by ryan92084** [AllTheMods/ATM-9#1601]
### Modpack Version

0.2.56

### Describe the issue

3 Issues with this quest

1st the setup for the quest  (5x echoing sculkshelf, draconic endshelf, 5x soul touched-deepshelf, 3x shelf of end-fused rectification, deepshelf of arcane treasures) doesn't actually max everything.  You are 25 rectification and 2.5 arcane short.  I believe the requirement is meant to be 5x soul-touched **sculkshelf** instead of deepshelf.

2nd the description is from the old version of this quest and no longer matches the requirements

3rd this quest did not complete properly despite having all shelves in my inventory at the same time.  The quest showed 100% but remained grayed out.  The draconic endshelf was not getting a green check so that is a likely culprit.

**Comment by TheBedrockMaster** [comment]
Fixed?

**Comment by ToshibaEC0Microwave** [comment]
This has been fixed for current versions, the description now matches the criteria. And yeah last part is definitely just haven't completed the previous quests

**Comment by ryan92084** [comment]
The last part was not that but i'm glad it is now fixed.

**Comment by TheBedrockMaster** [comment]
Might have to use FTBQuests editing mode
