### ISSUE TITLE
GTCEu MUO in reactor mode

### ISSUE THREAD

**Issue by Snakedon** [AllTheMods/ATM-9#1604]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

i try to do this
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/89083848-41bd-415b-8e8c-d2dc8a91dc67)
but either I'm doing something wrong, or something else is wrong, below are screenshots of MUO
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/6851aafc-2391-4b32-976c-b0085cb4b701)
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/0d81995c-1717-4cd3-a0c6-31ef03b3cfcd)
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/aeafbeb4-63ba-4c74-87bf-caa44ced945b)
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/382ad4e4-c765-4512-815d-87e7157f551c)
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/e4a30512-21b2-4902-ab0f-7f46e2d4a979)
![image](https://github.com/AllTheMods/ATM-9/assets/48630889/ed935c46-4848-49c1-be9d-422883cea4c4)
2 laser target hatch for MAX (until fix GT in 1 hatch)
Don't work energy generation

**Comment by Snakedon** [comment]
Can someone still tell me what the problem is here? Is there something wrong with me, or is the multiblock itself not working?

**Comment by loving2** [comment]
This is working now in ATM9 v0.3.5, just tested on a fresh installation.
