### ISSUE TITLE
[Bug]: GREGTECH RECIPE BUG

### ISSUE THREAD

**Issue by METABYTECODE** [AllTheMods/ATM-9#1607]
### Possible Fixes

Yes

### Modpack Version

last

### What happened?

It is impossible to get a lot of liquids and items from the GregTech mod. 1. Phosphorus_wafer (autocraft with refined storage, the machine does not accept items) 2. The distillation column does not produce argon, but accepts liquid air as input. Also, a lot of liquid is not produced in this column when slightly steamed cracking naphtha arrives. With the latest updates, I noticed that the blast furnace has stopped receiving items using refined storage. Cutter incorrectly calculates the energy for Phosphorus_wafer production. This is the recipe, but it does not have enough energy to produce even at the EV level. And many other baggy recipes that can be listed for a very long time.
![Screenshot_1](https://github.com/AllTheMods/ATM-9/assets/62258232/cb50dd89-63c6-49da-b8ee-5682fbc3c0c8)
![Screenshot_2](https://github.com/AllTheMods/ATM-9/assets/62258232/0261a171-81a9-4bc6-8064-e6a67051a779)
![Screenshot_3](https://github.com/AllTheMods/ATM-9/assets/62258232/30ab69c8-194c-46dd-b976-25c63fa19ad6)
![Screenshot_4](https://github.com/AllTheMods/ATM-9/assets/62258232/31f08b71-2907-4bad-8b3c-b58ef336a689)
![Screenshot_5](https://github.com/AllTheMods/ATM-9/assets/62258232/7dd5887c-2889-423d-b184-20ea152c587a)
![Screenshot_6](https://github.com/AllTheMods/ATM-9/assets/62258232/d473d212-ee64-40b5-b7ff-492773dc05a3)
![Screenshot_7](https://github.com/AllTheMods/ATM-9/assets/62258232/0e7104d7-8c71-4144-ada1-8f99de714d8d)

**Comment by screret** [comment]
fairly certain all of your issues are already fixed.

**Comment by METABYTECODE** [comment]
> fairly certain all of your issues are already fixed.

No

**Comment by METABYTECODE** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/62258232/3789eb4d-39d5-410a-a122-6fcd158818c8)
![image](https://github.com/AllTheMods/ATM-9/assets/62258232/43bde607-d6d0-45e9-97da-0b49ade9c747)

Its a Distilation Tower

lightly steam cracked naphta in input , but this liquid is not processed

**Comment by METABYTECODE** [comment]
UPD: Distillation tower work with hydro cracked naphta(ligtly and severly)
![image](https://github.com/AllTheMods/ATM-9/assets/62258232/90fe8442-18b0-4330-82e2-1ab8ba400098)

But it doesn't work with:
liquid air
ligtly + severly steam cracked naphta

**Comment by TrickShotMLG02** [comment]
I am having the same problem with liquid air. How did you solve it?

**Comment by TrickShotMLG02** [comment]
Nvm. For everyone else having this issue in the future, you need to add an Output Bus to the bottom layer of the distillation tower
