### ISSUE TITLE
EnderIO enchanter recipes

### ISSUE THREAD

**Issue by TrapHunter** [AllTheMods/ATM-9#161]
There are 3 recipes with the same items so can't craft them or rotate between them. Riptide, Impaling, Sweeping Edge and Piercing.

**Comment by Soofire** [comment]
I can confirm, i tried to craft Sweeping Edge and it have the same recipe as Impaling
![rcuX55J](https://github.com/AllTheMods/ATM-9/assets/19862525/481b9695-93b4-47ae-81d5-9781e753b250)
![qcPmglA](https://github.com/AllTheMods/ATM-9/assets/19862525/4873835b-4377-48e4-8bfa-91b923b1e7f6)
