### ISSUE TITLE
[Bug]: Quest "Best Enchanting set-up" asks for the wrong number of shelves

### ISSUE THREAD

**Issue by Khris777** [AllTheMods/ATM-9#1610]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

The last quest of Apotheosis Enchanting "Best Enchanting set-up" asks for different numbers of shelves delivered than the description states. The number of shelves you need to deliver do not bring every stat to 100%, so they are clearly wrong while the numbers in the description are the correct ones.

I am aware the current version is 0.2.56, but a fix for this quest is not in the changelog so it's still relevant.

**Comment by Kevin-Marsh** [comment]
These quests are going to get a full rewrite. The quest is supposed to have 5 Echoing sculkshelves, 5 soul-touched sculkshelves, 1 draconic endshelf, 3 end fused rectification to achieve maximum stats.

**Comment by TheBedrockMaster** [comment]
Add the quest bug label, also has this been fixed?
