### ISSUE TITLE
[Bug]: Multiblock images not showing in Blood Magic quests

### ISSUE THREAD

**Issue by g0urra** [AllTheMods/ATM-9#1611]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

The quests "Upgrading Our Altar to Tier 2" and "Upgrading the Altar: Tier 3" does not properly show the image in the quest.

![bild](https://github.com/AllTheMods/ATM-9/assets/12349921/a91f3c57-ef49-4164-8955-8253f417e022)
![bild](https://github.com/AllTheMods/ATM-9/assets/12349921/9496fb16-77c6-4ce1-8a6d-6f680241e05d)

**Comment by TheBedrockMaster** [comment]
This has since been fixed :)
