### ISSUE TITLE
[Quests issues]: stone age doesnt register furnace

### ISSUE THREAD

**Issue by SerpentTech** [AllTheMods/ATM-9#1612]
### Modpack Version

0.2.56

### Describe the issue

i have made amny furnaces and gotten a lot of cobble, but the questbook says 100% with agrayed out checkmark and wont let me progress to the rest of the quests, im already pretty deep into the game and am just trying to fill out the questbook

**Comment by SerpentTech** [comment]
![Screenshot 2024-04-12 120737](https://github.com/AllTheMods/ATM-9/assets/95395810/f250e54f-feb9-471a-85e8-642f31702e3f)

**Comment by TheBedrockMaster** [comment]
FTB Quests editing mode it is!

**Comment by ToshibaEC0Microwave** [comment]
Grey checkmark means you have the tasks completed but not previous quests. Green means both have been completed!
