### ISSUE TITLE
[Bug]: Copy Paste Gadget

### ISSUE THREAD

**Issue by RealWiJackson** [AllTheMods/ATM-9#1613]
### Possible Fixes

Yes

### Modpack Version

1.20.1

### What happened?

I try to open the building tool gui and it wont work, i have tried using different keys and non of it works, might be broken or im doing something wrong?? please can you fix or help me

**Comment by Kevin-Marsh** [comment]
Conflicting keybinds means that you either need to unbind everything else or rebind to another key that is free such as ;

**Comment by RealWiJackson** [comment]
Hi I’ve already done that, that’s why I made the bug thing, it isn’t working.
