### ISSUE TITLE
[Bug]: Morgan/Caliburn attack cap config issue (ATM9 modpack)

### ISSUE THREAD

**Issue by dpcollier128** [AllTheMods/ATM-9#1615]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

The innate cap set in All The Mods 9 pack by default for Caliburn is 5000. I set it to be higher in the mahoutsukai-server.toml for my world (single-player) and created a new Caliburn after the change while throwing in up to 512 of the required item to raise the cap. The cap was raised from the default 100, but the innate cap refuses to go above 5000 for some reason despite being set higher in the config file. I'm unsure if this is a bug within the mod or if the All The Mods 9 pack has an additional balancing safeguard to edit. To reiterate, this is only for single-player, navigating to the serverconfig folder.

**Comment by Kevin-Marsh** [comment]
Look at the line POWER_CONSOLIDATION_TIERS = . Closing since this isn't a bug or an issue.
