### ISSUE TITLE
[Bug]: Minecolonies FairyTale Style Missing Blocks

### ISSUE THREAD

**Issue by ApocRagnarok** [AllTheMods/ATM-9#1621]
### Possible Fixes

Yes

### Modpack Version

9-0.2.56

### What happened?

Certain blocks, such as the Create Block of Zinc for the FairyTale Town Hall lv 3 and the Quark Feeding Trough for the FairyTale Livestock huts, are not available in JEI and are seemingly uncraftable.
![2024-04-15_11 51 17](https://github.com/AllTheMods/ATM-9/assets/167113580/1e097b5c-871a-41e9-abea-5fbe1800e373)
![2024-04-15_11 51 34](https://github.com/AllTheMods/ATM-9/assets/167113580/e72e1ced-1098-44f5-867f-fcd1eb16d459)

### latest.log

https://gist.github.com/ApocRagnarok/113fc86a9aa9c815d026c63f2c3f4a4a

**Comment by Mitchell5200** [comment]
I have not yet found a proper way to fix this yet, However, i have found a workaround
Use the mekanism "oredictionificator", and set `'forge:storage_blocks/brass'` (or /zinc, or anyother material) as the filter, and click the arrows until the create brass shows up, then toss in ATO brass. ***(as pictured)***
![2024-08-13_21 53 33](https://github.com/user-attachments/assets/cd9f2e22-9468-4cd5-a594-eb08645d412f)
![2024-08-13_21 53 50](https://github.com/user-attachments/assets/4952261f-c977-4f89-b3fe-5b9c25e87dad)

Duplicate issues, #1431, #1356, #1621
