### ISSUE TITLE
[Quests issues]: 

### ISSUE THREAD

**Issue by nforrence** [AllTheMods/ATM-9#1624]
### Modpack Version

ATM9 0.2.56

### Describe the issue

Blood magic altar setup image is missing tier 2 and tier 3

![2024-04-16_05 36 07](https://github.com/AllTheMods/ATM-9/assets/105971938/00090fa6-ac05-4ef9-a734-6c5891bce255)

**Comment by TheBedrockMaster** [comment]
They're there now I believe :)
