### ISSUE TITLE
[Bug]: Sophisticated Storage Basic-to-Tier upgrade doesn't get used up.

### ISSUE THREAD

**Issue by hairlessOrphan** [AllTheMods/ATM-9#1629]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

Sophisticated Storage's Basic-to-[any tier] upgrade doesn't get removed from inventory after using it on a barrel placed in the world. Tried with Basic-to-Gold, Basic-to-Diamond, and Basic-to-Netherite upgrades on vanilla barrels.

To reproduce:
1. Craft a Basic-to-Netherite upgrade.
2. Craft 2 (or more) vanilla barrels (crafted with Oak wood).
3. Place the vanilla barrels in the world.
4. Use the Basic-to-Netherite upgrade on the barrels.
5. Observe that you still have the upgrade in inventory.

**Comment by Kevin-Marsh** [comment]
This will be fixed in the next update by updating sophisticated storage.
