### ISSUE TITLE
[Bug]: Applied doesn't recognize the completion of Occultism's recipes.

### ISSUE THREAD

**Issue by Rafamzo** [AllTheMods/ATM-9#1633]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

Occultism and Applied. When I request the creation of a Foliot Miner, Djinni, Afrit, or Marid, Applied does not recognize the completion of the recipe.

![unknown_2024 04 18-21 30_5](https://github.com/AllTheMods/ATM-9/assets/16180666/20dced2f-8781-403b-9a8c-451eef078b33)

**Comment by Kevin-Marsh** [comment]
This isn't a bug. Neither Applied Energistics nor Refined storage can differentiate the NBT on the items when you craft occultism items. You would need to do something like renaming a piece of paper and using that as the item for your craft to return instead of trying to just return the items.
