### ISSUE TITLE
[Bug]: No valid Forge Version

### ISSUE THREAD

**Issue by JoelYoung01** [AllTheMods/ATM-9#1635]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

Loading a fresh install causes a crash, the root cause: 

```
Mod rootsclassic requires forge between 47 and 47.1.3 (inclusive)
Currently, forge is 47.2.21
```

Full Report:
[crash-2024-04-19_16.33.49-fml.txt](https://github.com/AllTheMods/ATM-9/files/15045836/crash-2024-04-19_16.33.49-fml.txt)

Downgrading forge to 47.1.3 causes the following crash:
```
Mod shrink requires forge 47.1.29 or above
Currently, forge is 47.1.3
```

Full Report:
[crash-2024-04-19_16.28.27-fml.txt](https://github.com/AllTheMods/ATM-9/files/15045837/crash-2024-04-19_16.28.27-fml.txt)

There are a couple issues open on the rootsclassic github and a PR to fix the issue which has been sitting since Feb 2024. Maybe worth removing rootsclassic from pack?

**Comment by Mitchell5200** [comment]
Roots was removed from the pack many pack versions ago, remove it, or do a fresh clean install

**Comment by JoelYoung01** [comment]
@Mitchell5200 Ah yes after I removed the mod pack and did a fresh install the issue was gone, apologies not sure how I messed that up the first time…
