### ISSUE TITLE
[Bug]:  Missing items in game.

### ISSUE THREAD

**Issue by Chappy70** [AllTheMods/ATM-9#1638]
### Possible Fixes

Yes

### Modpack Version

V0.2.56

### What happened?

I am doing the fairytale mine colony and the "Block of Brass" from Create and "Feeding Trough" from Quark are not listed in JEI.

**Comment by Mitchell5200** [comment]
the feeding trough is toggled off in Quark's config, you can turn it back on of you choose, but i think it got turned off for server TPS reasons, if my memory is correct
as for create brass, maybe the mek oredictionificator? but if not, you'd have to mess with AlmostUnified, as it's hidden/removed the duplicate versions as part of the set unification
