### ISSUE TITLE
[Bug]: Server Files dont match mod pack!

### ISSUE THREAD

**Issue by Afgewezen** [AllTheMods/ATM-9#1640]
### Possible Fixes

Yes

### Modpack Version

Latest

### What happened?

Please update the server files. It is not working

**Comment by Mitchell5200** [comment]
do you mean https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5226700 for 0.2.56, attached as Additional files to the 0.2.56 client version?
If so, each server pack is uploaded with each client release, just sometimes takes a few days to get approved, but you possibly got the 0.1.0 server pack that for some reason is always displayed in the sidebar
