### ISSUE TITLE
[Bug]: Cannot get Ender Infused Teleportation Core

### ISSUE THREAD

**Issue by MaxQi233** [AllTheMods/ATM-9#1643]
### Possible Fixes

Yes

### Modpack Version

0.2.51-0.2.57 (no attempt was made on a lower version)

### What happened?

I placed the bookshelf according to the example given in the quest book, and the enchant given was soulbound rather than infusion.

I have found one feasible placement method myself, and I'm not sure if it will be helpful for you to fix this bug:

(5 dragon, 12 glowing hell, 2 stone, 3 melon)

![infusion](https://github.com/AllTheMods/ATM-9/assets/59874619/25558f36-b2da-4b39-9e4b-20d1124b48b9)

**Comment by Jmpp2909** [comment]
@Kevin-Marsh could you have a look at this, i severely lack knowledge about Apotheosis stuff lol

**Comment by Kevin-Marsh** [comment]
It appears that the teleportation core provides a 0.5 boost to arcan which pushes the infusion out of the range. I have made a note to revamp these quests. Here are some good setups for ease of enchanting there cores:
Cores:
5 soul sculkshelf, 5 echoing sculkshelf, 7 Melonshelf, 1 Draconic endshelf = Draconic
1 soul sculkshelf, 2 echoing sculkshelf, 4 draconic endshelf, 3 melonshelf = Ender
5 soul sculkshelf, 5 echoing sculkshelf, 10 melonshelf = Nether

**Comment by MaxQi233** [comment]
@Kevin-Marsh Thank you for your reply! This is very useful!

**Comment by Yusunoha** [comment]
> It appears that the teleportation core provides a 0.5 boost to arcana which pushes the infusion out of the range. I have made a note to revamp these quests. Here are some good setups for ease of enchanting there cores: Cores: 5 soul sculkshelf, 5 echoing sculkshelf, 7 Melonshelf, 1 Draconic endshelf = Draconic 1 soul sculkshelf, 2 echoing sculkshelf, 4 draconic endshelf, 3 melonshelf = Ender 5 soul sculkshelf, 5 echoing sculkshelf, 10 melonshelf = Nether

I've tried some setups myself, mainly to make it as compact as possible, and what worked for me was
Nether: 4 Echoing Deepshelf, 3 Draconic Endshelf (7 total)
End: 2 Melonshelf, 1 Deepshelf, 2 Echoing Sculkshelf, 4 Draconic Endshelf (9 total)
Draconic: 1 Echoing Deepshelf, 6 Echoing Sculkshelf, 2 Draconic Endshelf (9 total)
