### ISSUE TITLE
gregtech tool duplication

### ISSUE THREAD

**Issue by ambrosius42** [AllTheMods/ATM-9#165]
when combining gregtech tools such as the hammer in the crafting grid, instead of both durabilities being combined into a new tool they make a new tool and consume 1 durablility from each tool, leaving you with the two hammers you started with and a brand new hammer
https://github.com/AllTheMods/ATM-9/assets/140232744/8b29483a-eacd-4736-a1ed-21bcdd053986

**Comment by TheBedrockMaster** [comment]
Has this been fixed? Add bug label.
