### ISSUE TITLE
[Bug]: Kubejs:comb_processor error

### ISSUE THREAD

**Issue by Kiriao** [AllTheMods/ATM-9#1653]
### Possible Fixes

Yes

### Modpack Version

0.2.57

### What happened?

I updated to the lastest ver of ATM 9 and i got this error when i launch my world. tried to re-install a new ATM 9 and still having the same error msg, it cause some recipe missing like phyto not working with MA seed.

https://imgur.com/24Q6ByF

Here the log https://mclo.gs/Shr9t94

**Comment by Kiriao** [comment]
Am I only one got this kubejs error...

**Comment by Kiriao** [comment]
No I didnt modify. The the latest log

https://mclo.gs/nRJryuW

**Comment by loving2** [comment]
I cannot recreate this issue on the latest ATM9 version 0.3.5
