### ISSUE TITLE
The mods don't show or load

### ISSUE THREAD

**Issue by rvdmljbav** [AllTheMods/ATM-9#1657]
I don't know what to do. I downloaded the modpack, put the files in mods folder, downloaded and installed java and forge, and the only mods that show are java and minecraft because before my computer finishes loading the mods in the mojang logo screen, it's turned into the start minecraft screen

My version is 1.20.1 like forge and the modpack, I don't know what's wrong and am losing my mind

**Comment by thevortex** [comment]
what launcher are you using

**Comment by rvdmljbav** [comment]
> what launcher are you using
 
Minecraft Launcher

**Comment by rvdmljbav** [comment]
Alrighty I'll try that

**Comment by rvdmljbav** [comment]
Even after installing the launcher and downloading and loading the mods with it

**Comment by rvdmljbav** [comment]
Alright, I did it, boys. Thanks for your help, I just needed to open instance through the atlauncher.
