### ISSUE TITLE
Minecolonies Bug. Builder Stuck in loop

### ISSUE THREAD

**Issue by HPTD1** [AllTheMods/ATM-9#166]
As title says:
Builder is stuck in a loop of "need item, request item, got item, need item" when upgrading a building.
this happens when upgrading its own building from lvl2 to lvl3, Calcedonia Style Builder house as well as Colonial Builder house.
In Calcedonia its a spruce button, in Colonial its a Item Frame with a pickaxe. They are unable to process what item they need.

Known workarounds on the minecolonies-discord like letting the colony craft the item without it never touching the players hands, placing it yourself etc. dont work. I switched from colonial style to calcedonian style since I've never had issues with that style pack in the past (1.19, 1.18), but the builder gets stuck on the same level. Some buildings with buttons simply work just fine. The Level 2 Builder House even has buttons that worked when upgrading from 1 to 2.
It seems the item it wants to place has additional NBT tags, visible on the resource scroll bound to the affected builder, when the request is visible for 1sec. before looping again

This bug completly prevents progress in the minecolonies mod, since a builder needs to level up its own building before it can upgrade other buildings.

**Comment by cadexn** [comment]
I'm encountering the same bug. Specifically Steampunk style getting 

Builder from lv 4 to 5
Residences from lv 2 to 3
University from lv 2 to 3

All are getting stuck in a loop

**Comment by aAndrew3030** [comment]
https://github.com/ldtteam/minecolonies/issues/9255

**Comment by aAndrew3030** [comment]
Appears to be a conflict with AE2 and/or GregTech (I believe GT has compat for AE2, so it might be just AE2 causing the issue)

**Comment by aAndrew3030** [comment]
Just giving a update that AE2 and Minecolonies are working on a fix for this issue

**Comment by HPTD1** [comment]
well, it did look like mod problem outside of minecolony, but I didn't find any indication that it was AE2. this bug appeared before  GT was added,
When they update and the updated version is added to the modpack this issue should fix itself, then we can close this.

**Comment by aAndrew3030** [comment]
The updated Minecolonies (with the fix) has been added to .47 version of the pack

**Comment by HPTD1** [comment]
the ATM9 server I play on has updated to .47, the bug with the builder is gone. I think an update to Structurize, part of minecolonies mods, did the trick. 
If the others also confirm this problem fixed we can close this issue.
