### ISSUE TITLE
[Bug]: Possible Bug? -  Infinite Oak Logs from Oak Slabs

### ISSUE THREAD

**Issue by RoutYMO** [AllTheMods/ATM-9#1660]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

I'm not sure if intended, so please correct me if so.

Steps to replicate:
Craft 1x Oak log to 4 Planks, then 3 Oak Planks to 6 Oak Slabs, then 2 Oak Slabs to 1 Oak Log.
Essentially, 1 Oak log can be infinitely crafted into 3 logs.

The other slab recipes, create planks as intended from my testing.

![image](https://github.com/AllTheMods/ATM-9/assets/132172885/3d44d696-76e4-4d22-9338-afc2fe4fad38)

**Comment by RoutYMO** [comment]
Coming back to this a few days later and something weird has happened.
_(I've not updated the pack or changed versions, it is still v0.2.58)_

Now, instead of Oak Slabs converting to an Oak Log, they now properly convert to an Oak Plank.
However, **Dark Oak**, **Spruce** and **Acacia** Slabs now all convert into their respective log.
I have added updated screenshots.
![acacia](https://github.com/AllTheMods/ATM-9/assets/132172885/9da53738-1ff2-4731-8310-0d6745f378a9)
![birch](https://github.com/AllTheMods/ATM-9/assets/132172885/fd574f5c-5cce-4e50-8328-4a8c0d5bc083)
![cherry](https://github.com/AllTheMods/ATM-9/assets/132172885/5957ea7a-9e10-4daf-85a4-b68a7223cfce)
![dark_oak](https://github.com/AllTheMods/ATM-9/assets/132172885/92276801-0111-48d1-94b6-e0ea5ba09e26)
![jungle](https://github.com/AllTheMods/ATM-9/assets/132172885/46f05fb9-25a1-49af-b30e-eb63017af386)
![mangrove](https://github.com/AllTheMods/ATM-9/assets/132172885/7f67ce30-27cf-40f4-9bd2-8c0c86e69a73)
![oak](https://github.com/AllTheMods/ATM-9/assets/132172885/4dd73322-9e39-4cc4-bc36-8e7dd47b8a5f)
![spruce](https://github.com/AllTheMods/ATM-9/assets/132172885/f34f2cfe-85cf-424c-859d-4e2f30964a3f)

**Comment by battle00333** [comment]
I am on version 0.2.59 and I just discovered this bug as well.
When you put two slabs over each other in the crafting bench, it forms a log instead of a plank
![image](https://github.com/AllTheMods/ATM-9/assets/23027074/5b045431-c942-47b4-9b18-68039d48f8d8)
![image](https://github.com/AllTheMods/ATM-9/assets/23027074/d2d58f1f-a460-4a71-b86e-baca31c4e80f)

**Comment by ANZUARIAKE0127** [comment]
This seems to be an old Quark bug. Quark-4.0-**443**.jar is used in ATM9 ver0.2.60, but when I replaced it with the latest Quark-4.0-**450**.jar, the deliverables reverted to planks instead of logs.

**Comment by skelefour** [comment]
This is still occurring in the current version, 0.2.60.

**Comment by CatCubeNew** [comment]
it's alredy 0.3.0, and it's still doesn't fixed....

**Comment by RevyTL** [comment]
Not fixed yet
