### ISSUE TITLE
ATM9 needs this performance mod (FPS reducer)

### ISSUE THREAD

**Issue by Hithere21** [AllTheMods/ATM-9#1666]
All modpacks in minecraft can be incredibly intensive to run, there are tons of different machines running with animations, farms, mob grinders, etc involved with modded minecraft. This means that when you leave the game open to do something else you are wasting a lot of power, and you are degrading your pc components much faster. This is a serious issue that I've encountered while playing ATM9 and various other modpacks that don't have this mod, I'd argue it's pretty much essential for any modpack. FPS reducer is a mod that will allow each user to set when their game is considered "idle", and what the FPS cap is when their PC is "idle". This is especially helpful for people who use older hardware, as you don't have to constantly run your game it 60FPS. I know this isn't a bug but I have nowhere else to suggest this and I think it would be incredibly helpful.

**Comment by Mitchell5200** [comment]
#1 for mod suggestions, Noted

**Comment by Hithere21** [comment]
didnt see mod suggestions thread my bad

**Comment by Hithere21** [comment]
> #1 for mod suggestions, Noted

thanks for linking it
