### ISSUE TITLE
quests and questions

### ISSUE THREAD

**Issue by GIKExe** [AllTheMods/ATM-9#167]
in the last version of the build, the quests were well done, will they be in this version?
will there be crafting items with "creative" power?

as I understand it, the build is still being updated and not all mods have come out on 1.20.1, will Mekanism be added when it comes out on a new version?

**Comment by aAndrew3030** [comment]
I am not part of the ATM team, so take this FWIW. FTB Quests has not been updated yet, and the ATM Team has discussed quests (on discord). Mekanism is in alpha, but unreleased yet, expect that soon (lets hope). That said, in general, Github issues is the place to share bugs. Your questions would be better answered on the ATM Discord.
