### ISSUE TITLE
[Bug]: Can't take items out of all RS terminals

### ISSUE THREAD

**Issue by ElitBoxen** [AllTheMods/ATM-9#1670]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

I was automating the first LV circuit and i placed a interface. After i had placed it i couldn't take items out of my RS system. I removed the interface and it worked again.

**Comment by TheBedrockMaster** [comment]
So you fixed it?

**Comment by ElitBoxen** [comment]
> So you fixed it?

Ye

**Comment by TheBedrockMaster** [comment]
So this can be closed?

**Comment by TheBedrockMaster** [comment]
Close as complleted.
