### ISSUE TITLE
[Crash]:  MythicBotany Mjölnir placed in reforging Table crashes client

### ISSUE THREAD

**Issue by dennisburnsjr** [AllTheMods/ATM-9#1671]
### Possible Fixes

Yes

### Modpack Version

2.58

### What happened?

When you place Mjolnir from the mod MythicBotany into the reforging table by Apotheosis, it instantly crashes your client to desktop. Doesn't leave a crash log that I have found yet.

### Crash Log

None

### Latest.Log

None

**Comment by ManaLocked** [comment]
Seconded. The moment you go to highlight over an instance of Mjolnir with affixes, it crashes when attempting to render, getting a StackOverflowException -- Log: https://mclo.gs/n56YKJp

Likely universal, but mine occurred in an instance of ATM9-NF.

**Comment by Mitchell5200** [comment]
Hmm, this was supposed to be fixed by both mod devs, oh well, i'll just blacklist the mjolnir from reforging
