### ISSUE TITLE
[Bug]: Gregtech quest issues

### ISSUE THREAD

**Issue by g0urra** [AllTheMods/ATM-9#1673]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

The (optional) quest "IV Processing Array" under the Insane Voltage chapter requires an IV Processing Array that can't be crafted. Tooltip also says it's deprecated.
![bild](https://github.com/AllTheMods/ATM-9/assets/12349921/db6188ae-7f67-4bde-bd1a-5f9c04091386)
The quest "Re-Organization" under the Ludicrous Voltage chapter has a spelling error.
![bild](https://github.com/AllTheMods/ATM-9/assets/12349921/e945e8a6-5fdf-4cb9-9622-a9e896ea7496)

**Comment by TheBedrockMaster** [comment]
Add the quest issue label.

**Comment by TheBedrockMaster** [comment]
Remove bug label.
