### ISSUE TITLE
[Bug]: Productive Bees doesn't produce at a hive with gamma/omega upgrade

### ISSUE THREAD

**Issue by Malos13** [AllTheMods/ATM-9#1676]
### Possible Fixes

Yes

### Modpack Version

0.1.13

### What happened?

If a hive has untill a beta upgrade, the bees produce normally. After placing gamma/omega  upgrade in a hive,  the bees no longer leave the hive and don't produce. When upgrades are removed from the hive, the bees leave it but do not produce.

**Comment by Malos13** [comment]
thank you for the answer, but is this a configuration or a bug? because this way i'll miss a least one upgrade slot. this just don't make sense to me...

**Comment by Jmpp2909** [comment]
Its a mechanic
You are meant to get simulator as soon as possible
You can use Simulator by itself when you dont have enough materials for higher tier upgrades
Example: 3 speed + 1 Simulator, so you can still simulate bees, even with low resources
From the moment you get Gamma/Omega upgrades, you dont need a standalone Simulator anymore, as those come with it builtin, so you can do 4 Gamma/Omega in the hive

**Comment by Malos13** [comment]
thanks, can you close this issue please ?

**Comment by Jmpp2909** [comment]
You should be able to close at as you are the author, im not a dev, i cant close it
Maybe @Mitchell5200 can

**Comment by Mitchell5200** [comment]
and yes, the issue creator can also close issues

Additionally, this looks like it was meant for https://github.com/AllTheMods/atm9nf/issues rather than base ATM9

**Comment by Malos13** [comment]
thank you
