### ISSUE TITLE
[Bug]: nan certificate  takes too much time to craft.

### ISSUE THREAD

**Issue by finshope** [AllTheMods/ATM-9#1677]
### Possible Fixes

Yes

### Modpack Version

0.2.57

### What happened?

Since GTM version update, the large extruder is no longer perfect overclock. With 2 UHV energy input hatch, NAN certificate still takes nearly 60 hours to craft.

**Comment by loving2** [comment]
Thank you, we'll definitely come up with something to address this! We are currently discussing how we might approach changing it because 60 hours is far too long.
