### ISSUE TITLE
[0.0.45] PneumatiCraft: Reinforced Chest drops corail scroll when broken

### ISSUE THREAD

**Issue by SoullessCookie** [AllTheMods/ATM-9#168]
Every time I break a Pneumaticraft Reinforced Chest, it drops a spell scroll from corail tombstone. It doesnt matter how many times I break it, it happens every time. It's a good bug, but might as well report it.

**Comment by beamer91** [comment]
I think it is more just any block that is broken has a chance to spawn a scroll as it has happened to me multiple times when breaking different blocks such as a me controller.

**Comment by Corail31** [comment]
I will change this in my next release, to reduce the affected loot tables. Feel free to open the issue on my github.

**Comment by SoullessCookie** [comment]
Corail updated the mod quickly and gave a good response. 10/10 dev
