### ISSUE TITLE
[Bug]: muo recipes consume the catalyst

### ISSUE THREAD

**Issue by ffbw4hwj** [AllTheMods/ATM-9#1680]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

muo recipes for max hatch and creative energy both consume the 16 micro universe catalyst
is this intentional?

**Comment by loving2** [comment]
Yes, since these recipes produce creative tier items it felt appropriate to consume all the inputs

**Comment by ffbw4hwj** [comment]
gotcha
just making sure
