### ISSUE TITLE
gtceu UV energyhatch research bricked my world [Crash]: 

### ISSUE THREAD

**Issue by Drawen302** [AllTheMods/ATM-9#1682]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

The first crash hapaned when i tried to open the gtceu Network Switch,
The second crash that i think bricked my world was after i pluged multiple gtceu HPCA into the Network Switch, Network Switch into the reasercher for higher tier research. 
When I then opened the researhers and put in the research for the UV energyhatch my game crashed and now i can't load into the world again.

### Crash Log

https://gist.github.com/Drawen302/0d6dd059678cca38b4f323971e10be5e

### Latest.Log

https://gist.github.com/Drawen302/c722afe00fcd09eff9a49833055c04bb

**Comment by loving2** [comment]
This has been fixed in GTCEu-Modern and is in latest ATM9 v0.3.5
