### ISSUE TITLE
[Bug]:HPCA does not work, no CWU is generated.

### ISSUE THREAD

**Issue by BaoruLee** [AllTheMods/ATM-9#1683]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

In 0.2.58, GTM progressed to the “ZPM energy input hatch” stage and prepared to use the research_station to make the data orb. It established an HPAC, formed a multi-block structure, and connected the two machines with power. The GUI of the HPCA showed "0/8 CWU/t", but it showed standby. (I used enough cooling)
![2024-05-04_22 35 17](https://github.com/AllTheMods/ATM-9/assets/49811225/45577d6b-b6c6-44a4-911b-9c53501fb29f)

### latest.log

No

**Comment by BaoruLee** [comment]
The latest.log is so big ,uploading failing!

**Comment by Ghost-Asood** [comment]
data bottom middle, energy 2nd row left, maint top middle
Do this on the research station and it might work, this worked for me.

**Comment by BaoruLee** [comment]
> data bottom middle, energy 2nd row left, maint top middle Do this on the research station and it might work, this worked for me.

OMG! I did what you said and it running！thank you very much guy！But why doesn't it work even if the multi-block structure is formed according to my arrangement?真是个怪事

**Comment by Ghost-Asood** [comment]
Nice!
No idea, prolly a bug in the code for the research station
