### ISSUE TITLE
[Bug]: Vanilla Oak Bookshelf / Cooking for Blockheads bug

### ISSUE THREAD

**Issue by zrieprakis** [AllTheMods/ATM-9#1685]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

Looks like breaking a bookshelf in the current version of ATM9 yields a stack of 3 Cooking for Blockheads books rather than vanilla books.  Saw this in a post from another pack a while back (Vault Hunters?).  Unsure if this is related.

**Comment by Kevin-Marsh** [comment]
This happens if you have auto smelt on the took that you use to break. The cooking book is created by smelting a book.

**Comment by zrieprakis** [comment]
Ugh.  A random loot diamond axe with that as its only native ability.  Apologies - should have checked that first.
