### ISSUE TITLE
Question with Insanite Bee

### ISSUE THREAD

**Issue by XavoxMaster** [AllTheMods/ATM-9#1686]
Hello guys, I have a question.

I'm trying to make the extreme reactors mod bees to speed up my insane block production. I'm trying to make the insane bee, but I'm having difficulty with the magentite bee, where to make it I have to give a block of magentite to a blutonium bee, and I need a way to make the block of magentite.

Is there any way to do this?
The only way that appears in the JEI is to burn the magentite dust to make ingot, something that cannot be done because there is no way to make the dust.
Another way that appears is with the bees themselves, but I'm trying to make them, right?
Another way would be through creative? (But I don't want to have to resort to that choice).

Anyone with any ideas?

**Comment by GothBoyUK** [comment]
You can adjust the output on the reactor to create blocks rather than liquids. You need to have the correct output ports, it has been months since I did it so can't remember exactly. A quick check on Reddit will bring up posts about it.

**Comment by XavoxMaster** [comment]
> You can adjust the output on the reactor to create blocks rather than liquids. You need to have the correct output ports, it has been months since I did it so can't remember exactly. A quick check on Reddit will bring up posts about it.

Hey man, the scheme of using the reactor's solid port worked. I had done a test before and it hadn't worked. It could be a modpack bug or something like that, it happens to me a lot where some recipes in JEI don't appear.
Thanks man, I was almost giving up.
