### ISSUE TITLE
[Bug]: ME Pattern Provider and Powah's cables

### ISSUE THREAD

**Issue by rueckl** [AllTheMods/ATM-9#1691]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

If I connect an AE2's ME Pattern Provider to a Powah's cable (tried only with spirited), it will fill with something that looks like liquid Forge Energy (FE) and can only be emptied if you break the Pattern Provider.

**Comment by Mitchell5200** [comment]
Not a bug, a newly added mod https://www.curseforge.com/minecraft/mc-mods/applied-flux added a way to store RF in special AE2 cells.

Mod addition was noted in the 0.2.57 changelog.
