### ISSUE TITLE
[Shader Pack] Updated block.properties to include modded foliage

### ISSUE THREAD

**Issue by TakingFire** [AllTheMods/ATM-9#1692]
Hi folks, not a bug, just a tweak for the included shader pack.
A number of months ago when I started a session with my group, I noticed that there was no support for the modded foliage in the shader pack. So, I manually compiled every leaf, flower, sapling, vine, and other blocks into the `block.properties` file so that everything shades and sways properly. It should also resolve some backface issues with Chipped glass.
It can be placed in `shaderpacks > ComplementaryReimagined > shaders` and should update on shader reload.

As the shader pack seems to be acquired automatically I am unsure if this can be incorporated into the modpack. Still, some people may find it useful, so I am sharing it here.

Make sure to remove the `.txt` extension from the filename.
[block.properties.txt](https://github.com/AllTheMods/ATM-9/files/15239708/block.properties.txt)

**Comment by Jmpp2909** [comment]
@Kevin-Marsh  booping this one to you, this might be interesting, or not, idk
