### ISSUE TITLE
.45 Fps killed in jei

### ISSUE THREAD

**Issue by chevr057** [AllTheMods/ATM-9#170]
when opening JEI starting to type @ it drops fps until 0 if no other letters are typed, and each time if left in jei i re opened Jei to FPS drop until @ deleted or more text added, 2 minutes after quick testing with others on server, it crashed and had to restart, maybe related, may not

( happens when even only one character is typed atm not just @)

**Comment by aAndrew3030** [comment]
Are you using the current version of the pack, 0.0.45? If I am remembering correct, a previous version had the EMI mod that caused this issue

**Comment by aAndrew3030** [comment]
Could you provide a log?

**Comment by traxonLp** [comment]
I've noticed this too. It is significant worse when you have the marking active (the double click on the search bar).

I think this is an JEI issue. I'd recommend to report it there so they fix it or optimize it.
