### ISSUE TITLE
[Quests issues]: Can't complete quest Cursed Piramids

### ISSUE THREAD

**Issue by mtashchuk** [AllTheMods/ATM-9#1700]
### Modpack Version

ATM9 NoFrills

### Describe the issue

We play with friends on a server, to not overgrow memory usage we limited borders to 10 000
However, in these borders there is no Cursed Pyramids
So we spawned one in the desert using commands
But spawned structure doesn't give an achievement of finding the pyramid
What should we do to fix this?
![Base Profile Screenshot 2024 05 09 - 12 21 54 47](https://github.com/AllTheMods/ATM-9/assets/100440707/81dfbaa4-6f23-4982-a5ab-24181ff4447f)

**Comment by Jmpp2909** [comment]
Enable editing mode - pencil icon on bottom right
Click the quest
right click the condition, and click Complete
Disable editing mode afterwards

**Comment by TheBedrockMaster** [comment]
Not really an issue with the pack
