### ISSUE TITLE
[Crash]: Research Multiblock crashing with 144 CWU/t

### ISSUE THREAD

**Issue by DeadlySoren** [AllTheMods/ATM-9#1702]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

I saw that there is currently a crash report for the network switches causing crashes so I thought I'd try just connecting it up and just never look at the switch interface.
With 144 CWU/t (5 HPCA's) going through the switch and then into the research multiblock, the game crashes as soon as you try to use the multiblock to create a data orb. You can open the interface just fine.

### Crash Log

https://gist.github.com/DeadlySoren/e0128d239d5fd7a73bea45d0575f33a5

### Latest.Log

https://gist.github.com/DeadlySoren/d3a317f0c4ba86407418aa8b7e3414e3

**Comment by BaoruLee** [comment]
This should be a bug in the GTM  itself. Now that the mod has been updated, just wait for the modpacks author to update it.

**Comment by loving2** [comment]
This has been fixed in GTCEu-Modern and is in latest ATM9 v0.3.5
