### ISSUE TITLE
[Bug]: PIPE capacitance ，you can just see

### ISSUE THREAD

**Issue by lllty48** [AllTheMods/ATM-9#1713]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

![2024-05-15_08 16 51](https://github.com/AllTheMods/ATM-9/assets/130284914/1bb2157d-78f9-434d-a14f-b7c98123a0d5)
![2024-05-15_08 16 55](https://github.com/AllTheMods/ATM-9/assets/130284914/d3128850-9295-4e17-afdd-7c918109a736)
you can see, the difference pipe had the same capacitance. I ve never played MEK, im not sure it's the bug of modpack or MEK.
ATM9's nice, thank you.

**Comment by Jmpp2909** [comment]
Mekanism pipes/cables work in a network, the more pipes/cables are connected, the bigger is the buffer / transfer speed
1 Ultimate cable - 3.27MFE
2 Cables connected - 6.54MFE
3 Cables connected - 9.81MFE

and so on

https://wiki.aidancbrady.com/wiki/Universal_Cable
Read under "Cable Mechanics"
