### ISSUE TITLE
[Bug]: JEI Highlight issue

### ISSUE THREAD

**Issue by eksoul** [AllTheMods/ATM-9#1717]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

JEI Highlight does not grey the text out for a search, I've had this issue when first joining this version of a server even before resource packs and extra mods were added. This makes searching harder because the highlight is barely visible with my bad eyes.

Is there no way to change the color of the highlight to something like yellow on the item?

![javaw_LcMVT9WVj9](https://github.com/AllTheMods/ATM-9/assets/169922577/a04dc667-a914-4e07-a1f6-11cbecaced8c)

**Comment by Jmpp2909** [comment]
Thats not up to ATM
i searched for a config for that, but didnt have luck, 

Gotta ask in 
https://github.com/mezz/JustEnoughItems


(close the issue pls)
