### ISSUE TITLE
stuck on "state transition CONFIG_LOAD running" when attempting to load modpack. 

### ISSUE THREAD

**Issue by Florielles** [AllTheMods/ATM-9#172]
Noticed there had been quite a few posts of the same issue today in the All the mods discord with no resolution posts attached and I am having the same issue. 

Please see attached log hopefully it's useful. https://mclo.gs/NhLQU7x

Thanks kindly.

**Comment by aAndrew3030** [comment]
Check in the config folder to see is the fml.toml file is corrupted. Forge sometimes corrupts this file for whatever reason. You can delete it and let it create a new one on restart to see if it fixes your issue

**Comment by Florielles** [comment]
Tried that just now, same result sadly. Stuck at exactly the same spot.

**Comment by issei5212** [comment]
On config/generatorgalore/generators i`ve duplicate the cooper.json and rename it to lead.json and this fix the bug. But to create a new world you need to install the server and create on the server side, cause there`s a bug that you can`t create a world single player
