### ISSUE TITLE
[Bug]: Quarry Plus Quarries cannot operate within claimed chunks

### ISSUE THREAD

**Issue by sillysimon** [AllTheMods/ATM-9#1725]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

Hi ATM Devs,

I believe, I've found a problem with the quarry plus quarries.

# Problem

When placing a "quarry plus" quarry inside a ftb-chunks claimed chunk, the quarry will not mine. This prevents the quarry from being force-loaded through regular means. This has been tested in the mining dimension with the solid fuel quarry

# Steps to reproduce

1. Claim a chunk
2. Allow All Fake players in your team
3. Place a quarry-plus quarry and its range fully in the claimed chunk
4. Enable it and watch it not mine

# Problem and Fix

Mining in FTBChunks claimed chunks is disabled in the config.

In order to enable it, set `allowWorkInClaimedChunksByFTBChunks` to `true` in the file `config/quarryplus-common.toml`

If you need more info, feel free to ask.
Kind regards,
Simon

**Comment by Jmpp2909** [comment]
That setting will allow  everyone's chunks to be quarried in servers

The fix would be unclaim the area, place and start the chunk destroyer / the quarry, and then Claim + Chunkload, by doing that, it will be automatically allowed to work in that chunk

Also, only claim the quarry itself, the rest doesnt need to be claimed/chunkloaded

**Comment by sillysimon** [comment]
ah, my bad, did not know it would do that, thanks for clarifying
