### ISSUE TITLE
[Bug]: "forges:ores" not working in Export Tag Bus

### ISSUE THREAD

**Issue by xyZANEtv** [AllTheMods/ATM-9#1727]
### Possible Fixes

Yes

### Modpack Version

MineColonies Dimensional Adventure : 204

### What happened?

I'm trying to convert differents ores into one version of themself by exporting everything into Mekanism Oredictionification to simplify export/import process, but unfortunatly the forge:ore don't work
The only thing i can do is to type forge:ores/ +every ores possible in the game

**Comment by Jmpp2909** [comment]
forge:ores/*

" * " means all under that tag
