### ISSUE TITLE
Client Crash by Alchemistry render error

### ISSUE THREAD

**Issue by SpaceMoehre** [AllTheMods/ATM-9#173]
Version: ATM9 0.0.41

What happend: Crafted Nether Star in the alchemistry Combiner. Staying in/Opening the Combiner Menu Crashes the game

Client Error Message:

```
The game crashed whilst rendering screen
Error: java.lang.ClassCastException: class com.smashingmods.alchemylib.api.blockentity.container.WrappedVertexConsumer cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.smashingmods.alchemylib.api.blockentity.container.WrappedVertexConsumer is in module alchemylib@1.0.24 of loader 'TRANSFORMER' @43294e9b; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @43294e9b)
```

(No error message on server)

[crash-2023-07-30_11.45.16-client.txt](https://github.com/AllTheMods/ATM-9/files/12208886/crash-2023-07-30_11.45.16-client.txt)

I'm well aware that this might be caused by alchemistry and not the atm project, but I wanted to raise awareness to this and ask if someone encountered similar errors

**Comment by aAndrew3030** [comment]
You are using a outdated version of ATM9, this was fixed in version .42. Current version is .45

**Comment by SpaceMoehre** [comment]
ok guess this can be closed, stayed on 41, because 42 crashed the server and 45 still screwed some vanilla recipes by gregtech
