### ISSUE TITLE
[Bug]: Gregtech Parallel Control Hatch Breaks Multiblock

### ISSUE THREAD

**Issue by lars1999vk** [AllTheMods/ATM-9#1733]
### Possible Fixes

Yes

### Modpack Version

0.2.59

### What happened?

when you add a Parallel Control Hatch (PCH) to the gregtech multiblocks they stop working. the multiblock stays formed but it does not proces recepies. last version (0.2.58) this was aleady the case for the Advanced Large Chemical Reactor (ALCR) but after updating my world it seems that almost every mutiblock now breaks when using the PHC. i tried every tier of PHC and every configuration in both my updated world and a testworld and both give the same outcome.
without the PCH the multiblocks are not worth it, not sure if this ia a ATM9 bug or a Gregtech bug tho, but for the gregstar these multiblocks are almost mandatory

**Comment by STArkarian** [comment]
Adding on to this, the PCHs work, as long as the value is set to 1. If you set it any higher, you need to have the number of resources available to perform the recipes X times, where X is the value the PCH is set to.

**Comment by SethaWetha** [comment]
> Adding on to this, the PCHs work, as long as the value is set to 1. If you set it any higher, you need to have the number of resources available to perform the recipes X times, where X is the value the PCH is set to.

Can you elaborate? I cannot get my machines to work when setting the value >1. I have more than sufficient resources to perform the recipes.

**Comment by STArkarian** [comment]
From what I can tell, the PCH has been changed from machine global (X recipes of same or different type, where X is the value of the PCH setting) to a global per-recipe basis (It can perform X of ONE recipe, where X is the value of the PCH setting).

Example: I have a large material press with a PCH set to 4. If I did 1, 2 or 3 Tungstensteel plates, the Tungstensteel ingots would sit in the machine. As soon as I sent another one in, it processed all 4 ingots into 4 plates.

**Comment by SethaWetha** [comment]
> Example: I have a large material press with a PCH set to 4. If I did 1, 2 or 3 Tungstensteel plates, the Tungstensteel ingots would sit in the machine. As soon as I sent another one in, it processed all 4 ingots into 4 plates.
I have 1024 Silicon Ingot in my Large Extraction Machine, yet it only performs when the PCH is set to 1. Anything higher and the machine just stops.

**Comment by STArkarian** [comment]
Hmmmmm. Sounds like there may be two separate issues here.

**Comment by lars1999vk** [comment]
> > Example: I have a large material press with a PCH set to 4. If I did 1, 2 or 3 Tungstensteel plates, the Tungstensteel ingots would sit in the machine. As soon as I sent another one in, it processed all 4 ingots into 4 plates.
> 
> I have 1024 Silicon Ingot in my Large Extraction Machine, yet it only performs when the PCH is set to 1. Anything higher and the machine just stops. This is significantly more annoying in my ALCR where I have 512B of Fluorine Gas and Hydrogen Gas. It says it's performing 64 recipes in parallel, but it's just making one bucket of Hydrofluoric Acid at a time.

Exactly this, and some machine like my extractor completely stop working untill you completely remove the PCH.

**Comment by WirtualRC** [comment]
> > Example: I have a large material press with a PCH set to 4. If I did 1, 2 or 3 Tungstensteel plates, the Tungstensteel ingots would sit in the machine. As soon as I sent another one in, it processed all 4 ingots into 4 plates.
> 
> I have 1024 Silicon Ingot in my Large Extraction Machine, yet it only performs when the PCH is set to 1. Anything higher and the machine just stops. This is significantly more annoying in my ALCR where I have 512B of Fluorine Gas and Hydrogen Gas. It says it's performing 64 recipes in parallel, but it's just making one bucket of Hydrofluoric Acid at a time.

Same issue :( Fixes exist?

**Comment by loving2** [comment]
I just tested this on a fresh install of ATM9 0.3.5, and this appears to be resolved. Please reopen the issue if any issues reappear
