### ISSUE TITLE
Generalised End Prediction Quest Mistake

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1737]
### Modpack Version

0.2.59

### Describe the issue

Instead of saying End materials, it says Nether materials.
![2024-05-20_17 58 26](https://github.com/AllTheMods/ATM-9/assets/164738841/945a44b9-5b7f-4a3b-ac22-2bdee15108de)

**Comment by Jmpp2909** [comment]
Should be fixed in the next update

**Comment by TheBedrockMaster** [comment]
Nice :)
