### ISSUE TITLE
Large Digital Storage Quest is optional.

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1738]
### Modpack Version

0.2.59

### Describe the issue

The Quest "Large Digital Storage" in the Chapter 2 questline is optional despite being required for the ATM Star.
![2024-05-20_18 01 37](https://github.com/AllTheMods/ATM-9/assets/164738841/6e1d0b85-2334-4974-97cc-de6ef0d93711)

**Comment by ToshibaEC0Microwave** [comment]
Will no longer be optional!
