### ISSUE TITLE
[Crash]: Crash when entering the world after uptade

### ISSUE THREAD

**Issue by XavoxMaster** [AllTheMods/ATM-9#1740]
### Possible Fixes

Yes

### Modpack Version

0.2.59

### What happened?

When entering the world the game crashes after a while, or when opening the inventory or quests. It seems like it has something to do with the applied or refined system, I have both in the same dimension, but I'm not sure, it's the third attempt, I'll attach the crash reports.

### Crash Log

https://gist.github.com/XavoxMaster/b4f3fb32eb463a095ead6067ca732073

**Comment by Alacho2** [comment]
Seeing the same

**Comment by Mitchell5200** [comment]
Looks like it's Xnet crashing there, should be fixed in the next pack update

**Comment by XavoxMaster** [comment]
Hello guys, it looks like the problem has been resolved with the new pack update. I liked that the authors are updating the pack a lot.
