### ISSUE TITLE
[Bug]: FTB Quests fehlen und Barrenrezepte

### ISSUE THREAD

**Issue by MarcelSK** [AllTheMods/ATM-9#1748]
### Possible Fixes

Yes

### Modpack Version

1.20.1

### What happened?

Ich habe mit dem Serverpack von ATM9 / No Frills eine Server am laufen aber die Quests sind nicht da ( Nur leeres Questbuch ).
Außerdem habe ich einige Erze/Barren wie Invar oder Lumium zb wo ich keine möglichkeit habe laut Rezepten diese herzustellen. Wenigstens kann ich hier Glas auf normale weise herstellen im gegensatz zum ATM9 Voll Paket wo das nicht geht da es kein rezept mit Sand gab.. Ich hoffe es ist möglich mir da zu halfen denn ich verliere langsam die Lust am Lösung suchen..

**Comment by Mitchell5200** [comment]
sounds (with a translation) like an install issue, Please reinstall the server, and copy all folders from the released `Server-Files .zip` to the server
Additional server install instructions below
https://allthemods.github.io/alltheguides/help/server/
https://allthemods.github.io/alltheguides/help/server/#updating

**Comment by MarcelSK** [comment]
I have completely reinstalled everything on the server of 4NetPlayers but still the same errors are present that the quest book is empty and also some bar recipes are not there. I also looked again at the server data and there was also all the data.

**Comment by Torben4** [comment]
hey, 
when dicussing this issue in the dc due to another person not beeing able to smelt sand into glass the info got postet, that GT has a config for harder recepies including glass production. maybe thats something u could take a look at to try solving one part of the problem
