### ISSUE TITLE
[Bug]: Neutronium Bee not working on Apiary Mk II

### ISSUE THREAD

**Issue by guimas** [AllTheMods/ATM-9#1752]
### Possible Fixes

Yes

### Modpack Version

0.2.59

### What happened?

The "Not a Neutronium Bee" works perfectly on the advanced apiary, but to make it work on GT's Apiary Mk II you have to rename it with a name tag to "Neutronium Bee". As far as I tested, several other bees worked normally on GT's Apiary.

**Comment by loving2** [comment]
This has been fixed as of ATM9 v0.3.5

**Comment by frsfdc** [comment]
Um,how can I fix it?I'm playing on latest version on a server,and it doesn't work

**Comment by frsfdc** [comment]
Nvm,naming the bee to "Not a Neutronium Bee" fixed it
