### ISSUE TITLE
[Crash]: Server keeps crashing when flying around with jetpack; timeout due to watchdog

### ISSUE THREAD

**Issue by FreshDumbldore** [AllTheMods/ATM-9#1769]
### Possible Fixes

Yes

### Modpack Version

0.2.59

### What happened?

Basically i run a server for a few friends and myself. But i started to experience a "quite" annoying bug. When i start to fly around the world (i have generated 1000 chunks around 0 0 0 before we started via command) at some point the world doesn't load in anymore and i either have to wait for like a few minutes at a time (which is quite annoying when over water) or the whole server crashes with watchdog saying: _one tick took more than 60 seconds_ (i know 60 might be a bit short for modded servers but oh well). Even after increasing that to 180 seconds the same issue still persists. 
I also tried with a complete new map just to see if i can replicate it without pre-generating chunks but the same happens. After some time flying around the server stops loading and either crashes or loads after like 5 minutes.

I'm gonna add that i use pterodactyl as the server manager. Made a forge server and extracted the server files into it. 
Should i possibly change to a windows server or run it locally?

### Crash Log

https://gist.github.com/FreshDumbldore/91f70e89cb8f898ccab976efe80447a9

### Latest.Log

https://gist.github.com/FreshDumbldore/c9be0724884afbf7a67c2d85a4c414a6

**Comment by TheSnowyChickens** [comment]
Fresh D, I experience the same bug in 0.2.60 on a server and in another modpack (skyblock, with far less mods), I could not figure out which mod create this bug and at all it's totally weird and annoying. :(

**Comment by FreshDumbldore** [comment]
Someone told me it is probably due to the deep dark and the standard view- and sim-distance of 10 in the server.properties :/

**Comment by langbart96** [comment]
Do you use AMP for server management? If so then disable "Use Synchronous IO" :)

**Comment by FreshDumbldore** [comment]
nope. as mentioned above i use Pterodactyl

**Comment by langbart96** [comment]
> nope. as mentioned above i use Pterodactyl

Maybe there is a similar option there that produces the error.
![Unbenannt](https://github.com/AllTheMods/ATM-9/assets/172848834/c4c48dbe-c825-4f1e-a29d-ae6fa076446e)

**Comment by FreshDumbldore** [comment]
![ATM1](https://github.com/AllTheMods/ATM-9/assets/21024850/2f380fc2-7374-4ef1-be73-69975204a849)
![atm2](https://github.com/AllTheMods/ATM-9/assets/21024850/8c0e1bed-292d-4f84-bf32-bd0fb3797374)
![atm3](https://github.com/AllTheMods/ATM-9/assets/21024850/fe973adc-13d1-47e1-afa2-7a4d3356f31f)
No information on synchronous IO, also nothing on google indicating anything...

**Comment by FreshDumbldore** [comment]
but the thing is... i even had the server running on my unraid maschine as it's dedicated docker container and it had the same issues as now

**Comment by langbart96** [comment]
> but the thing is... i even had the server running on my unraid maschine as it's dedicated docker container and it had the same issues as now
> 
> also i might get the feeling that it has to do with some ryzen cpu's creating this issue as someone mentions [here](https://github.com/AllTheMods/ATM-9/issues/1533) the same issues with a ryzen 7 3700x and i am on a ryzen 9 3900x

Haha that's my work account, I didn't see that it was logged in. So it works for me on Ryzen 7 3700x and 3900x without any problems, even on Unraid.
It's really just a matter of settings, the only question is where.

**Comment by FreshDumbldore** [comment]
> > but the thing is... i even had the server running on my unraid maschine as it's dedicated docker container and it had the same issues as now
> > also i might get the feeling that it has to do with some ryzen cpu's creating this issue as someone mentions [here](https://github.com/AllTheMods/ATM-9/issues/1533) the same issues with a ryzen 7 3700x and i am on a ryzen 9 3900x
> 
> Haha that's my work account, I didn't see that it was logged in. So it works for me on Ryzen 7 3700x and 3900x without any problems, even on Unraid. It's really just a matter of settings, the only question is where.

Let me ask you this:
How many cores are you giving your server?
Right now mine has 12 and is liek using not even one to it's fullest. I also experimented with different java versions and arguments. still nothing in regards to the server running better.

**Comment by langbart96** [comment]
> > > but the thing is... i even had the server running on my unraid maschine as it's dedicated docker container and it had the same issues as now
> > > also i might get the feeling that it has to do with some ryzen cpu's creating this issue as someone mentions [here](https://github.com/AllTheMods/ATM-9/issues/1533) the same issues with a ryzen 7 3700x and i am on a ryzen 9 3900x
> > 
> > 
> > Haha that's my work account, I didn't see that it was logged in. So it works for me on Ryzen 7 3700x and 3900x without any problems, even on Unraid. It's really just a matter of settings, the only question is where.
> 
> Let me ask you this: How many cores are you giving your server? Right now mine has 12 and is like using not even one to it's fullest. I also experimented with different java versions and arguments. still nothing in regards to the server running better.

The server has access to all cores. In Unraid the load is usually at 10%. I also used "Crafty Controller" to test it and had the same error, but couldn't figure out what the problem was.

**Comment by FreshDumbldore** [comment]
you think it might me a problem with amd cpu's?

**Comment by FreshDumbldore** [comment]
It was apparently a disk issue... was using it on my slower hdd's and not on my cache drives. now it works flawlessly.
