### ISSUE TITLE
[Bug]: Mega Rusion Reactor Not Working

### ISSUE THREAD

**Issue by RajBaj1** [AllTheMods/ATM-9#1770]
### Possible Fixes

Yes

### Modpack Version

0.2.60

### What happened?

Mega fusion reactor still isnt able to make star matter plasma, freezes during recipe duration and never completes. Issue carrying over from 0.2.59, still unable to make MUO and Max energy hatches because of this.

**Comment by guimas** [comment]
Mine can't complete Argon Plasma too

**Comment by RajBaj1** [comment]
Works with Max Energy Hatches, has to be cheated in however.

**Comment by loving2** [comment]
I've tested this on a fresh install of ATM9 v0.3.5 and it is working. Do note that there is a fusion "Heat" requirement of 600M EU for Star Matter Plasma. If the Mega Fusion Reactor doesn't have enough energy stored it cannot start the recipe.
