### ISSUE TITLE
[Quests issues]: Reconstruct task line of Gregtech

### ISSUE THREAD

**Issue by FwFeiVan** [AllTheMods/ATM-9#1772]
### Modpack Version

0.2.60

### Describe the issue

I've played Gregtech for over 1000h and I think the task line of Gregtech part in ATM9 leads a wrong direction.
The tasks use circuit to separate different Voltage Tier but it is wrong and the correct way is by materials that make up corresponding machine casings. And here's my suggestions:
1. Add the checkpoint of electric motor/pump/piston, conveyor module, emitter, sensor and robot arm. also Add optional tasks of field generator for each tier.
2. Tasks of:
Steam Age: Introduce basic concepts of GT like ore production and overlock logic.
LV Tier: Finish the LV with aluminum ingot(though it can be obtained without EBF) but not the MV circuit. Add the checkpoint of multi smelter because it will be stronger than mek's ultimate smelting factory soon.
MV Tier: Begin with aluminum ingot and Finish it with stainless steel. 
HV Tier: 5 important things we must done at HV is oil production, cleanroom, freezer, LCR and titanium line. Add them to the task line and maybe remind that titanium need to be automatically and LCR has perfect overlock. Additionally, the micro processor circuits, form MV to IV, can be finished at HV Tier. Finish it with titanium ingot.
EV Tier: Add the tungsten production line to task line and finish EV with tungstensteel ingot. Platinum production should be finished before LuV, maybe you can add a whole production line in IV's task. Nano processor circuits can be finished at EV, so add them till the mainframe(LuV circuit). Also add task of RTM coils and rareearth production line.
IV Tier: Alloy blast smelter and multiblock machines can be done at IV. After ABS is the quantum processor circuit and assemble line. After the assemble line is data bank. Finish it with Pd3Rh ingot. 

At EV-IV, we must finish several chemical production line including two rubber, PBI, epoxy, polyphenlene. It's nice that they're already at IV's task line. For IV+ Tier, we only need assmebler of small machines and every tier need checkpoints of energy input hatch and parallel hatch(Yes, we can obtain IV parallel hatch at IV).
LuV Tier: The Mk1 fusion to produce europium, the superconduciting coil, the active transformer(it's unnecessary because of the infinity FE), research station and the HPCA. Add the naquadah production line before the HPCA and research station. Add naquadah  coils, trinium coils and URhNq2 ingot for research station's needs. Besides, All crystal processor circuits can be produced at LuV. End LuV with naquadah alloy. 
ZPM Tier: tasks of MK2 fusion to produce Am, Ds, Dr and tritanium. Add the task of tritanium coils. Bacteria production can be finished at ZPM, so add the wetware processor circuits(except mainframe because it needs UV) to task line.
UV Tier: we can end the game at UV Tier. UHV is unnecessary.

3. Add some suggestion of how to share blocks when bluid a multiblock machine, of how to avoid FPS/TPS decrease by replacing pipes by AE subnetwork. Here are some examples from Gregtech Leisure that I'm playing now:
![LEBF](https://github.com/AllTheMods/ATM-9/assets/159519096/dbce625f-b5b6-4df0-b951-9dc17067b6e4)
Quadruplex EBFs

![ABF](https://github.com/AllTheMods/ATM-9/assets/159519096/1dbbcbef-d391-4cd5-92b5-08043c59f705)
6x Quadruplex ABFs

![CR](https://github.com/AllTheMods/ATM-9/assets/159519096/6704585e-0f00-4f85-bc27-d976fd6781cc)
Cleanroom with 4LCR 3Large laser 4Large Cutter 4Large Circuit Assembler in it

![YM](https://github.com/AllTheMods/ATM-9/assets/159519096/fa9112ec-007c-40dd-8886-8ec5d9e6db6f)
12x Large extruder

![LA](https://github.com/AllTheMods/ATM-9/assets/159519096/28f954c9-698b-4a00-a859-ac594f346070)
Liquid Air distilling

**Comment by TheBedrockMaster** [comment]
Feel free to change them yourself and put it on GitHub.
