### ISSUE TITLE
[Bug]: Mjolnir when put into apotheosis reforging table crashes the game.

### ISSUE THREAD

**Issue by Meowmer420** [AllTheMods/ATM-9#1774]
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

Putting Mjolnir from botania into apotheosis reforging table crashes the game. Only crashes your game, not the server.

![2024-06-01_17 40 57](https://github.com/AllTheMods/ATM-9/assets/120033373/6731a22f-982a-4912-a921-5972c87ca1ce)

### latest.log

<script src="https://gist.github.com/Meowmer420/2f154411be4bd6cb7655e25b08f24d99.js"></script>

**Comment by Mitchell5200** [comment]
Fixed in pack version 0.2.59, by blacklisting the mjolnir from the reforging system, it's a bug that was supposed to be fixed by both devs, (according to the information i was given)
