### ISSUE TITLE
[Bug]: [GTCEuM] The Micro Universe Orb cannot be formed.

### ISSUE THREAD

**Issue by cjx2154148** [AllTheMods/ATM-9#1782]
### Possible Fixes

Yes

### Modpack Version

0.2.60

### What happened?

https://github.com/AllTheMods/ATM-9/issues/1618
My situation is much like his. After placing the final block, blocks stop droping anything, and I can't interact with anything either.
Because it does not cause any crash, and the game cannot be closed nommally, I have to kill it with task manager every time.
The game isn't frozen, FPS also shows well, before the the final block is placed, everything goes ok.

### latest.log

https://gist.githubusercontent.com/cjx2154148/4eb3521fc2fe461d07f5805a055ae60e/raw/dfb524e25b5031bd75709ab003f7840b6ff42d92/gistfile1.txt

**Comment by cjx2154148** [comment]
Place all the blocks but the last one, quit game and reload it, place the last block about 1 hour later, the MUO can be formed successfully.
I don't know if it is a bug or something else.

**Comment by loving2** [comment]
I cannot recreate this issue on a fresh installation of ATM9 v0.3.5

**Comment by yukiryo** [comment]
Same issue occurs with 1.0.4
