### ISSUE TITLE
[Quests issues]: Infinity Pipe Upgrade uncraftable

### ISSUE THREAD

**Issue by BlackStar7713** [AllTheMods/ATM-9#1783]
### Modpack Version

0.2.60

### Describe the issue

Hi, In a recent update the recipe for infinity pipe upgrades from Pipez was removed #1527
There is however a quest in Chapter 3 to make it.
Will the quest be changed, or will the upgrades come back?

**Comment by TheBedrockMaster** [comment]
This can now be closed. The quest is gone.
