### ISSUE TITLE
[0.0.45] A fatal crash with a mix of EnderIO and Mahou

### ISSUE THREAD

**Issue by Asmodeus-MKcrafter3** [AllTheMods/ATM-9#179]
I am not sure, but I think having a working(powered) EnderIO mob spawner crashes the game(it freezes entities[the player can still move] and you can no longer interact with the world) when I close the world it stays on the SAVING screen and freezes, the only option I found is to task manager it into a forced exit.  It crashes when the first zombie dies(I have a Mahou Tsukai life drain barrier)(might be because of the vacuum chest???)

**Comment by stepsword** [comment]
If you can replicate it can you post your latest.log from your logs/ folder after getting it to happen again?

**Comment by Asmodeus-MKcrafter3** [comment]
Since it doesn't crash but freezes I had to force close it with task manager.(the world doesn't save and gets reverted a few minutes). It froze around 45 seconds after I joined the world.

[latest.log](https://github.com/AllTheMods/ATM-9/files/12238284/latest.log)

[debug.log](https://github.com/AllTheMods/ATM-9/files/12238306/debug.log)

[2023-08-02-2.log](https://github.com/AllTheMods/ATM-9/files/12238308/2023-08-02-2.log)

https://drive.google.com/file/d/1D72-RI80J69rmSjqoAU3ekw66UxVYvQh/view?usp=sharing
