### ISSUE TITLE
[Quests issues]: Engineer's Goggles Quest Misspelling 

### ISSUE THREAD

**Issue by dk0314** [AllTheMods/ATM-9#1792]
### Modpack Version

0.2.60

### Describe the issue

In the description of the Engineer's Goggles quest from Create, there is a typo saying "contrations" instead of presumably "contraptions."
![image](https://github.com/AllTheMods/ATM-9/assets/57114128/ab294c9c-c6bf-4688-be15-ffaba3ee4cf7)

**Comment by ToshibaEC0Microwave** [comment]
Was a problem in sky block as well but will be fixed in next update for both!

**Comment by TheBedrockMaster** [comment]
Fixed, this can now be closed.
