### ISSUE TITLE
[Quests issues]: Reinforced Deorum Sword cannot be craft.

### ISSUE THREAD

**Issue by Kiriao** [AllTheMods/ATM-9#1796]
### Modpack Version

0.2.60

### Describe the issue

Hi,

trying to complete this "basic tools" quest but it seem that Reinforced Deorum Sword have no recipe. how do i obtained it to complete the quest. my OCD is killing me x.x

**Comment by TheBedrockMaster** [comment]
It seems like you mentioned this again in another issue?

**Comment by Kiriao** [comment]
Dont if it meant to uncraftable or get from somewhere else. Need answer if it really cannot obtain.

The 2nd post it remove it from quest

**Comment by TheBedrockMaster** [comment]
Yeah, it's uncraftable on the mod's end I believe

**Comment by EyrisMineQueen** [comment]
Same problem here. I'm playing hardcore, all quests challenge and still need this sword :/

**Comment by ToshibaEC0Microwave** [comment]
Yall did not read the part of how you're not supposed to complete this quest page 😂 I'm just kidding it'll be removed for next update

**Comment by TheBedrockMaster** [comment]
Optional means nothing to us

**Comment by TheBedrockMaster** [comment]
This can now be closed.
