### ISSUE TITLE
Biomes of plenty and probably terralith aren't commonly generating some required blocks

### ISSUE THREAD

**Issue by Nukiloco** [AllTheMods/ATM-9#180]
I don't know if this is just bad seeds I been getting, but in all my worlds I been going through, andesite, granite, and other stone variants seem to be rare in this modpack. Usually it requires me about to travel around 5000 blocks or more just to find the resources I need. I know that biomes of plenty can generate those blocks in some specific biomes though I assume to bad luck I been not getting those biomes at all.

Is it possible to make it where blocks like andesite, granite, and diorite spawn in any stone layer? Thanks!

**Comment by HPTD1** [comment]
I noticed andesite as well, but later found tons of it. There are unlucky chains of biomes where you cant find certain stones for a long time, but they are still there. More biome types make certain biomes much more rare, for example finding sunflowers for my colony took a while as well. I don't think its really an issue, its a noticable effect from the different biome mods however.
