### ISSUE TITLE
[Quests issues]: 2 Quest Item unable to Craft/Obtain

### ISSUE THREAD

**Issue by Kiriao** [AllTheMods/ATM-9#1805]
### Modpack Version

0.2.60

### Describe the issue

Able to update the quest book cuz there 2 item seem unobtainable (Infinity Pipe Upgrade from Chapter 3: Creative) & (Reinforced Deorum Sword from Basic Tools)

**Comment by ToshibaEC0Microwave** [comment]
Both will be removed for next update

**Comment by TheBedrockMaster** [comment]
This can now be closed.
