### ISSUE TITLE
"Aether and Undergarten Diamond Swords" Quest Typo

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1808]
### Modpack Version

0.2.60

### Describe the issue

The quest "Aether and Undergarten Diamond Swords" should be "Aether and Undergarden Diamond Swords".
![2024-06-10_20 06 11](https://github.com/AllTheMods/ATM-9/assets/164738841/231b0a0a-9c4a-479e-b899-e30a6a9b28ea)

**Comment by ToshibaEC0Microwave** [comment]
The T will be a D
