### ISSUE TITLE
[Crash]: ServerVersion didnt startup

### ISSUE THREAD

**Issue by nhet** [AllTheMods/ATM-9#1809]
### Possible Fixes

Yes

### Modpack Version

0.20.6

### What happened?

I have downloaded ServerVersion0.20.6.zip and started up by using startserver.bat.
Some files were downloaded or generated automaticly. 
So far everything is ok. However, starting the server does not work.

Win10
java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

### Crash Log

https://gist.github.com/nhet/735570e5029106c546ec16aa39b89a2e

### Latest.Log

https://gist.github.com/nhet/65044da3120a0f7feeec5215d1599d25

**Comment by Mitchell5200** [comment]
You need to use Java 17, not 22, for MC 1.20.x
