### ISSUE TITLE
mods suggestions

### ISSUE THREAD

**Issue by lebarjodu50** [AllTheMods/ATM-9#181]
Hello the ATM team is it possible to add these mods please ? 
[immersive aircraft](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[create immersive aircraft](https://www.curseforge.com/minecraft/texture-packs/create-immersive-aircrafts-resource-pack)
[progressive bosses](https://www.curseforge.com/minecraft/mc-mods/progressive-bosses)
[enhanced ai](https://www.curseforge.com/minecraft/mc-mods/enhanced-ai)
[alex's mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[advent of ascension](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine)
[shield expansion](https://www.curseforge.com/minecraft/mc-mods/shield-expansion)
[create : structures](https://www.curseforge.com/minecraft/mc-mods/create-structures)
[create planetary tweaks](https://www.curseforge.com/minecraft/mc-mods/create-planetary-tweaks)
[serene seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
Thank you for all these extremely good modpack and all the hours i could play on.

**Comment by beamer91** [comment]
This is in the wrong place. https://github.com/AllTheMods/ATM-9/issues/1 for suggestions
