### ISSUE TITLE
[0.0.45] EvilCraft Dark Ore rarity

### ISSUE THREAD

**Issue by ScoopMcGoo** [AllTheMods/ATM-9#182]
I have noticed this myself and have heard others mention it too but dark ore from EvilCraft seems to be exceptionally rare in ATM9. I have dug out multiple chunks from -59 to 66 and haven’t seen one dark ore.

Is Dark Ore supposed to be nearly nonexistent rendering EvilCraft almost useless? Or is this a bug?

I’ve tested in Biomes o’ Plenty biomes as well as vanilla minecraft biomes.

**Comment by DerpyFrood0421** [comment]
I'm seeing the same issue.  From my understanding, it's supposed to be same frequency as redstone but definitely seems MUCH MUCH rarer. I wonder if some other oregen is overwriting spots where it would otherwise spawn...

**Comment by ShadedPL** [comment]
Yeah the rarity is just too rare, especially if it's one of the first items you begin the mod with

**Comment by TheBedrockMaster** [comment]
Are you still having trouble finding lots of the ore?

**Comment by Mydayyy** [comment]
Running into the same issue. JEI doesnt list Dark Ore in World Gen. Spend about 30 minutes Shapeless Ultimining in the Overworld and Mining Dimension. Not a single Dark Ore. Guess I'll resort to creative for this one
