### ISSUE TITLE
"Mekanism and Undergarden Iron Pickaxes" Quest Typo

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1841]
### Modpack Version

0.2.61

### Describe the issue

The quest "Mekanism and Undergarten Iron Pickaxes" should be "Mekanism and Undergarden Iron Pickaxes", t to d.
![2024-06-23_08 26 24](https://github.com/AllTheMods/ATM-9/assets/164738841/ca11d721-f80e-4cc8-bc92-94f76bf43801)

**Comment by ToshibaEC0Microwave** [comment]
Must have missed that one when fixing the sword one. Will no longer be missed though!
