### ISSUE TITLE
"Mekanism: Reactors" instead of "Mekanism: Advanced"

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1842]
### Modpack Version

0.2.61

### Describe the issue

The Quest "Advanced Mekanism" in the "Mekanism" Chapter says to check out the "Mekanism: Reactors" Chapter when it means "Mekanism: Advanced" Chapter.
![2024-06-23_08 39 49](https://github.com/AllTheMods/ATM-9/assets/164738841/34ba0a65-05e9-41b7-832c-91ba321df101)

**Comment by ToshibaEC0Microwave** [comment]
Now to be advanced
