### ISSUE TITLE
"Chemical Infuser" Quest Typo

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1843]
### Modpack Version

0.2.61

### Describe the issue

The second "Hydrogen" is spelt "Hyrdogen".
![2024-06-23_08 42 59](https://github.com/AllTheMods/ATM-9/assets/164738841/c6bfc127-6dab-4740-8757-19bf3fbd5e1a)

**Comment by ToshibaEC0Microwave** [comment]
Both will now be hydrogen
