### ISSUE TITLE
"All The Translations" Quest Format Error

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-9#1844]
### Modpack Version

0.2.61

### Describe the issue

Invalid Formatting in the "All The Translations" Quest.
![2024-06-23_07 48 03](https://github.com/AllTheMods/ATM-9/assets/164738841/008c3fc7-a9ee-40bb-be91-7c233d65cde5)

**Comment by ToshibaEC0Microwave** [comment]
A 2 after & was missed but is now in there
