### ISSUE TITLE
[Bug]: Cant autocraft Essences with master infusion crystal (Mystical Agriculture + Refined Storage)

### ISSUE THREAD

**Issue by TimelessPotato** [AllTheMods/ATM-9#1861]
### Possible Fixes

Yes

### Modpack Version

.2.61

### What happened?

![image_2024-06-27_200933049](https://github.com/AllTheMods/ATM-9/assets/146679874/36edb7c8-c550-4027-a030-f8daff2ecd63)
not allowing to auto craft any essence, I assume this is a bug but I don't really know

**Comment by TheBedrockMaster** [comment]
This isn't a bug, this is just RS being RS.

**Comment by TimelessPotato** [comment]
> This isn't a bug, this is just RS being RS.

any work around?

**Comment by TheBedrockMaster** [comment]
Use RFToolsStorage, there's a quest about it in the Mystical Agriculture Quest Chapter.

**Comment by TimelessPotato** [comment]
> Use RFToolsStorage, there's a quest about it in the Mystical Agriculture Quest Chapter.

**Comment by TheBedrockMaster** [comment]
There might not be that quest in ATM9, I'll look into it.
