### ISSUE TITLE
[0.0.46] Grains of Infinity Seeds recipe for Botany Pots missing

### ISSUE THREAD

**Issue by guhler** [AllTheMods/ATM-9#187]
In case this is not intentional, there is no recipe for the Grains of Infinity Seeds(Mystical Agriculture) in Botany Pots/Hopper Botany Pots.

**Comment by aAndrew3030** [comment]
The EnderIO seeds were just added to Mystical Agriculture. You will need to wait for Botany Pots to add it to the mod, or ATM to add it once Kubejs is updated to 1.20.1. Alternatively Botany Pots includes support for adding seeds threw Craftweaker or datapacks, with links on how to do that on there curseforge page
