### ISSUE TITLE
[Bug]: Traveler's Backpack missing after death even though it was souldbound

### ISSUE THREAD

**Issue by au-wap** [AllTheMods/ATM-9#1877]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

I died and when I retrieved my grave I got back everything but my Traveler's Backpack. I would also like to mention that it was tombstone soulbound and it still was missing.

**Comment by efegue** [comment]
Could you respond to this account. The one a made the post with is a work account.
