### ISSUE TITLE
[Quests issues]: mystical agriculture starting quest not completing

### ISSUE THREAD

**Issue by nanaki234** [AllTheMods/ATM-9#1880]
### Modpack Version

1.0.7

### Describe the issue

on the mystical agriculture quest line, the 20x soul sand quest isn't completing, I have had the items in my inventory and there is a dark tick next to the quest to say its complete but cannot be claimed yet. there are no dependencies for this quest so unsure as to why this isn't completing. screenshot attached
![2024-07-04_13 13 11](https://github.com/AllTheMods/ATM-9/assets/69122865/28fa2866-0fc1-478c-9dd7-0a78292beeb5)

**Comment by TheBedrockMaster** [comment]
Wrong Git: https://github.com/AllTheMods/All-the-mods-9-Sky
