### ISSUE TITLE
[Bug]: Elytra Slot Missing

### ISSUE THREAD

**Issue by bcrotty** [AllTheMods/ATM-9#1883]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

I see that the mod Elytra Slot is in the pack, but there doesn't seem to be a separate elytra slot, which would be nice so I don't have to pick between a backpack and an elytra. Is the mod not working, or am I not understanding something?

**Comment by Mitchell5200** [comment]
https://github.com/illusivesoulworks/elytraslot/issues/106#issuecomment-2381086621
> For clarification, the Back slot _is_ the slot used for elytra in this mod (at least in Curios). There is no dedicated slot for only elytra.
