### ISSUE TITLE
[Bug]: Compressed cobblestone recipe issue

### ISSUE THREAD

**Issue by dhasial** [AllTheMods/ATM-9#1889]
### Possible Fixes

Yes

### Modpack Version

1.0.7

### What happened?

If you put 9 cobble in the crafting table to make compressed cobble, it makes the AllTheCompressed variant instead of the Ex Deorum variant. For some reason, this AllTheCompressed variant only produces a single, uncompressed gravel when crushed with the compressed hammer, regardless of the level of compression. 

What I expected (and what happened in older To The Skies) is that you'd put compressed cobble in, and get the same amount of compressed gravel out. I'm pretty certain that this current behaviour is unintended.

### latest.log

https://gist.github.com/dhasial/cb45719c2575659343e897239c37830c

**Comment by TheBedrockMaster** [comment]
It turning in the ATC compressed cobble is intentional, the rest seems to be a bug.

**Comment by dhasial** [comment]
I should mention that the Ex Deorum variant behaves normally, producing compressed gravel as expected.

**Comment by TheBedrockMaster** [comment]
Also wrong Git: https://github.com/AllTheMods/All-the-mods-9-Sky
