### ISSUE TITLE
[Quests issues]: GregTech ZPM Energy Hatch quest

### ISSUE THREAD

**Issue by CodeMastr3** [AllTheMods/ATM-9#1890]
### Modpack Version

0.2.61

### Describe the issue

As it stands just doing what the quests ask it is impossible to complete this quest as you need to go into the research station which means you also need the HPCA. The HPCA portion isn't intuitive as being needed and at this point I still can't get the research station to research. I think this should be added as a part of the prereqs to the ZPM Energy Hatch quest

**Comment by TheBedrockMaster** [comment]
These quests were made before that mechanic existed, these will be updated at some point.
