### ISSUE TITLE
[Bug]: Can't build Immersive Engineering Pumpjack

### ISSUE THREAD

**Issue by 5thWolf** [AllTheMods/ATM-9#1897]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

There is no "Steel Block" available in Immersive Engineering to build the Pumpjack like the mod requires. It is missing.
The Steel Blocks from other mods do not work either.

**Comment by Mitchell5200** [comment]
ATO steel blocks should work fine, However, the Pumpjack is from [Immersive Petroleum](https://www.curseforge.com/minecraft/mc-mods/immersive-petroleuml), and that mod has not been updated to 1.20.1, and is therefore not in atm9.
