### ISSUE TITLE
[Crash]: Exit Code 1

### ISSUE THREAD

**Issue by R2D2Masterr** [AllTheMods/ATM-9#1901]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

My buddies and I keep having an issue. His is that he can't launch the modpack at all and gets an Exit Code 1, I can play for a little, but I end up crashing with Exit Code 1. Any thoughts?
I'm more worried about my buddy. He has done just about everything he can. He has uninstalled everything related to minecraft and reinstalled the mod pack, wont launch. Updated graphics drivers, Java, downgraded drivers and java. Nothing is working. Other launchers like ATLauncher will not work

### Crash Log

https://gist.github.com/R2D2Masterr/ead9d89a6b201e83e27b009c7c48e9dd

**Comment by PlatinumMicah** [comment]
we're having that same issue, though for us it never gets past the launcher, it'll load up the game with the red screen where it's loading the mods and then a few seconds into loading it will crash. if this gets fixed please let me know

**Comment by Koupius** [comment]
With there being only one crash log here it's hard to say if you and your friend are having the same issue. It sounds like you are having a memory leak in which case I recommend using the recommended JVM Args and installing memoryleakfix from Modrinth. In the log itself it mentions a keybind event not functioning correctly relating to Gregtech. Regardless, please post another crash report and specify which one is yours and which is your friend's.

**Comment by Mitchell5200** [comment]
@vladmw5 that's the AMD crash there, fix --> https://github.com/AllTheMods/ATM-9/issues/211#issuecomment-1671402423

**Comment by R2D2Masterr** [comment]
It worked

**Comment by R2D2Masterr** [comment]
It worked, thank you.
