### ISSUE TITLE
 [Bug]: 2 Jungle Slaps craft to Jungle Log

### ISSUE THREAD

**Issue by MatteoNiem** [AllTheMods/ATM-9#1907]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

If you craft to jugle slaps in a crafting table you receive jungle logs and not planks

**Comment by The-Final-Empire-Of-Dogs** [comment]
this works for every vinnila log. also in 0.3 (maybe 0.2.61) you can use polymorph to make unlimited aluminium buzsaws
