### ISSUE TITLE
[Bug]: Gregmachines Flux Network problem

### ISSUE THREAD

**Issue by MaGeBZz** [AllTheMods/ATM-9#1909]
### Possible Fixes

No

### Modpack Version

0.2.61

### What happened?

If I wanna charge gregtech machines sometimes they will work with flux network and sometimes they can't get enough energy from the flux network although there is enough energy for that
I guess it has to do with the amp system in greg but can't help with that dev-wise but wanna report it at least

**Comment by Pumpkin7266** [comment]
@Mitchell5200 I've been using flux networks a lot both with gregtech 1.3.1 and with 1.4. and i've had no issue
