### ISSUE TITLE
'Move item' button disappearing from crafing tables attached to stoegae. [Bug]: 

### ISSUE THREAD

**Issue by Burjo83** [AllTheMods/ATM-9#1917]
### Possible Fixes

Yes

### Modpack Version

atm9sky-1.0.9

### What happened?

Not sure f this is intended or a bug.
Crafting Station Crafting tables lose the ability to "move item" to grid button if they are attached to a Chest. It appears it only has a bookmark this recipe button. 
Tested with crafting tables not attached to storage and the button has returned.

**Comment by TheBedrockMaster** [comment]
9sky has it's own repo: https://github.com/AllTheMods/All-the-mods-9-Sky :)

**Comment by Burjo83** [comment]
Thanks,
