### ISSUE TITLE
[Crash]: GregTechCEU Crash

### ISSUE THREAD

**Issue by Yabukiq** [AllTheMods/ATM-9#1919]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

When opening creative tab it's crashing.

### Crash Log

https://gist.github.com/Yabukiq/179237de1aeba3ad7aeb2c091e5b087a

**Comment by loving2** [comment]
This appears to be fixed in latest, but please reopen if it is still happening!
