### ISSUE TITLE
[Quests issues]: "Fuel for our Furnace"

### ISSUE THREAD

**Issue by garecrow** [AllTheMods/ATM-9#1931]
### Modpack Version

0.3.0

### Describe the issue

The quest book instructs you to craft tiny charcoal by deconstructing 1 charcoal in the crafting table, but this recipe gives you black dye, not tiny charcoal. there is no way to get the tiny charcoal

**Comment by ToshibaEC0Microwave** [comment]
When you craft a switch button will appear above the recipe to change it to craft Tiny Charcoal.
