### ISSUE TITLE
[Quests issues]: Ars Nouveau Mage's Spell Book 100%, can't claim

### ISSUE THREAD

**Issue by shesotoxxic** [AllTheMods/ATM-9#1934]
### Modpack Version

0.2.60

### Describe the issue

![2024-07-28_11 29 40](https://github.com/user-attachments/assets/ad311f54-f3dd-4226-a71e-0b8227329bf8)

I have two of them in my inventory, not my backpack, and cannot claim this quest.

**Comment by shesotoxxic** [comment]
I've never done this before, so apologies if I've not given enough info.  Please let me know what else is needed.

**Comment by shesotoxxic** [comment]
![2024-07-28_11 32 47](https://github.com/user-attachments/assets/586c83b9-6d43-4bfb-9297-4ef944e59764)

**Comment by shesotoxxic** [comment]
I was just able to complete this by going in to edit mode and resetting the progress.  After I moved the books to my backpack and back, it was marked complete and I could claim the rewards.  Unsure if I should delete this or leave it here.

**Comment by TheBedrockMaster** [comment]
That happens sometimes with FTBQuests, unfortunately that's the only way to fix it.
