### ISSUE TITLE
Ender Io crafter causing large amounts of TPS lag

### ISSUE THREAD

**Issue by Tr1ggerfish1** [AllTheMods/ATM-9#194]
I have recently come across the issue of ender io crafters while playing on a server (have not tested to see if this is also true for client side single player). While I was automating some recopies using ender io crafters I had placed roughly 12 crafters down and began to notice block and entity lag. Seeing this I checked my fps seeing that it was not my client that was having issues but rater the server that was hosting the instance. using a "/forge tps" command I saw that my mean ticks per second (MTPS) was in the 90's-100's for the dimension I was currently in. Knowing not long before this I was not having any issues I proceeded to roll back the world prior to the crafters. The MTPS was roughly 3 after the rollback. this was reproduced when the ender io crafters where placed down in an empty area with no connections or alteration in the gui (replicated to each dimension where they where placed, resulted in increased tick time).

**Comment by everettperiman** [comment]
I would recommend to use /spark to record some gameplay and it will tell you specifically what mod is taking up the TPS. Maybe attaching that report might help narrow down exactly what is wrong.

**Comment by Rover656** [comment]
This should have been fixed in Ender IO [v6.0.12-alpha](https://github.com/Team-EnderIO/EnderIO/releases/tag/v6.0.12-alpha). If you're using 6.0.12 or later, please profile it and submit a new issue to our repository so we can investigate further.
Cheers!
