### ISSUE TITLE
[Crash]: Pressing U on the liquifier from Alchemistry in JEI (keybind to see liquifier uses) immediately crashes game

### ISSUE THREAD

**Issue by SaturatedMatt1** [AllTheMods/ATM-9#1940]
### Possible Fixes

Yes

### Modpack Version

1.1.0

### What happened?

In JEI pressed U on liquifier from Alchemistry to see its recipes, crashes game instantly. Does not happen with anything else from alchemistry

### Crash Log

https://gist.github.com/SaturatedMatt1/9af4b5f6fd95893544df5f5bfab77c6e

**Comment by BlackStar7713** [comment]
I can't reproduce your issue on modpack version 0.3.0
You state your version as 1.1.0, which is beyond the current version of ATM9, are you sure you're on the correct github?

**Comment by TheBedrockMaster** [comment]
I think they remade it on the 9sky GitHub, so this can be closed.

> I can't reproduce your issue on modpack version 0.3.0 You state your version as 1.1.0, which is beyond the current version of ATM9, are you sure you're on the correct github?
