### ISSUE TITLE
Mob Bell causes crash when holding it

### ISSUE THREAD

**Issue by shrekshrek214** [AllTheMods/ATM-9#195]
Mob Bell causes a crash when holding it no matter what
[crash-2023-08-05_23.20.46-client.txt](https://github.com/AllTheMods/ATM-9/files/12268794/crash-2023-08-05_23.20.46-client.txt)

**Comment by leikenghou** [comment]
Same with you, When I hold the hand bell the game crash. no matter the client or server.
