### ISSUE TITLE
[Bug]: (Chipped) Mason Table needs its recipes re-added

### ISSUE THREAD

**Issue by johndoe1353** [AllTheMods/ATM-9#1959]
### Possible Fixes

Yes

### Modpack Version

0.3.0

### What happened?

You can craft the mason table, but all the recipes are missing all the items are still in game. just unobtainable in survival because of the missing recipes. I'd like to see these added back in a future update if possible thanks for your time. :)

**Comment by Mitchell5200** [comment]
not quite sure what you're asking, it's working fine for me in the release version (on a server)
![2024-08-07_19 05 53](https://github.com/user-attachments/assets/73bd9dbd-459f-4e08-ba76-b48398fce802)
![2024-08-07_19 04 21](https://github.com/user-attachments/assets/67c837f9-604c-4d52-83a5-e649d4092fb0)

**Comment by johndoe1353** [comment]
Not sure why, but the recipes are there now closing ticket.
