### ISSUE TITLE
[Bug]: Death beam that i have no idea how to remove

### ISSUE THREAD

**Issue by EnderDrag0n** [AllTheMods/ATM-9#1962]
### Possible Fixes

Yes

### Modpack Version

0.3.0

### What happened?

![2024-08-08_23 11 05](https://github.com/user-attachments/assets/d820cbca-fa42-4e68-a976-b347385c33f1)
After dying a red beam appears, that i have no idea how to remove. When getting closer it dissappears.
I have added a few mods and changed some to versions i prefer (example: JEI to REI), but i dont think that they are an issue.
The only mod i was thinking that could cause this is xaero's minimap/world map, but after removing, beam is still there
additional mods: https://gist.github.com/EnderDrag0n/5576317277dbca467e3d4b2176368869

**Comment by EnderDrag0n** [comment]
It's playable with this beam, but i'd would like to remove it

**Comment by Mitchell5200** [comment]
i believe that's the FTB maps death marker, open that map with default "M" key, and the waypoint should show on that screen, right click it to get options

**Comment by EnderDrag0n** [comment]
Thanks, it really was FTB Chunks!
