### ISSUE TITLE
[Bug]: Immersive Engineering version is 10.0.0-169 and shows as incompatible. Also missing clinker blocks.

### ISSUE THREAD

**Issue by NerdimusPrime** [AllTheMods/ATM-9#1971]
### Possible Fixes

Yes

### Modpack Version

0.3.0

### What happened?

I was gathering materials for a building schematic that includes clinker blocks from IE, but those blocks are not visible/available in ATM9. After some investigation and speaking with the schematic author, who created the schematic in ATM9TTS, they have IE version 10.1.0-171 in both TTS and ATM9, but my pack has 10.0.0-169. There is no option to update, and there's an error flag saying my version is incompatible with the modloader Forge. Trying to install the mod directly to the ATM9 profile also gives the incompatibility message.

![ATM9-ImmersiveEngineering-VersionIncompatible](https://github.com/user-attachments/assets/cb194cb0-ebbb-403a-a572-ea9bd036fa4d)

### latest.log

https://gist.github.com/NerdimusPrime/e0579789be83f8203285d6080d0c01a5

**Comment by Mitchell5200** [comment]
yes, the incompatible flag is due to the IE dev marking the mod for NEOFORGE, it's still compatable with Forge for MC 1.20.1 though, however i do not believe CF was aware of this.
I'll make a self note in dev to force update IE though

**Comment by NerdimusPrime** [comment]
Thank you!

**Comment by NerdimusPrime** [comment]
Is the invisibility of clinker blocks in ATM9 vs TTS related to this, or is that a separate thing?

**Comment by NerdimusPrime** [comment]
The schematic author checked his instances of ATM9 and TTS, and says both of them have IE 10.1.0-171, but that the clinker blocks are only visible in TTS.

**Comment by TheBedrockMaster** [comment]
> Yes, the incompatible flag is due to the IE dev marking the mod for NEOFORGE, it's still compatible with Forge for MC 1.20.1 though, however I do not believe CF was aware of this. I'll make a self note in dev to force update IE though

This should also fix the broken Steel Armour names.
