### ISSUE TITLE
[Bug]: Limit circles in the mahou tsukai mod.

### ISSUE THREAD

**Issue by EdAiVeR20** [AllTheMods/ATM-9#1989]
### Possible Fixes

Yes

### Modpack Version

0.3.0

### What happened?

Hello, as soon as I want to activate more than 9-10 circles from the mahou tsukai mod, I get an inscription that I can not do this. is there any way to remove this restriction? Sorry for the translation errors, I don't know English.
![2024-08-18_21 56 41](https://github.com/user-attachments/assets/50b7c0f6-a230-478b-8186-48c06933ce28)

### latest.log

https://gist.github.com/EdAiVeR20/050e615961002ced0e614a12c83ce07a

**Comment by stepsword** [comment]
this is a new mod-added default - you can edit the following two configs in server config (just make them empty lists to remove the limits)
	#Names of magic circles to have restrictions
        ACTIVE_MAGIC_CIRCLE_NAMES = ["mahoutsukai:mahoujin_drain_life_barrier"]
	#How many active circles of one type a caster can have. Requires NAMES config
	ACTIVE_MAGIC_CIRCLE_LIMITS = [10]

**Comment by EdAiVeR20** [comment]
Thank you very much, but could you describe in more detail where and what to edit. Thank you in advance.

**Comment by EdAiVeR20** [comment]
Thank you very much, you helped a lot.
