### ISSUE TITLE
(>0.0.46) No Breaking Block Animation

### ISSUE THREAD

**Issue by tekook** [AllTheMods/ATM-9#199]
Currently there is no anmation when breaking a block.
This is missing since version 0.0.46.

You can see it in this screenshot:
![2023-08-07_19 09 38](https://github.com/AllTheMods/ATM-9/assets/976407/37e437c3-c610-4cb0-846f-e6cd39ef265e)

Jade shows almost 80% breaking, but the block texture did not change.
This applies to every block in the game.

kind Regards

**Comment by tekook** [comment]
fixed with 0.0.51 (downgerade of gregtech)

**Comment by screret** [comment]
fixed in GT 1.0.11
