### ISSUE TITLE
[Bug]: aluminium buzz saw from 2 slabs staked on top of eachother. 

### ISSUE THREAD

**Issue by The-Final-Empire-Of-Dogs** [AllTheMods/ATM-9#1992]
### Possible Fixes

Yes

### Modpack Version

3.0

### What happened?

so if you make slabs with any vinnila log and then stack them verticaly you can use polymorph to turn them to aluminum buzzsaws. and you can also dupe wood this way.

**Comment by EnderDrag0n** [comment]
You discribed the bug badly, or it isn't case in 0.3.0 (last version)

**Comment by The-Final-Empire-Of-Dogs** [comment]
> You discribed the bug badly, or it isn't case in 0.3.0 (last version)

sorry if i discribed it porely. i have no clue how this part of github works. i had this bug and maybe its conditinal but i now have 64 buzzsaws with only a bit of playtime.
