### ISSUE TITLE
Glowstone nest 

### ISSUE THREAD

**Issue by Leo0hds** [AllTheMods/ATM-9#20]
I walked 10,000 blocks in the nether and not found glowstone nest and in the jei there is no recipe, i don't know if it's a world generation bug, but it happened in my world and my friend's world.

**Comment by quikenb** [comment]
Just to add onto this issue.

Recipes for Solitary Nests are either not implemented or not enabled.

Nether nests found: Nether Brick Nest, Warped Nest, Crimson Nest.

Nether nests not found: Glowstone Nest, Soul Nest, Quartz Nest, Gold Nest

Using nests locators travelled 10k block in one direction only in creative. Nest locators have a range of 100 blocks. That equates to 25 million blocks, which either has to do with the generation or non implementation

**Comment by JaisDK** [comment]
Recipes will be back in the next version
