### ISSUE TITLE
Ended io powered spawner 

### ISSUE THREAD

**Issue by Bigoldonut** [AllTheMods/ATM-9#200]
With the update of 0.47 to atm9 the ender io powered spawner is now super slow regardless of the capacitor you add to it 

1 mob spawns about every 30 seconds even with the max capacitor and multiple spawners.

**Comment by gogedo** [comment]
I have no Issues with it.
0.0..46 I have a double layer capacitor and the wither skeletons spawns 1-4 , after spawns  killed by shield and room is empty.
Spawner is powered by a Ender Cell  10k FE/t.   RFtool Shield (Player) kills directly.  Spawn interval is 2 seconds. 
May be you have not enough Power. Then try Powah Reactors, very powerfull in contrast to other Powah versions.  

0.0.47 Soul Vial don't work, so no Spawner.

**Comment by Bigoldonut** [comment]
> I have no Issues with it. 0.0..46 I have a double layer capacitor and the wither skeletons spawns 1-4 , after spawns killed by shield and room is empty. Spawner is powered by a Ender Cell 10k FE/t. RFtool Shield (Player) kills directly. Spawn interval is 2 seconds. May be you have not enough Power. Then try Powah Reactors, very powerfull in contrast to other Powah versions.
> 
> 0.0.47 Soul Vial don't work, so no Spawner.

sorry I meant 0.47 but if the soul vial is broken an the powered spawner is already made how can that affect the spawn rate I just wondering cause I have lots of power and ocd capacitor 
My spawn rate in 0.47 is like 2-3 mobs every minute.

**Comment by Rover656** [comment]
This is not a bug; we've been trying out new values for balancing energy consumption in Ender IO. If you feel that something is too fast or too slow, come along to our Discord or Ender IO github to discuss these changes :)

**Comment by agnor99** [comment]
we also increase the spawn time of spawners if more spawners are in close proximity than allowed by the maxspawners config, maybe you run into this too?

**Comment by macCormack** [comment]
> This is not a bug; we've been trying out new values for balancing energy consumption in Ender IO. If you feel that something is too fast or too slow, come along to our Discord or Ender IO github to discuss these changes :)

Ah okay! Can't thank everyone working on the project enough. EnderIO is amazing

> we also increase the spawn time of spawners if more spawners are in close proximity than allowed by the maxspawners config, maybe you run into this too?

I only had one setup, on the surface of my world.
