### ISSUE TITLE
[Bug]: ME Output Hatch doesn't work

### ISSUE THREAD

**Issue by nesa402610** [AllTheMods/ATM-9#2003]
### Possible Fixes

Yes

### Modpack Version

0.3.0

### What happened?

Conneted, but not online and machines dont work
![image](https://github.com/user-attachments/assets/fae7ec7f-a0fe-4664-aa80-18e1a3e0b8b4)
![image](https://github.com/user-attachments/assets/28822382-e946-4ea6-8b7d-7d6d1650489d)

but ME Output Bus in status offilne going to online after crafting

**Comment by Pumpkin7266** [comment]
Will be fixed in next pack update or whenever the pack updates to GTM / Gregtech Modern 1.4.
