### ISSUE TITLE
[Feature improvement]: Upload modpack to Modrinth

### ISSUE THREAD

**Issue by ultimateshadsform** [AllTheMods/ATM-9#2004]
It would be nice to have it on [Modrinth](https://modrinth.com/mods) too since I don't use Curseforge.

**Comment by ultimateshadsform** [comment]
And if it's allowed I can do it myself if I'm allowed and nobody else want to do it.

**Comment by Mitchell5200** [comment]
> It would be nice to have it on [Modrinth](https://modrinth.com/mods) too since I don't use Curseforge.

No, 

> And if it's allowed I can do it myself if I'm allowed and nobody else want to do it.

Even bigger no.

The long and short of it is that the mods we use also have to be uploaded to modrinth, by the original mod devs, Additionally, some of our own mod devs have no intention of re-uploading their mods to modrinth, for whatever not my business reason.
