### ISSUE TITLE
[Crash]: AllTheModium and better armors crash the game

### ISSUE THREAD

**Issue by Smoack** [AllTheMods/ATM-9#2011]
### Possible Fixes

Yes

### Modpack Version

0.3.1

### What happened?

I was playing on a server with my friends on 0.3.0, which worked fine. After that, the server automatically updated the modpack, so we started playing on 0.3.1. However, after I got hit by a skeleton (I was wearing Unobtainium Armor) the server crashed due to a ticking entity. It seems that every single projectile that hits a wearer of AllTheModium, Vibranium or Unobtainium (maybe even more, those are just the ones that I tested) becomes a ticking entity and crashes the server. Every time I joined the server, it instantly crashed. I managed to fix it by enabling the forge serverconfig option to remove ticking entities instead of crashing the server, and then removing my armor. This is pretty annoying, since this means I can't use my Unobtainium armor anymore.

### Crash Log

https://gist.github.com/Smoack/e533ebf335d361faf97b668723ea82aa

**Comment by JordanWalter2014** [comment]
Happening to me too. I spent about 12 hours trying to figure out why my server was going down. It's this.

**Comment by gorgarp** [comment]
Confirmed. Same.

**Comment by Mitchell5200** [comment]
Related to DeeperDarker 1.2.1, related to https://github.com/KyaniteMods/DeeperAndDarker/issues/351
