### ISSUE TITLE
[Bug]: Apiary MK II producing blank comb blocks

### ISSUE THREAD

**Issue by Special70** [AllTheMods/ATM-9#2019]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

When checking the recipe to make a diamond comb block, JEI seems to only display Apiary MK I recipes but not Apiary MK II recipes. I checked what the Apiary MK II produces and it just produces "Comb Block". 

Extra info: I am playing at `atm9.moddedmc.net` not in singleplayer

**Comment by Pumpkin7266** [comment]
yeah this is current gregtech bug that's fixed in dev.
It got found on Nomi recently too

**Comment by Pumpkin7266** [comment]
https://github.com/GregTechCEu/GregTech-Modern/issues/1829
it's fixed in dev though, will have to wait for a release

**Comment by RealKC** [comment]
As far as I can tell, gregtech's 1.4.1 release should fix this

**Comment by loving2** [comment]
This should be fixed in latest!
