### ISSUE TITLE
[Crash]: Error occurred applying transform of coremod coremods/field_to_method.js function biome

### ISSUE THREAD

**Issue by HotfirePT** [AllTheMods/ATM-9#2021]
### Possible Fixes

Yes

### Modpack Version

ATM 9-0.2.5.4

### What happened?

Yesterday i was playing with no problems and restarted my atm9 instance so i could change quarryplus config.
However when i launched it back , it just crashed a few seconds later. I came here since i've never seen this type of bug about coremods/field_to_method.js function biome
Here are the logs:

[latest.log](https://github.com/user-attachments/files/16838933/latest.log)
[2024-09-02-4.log.gz](https://github.com/user-attachments/files/16838937/2024-09-02-4.log.gz)

Any help would be appreciated!

### Crash Log

https://gist.github.com/HotfirePT/5bf95966d5dc0c0bd5cc1db56ae5213b

**Comment by HotfirePT** [comment]
HUGE thing i forgot to mention:
I just realised the crash happened when i ran out of disk space. however, even after clearing out 100+gb it still crashes... so i guess its for a different error now

**Comment by Mitchell5200** [comment]
Cracked Launcher, Closing
