### ISSUE TITLE
[Quests issues]: Electric blast furnace quest bug

### ISSUE THREAD

**Issue by codAlienwx** [AllTheMods/ATM-9#2029]
### Modpack Version

0.3.2

### Describe the issue

I crafted my EBF and looked inside when it was complete but the quest isnt validated ?
![2024-09-06_10 55 17](https://github.com/user-attachments/assets/8a196ac7-90f6-44cd-ab70-c967b0cff815)
![2024-09-06_10 54 36](https://github.com/user-attachments/assets/43b44841-8db7-4c6a-af42-bfdc1ced9d82)
![2024-09-06_10 54 26](https://github.com/user-attachments/assets/7720b637-984b-457f-982f-6f47ab408b32)

**Comment by Rommelski** [comment]
Same problem here too, And not only the EBF, but every Greg multiblock quest that requests to look inside is incompletable in 0.3.2

**Comment by DmitryScaletta** [comment]
> not only the EBF, but every Greg multiblock quest that requests to look inside is incompletable in 0.3.2

Same issue with the "Mekanism: Advanced" tab

**Comment by Unreal-Technologies** [comment]
Also have the same issue

**Comment by Everyth1ngNinja** [comment]
Same Issue
