### ISSUE TITLE
Add Smithing Table automations campatible with Refined Storage

### ISSUE THREAD

**Issue by RumanLucas2** [AllTheMods/ATM-9#2038]
is very inconvinient to make ALL the Smithing table itens u have to make a sub AE2 system just to make it work... 

im just putting itin to hand cause a lot of people use refined storage as their main system ( Me included), and by adding easyer automations to all this recipes it would be more convinient for new players and casualplayers, that just wanna play withought remembering how much channels they have left in a specific cable

**Comment by Mitchell5200** [comment]
That's not a feature we can add, you'd be better off suggesting that to the RS dev, but as they're working on RS2, it likely won't be something they add for RS1, but might be on the roadmap for RS2
