### ISSUE TITLE
[Quests issues]: Rewards provide previous Apotheosis items before they were renamed

### ISSUE THREAD

**Issue by ToastyCoral** [AllTheMods/ATM-9#2041]
### Modpack Version

0.3.2

### Describe the issue

Reward "Superior Sigil of Socketing" no longer exists
![Screenshot 2024-09-10 160228](https://github.com/user-attachments/assets/8c363564-9d49-426b-875e-338b47d2f557)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-9/issues/1994
