### ISSUE TITLE
[Quests issues]: "Alchemistry Basics" auto-unlocks when completing "Intro to Allthemodium!"

### ISSUE THREAD

**Issue by ShinryuAspect** [AllTheMods/ATM-9#2042]
### Modpack Version

0.3.2

### Describe the issue

I've been exploring the FTB Quests folder checking if there was any issues regarding typos or whatever, but I've been unable to find any clue of why would this be happening. It used to happen also in ATM9 v0.3.0 so it's something recurrent.
Simply put, when you claim the reward from the "intro to Allthemodium!" quest inside the "Allthemodium" chapter, it auto-unlocks the "Alchemistry Basics" quest from the "Alchemistry" chapter, even tho the book requested by said quest is not the one obtained from the main quest - the tags are simply different. Or maybe I'm seeing it wrong and it should be using NBT instead of tag (dunno if there are any differences inside the chapters' files from FTB Quests).

**Comment by TheBedrockMaster** [comment]
The Alchemistry Basics quest task is missing the Match NBT filter.,
