### ISSUE TITLE
[Bug]: Gregtech bees impossible to get

### ISSUE THREAD

**Issue by disgraceb** [AllTheMods/ATM-9#2043]
### Possible Fixes

Yes

### Modpack Version

All the Mods 9-0.3.2

### What happened?

From what I can tell, the gtceu-1.20.1-1.4.0 and gtceu-1.20.1 updates modified the likelihood of getting a bee spawn egg from a gregtech machine to 0.01%. After using a lot of time in a bottle in survival, I ran some tests in creative. With 16 max speed machines for over an hour, no eggs were created. I'm continuing to run the machines, but I think there's a problem with the odds.

**Comment by phrostt** [comment]
Can confirm, same issue.

**Comment by RandonActs** [comment]
Same issue. I've been running 128 machines in survival for the past hour with zero successes.

**Comment by tenfoottom** [comment]
Same issue here too.

**Comment by Quphoria** [comment]
I'm having the same issue,
and a similar issue with the graphite bee egg,
which is a 0.01% chance from a coal bee egg in a macerator, been running for over 2 weeks and still no egg

**Comment by Pumpkin7266** [comment]
Fixed in current GTM versions, need an update

**Comment by DmitryScaletta** [comment]
It was fixed in the Productive Bees mod but it's not released for 1.20.1 yet
Looks like it meant to be 100% chance instead of 0.01%

https://github.com/JDKDigital/productive-bees/pull/567
