### ISSUE TITLE
[Bug]: Most Create recipes don't show up in JEI

### ISSUE THREAD

**Issue by Yadokingu** [AllTheMods/ATM-9#2047]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

If you search in JEI for @Create a bunch of decorative blocks will show up but none of the functional ones. For a specific example searching for "mechanical crafter" will bring up nothing.

**Comment by Mitchell5200** [comment]
Related to https://github.com/Creators-of-Create/Create/issues/6222, fixed in create 0.5.1.h
