### ISSUE TITLE
[Bug]: Netherite upgrades show up wrong in JEI

### ISSUE THREAD

**Issue by Yadokingu** [AllTheMods/ATM-9#2048]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

In JEI all netherite upgrades in a smithing table show that you need the netherite version to upgrade to the netherite version. So for example netherite helmet to netherite helmet, or functional storage netherite upgrade to netherite upgrade.
When you actaully put the diamond version, like a helmet or an upgrade, into the smithing table, along with a smithing template and netherite ingot, it works just fine, but the wrong JEI recipes are confusing.

**Comment by DmitryScaletta** [comment]
Fixed in the latest JEI version
