### ISSUE TITLE
[Quests issues]: Some tasks don't recoginize Items

### ISSUE THREAD

**Issue by Naini0712** [AllTheMods/ATM-9#2049]
### Modpack Version

0.3.0

### Describe the issue

Hi.
I'm playing ATM9 on the server with my team.
These quests don't recognize Observer and Coal Coke.
![2024-09-15_12 29 02](https://github.com/user-attachments/assets/6453a967-d56c-41ea-90a8-1a468e162d08)
![2024-09-15_12 42 45](https://github.com/user-attachments/assets/f742d024-d169-4d92-9bb9-df47863f6dcf)
![2024-09-15_12 42 54](https://github.com/user-attachments/assets/8cf92e6e-1c10-4fe6-b633-4e10cfbddc9a)

**Comment by TheBedrockMaster** [comment]
"My quest is stuck/grey"
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

"I want the reward from the quest though"
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.
