### ISSUE TITLE
[Bug]:Bee spawn eggs don't change in any GT machine

### ISSUE THREAD

**Issue by frsfdc** [AllTheMods/ATM-9#2065]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

I tried to craft various bee spawn eggs that use GT,yet for all of them materials don't get used and timer just goes to 0 and back again.This didn't happen before,only after server admin updated to 0.3.2.
![2024-09-23_16 27 55](https://github.com/user-attachments/assets/f25437f0-c36f-48b9-8ef8-5bcb759e3dc4)

**Comment by Pumpkin7266** [comment]
https://github.com/AllTheMods/ATM-9/issues/2043

**Comment by frsfdc** [comment]
> #2043

So it needs to e updated to latest GT?

**Comment by loving2** [comment]
This has been fixed in latest
