### ISSUE TITLE
[Suggestion] Enable MA Default Secondary Seed Drops

### ISSUE THREAD

**Issue by MCterra10** [AllTheMods/ATM-9#2066]
Hi,

I would like to suggest enabling the secondary seed drops for MA by default. I understand that the likely reason for this is balancing around AllTheModium seeds and friends.

You can set the chance per seed in Mystical Customization: https://blakesmods.com/docs/1.21/mysticalcustomization/adding-crops#base-secondary-drop-chance

**Comment by Mitchell5200** [comment]
Intentionally turned off packside.
