### ISSUE TITLE
[Bug]: Item Visibility Issue with Terminal and Attempted Fixes

### ISSUE THREAD

**Issue by LemCsZ** [AllTheMods/ATM-9#2067]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

Firstly, I believe my issue started when I had the wireless universal terminal open and picked up an item with my second hand. Now, only autocraft recipes are visible, and even if I disconnect the connection to them, no items appear in the system at all not those in the disk drivers nor those in the storage bus. I've checked all the key binds, but I couldn't find anything. I also deleted the config files and restarted, but nothing changed.

https://github.com/user-attachments/assets/67a86184-337f-4e8f-abcb-19c146d2c669

**Comment by Mitchell5200** [comment]
you have your terminal set to view the crafting patterns, click the 3td button down, that looks like a hammer.

**Comment by LemCsZ** [comment]
> You have your wireless terminal set to view only the crafting patterns, click the 3rd button down, that looks like a hammer.
> 
> And with your storage disconnected, of course none of your items are going to show in the terminals, or allow the deposit of any new items.

I wish what you mentioned was really the issue because I was actually doing what you said later in the video, but I had to cut it to keep it under 10 MB. However, my problem is definitely not that. The sorted items only appear when selected, and in the storage bus, only the water in the sink is visible, but nothing shows up in the other buses or the items in the disks.
![Ekran görüntüsü 2024-09-24 182534](https://github.com/user-attachments/assets/377bb46b-0434-4af0-9c93-5bac162b0b0b)
![Ekran görüntüsü 2024-09-24 182538](https://github.com/user-attachments/assets/79435d93-0528-48e4-82fe-5a8f3a42bc15)

**Comment by Mitchell5200** [comment]
![Screenshot 2024-09-24 23 39 41](https://github.com/user-attachments/assets/bcc59e2d-c8d5-4a1d-944d-e48a2477ede8)
Your storage is not connected to the network, note the "Device Offline" bit in the JADE tooltip.

**Comment by LemCsZ** [comment]
> ![Screenshot 2024-09-24 23 39 41](https://private-user-images.githubusercontent.com/45913837/370358332-bcc59e2d-c8d5-4a1d-944d-e48a2477ede8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTQzMjMsIm5iZiI6MTcyNzE5NDAyMywicGF0aCI6Ii80NTkxMzgzNy8zNzAzNTgzMzItYmNjNTllMmQtYzhkNS00YTFkLTk0NGQtZTQ4YTI0NzdlZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE2MDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYzUwMWM2M2I2MTkzMTgwN2E5MGQ2Mzg4N2JjMDk1YTE3MzRkMjZiMGUxZWM1NTk1MzBjMjJjZDQ4OGFiMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fNqIOyYPPZvvkyJao26Hyoej2mrIQGAjmxzlyKPf8x4) Your storage is not connected to the network, note the "Device Offline" bit in the JADE tooltip.

Aaaaaa seriously, how did you not notice? Sometimes you get so focused on other things that you forget what's right in front of you. Anyway, I figured it out, it was really due to my carelessness. My friend had broken the cables there. Anyway, have a good day.
