### ISSUE TITLE
[Bug]: Armor Will Tick Mobs

### ISSUE THREAD

**Issue by Fishirboy** [AllTheMods/ATM-9#2072]
### Possible Fixes

Yes

### Modpack Version

My Own 

### What happened?

I apologies if this is the wrong but I don't have anywhere else I could go after researching. 

So I don't have a place to file a bug report for just Allthemodium pack. This error is occurring for armor in this mod. The same issue is occurring for the Aether mod and I have test every other armor in my pack and this is the only two that does this.
I posted on reddit first to see if anyone had ideas :
https://www.reddit.com/r/allthemods/comments/1fojyag/allthemodium_armor_ticking_entities_in_personal/
I also filed a bug report and they just said they had a fix for next patch but who know when that is coming out :
https://github.com/The-Aether-Team/The-Aether/issues/2276
I just wanted to see if this is something I could fix or is this something that would need to be done on your end?

**Comment by Mitchell5200** [comment]
Those logs are pointing at DeeperDarker, as per https://github.com/AllTheMods/ATM-9/issues/2011 and https://github.com/KyaniteMods/DeeperAndDarker/issues/351, Update DeeperDarker in your personal instance

Additionally, https://github.com/AllTheMods/AllTheModium/issues

**Comment by Fishirboy** [comment]
Ok! Thank you and sorry for the inconvenience.
