### ISSUE TITLE
[Quests issues]: apotheosis vial of extraction

### ISSUE THREAD

**Issue by HazardEST** [AllTheMods/ATM-9#2074]
### Modpack Version

0.3.2

### Describe the issue

![image](https://github.com/user-attachments/assets/c60b4d22-4d07-4420-92ef-c2e947ea4343)
one of the quest rewards is this broken item. sorry i dont know which one exactly.

**Comment by ZyPA** [comment]
+1
![image](https://github.com/user-attachments/assets/336da968-aca3-4710-bc82-b27a53d2cf2d)
