### ISSUE TITLE
[Bug]: Thermal Dynamics Missing Item

### ISSUE THREAD

**Issue by BaddKidd** [AllTheMods/ATM-9#2078]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

Thermal Dynamics is missing an item called "ItemDuct". Recipe isn't craftable but is a item that is present mod.

**Comment by superbrotherx4** [comment]
Thermal Dynamics does not have Itemducts anymore. The mod author has tons of other things to work on so has not implemented them. You can actually see this in the Thermalpedia
