### ISSUE TITLE
[Bug]: Meka suit lags the hell out of the server

### ISSUE THREAD

**Issue by QBos07** [AllTheMods/ATM-9#2106]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

Meka suit charge changes lag due to FTB Quests and Advancements constantly updating. Using Vision Enhancement

### Developer reports

https://github.com/mekanism/Mekanism/issues/7625

**Comment by Luminisc** [comment]
I am gonna add some details too, as I getting a lot of lags from MekaSuit on players.
I found bugreport from Mekanism (https://github.com/mekanism/Mekanism/issues/7625), and followed the advice to disable night vision on suit, and viola - tick time of players with MekaSuit reduced from avg. ~2500us/t to ~150us/t. Looks like bug is still present on their side.
There are still one thing to consider - I wanna try optimization mods from https://github.com/AllTheMods/ATM-9/issues/2101, maybe it will help

**Comment by santosgamingdev-pixel** [comment]
https://www.curseforge.com/minecraft/mc-mods/mekanism-gear-optimizer Fixed it for 1.21.1
