### ISSUE TITLE
[Crash]: Exit Code 1

### ISSUE THREAD

**Issue by SenpaiSan15** [AllTheMods/ATM-9#2108]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

Hello
I am trying to play with the ATM 9 to the skye modpack, but when I start up the modpack it crashes and gives me the following code:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffee8092b60, pid=7052, tid=13340
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x192b60]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://aka.ms/minecraftjavacrashes
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Djna.tmpdir=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Dorg.lwjgl.system.SharedLibraryExtractPath=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Dio.netty.native.workdir=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=3.3.13 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-47.2.20.jar,forge-47.2.20 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=\curseforge\minecraft\Install\libraries --module-path=\curseforge\minecraft\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;\curseforge\minecraft\Install\libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm/9.5/asm-9.5.jar;\curseforge\minecraft\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx4096m -Xms256m -Dminecraft.applet.TargetDirectory=\curseforge\minecraft\Instances\All the Mods 9 - To the Sky - atm9sky -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -DlibraryDirectory=\curseforge\minecraft\Install\libraries -Dlog4j.configurationFile=\curseforge\minecraft\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username SenpaiSan15 --version forge-47.2.20 --gameDir \curseforge\minecraft\Instances\All the Mods 9 - To the Sky - atm9sky --assetsDir \curseforge\minecraft\Install\assets --assetIndex 5 --uuid 562b4771ad584bdebefd5fd76ad6ba03 --clientId MjYyNWJkMzEtMTExNy00MWRlLWI2NTctOGY5MDNkZTE5MDJj --xuid 2535430408416913 --userType msa --versionType release --width 1024 --height 768 --quickPlayPath \curseforge\minecraft\Install\quickPlay\java\1730218420873.json --launchTarget forgeclient --fml.forgeVersion 47.2.20 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Host: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz, 4 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.4957)
Time: Tue Oct 29 17:13:48 2024 Közép-európai téli idBuild 19041 (10.0.19041.4957) elapsed time: 7.620056 seconds (0d 0h 0m 7s)
....

END.
(If you need the full log I will upload it)

So I tried:
-uninstalling the modpack, curseforge
-updating the video driver ( AMD )
But never find any solution.
Anyone have any idea what should it be?
Thank you!

### Crash Log

https://gist.github.com/SenpaiSan15/557fd02e0c9bae448e423c33d1b53e6c

**Comment by SenpaiSan15** [comment]
Update after reinstalling Windows I get the following line:
Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Djna.tmpdir=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Dorg.lwjgl.system.SharedLibraryExtractPath=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Dio.netty.native.workdir=\curseforge\minecraft\Install\bin\6640930412af2b21aa7a038f74c2463b99408d68 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=3.3.13 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-47.2.20.jar,forge-47.2.20 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=\curseforge\minecraft\Install\libraries --module-path=\curseforge\minecraft\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;\curseforge\minecraft\Install\libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar;\curseforge\minecraft\Install\libraries/org/ow2/asm/asm/9.5/asm-9.5.jar;\curseforge\minecraft\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx4096m -Xms256m -Dminecraft.applet.TargetDirectory=\curseforge\minecraft\Instances\All the Mods 9 - To the Sky - atm9sky -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -DlibraryDirectory=\curseforge\minecraft\Install\libraries -Dlog4j.configurationFile=\curseforge\minecraft\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username SenpaiSan15 --version forge-47.2.20 --gameDir \curseforge\minecraft\Instances\All the Mods 9 - To the Sky - atm9sky --assetsDir \curseforge\minecraft\Install\assets --assetIndex 5 --uuid 562b4771ad584bdebefd5fd76ad6ba03 --clientId NWQ2YzA2YWEtNzQxZC00NTQzLWEzMjQtNzEwNjFkNTZiMTk5 --xuid 2535430408416913 --userType msa --versionType release --width 854 --height 480 --quickPlayPath \curseforge\minecraft\Install\quickPlay\java\1730238392742.json --launchTarget forgeclient --fml.forgeVersion 47.2.20 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Any ideas now?

**Comment by clienthax** [comment]
Looks like you didn't update your video drivers correctly. 
Did you update from here?
https://www.amd.com/en/support/download/drivers.html
