### ISSUE TITLE
AMD GPU DRIVER CRASH. (crash after minecraft launcher) [Fix Included]

### ISSUE THREAD

**Issue by ledracks** [AllTheMods/ATM-9#211]
Hi everybody,

Can someone explain me why isthe game doesn't launch ? It is launching the minecraft launcher, charging and crash.
I set up 12 gigas of allocated memory.
here is the error.

[hs_err_pid8980.log](https://github.com/AllTheMods/ATM-9/files/12303284/hs_err_pid8980.log)

**Comment by ledracks** [comment]
[latest.log](https://github.com/AllTheMods/ATM-9/files/12303398/latest.log)

andhere is the log

**Comment by ledracks** [comment]
and here is the first and the second logs
[2023-08-09-1.log](https://github.com/AllTheMods/ATM-9/files/12303414/2023-08-09-1.log)
[latest.log](https://github.com/AllTheMods/ATM-9/files/12303415/latest.log)

**Comment by ledracks** [comment]
you're thebest thank you ! <3

**Comment by GordonHollow** [comment]
[hs_err_pid6296.log](https://github.com/AllTheMods/ATM-9/files/12445328/hs_err_pid6296.log)
i keep getting similar crashes after .57 update randomly while playing, but i have nvidia, not AMD
