### ISSUE TITLE
[Bug]: Allthemodium seeds not rendering

### ISSUE THREAD

**Issue by Manlox** [AllTheMods/ATM-9#2120]
### Possible Fixes

Yes

### Modpack Version

0.3.3a

### What happened?

This is for the allthemodium seed and vibranium seed
![2024-11-08 19_48_56-Minecraft_ Forge 1 20 1 - Multiplayer (3rd-party Server)](https://github.com/user-attachments/assets/c72df9f9-8a67-40de-828d-6b244cd1735b)

**Comment by OGNaes** [comment]
Got the same issue. Also affects the Unobtainium seed/plant texture.
