### ISSUE TITLE
[Bug]: Cobaltite Bee Recipe Broken?

### ISSUE THREAD

**Issue by kchanakira** [AllTheMods/ATM-9#2121]
### Possible Fixes

Yes

### Modpack Version

0.3.2

### What happened?

The recipe for the Cobaltite Bee Spawn Egg has a 0.1% chance which seems wrong.
![Screenshot 2024-11-08 193216](https://github.com/user-attachments/assets/35359139-da2d-41ab-9d0f-7939763fcae2)

**Comment by Mitchell5200** [comment]
Fixed in 0.3.3a
