### ISSUE TITLE
[Crash]: Exception during multithreaded recipe lookup (after updating to 0.3.3a)

### ISSUE THREAD

**Issue by asineth0** [AllTheMods/ATM-9#2122]
### Possible Fixes

Yes

### Modpack Version

0.3.3a

### What happened?

Issue seems to be with Fastsuite/Polymorph, something to do with recipe lookups. We've had about 4 or 5 crashes today, they seem to be pretty random and they seem to happen when a player is searching up items in their inventory.

### Crash Log

https://gist.github.com/asineth0/a60c5d71b25c6308137880d3fc3e2789

### Latest.Log

https://gist.github.com/asineth0/97edb24b6839a250b0a0bd0b99c08048

**Comment by SeemWind** [comment]
yes, so do I

**Comment by dannypas00** [comment]
I've had this crash three times so far since the 0.3.3a update, happens when click-dragging items in an ME crafting terminal. 

[Crash log](https://mclo.gs/PE5be6f)  
[Latest log](https://mclo.gs/N8HmTxP)
