### ISSUE TITLE
[Bug]: Wrong recipes in atm9 server

### ISSUE THREAD

**Issue by SeemWind** [AllTheMods/ATM-9#2127]
### Possible Fixes

Yes

### Modpack Version

0.3.3a

### What happened?

![image](https://github.com/user-attachments/assets/5ffbfb7f-ca3e-4f57-a233-c11f42dcb12d)
Actually I only need to use one ingot in each slot 
But it will stop me frrom use pattern encoding terminal with jei easily

**Comment by Nivid-IT** [comment]
![image](https://github.com/user-attachments/assets/ed0bf863-3bb5-43d8-b3ed-03cd31d41e10)

It's indeed an issue in multiple recipes, specifically with iron ingots

**Comment by Mitchell5200** [comment]
fixed in 0.3.4
