### ISSUE TITLE
ATM 9 Crashs

### ISSUE THREAD

**Issue by Robsonsqn** [AllTheMods/ATM-9#213]
I used a **Blackhole Tank** along with an **XP Hoper** on Nether in a **Blaze spawn**, but when entering Nether again I received this error and now my map no longer opens

`Error: java.lang.ClassCastException: class net.p3pp3rf1y.sophisticatedstorage.client.render.TranslucentVertexConsumer cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (net.p3pp3rf1y.sophisticatedstorage.client.render.TranslucentVertexConsumer is in module sophisticatedstorage@1.20.1-0.8.46.579 of loader 'TRANSFORMER' @57515944; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @57515944)`

**Comment by loving2** [comment]
I also had this error when putting multiple Sophisticated Storage storage upgrades into my inventory, which caused me to crash every time I tried loading into my server. 

The latest version of Sophisticated Storage (0.8.46.579) uses Rubidium 0.7.0+ and we have Rubidium 0.6.5 in ATM9.

The solution that worked for me was downgrading Sophisticated Storage to 0.8.44.571, as upgrading Rubidium resulted in crashing while opening Minecraft.

https://github.com/P3pp3rF1y/SophisticatedStorage/issues/271 for reference.
