### ISSUE TITLE
[Bug]: u can get any item from jei

### ISSUE THREAD

**Issue by Lostaresto** [AllTheMods/ATM-9#2130]
### Possible Fixes

Yes

### Modpack Version

latest

### What happened?

item cart detector from railcraft reborn can create any items (issue for gravitas too, cuz it has railcraft too)
place item cart detector and hopper under it
then open the detector and drag the item u need from jei to this filter
and tadaa this item in hopper
random guy on mmcn atm9 showed me it and now stupid mods are banned me (that was long time ago)

**Comment by Edivad99** [comment]
@Lostaresto Fixed!
