### ISSUE TITLE
[Bug]: Hostile Neural Network (HNN) gives infinite items

### ISSUE THREAD

**Issue by MrFaboboro** [AllTheMods/ATM-9#2131]
### Possible Fixes

Yes

### Modpack Version

0.3.4 - Latest

### What happened?

Started on HNN, got my witch model to self-sufficient. Ran 1 simulation in the Simulation Chamber, used the Prediction in the Loot Fabricator (selected Redstone in my case), I got the 16 redstone I was supposed to get but the Loot Fabricator kept going. Hooked a pipe to it with a chest. I am now getting infinite Redstone.
Used other mob predictions too and kept getting an infinite amount of the item I selected.
Attached 2 pictures, 1 picture shows the machine going (blue bar). 2nd picture shows items going into the chest so it cant be just a visual glitch.
![8uvt6wcbemyx](https://github.com/user-attachments/assets/23ab9dd5-622e-471d-b2f3-39241a701044)
![nj77id80hc73](https://github.com/user-attachments/assets/d7a195e0-0a9a-4327-8610-f3e0fddc5772)

**Comment by Supergod99** [comment]
can you send a picture of your setup? going to see if I can replicate this.

**Comment by MrFaboboro** [comment]
> can you send a picture of your setup? going to see if I can replicate this.
@Supergod99 
Power coming in from the bottom. I put in the items myself into loot fabricator

![sy897ktbz0ag](https://github.com/user-attachments/assets/dee66ba4-58d1-467e-ad3a-f2a84848f40c)

**Comment by Supergod99** [comment]
using mek cables for power?

**Comment by MrFaboboro** [comment]
@Supergod99 yes, the blue ones

**Comment by Nivid-IT** [comment]
Fixed by the dev: https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/71
