### ISSUE TITLE
Stuck on "Transition from Running CONFIG_LOAD State" When Trying to Load Minecraft 1.20.1 Modpack Forge Version Help Please

### ISSUE THREAD

**Issue by kersy333** [AllTheMods/ATM-9#2136]
### Possible Fixes

Yes

### Modpack Version

1.20.1 forge 47.3.0

### What happened?

I put a few mods to Minecraft but somehow previously if it loaded me until one day I got the same error, I tried to uninstall everything again and reinstall it but it didn't work

### latest.log

https://mclo.gs/aIqB19V

**Comment by Mitchell5200** [comment]
That log is very incomplete, please upload a full `Latest.log` file. additionally "Modpack Version" needs to be an actual ATM9 pack version, please state the pack version, not MC and Forge versions
