### ISSUE TITLE
[0.0.48] ATM9 Crashing Immediately 

### ISSUE THREAD

**Issue by smoove999** [AllTheMods/ATM-9#215]
i was playing on my friends server when i went to craft another upgrade base for sophisticated storage and as i finished the craft my game insta closed, now everytime i try to load back into the server it crashes me instantly and throws this log: https://mclo.gs/LiveNfk any help would be greatly appreciated as i cannot get on at all :(

**Comment by loving2** [comment]
You'll need to downgrade the version of the Sophisticated Storage mod on both your client and the server - #213 has some additional details

**Comment by tekook** [comment]
got fixed in 0.0.49

**Comment by ArcadeArchie** [comment]
had the same issue, doing a clean install of v0.9.48 fixed it
