### ISSUE TITLE
[Bug]: RFTools Builder FTB Claims

### ISSUE THREAD

**Issue by xWaller0119** [AllTheMods/ATM-9#2150]
### Possible Fixes

Yes

### Modpack Version

0.3.5

### What happened?

When trying to use the builder (Clearing quarry) in my case, when you try to quarry out chunk(s) that are claimed by the FTB claim manager, it does not work unless you un-claim the area.

**Comment by Aquaeyes** [comment]
Have you enabled fake player access?
