### ISSUE TITLE
[Quests issues]: Tertium Pickaxe listed with incorrect tier

### ISSUE THREAD

**Issue by drbleh21** [AllTheMods/ATM-9#2151]
### Modpack Version

0.3.5

### Describe the issue

According to the basic tools page, a tertium pickaxe should be a tier 5 pickaxe. But when I crafted the pickaxe, it was only tier 3.

**Comment by TheBedrockMaster** [comment]
I just tried in game and it was a tier 4 pickaxe, either way the quest is incorrect.
