### ISSUE TITLE
[Bug]: GregTech CEu connected textures bugged ATM9 0.3.5

### ISSUE THREAD

**Issue by NeonFXFusion** [AllTheMods/ATM-9#2156]
### Possible Fixes

Yes

### Modpack Version

0.3.5

### What happened?

The pictures in question show the difference with the textures. The previous picture where it worked was taken on version 0.3.2 of the modpack. 

* Checked a new singleplayer world so world / metadata corruption is not the cause.
* Disabled shaders with same results.

![2024-12-01_22 25 31](https://github.com/user-attachments/assets/98c00992-1a52-4474-80c8-8fca996abc86)
![2024-12-01_16 38 52](https://github.com/user-attachments/assets/77d92db7-a4d1-4f35-9029-4df9151db09e)

### latest.log

https://gist.github.com/NeonFXFusion/b08ea213088f3284f965dc8b5abb3851

**Comment by Pumpkin7266** [comment]
latest update to ModernFix includes a fix to make Gregtech CTM work with the current ATM9 config @Mitchell5200
