### ISSUE TITLE
[Bug]: Extreme Reactor quest line is broken

### ISSUE THREAD

**Issue by RadicalRhino353** [AllTheMods/ATM-9#2158]
### Possible Fixes

Yes

### Modpack Version

0.3.5

### What happened?

Only on the Extreme Reactor quest line descriptions are broken, all other quests are work as intended. The quests descriptions are file names of the descriptions. Pictures also work fine.
![screenshot of what quests look like](https://github.com/user-attachments/assets/aeb810b1-1a87-48d7-a4b8-2433e1f15081)

### latest.log

https://gist.github.com/RadicalRhino353/9deb0641becd6b51ca847409faca69c4

**Comment by loving2** [comment]
A fresh install of 0.3.5 doesn't have this issue, so I suspect something went awry during an update.

There may be several ways to rectify this, but what I would do is try deleting and then copying over a fresh install's `kubejs`, `config`, `defaultconfigs`, and `packmenu` folders into your current instance. You could also try copying over the old instance's `/saves/` folder into a new install of ATM9.
