### ISSUE TITLE
[Bug]: Having issues setting up a server on an interfaced server

### ISSUE THREAD

**Issue by Hirisu** [AllTheMods/ATM-9#2162]
### Possible Fixes

Yes

### Modpack Version

latest

### What happened?

I have been trying to set up a server, but when i set up the server to start based of the jar file since the server doesnt accept batch files to start. Is there a simple Server Jar file that sets everything up and if yes, where can it be found

**Comment by Mitchell5200** [comment]
https://allthemods.github.io/alltheguides/help/server/#server-host-custom-jar
and https://github.com/neoforged/ServerStarterJar
