### ISSUE TITLE
AE2 Wireless Terminal Quantity Bug.

### ISSUE THREAD

**Issue by delolione** [AllTheMods/ATM-9#217]
Version 0.0.48
When using shift+click or space+click to move items in or out of the ae2 wireless terminal(s) it will only transfer half the total value for the action. 

Example: shift+click will transfer 32 instead of 64

This does NOT happen with the wired terminals.

Also, it randomly sends the items to the offhand shield slot as well.

**Comment by MPThLee** [comment]
Remove AEInfinityBooster Item on Wireless Transceiver, Use singularity instead meanwhile.

**Comment by delolione** [comment]
> Remove AEInfinityBooster Item on Wireless Transceiver, Use singularity instead meanwhile.

Pretty sure that doesn't work with the wireless terminals and only works to link two ae2 systems together. If I am wrong, please explain.

**Comment by MPThLee** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/26970092/bb6d7397-117f-46b2-994e-1a719f7c20de)

You can insert singularity here. with bridge card. It's feature of AE2WTLib. So you need to use AE2WTLib's Terminal (universal)

**Comment by delolione** [comment]
> ![image](https://user-images.githubusercontent.com/26970092/259835096-bb6d7397-117f-46b2-994e-1a719f7c20de.png)
> 
> You can insert singularity here. with bridge card. It's feature of AE2WTLib. So you need to use AE2WTLib's Terminal (universal)

Awesome, I got it working. Thank you very much for the information <3
