### ISSUE TITLE
[Bug]: Mekanism - Chemical Washer doesn't accept ***** Iridium Slurry

### ISSUE THREAD

**Issue by FakeDomi** [AllTheMods/ATM-9#2182]
### Possible Fixes

Yes

### Modpack Version

1.0.0

### What happened?

It is not possible to pump dirty Iridium Slurry into the Chemical Washer. It accepts Mekanism's own slurries (tried gold and osmium) so it's not an issue with the machine I/O configuration.

> [!NOTE]
> This content was automatically updated to _filter out profanity_. If you feel as though this was done in error, please [file an issue with the details](https://github.com/IEvangelist/profanity-filter/issues/new).

**Comment by Mitchell5200** [comment]
Seems to work fine in my dev test instance, and a clean instance
![2024-12-30_21 27 25](https://github.com/user-attachments/assets/78884c63-ae28-437b-8778-07a9da7d90db)
![2024-12-30_21 27 29](https://github.com/user-attachments/assets/2f328269-488a-4783-bdb1-83ba4ef58d54)
![2024-12-30_21 55 30](https://github.com/user-attachments/assets/801fb05d-31b4-4a6e-b6ac-67ab35dcdd25)

**Comment by FakeDomi** [comment]
Fixed by server restart... I hope it keeps working this time.
