### ISSUE TITLE
RFTools

### ISSUE THREAD

**Issue by NINJAHAX152** [AllTheMods/ATM-9#22]
Got myself a Storage scanner and everything there shows up like a double. Like 2 times more items than there are, also some numbers are overlapping.
![Bug](https://github.com/AllTheMods/ATM-9/assets/137185571/c1d3df49-5646-48c3-a905-35cb3daaea12)

**Comment by xslugx** [comment]
Are you using chests? especially double chests, I think that is an actual issue for RFtools, not ATM.
