### ISSUE TITLE
[0.50] Extreme Reactors Basic Passive Export not exporting

### ISSUE THREAD

**Issue by HellWhyNot** [AllTheMods/ATM-9#223]
So I've been updating my world through several versions, I assume I'll have to replace it eventually but for now it is mostly working. However this update (but could have been caused in the past five updates because I updated from .46 to .50) my extreme reactor is no longer exporting power through my Pipez energy pipes. I have replaced every block of the reactor, all of the pipes, and the recieving blocks, as well as tested a Generators Galore generator and that worked, so its definitely a problem with the reactor which wasnt one before.

**Comment by ArcadeArchie** [comment]
this also happens on v0.0.47 and up, i've tested it with pipez, EnderIO conduits and powah cables only ones working were the powah ones

**Comment by ZeroNoRyouki** [comment]
I think I've already found the problem. I've already fixed it in 1.16 and I'm porting it up

**Comment by ArcadeArchie** [comment]
> I think I've already found the problem. I've already fixed it in 1.16 and I'm porting it up

@ZeroNoRyouki would it be possible to push a beta release to curseforge or modrinth to test the fix?

**Comment by ZeroNoRyouki** [comment]
Fixed in ZeroCore 2.1.39 and Extreme Reactors 2.0.70 (1.16.5 / 1.18.2 / 1.19.2 / 1.20.1)

Have fun
Z
