### ISSUE TITLE
[0.50] Picking up Powah Energy Cables with CarryOn

### ISSUE THREAD

**Issue by xXYuudachi** [AllTheMods/ATM-9#224]
Playing on Version 0.50. You can pick up Powah Energy Cables with the CarryOn mod. If you do so, it will be stuck in your hands and there is no easy way to fix it. You can place infinite amounts of cables, but you can't open your inventory or drop them.

I'm playing on a Server. If you disconnected, the Server will kick you on every reconnect, until you restart the server. 

I could fix the Problem by disabling the CarryOn mod join the server/world and then reanable it.

**Comment by boskikker** [comment]
I have experienced this exact issue playing on a server with 0.50 aswell. I tried commiting suicide which locked me in the respawn menu being unable to respawn. the server admin reset my player id which made me able to player again.

**Comment by MPThLee** [comment]
Should back port this pr AllTheMods/VolcanoBlock#49. CarryOn has serious issue with powah blocks.

Also, **DO NOT carry the powah reactor block**. It will crash the server and corrupting the world. Should be fixed with Amulet(MCEdit) by deleting reactor block but maybe there's side impact too.

**Comment by traxonLp** [comment]
Just don't pick up Powah! blocks. 
This has always been an error. You could try to uninstall the carryon mod, load the world, and install it again. Or simply clear your playerdata as a ultima ratio.
