### ISSUE TITLE
RFTools shape cards

### ISSUE THREAD

**Issue by iiJonno** [AllTheMods/ATM-9#23]
when clicking shapecards (except the basic one "shape_card_def") no recipe shows up, items are craftable if you know the recipe from memory though.

**Comment by MaverickMartyn** [comment]
As a workaround, the recipes can be seen be rightclicking (or pressing U while hovering over) the basic Shape Card in JEI.
That will show the recipes it is used in, for use in the Mechanical Crafter form Create. The output is blank though, so some guesswork is still required, and the recipes can't be autofilled in the crafting table.
![image](https://github.com/AllTheMods/ATM-9/assets/2946618/7648b242-1b4d-4b59-a39d-e76f84f5714e)
