### ISSUE TITLE
Certus Quartz can be duped indefinetly

### ISSUE THREAD

**Issue by screret** [AllTheMods/ATM-9#231]
you just need to craft the AE2 certus quartz into blocks, and then craft back into GT certus.

**Comment by HolidayTheBoi** [comment]
I can't seem to replicate this?
The most I've got out of this is 5 extra certus quartz per block and it doesn't seem like this can be transformed back into AE2 Quartz making it less valuable for this purpose.

**Comment by TheDyreBanana** [comment]
you can grind the greg certus back down into AE2 certus dust and use it for crystal transformation.
