### ISSUE TITLE
Saves

### ISSUE THREAD

**Issue by C95M** [AllTheMods/ATM-9#239]
Hi all, I would like to copy my world from ATM8 to ATM9 but it tells me that the world cannot be loaded because it has experimental data, can I do something about it to make it work? Thank you.

**Comment by Spacelord09** [comment]
Hey, ATM9 is a new pack. It doesnt support importing your ATM8 world.

**Comment by C95M** [comment]
So should I start all over again being just a save with pretty much the same mods?

**Comment by aAndrew3030** [comment]
Most of modded minecraft is not able to load worlds created on older versions of minecraft. You are only able to do that with a vanilla (non modified) world. That said, there are various mods (save and load inventories mod is one) that allow you to save items (via a file that has a list of the items) from old worlds, and load them in new worlds. You would need to install the mod yourself.

**Comment by aAndrew3030** [comment]
You could also save your builds with mods, like the create mods schematics canon, so you don't need to totally start new
