### ISSUE TITLE
Simplebackups doesn't create backup

### ISSUE THREAD

**Issue by msamsel** [AllTheMods/ATM-9#244]
I think from version 0.0.46 simple backup stopped creating config files and making any backups. I also cannot trigger manual backup anymore.
Config `simplebackups-common.toml` is crated on 0.0.45 but not on 0.0.46.

**Comment by aAndrew3030** [comment]
The current version is .51, they may have fixed the issue in a version since .46

**Comment by msamsel** [comment]
> The current version is .51, they may have fixed the issue in a version since .46

It doesn't work in .51, it doesn't work in any version since .46

**Comment by Alucard1313** [comment]
> > The current version is .51, they may have fixed the issue in a version since .46
> 
> It doesn't work in .51, it doesn't work in any version since .46

Simple Backups was removed from server pack since .46, you must add manually

**Comment by adkinss** [comment]
I just came here to look at what happened to SimpleBackups.  I never saw it in the list of changes and went to restore a previous version of the world and found my simplebackups directory was empty.  After a lot of digging, I saw it was removed in .46 on the server side and I was wholly unprepared for it.

Interestingly enough, the mod is still in the client-side pack.

Why was it removed?

**Comment by Alucard1313** [comment]
> I just came here to look at what happened to SimpleBackups. I never saw it in the list of changes and went to restore a previous version of the world and found my simplebackups directory was empty. After a lot of digging, I saw it was removed in .46 on the server side and I was wholly unprepared for it.
> 
> Interestingly enough, the mod is still in the client-side pack.
> 
> Why was it removed?

It was removed to avoid duplicate backups, as many server hosts have their own automatic backup system. I wasn't prepared either, I lost a whole day of gameplay, as there was a power outage, and the world was corrupted. When trying to restore the world, I discovered with surprise that there were only backups from the previous day. Pretty frustrating...
