### ISSUE TITLE
Mining Gadget Crash involving Refined storage cables

### ISSUE THREAD

**Issue by fishermedders** [AllTheMods/ATM-9#246]
If you use a mining gadget, and attempt to destroy refined storage cables with it, your game will crash.

I have done this several times by accident, and this is pretty low priority, but still annoying. I'd imagine the mining gadget mod would have some sort of blacklist, but I do not know.

If I can be of any assistance in this issue, please do not hesitate to ask.

Thanks,
Fisher.

**Comment by fishermedders** [comment]
It seems that if you break a block next to a cable (even using 1x1 mode), this will happen as well.

**Comment by vedrte** [comment]
I got the same issue with Refined Storage Cables, but also with other blocks like Hydroponic Beds.

When other players are nearby their client also crashes.

**Comment by ChillUpX** [comment]
I got the same issue with Refined Storage Cables, but also with other blocks like Hydroponic Beds.

When other players are nearby their client also crashes.
