### ISSUE TITLE
Immersive Aircraft

### ISSUE THREAD

**Issue by WendyJaja** [AllTheMods/ATM-9#247]
I just discovered this mod and it is so much fun to travel with!
https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft

**Comment by Mitchell5200** [comment]
use #1 for mod suggestions, Not new issues please

**Comment by WendyJaja** [comment]
I am very sorry! I tried to delete it but did not see where I could do it.
I am new to this all and don't see where I can add my mod suggestions
I am truly sorry

Op do 17 aug 2023 om 10:26 schreef Mitchell5200 ***@***.***>:
