### ISSUE TITLE
[0.0.50] Shift + Right Clicking "Powah" cables Server Crash

### ISSUE THREAD

**Issue by EcksDeeCnt** [AllTheMods/ATM-9#255]
Powah mod cables when Shift + Right Clicking picks up the cable. When trying to place the cable back down it infinitely places more cables (possibly from excess cables in your inventory) bricking my game in the Shift + right click pick up mode. After atempting to disconnect and reconnect to the server the entire server crashed giving the "Connection refused: no further information" prompt. At the time of picking up the cable I also happened to be using the personal shrink device at 0.2 size. Upon the server restarting I tried to kill my player to see if that would fix the issue but it bricked me on the respawn screen not allowing the respawn button to work. Once again after leaving the server seem to kill the entire server again.

**Comment by EcksDeeCnt** [comment]
Forgot to add but I also have excess cables in my inventory which might have been supplying the "infinite" amount of cables i was placing down while in the Shift + Right click pickup mode

**Comment by EcksDeeCnt** [comment]
https://www.youtube.com/watch?v=hVi7zAZb6cY&ab_channel=EcksDeeCnt video showing the bug, seems the personal shrink device isnt part of the problem

**Comment by MPThLee** [comment]
#224
This is why carryon is removed temporarily on 0.0.51.

**Comment by EcksDeeCnt** [comment]
> #224 This is why carryon is removed temporarily on 0.0.51.

ah nice I wasnt aware which mod got removed in 0.0.51 we started this server a day before the new patch came out cheers.
