### ISSUE TITLE
AdvancedPeripherals' RS Bridge missing recipe

### ISSUE THREAD

**Issue by fishermedders** [AllTheMods/ATM-9#256]
The Refined Storage Bridge from advanced peripherals is missing a recipe.

Definitely not high priority but it should have a recipe.
Thanks for putting together a killer pack :)

Fisher

**Comment by sakkie6** [comment]
+1

**Comment by huntert98** [comment]
If you want to add a recipe to your server do the following:

Make a new script in this location
`You_Minecraft_Server\kubejs\server_scripts\mods\refinedstorage\recipes.js`

Paste the following into the file and save it
`
ServerEvents.recipes(event => {
  event.shaped('advancedperipherals:rs_bridge', ['ABA','BCB','ABA'],{
    A: 'refinedstorage:quartz_enriched_iron_block',
    B: 'refinedstorage:interface',
    C: 'advancedperipherals:peripheral_casing'
  }).id('kubejs:advancedperipherals/rs_bridge')
})
`

reload or restart your server

Enjoy :)
