### ISSUE TITLE
Quartz Enriched Iron Bee do not produce any honey comb

### ISSUE THREAD

**Issue by Anthalgique** [AllTheMods/ATM-9#257]
Hello,

While playing "All The Mods 9" modpack, I noticed the "Quartz Enriched Iron Bee" was not producing any honey comb for about few hours while it was solo in a beehive (no other bee with it). However, it goes out and in. It also converts (sometimes, rarely I would say) some "iron blocks" into  "quartz enriched iron blocks". In JEI, it is said that it converts those, but also produce honey comb. I find that (in my case) it does not produce any honey comb even if JEI tells me that.

Is there an update to patch that ? Is it a known bug ? Maybe there is something that I do wrong.

Regards,
Anthalgique

**Comment by ferry3009** [comment]
I have the Same issue! Have you figured it out yet?
