### ISSUE TITLE
Rendering Crash Caused by Incompatibility Between Hostile Neural Networks and Sodium

### ISSUE THREAD

**Issue by Bradderz65** [AllTheMods/ATM-9#261]
I encountered a rendering crash when trying to view a Wither data model item from the Hostile Neural Networks mod in JEI. The crash seems to be caused by an incompatibility between Hostile Neural Networks and Sodium.

Steps to reproduce:

Have Hostile Neural Networks and Sodium mods installed
Open JEI and search for the "Wither" data model
Hover over the data model item to preview it
Crash occurs

The key error is a ClassCastException between different vertex builder classes used by Hostile Neural Networks and Sodium:
java.lang.ClassCastException: class dev.shadowsoffire.hostilenetworks.client.GhostVertexBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter

**Comment by aAndrew3030** [comment]
HNN has been removed to stop this crash from happening, but a workaround is to add the HNN predictions to the JEI blacklist, so they wont show up in JEI, and not cause the crash

**Comment by aAndrew3030** [comment]
`hostilenetworks:data_model` to JEI blacklist.cfg
