### ISSUE TITLE
crash when searching build catalogue

### ISSUE THREAD

**Issue by pokemondiamond** [AllTheMods/ATM-9#263]
whenever I try to type the word "town" (i was trying to see the recipe for the minecolonies town block), or scroll to page 83 in the build catalogue, the game instantly crashes giving me exit code -1
[crash-2023-08-19_23.38.56-client.txt](https://github.com/AllTheMods/ATM-9/files/12386806/crash-2023-08-19_23.38.56-client.txt)
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class dev.shadowsoffire.hostilenetworks.client.GhostVertexBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (dev.shadowsoffire.hostilenetworks.client.GhostVertexBuilder is in module hostilenetworks@5.1.3 of loader 'TRANSFORMER' @71f056a; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @71f056a)

**Comment by aAndrew3030** [comment]
Update the pack, Hostile Networks was removed to stop this crash
