### ISSUE TITLE
Almost Unified: fire_for_standing_torch vs tiny coal vs tiny charcoal

### ISSUE THREAD

**Issue by elektronemulo** [AllTheMods/ATM-9#265]
Almost Unified seems to unifying the recipe conflict between fire_for_standing_torch<->tiny charcoal and fire_for_standing_torch<->tiny coal. Could y'all mark an exception so we can turn charcoal into tiny charcoal again?

(Actually fire_for_standing_torch doesn't seem to be useful for anything so would it break anything to disable that recipe?)

Thanks for the awesome pack!

**Comment by Glittersword** [comment]
I disagree, I can get light sources without having to use sticks to make torches.  All I need is Charcoal or coal.  You can also place them on fenceposts.  Now I only use torches to mark a path and if I am in the mood to splurge I will put a Standing Torch flame on top of a torch to give it an animated flame.

**Comment by elektronemulo** [comment]
Interesting. You can place them? Thanks, I didn't know.

The recipes still shouldn't be unified.

Closing the issue because the latest version fixed it.
