### ISSUE TITLE
Crafting Certus Quartz Blocks mined from an AE2 meteorite crafts into Greg Tech Certus Quartz which can't be charged in a charger

### ISSUE THREAD

**Issue by ther0n** [AllTheMods/ATM-9#266]

**Comment by wesselvl1** [comment]
You can throw them into water with charged certus to get budding blocks where normal crystals grow on. A better way of getting Certus anyways.

**Comment by realspinelle** [comment]
didnt know that

> You can throw them into water with charged certus to get budding blocks where normal crystals grow on. A better way of getting Certus anyways.

thx
