### ISSUE TITLE
RFTools Storage Tablet does not remember bound Storage Scanner

### ISSUE THREAD

**Issue by DerpyFrood0421** [AllTheMods/ATM-9#274]
I'm in v00.54 of pack. Have a storage scanner. Have a storage tablet -- it has the scanner module. I shift-right click the module on the storage scanner and the message says something like "Storage scanner set" but in the tooltip for the module it says Storage Scanner <unset>. Also when I add the module to the tablet right-clicking does nothing.

So I think for whatever reason the module is not remembering the block it was bound to.

**Comment by Joniator** [comment]
It's broken since 0.0.46: #189

**Comment by imposiblaa** [comment]
I am having the same issue
