### ISSUE TITLE
Crash building gadget

### ISSUE THREAD

**Issue by madkoin** [AllTheMods/ATM-9#275]
english tranlate :
I used the building gadget copy-paste, in my selection there were framed blocks. When switching to paste mode, the client crashed and has been crashing ever since. I guess it can't generate the framed block rendering. Here's the crash report

Original french:
J'ai utilisé le copy-paste de building gadget, dans ma selection il y avait des framed block. Lors du passage en mode paste, le client à crash et depuis crash en boucle. Je suppose qu'il n'arrive pas à générer le rendu des framed block. Voici ci-joints le crash report

[crash-2023-08-21_19.38.26-client.txt](https://github.com/AllTheMods/ATM-9/files/12399229/crash-2023-08-21_19.38.26-client.txt)

**Comment by XFactHD** [comment]
This crash is caused by Rubidium breaking the preview rendering of Building Gadgets. If you want to use Building Gadgets, then you'll have to remove Rubidium and Oculus until the version of Rubidium included in the pack can be updated to the latest version

**Comment by madkoin** [comment]
English translate:
Thank you for your reply, for the moment I'm not thinking of modifying the list of mods present, I'll only be using the building gadget items on vanilla blocks until this is resolved.

Original french:
Merci pour votre réponse, pour le moment je ne pense pas modifié la liste des mods présent, je n'utiliserais les item de building gadget que sur des blocks vanilla en attendant que cela soir résolu.

**Comment by XFactHD** [comment]
This has nothing to do with the kind of blocks you are copying and the crash you posted did infact happen when rendering a vanilla chest and not a modded block
