### ISSUE TITLE
Recipe Conflict: Stone Button and GregTech Stone Dust

### ISSUE THREAD

**Issue by SekhetBR** [AllTheMods/ATM-9#276]
It appears that Stone Buttons can't be crafted, as the recipe for crafting nine stone dust from GregTech conflicts with it.

Polymorph is out for 1.20.1 - I haven't tested it yet but I bet that would solve the issue.

**Comment by screret** [comment]
the stone block -> 9 dust recipe shouldn't exist at all wtf

**Comment by screret** [comment]
I swear this will be the 3rd time im fixing this
