### ISSUE TITLE
refined storage dimensional card not working

### ISSUE THREAD

**Issue by DisaPanda** [AllTheMods/ATM-9#277]
I have a dimensional card in my wireless transmitter, connected to my rs system. Everything has enough power, the transmitter says the range is 2 billion blocks, and I can use it whereever in the overworld but as soon as I go into the nether, my wireless crafting grid says it's not connected to anything. And yes, I'm sure it is a dimensional card and NOT a infinity range booster.

**Comment by lwgabo** [comment]
Hello, were you able to solve it? I have the same problem, I cannot use dimensional cards nor the global one. 
![2024-01-15_03 07 12](https://github.com/AllTheMods/ATM-9/assets/156643260/2482b639-f960-47d8-af00-1024e607d8c2)

**Comment by MrLoLf** [comment]
@lwgabo the problem is, that you are using an advanced wireless transmitter, this one doesn't work with these upgrades for some reason I had the same problem and I fixed it by changing to a normal wireless transmitter.
