### ISSUE TITLE
No way to get uraninite for reactor

### ISSUE THREAD

**Issue by gogedo** [AllTheMods/ATM-9#281]
ATM9 0.0.56

1.
Wrong recipe in gregtech
In Gregtech you make **uraninite dust from** **RAW URANINITE** in furnace
But raw uraninite have to become uraninite in furnace first.
and then you make **uraninite dust** in furnace from **URANINITE**

2.
With energizing Orb you need uraninite ore
But silk touch not working cause Bug in Powah
https://github.com/owmii/Powah/issues/228

no way to get uraninite for reactor

**Comment by screret** [comment]
the GT recipe is correct, because **gt uraninite is a stepping stone item, and doesn't have an ingot last i checked**

**Comment by gogedo** [comment]
You be wrong
, i had send you a picture frome Powah uraninite getting from furnace. It is like a ingot for reactor

**Comment by screret** [comment]
what i was trying to say is that the GT recipe isn't inherently _wrong_, it's just for a different purpose.

**Comment by M4RC0Sx** [comment]
I think Powah uraninite ore should be melted in a normal way and give you Powah uraninite instead of GT uraninite dust

**Comment by 12lewisFTW** [comment]
you can refine raw urananite in a furnace
