### ISSUE TITLE
Mystical Agriculture Infusion Crystal creation bug

### ISSUE THREAD

**Issue by Brakish** [AllTheMods/ATM-9#283]
When creating the next level of an Infusion Crystal, for example from Prudentium to Tertium, the original crystal in the formula is not used. 

Not sure if this is a new "feature" or if the crystal should be getting used up in the pattern. I seem to remember it getting used up in ATM8.

Forgot - I saw this in 0.55 and still in 0.56. I believe MA version is 1.20.1-7.0.2.

**Comment by LupusTheFallen** [comment]
Checked in 0.0.63, the crafting uses 1 durability from the original crystal.

I also checked ATM8 and the mod that adds these crystals (Mystical Agriculture Tiered Crystals) isn't there.
