### ISSUE TITLE
Occultism Divination rod bug

### ISSUE THREAD

**Issue by SmrooneyCs** [AllTheMods/ATM-9#288]
When you hold down right click while the divination rod is attuned to netherrack the game crashes.

[Bug Report](https://pastebin.com/cHt5XuCx)

**Comment by lucasolib** [comment]
It happened to me too

**Comment by klikli-dev** [comment]
This was fixed in https://github.com/klikli-dev/occultism/releases/tag/release%2Fv1.20.1-1.86.1, if you update occultism to latest (updating client side is enough, server not needed) it will work
