### ISSUE TITLE
DeeperAndDarker Sculk Transmitter causing crash when hovering over with mouse in inventory.

### ISSUE THREAD

**Issue by Fishpit** [AllTheMods/ATM-9#292]
I linked the Sculk Transmitter* to my apoth enchanting table setup and all was working fine until I reloaded the game.

Now whenever I hover over the item it crashes me to desktop.

I've tried breaking the linked block (the enchanting table) but that didnt stop the crash either. 
So now I have an item in my inventory I have to avoid or I crash.

[Crashlog](https://mclo.gs/tzIQQhR)

**Comment by aAndrew3030** [comment]
Have you tried temporarily disabling Rubidium? Some mods have issues rendering blocks with the Rubidium biome blend

**Comment by aAndrew3030** [comment]
https://github.com/KyaniteMods/DeeperAndDarker/issues/191

**Comment by Fishpit** [comment]
> Have you tried temporarily disabling Rubidium? Some mods have issues rendering blocks with the Rubidium biome blend

Thanks but I have already tried removing Rubidium, Rubidium extras and Oculus with no change of result.

**Comment by aAndrew3030** [comment]
I didn't quote? I linked the issue as to make it easy to follow, as it will also links on the other issue.
