### ISSUE TITLE
Game no longer responding when using nomowanderer

### ISSUE THREAD

**Issue by Feelzor** [AllTheMods/ATM-9#293]
Hello,

While approaching a cemetery (from a cherry biome near what seems to be a volcano), I've found the game to be unresponding. I cannot send messages, run commands, break blocks, etc. I'm in singleplayer in a default worldgen without cities.

You can find the logs: [2023-08-26-2.log](https://github.com/AllTheMods/ATM-9/files/12445441/2023-08-26-2.log)
I cannot use spark profiler since the game never responds (I've waited at least 10 minutes and still nothing).
Disabling the mod nomowanderer did the trick for me, but I'm unsure if the problem comes from the mod or the modpack, so I report it here.

**Comment by J-Dill** [comment]
This issue is now fixed in the latest version of NoMoWanderer for MC 1.20.1
