### ISSUE TITLE
Aluminum vs Aluminium Tags

### ISSUE THREAD

**Issue by SarahGreyWolf** [AllTheMods/ATM-9#294]
Either forge:\*/aluminum needs to be added to the Gregtech Aluminium stuff or forge:\*/aluminum should be added to the All the Ores Aluminum stuff otherwise AlmostUnified will not unify them and their recipes.

**Comment by rlnt** [comment]
Adding one tag to another is not a sufficient fix because recipes will still use the tag that is no longer in use.
But Almost Unified has a feature called TagOwnerships that can take care of that.

But I guess that will break the Gregtech progression.

**Comment by SarahGreyWolf** [comment]
It does which makes the choice of what to do here somewhat difficult, though the progression is somewhat broken already since the config is spawning vanilla ores like normal, I guess it's really down to how you want the pack to progress, either focusing on gregtech or not

**Comment by aAndrew3030** [comment]
Aluminum is still very early in the Gregtech progression, so unifying them isn't going to break Gregtech.
