### ISSUE TITLE
[0.0.57] DNA treats not working, ProductiveBess

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-9#295]
When you feed a bee with a DNA treat 100% high productivity, for example, the treat gets consumed but the bee has its original stats, it does not apply the stats on the treat. It was working perfectly until 0.0.57

**Comment by aAndrew3030** [comment]
According to the Productive Bees github, this was fixed in version 12.1.7 of the mod. Should be fixed in the newest version of the pack

**Comment by fkempf78** [comment]
Still same Problem in Version 0.0.65
