### ISSUE TITLE
problems with refined storage mod

### ISSUE THREAD

**Issue by pathix1** [AllTheMods/ATM-9#299]
Good day, I encountered such a problem as the destruction of the liquid when importing it into the refined storage system. The import tires were set to liquid mode in order to take liquids, of course, but when I enter the liquid terminal, I don’t see the liquid I need from the GregTech mod, all liquids disappear only from this mod.

**Comment by aAndrew3030** [comment]
In a test world with only GregTech and Refined Storage, I placed GT fluids in a GT tank, while it did delete the bucket (it should not), the fluid went into the system. I also tried imputing a bucket into a fluid interface with no problem. Also note, there is a fluid voiding option in the GT tank. Are you using a importer or disk from a RS addon mod?

**Comment by aAndrew3030** [comment]
Also, what is the fluid your trying to import?

**Comment by screret** [comment]
Uh pls report the bucket thing to GTCEu modern github

**Comment by pathix1** [comment]
I have used tanks from the Ender io mod as well as tanks from the pneumaticraft mod, also used liquid crates from the functional storage mod, liquid import tires from RS just remove liquids that are labeled "gaseous"
