### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ItzFiiree** [AllTheMods/ATM-9#3]
[crash-2023-06-15_12.24.04-client.txt](https://github.com/AllTheMods/ATM-9/files/11757051/crash-2023-06-15_12.24.04-client.txt)

**Comment by madleit** [comment]
[2023-06-15-1.log.gz](https://github.com/AllTheMods/ATM-9/files/11760837/2023-06-15-1.log.gz)
ATM9 crashed right after I create an waypoint on my base.

**Comment by madleit** [comment]
[crash-2023-06-15_18.26.50-client.txt](https://github.com/AllTheMods/ATM-9/files/11763438/crash-2023-06-15_18.26.50-client.txt)
Another crash right after I die for a Skeleton.

**Comment by Adec91** [comment]
[crash-2023-06-16_15.56.24-client.txt](https://github.com/AllTheMods/ATM-9/files/11771059/crash-2023-06-16_15.56.24-client.txt)
[crash-2023-06-16_15.57.19-client.txt](https://github.com/AllTheMods/ATM-9/files/11771060/crash-2023-06-16_15.57.19-client.txt)

Also a crash (and an instant follow up on the same world) right shortly after placing a waypoint.

**Comment by whatthedrunk** [comment]
Thanks this was fixed when we changed map mods.
