### ISSUE TITLE
[FULL][0.0.10] Can't interact with Fletching Table

### ISSUE THREAD

**Issue by xiaxuee** [AllTheMods/ATM-9#30]
Can't interact with Fletching Table

**Comment by enigmaquip** [comment]
The fletching table in vanilla has no actual functionality <https://minecraft.fandom.com/wiki/Fletching_Table>
That interaction was always added by another mod

**Comment by enigmaquip** [comment]
for future reference, in our packs that functionality is generally added by Apotheosis
