### ISSUE TITLE
medium and small slimes are invincible

### ISSUE THREAD

**Issue by ambrosius42** [AllTheMods/ATM-9#304]
i have't run into naturally occuring slimes so i'm not sure it's the same with them but medium and small slimes coming from gateways and spawners are invincible

**Comment by LupusTheFallen** [comment]
I finished a slime gate on 0.0.63 with no issues using a sword from Silent Gear + rare Apotheosis modifier. Didn't they just have extremely high bonus to armor/armor toughness?
