### ISSUE TITLE
theurgy - caloric emitters crash server

### ISSUE THREAD

**Issue by 12lewisFTW** [AllTheMods/ATM-9#308]
placed a caloric emitter from theurgy under a mercury distill, instantly crashed the server and will continue to crash game when chunk is loaded.

unfortunately i dont own the server so i cant get a log.

**Comment by 12lewisFTW** [comment]
[crash-2023-08-29_20.03.02-server.txt](https://github.com/AllTheMods/ATM-9/files/12469328/crash-2023-08-29_20.03.02-server.txt)

**Comment by klikli-dev** [comment]
Fixed in 1.6.4

**Comment by lpjn** [comment]
Thanks @klikli-dev
