### ISSUE TITLE
Server crashed when exploring in nether

### ISSUE THREAD

**Issue by chengheipui** [AllTheMods/ATM-9#312]
As title, happened a few times, I have to tp the player back to overworld and reset nether to make it works again.

Description: Ticking entity

java.lang.NullPointerException: Ticking entity

[crash-2023-08-31_02.06.10-server.txt](https://github.com/AllTheMods/ATM-9/files/12481494/crash-2023-08-31_02.06.10-server.txt)

**Comment by zabory** [comment]
Same thing happens on my server with the same crash report

**Comment by CherishedZero** [comment]
I'm also running into this issue. (If you have multiple people you can tp the person out and it is fixed, but it's a constant issue that makes me afraid to explore in the nether.)

**Comment by zabory** [comment]
Sometimes I can’t TP them out and I have to edit the players NBT data to bring them back into the overworld. 

I also found a super useful command: /tbrecovery load_player <player> .latest

this will reset their player data to a previous backup but its not always a recent backup so they could lose some progress.

**Comment by Kavy10** [comment]
This issue can happen when going in with a twilight cloak. for some reason it breaks with piglins and hoglins and piglin brutes. if you turn them off the crash shouldnt happen again.
