### ISSUE TITLE
[ATM9 v0.0.61] Too Many Spawners In One Area

### ISSUE THREAD

**Issue by SaturdayHS** [AllTheMods/ATM-9#313]
I went to a large cave around Y-level 0 and there were at least 10 Apotheosis spawners (the ones that have a block like crying obsidian on top with a chest under) in a 2 chunk x 2 chunk area, which I'm sure isn't normal.

**Comment by GoldenretriverYT** [comment]
Yeah, I also feel like there are way too many spawners
