### ISSUE TITLE
AE2 Facades and Full Framed block (Double Half Slab) next to Each other Crashes the Client

### ISSUE THREAD

**Issue by Sotabi** [AllTheMods/ATM-9#318]
edHello all,

three of us play on one server. As soon as someone puts a facade on an AE2 cable next to a full framed block, the game crashes for all people who are within approx. 3 chunks. When logging in again, the blocks are shown transparent and only removing the facade and restarting the modpack solves the problem. 

If a player is outside the 3 chunk radius and then runs into the area, everything is okay as long as he does not right/left click the facade. If he does, his game will crash as well.

The server continues to run without problems and does not generate a log.

Error existed in 0.0.50, patch to 0.0.54 and currently to 0.0.58 has shown no change with the problem.

Attached is my logfile from the crash

[Crash_ATM9_Framed Block.txt](https://github.com/AllTheMods/ATM-9/files/12500333/Crash_ATM9_Framed.Block.txt)

**Comment by XFactHD** [comment]
This is a known issue related to connected textures support in FramedBlocks. I have a fix in the pipeline but cannot release it at this time. You can work around the issue on your side for now by setting the `conTexMode` option in the `framedblocks-client.toml` config to `NONE`

**Comment by Sotabi** [comment]
Fixed the Issue for me, thank you very much!
