### ISSUE TITLE
Other Dimension Crash

### ISSUE THREAD

**Issue by Freakyman403** [AllTheMods/ATM-9#319]
Going to the other Crashes the server.

https://mclo.gs/CL9tcll

**Comment by Alucard1313** [comment]
Same happened in my world, but the server not crashed.

**Comment by Freakyman403** [comment]
I think i have found the cause of the issue
![image](https://github.com/AllTheMods/ATM-9/assets/6248310/7c2cf440-9bf6-46e6-9ea0-777757ca3ef4)

**Comment by LamaFahrrad** [comment]
I have this Problem too, is there a way to fix this?

**Comment by Freakyman403** [comment]
Only way i found to fix it is, Create a new world in creative, goto the other and use "/forge generate" i used 24K for my server, but i would recommend between 8K - 12K
