### ISSUE TITLE
Extreme Reactor Fluidizer requires Yellorium which is unobtainable

### ISSUE THREAD

**Issue by MSandro** [AllTheMods/ATM-9#320]
there is no recipe for Yellorium Ingots, but the parts of the fluidizer Multiblock like the fluidizer casing requires it in its recipes.
![image](https://github.com/AllTheMods/ATM-9/assets/10937159/3352b0e2-e95b-491c-a8ec-59b27e600ba1)
Please change it to uranium.

**Comment by DynamicReality1** [comment]
This issue is still present, just commenting so it gets recognized again.

**Comment by McKitten** [comment]
Put Uranium in the reactor and eject it again, the result will be Yellorium.

**Comment by wraithhawit** [comment]
still should get fixed with kubeJS. no reason to have to go through extra steps for a problem that shouldn't exist in the first place

**Comment by ShadedPL** [comment]
This is fixed in 0.2.1
