### ISSUE TITLE
unable to upgrade from 0.62 to 0.63 in the curseforge app

### ISSUE THREAD

**Issue by gzcwnk** [AllTheMods/ATM-9#322]

**Comment by Mitchell5200** [comment]
Known, the FTB app seems to work, as do 3rd party apps

**Comment by Tolgajk3** [comment]
dont work to update

**Comment by zappermax** [comment]
0.63 a beta for a reason,
Look at the changelog before posting a Git issue

**Comment by chengheipui** [comment]
63 is on release now, so the curseforge issues should've been fixed.

**Comment by Sargauss** [comment]
Still doesn't work for me, mentions a problem with shaders, restores back up and cancels.

**Comment by trephas** [comment]
This still is a problem for me with the curseforge app. I even tried making updating to a new profile and it did the same thing

**Comment by aAndrew3030** [comment]
Curesforge released a update for the app to fix this issue

**Comment by trephas** [comment]
can confirm after restarted curseforge app it updated fine. Thank you
