### ISSUE TITLE
Client crashed in Creative Mode 

### ISSUE THREAD

**Issue by nico1972weimar** [AllTheMods/ATM-9#335]
0.0.63 Client crashes when pressing E key for inventory.
Tested in Creative Mode.
 Survival Mode, the error does not appear
[crash-2023-09-05_15.11.24-client.txt](https://github.com/AllTheMods/ATM-9/files/12523992/crash-2023-09-05_15.11.24-client.txt)

**Comment by J-Dill** [comment]
I do not see the mod NoMoWanderer in the 0.0.63 version. I think this issue can be closed.
