### ISSUE TITLE
Overlapping item recipe: Construction wand in the mods: Structurize and Construction Wand 

### ISSUE THREAD

**Issue by LibriMine** [AllTheMods/ATM-9#337]
To Build the Construction wand you can use any type of stick and stone, so you have a problem. 
Both take both recipes to craft an item. in my case i want the Structurize Structurize tool (the wand) but i can just craft the wand from the Construction Wand mod

**Comment by McKitten** [comment]
Does polymorph (symbol above the output) not trigger with options for you?
