### ISSUE TITLE
[ATM9 - 0.0.64] Game crash on bulk crafting

### ISSUE THREAD

**Issue by Cattman423** [AllTheMods/ATM-9#341]
I was crafting some tier one stack upgrades from Sophisticated Storage. I wanted to make two of them so I shift-clicked two from the crafting table in to my inventory. This caused my game to crash every time I load back into the world. 

I was doing this as the host on my local network

[crash-2023-09-06_16.28.43-client.txt](https://github.com/AllTheMods/ATM-9/files/12543237/crash-2023-09-06_16.28.43-client.txt)

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of sophisticated storage so just updating to that prevents the crashes

**Comment by Cattman423** [comment]
Yes, I am no longer crashing on version 0.0.65
