### ISSUE TITLE
Jetpack Vertical Hover Speeds

### ISSUE THREAD

**Issue by wraithhawit** [AllTheMods/ATM-9#348]
I've been noticing that even with emerald jetpacks the vertical hover speeds are painfully slow, even slower than vanilla creative flight, I've developed a formula to keep the feeling of fighting gravity while going up and still move at decent speeds. I've pre configured it in the zip for you.

speedHoverAscend = speedVertical 
speedHoverDescend = speedVertical + speedHover

[jetpacks.zip](https://github.com/AllTheMods/ATM-9/files/12561867/jetpacks.zip)

**Comment by JayPKinger** [comment]
These speeds are super rough
