### ISSUE TITLE
game fails to launch reason Connection lost invalid player data

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-9#352]
0.0.65 update 
seeing 
Connection Lost
Invalid player data 
using ATLauncher

**Comment by gbusrt** [comment]
well i kill everything relaunch the launch and now the game works 
nuts

**Comment by Ghostmonk125** [comment]
What do you mean you killed everything? I'm having the same issue.

**Comment by gbusrt** [comment]
switch it all off and then on and relaunched the pack
