### ISSUE TITLE
Missing items in ProductiveBees quests

### ISSUE THREAD

**Issue by Seeloewen** [AllTheMods/ATM-9#353]
While I know that the quests were only partially ported yet, I thought it would be helpful to be informed about some of the issues that I've found so far, especially in the ProductiveBees category.

First off, the task for the Quarry Bee requires stone chips, which are no longer part of the mod.
Secondly, the lumber bee needs wood chips, which were also removed.
Lastly, there is a quest for a fluorite bee, but no such bee exists making the quest impossible as well.

Additionally, I've found a minor issue in the text formatting of one of the quests, there's an extra line in the description of the Crimson ShroomBee (See image below)

![image](https://github.com/AllTheMods/ATM-9/assets/74246933/bec0cfd7-d6f3-49bb-91f9-15ad267559aa)

I'm using version 0.0.65 of the modpack.

**Comment by alfredggttv** [comment]
This will be fixed in a future version. Thank you!
