### ISSUE TITLE
[0.1.0] Advanced Peripherals Colony Integrator missing recipe

### ISSUE THREAD

**Issue by Brother-Blue** [AllTheMods/ATM-9#354]
Not an urgent issue but would be nice to have this recipe added

**Comment by adkinss** [comment]
Just came here to create an issue for this as well.  As of 0.1.6, there isn't a recipe for the Colony Integrator.

**Comment by wildmanjuljul** [comment]
Issues is also linked with this #256 not sure if there is correlation or api issues. The ME link from AP has a recipe unlike the RS link and the Integrator.
