### ISSUE TITLE
Osmium seeds not craftable

### ISSUE THREAD

**Issue by Seeloewen** [AllTheMods/ATM-9#356]
The Osmium seeds needed for one of the Mystical Agriculture quests has no crafting recipe. Furthermore, they don't even seem to exist since both the seeds and their essence are not in JEI.

I'm using Version 0.0.65 of the modpack.

**Comment by ShadedPL** [comment]
Same with Fluorite Seeds. Unable to finish the questline.

**Comment by ShadedPL** [comment]
this one can be closed since Mekanism and it's seeds are now added
