### ISSUE TITLE
'Tips and Tricks' quest category not being marked as completed

### ISSUE THREAD

**Issue by Seeloewen** [AllTheMods/ATM-9#357]
The 'Tips and Tricks' quest category is not being marked as completed (green in the sidebar), even though all of the quests have been completed. Am I missing something or is this a bug?

![image](https://github.com/AllTheMods/ATM-9/assets/74246933/83af1113-3a55-4fd1-abc8-3b7fc711aff3)

I'm using version 0.0.65 of the modpack.

**Comment by alfredggttv** [comment]
Can you confirm that it is still happening in the latest version?

**Comment by Seeloewen** [comment]
Still looks the same in 0.1.12. Maybe that's just how it's set up? To always be blue? Similar can be seen in the Main Questline.
![image](https://github.com/AllTheMods/ATM-9/assets/74246933/49fb4740-a539-41ac-b06e-a603efe63beb)

**Comment by alfredggttv** [comment]
Ah, it's because I gave it a color. lol That solves it!
