### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by Typositoire** [AllTheMods/ATM-9#359]
Hello, for some reason I'm unable to launch ATM9 from PolyMC, other packs work well I've tried multiple version and nothing works.

https://mclo.gs/y6OIiMv

Is it related to PolyMC or ATM9?

EDIT: Just to be safe I tried JDK 19 and JDK 17 too, they gives me this error while JDK 20 just isn't compatible and refuses to start. I'm pretty sure this eliminates any potential Java issue being the cause.

**Comment by nitrog0d** [comment]
Try Prism Launcher maybe?

**Comment by Typositoire** [comment]
Oh never heard of Prism Launcher, let me try, I use the official JDK from Oracle.

**Comment by Typositoire** [comment]
Well turns out it works with Prism Launcher and JDK 17 Thanks a lot!
