### ISSUE TITLE
RFToolsStorage Ui Glitch/Bug/Fault Double Quantity Item Counter 

### ISSUE THREAD

**Issue by OVossoMarco** [AllTheMods/ATM-9#36]
![UIRftoolsStorage](https://github.com/AllTheMods/ATM-9/assets/80985825/9bf4ec16-e40b-48dc-abd7-d39b2bd1ab0c)

**Comment by OVossoMarco** [comment]
Its Pretty Self Explanatory Here So As Shown Above Some Of The Item Counters Are Duped, No Matter How Many Storage Scanners I Make Survival Or Creative Worlds Its Dupped On Some Always, To Be Checked On With Time And Pattience, No Rush, Its Still Managable The Way It Is, Good Work #allthemodsRFTOOLSSTORAGE

**Comment by Batlh** [comment]
Well this ui bug is still in the latest version of the modpack. It's sometimes rly annoying to divide it with 2 if you have like 32k+ items of the same thing in your storage. would be glad if this could be fixed in a patch somewhere down the road...

**Comment by Kevin-Marsh** [comment]
This is cause by connecting double chests to the storage scanner and can't be fixed. It registers them as 2 chests with identical items.
