### ISSUE TITLE
[ATM9 - 0.0.67] Game crash when attempting to adjust cover settings

### ISSUE THREAD

**Issue by Cattman423** [AllTheMods/ATM-9#362]
I have experienced multiple game crashes when attempting to change the settings on an LV pump cover module. The first two times experienced this crash the pump was on a bronze fluid pipe, the third time I was using the cover settings GUI on a Super Tank 1. I attempted to recreate the crash with a conveyer module, however that worked as intended. The fourth crash was attempting to adjust an MV pump cover module on an MV ore washer via the ore washer's GUI. I have not tried anything else at this time, I will also send this report to the GTCEU dev team.

Crash report 1;
[crash-2023-09-10_14.11.33-server.txt](https://github.com/AllTheMods/ATM-9/files/12570845/crash-2023-09-10_14.11.33-server.txt)

Crash report 2;
[crash-2023-09-10_14.40.09-server.txt](https://github.com/AllTheMods/ATM-9/files/12570847/crash-2023-09-10_14.40.09-server.txt)

Crash report 3;
[crash-2023-09-10_15.01.17-client.txt](https://github.com/AllTheMods/ATM-9/files/12570848/crash-2023-09-10_15.01.17-client.txt)

Crash report 4;
[crash-2023-09-10_15.06.53-client.txt](https://github.com/AllTheMods/ATM-9/files/12570849/crash-2023-09-10_15.06.53-client.txt)

**Comment by screret** [comment]
Fixed in the latest GT release.

**Comment by Cattman423** [comment]
Will that be part of ATM9 0.0.68?

**Comment by Wtfigohere** [comment]
Where can i get atm9 .66 or .67?
