### ISSUE TITLE
AE2 System won't let me pull out items

### ISSUE THREAD

**Issue by madleit** [AllTheMods/ATM-9#37]
Sometimes my AE2 system wont allow me to pull or craft items using the crafting terminal. Then I need to re-arrange the ME disks and it works again for while.

**Comment by JakeMoe** [comment]
I've got a similar problem; I can't pull items out of my Crafting Terminal, but I can start autocrafting.  If I pull the ingredients from JEI and arrange them, I can extract the crafted item.  And my Wireless Crafting Terminal works fine, it only seems to affect wired one.

Moving disks in my ME Drive didn't help, but most of my items are stored in Functional Drawers via a Storage Controller attached to a Storage Bus.  The Storage Buses are configured with highest priority and are bi-directional.

----

While writing this up and checking a few more things, I realized it started happening after I added some wireless boosters to my access point, and long story short, it looks like I was choking on power slightly.  Not enough to bring the system down, but enough that it wouldn't let me craft.  Added more generation and my battery started filling again and the Crafting Terminal started working.  So @madleit you might check that?
