### ISSUE TITLE
Server hangs on chunk generation

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-9#376]
When generating new chunks the server often hangs up completely, until the watchdog kills it. Sadly there is no error or crash log at all.

This did not happen before 1.0, but suddenly appeared in 1.0. It happens in single- and multiplayer.

**Comment by metroidboy** [comment]
I also have the same problem
I have noticed that when it happens the world somewhat freezes you can't interact with anything else in the world and you can't save and guit

**Comment by chengheipui** [comment]
having the same issue with 0.1.0 version

**Comment by SimonSoby** [comment]
Having same kind of issue on singleplayer world. Can move freely around, but can't do anything. Log said something with a tick took longer than 40.000 mili seconds

**Comment by Acetyld** [comment]
Same here

**Comment by olivia-mativi** [comment]
I've noticed that teleporting to areas previously undiscovered reliably reproduces this issue, though it seems to happen when traveling normally as well.

**Comment by twothe** [comment]
Problem has NOT been solved with the 1.1 update. Server immediately crashed when players started moving around.

**Comment by twothe** [comment]
Additional info:
It seems that sometimes the server keeps running, just new chunks are no longer generated, because the generation thread hangs completely.
![image](https://github.com/AllTheMods/ATM-9/assets/1131621/078a4846-6a61-4fc7-abd9-7b8f7ba8fe7b)
Players can normally play, but as soon as they enter a not yet generated chunk, the server runs into a timeout and dies.

Seems like some mod authors are challenged by the new threaded generation.

**Comment by isharris1** [comment]
0.1.1 patch still crashing.  Log attached.
Was a new 0.1.0 world, crashed several times in 0.1.0.
Updated to 0.1.1 still crashing when moving into new chunks (but not every new chunk it feels?)

[crash-2023-09-16_13.10.19-server.txt](https://github.com/AllTheMods/ATM-9/files/12640660/crash-2023-09-16_13.10.19-server.txt)

**Comment by twothe** [comment]
The problem seems to be fixed with 1.2. Server running smooth for over an hour now.

**Comment by isharris1** [comment]
Yeah seems fixed for me too!  Thanks and well done for the quick turn around!

**Comment by screret** [comment]
> Sidenote: Greg-Tech ores can still be generated by using Boon of the Earth enchant, so you could keep it like this and call it Greg Mode. ;)

on this, we're working on fixing the actual issue behind this. First patch will be limiting vein size back into standard limits, and in the future, we're doing a revamp of how we generate the ores to make them actually work as intended again.

**Comment by Techno3d** [comment]
Hey guys, does anyone know what the issue ended up being here? I wanted to see if I could use that information to fix a server my friends run that is hanging on generating chunks at 10,000+ coords

**Comment by Techno3d** [comment]
> > Hey guys, does anyone know what the issue ended up being here? I wanted to see if I could use that information to fix a server my friends run that is hanging on generating chunks at 10,000+ coords
> 
> As so often: Greg Tech.
> The issue was fixed in a later patch iirc so updating the pack should solve it. Otherwise deactivating greg tech should also help.

Ah, thanks for replying. Looks like the pack me and my friends made doesn't have Greg Tech, so we still got some searching to do :p. Thanks!

**Comment by skadlig** [comment]
> Ah, thanks for replying. Looks like the pack me and my friends made doesn't have Greg Tech, so we still got some searching to do :p. Thanks!

Did you ever figure out the cause? Facing similar issue without Greg tech.

**Comment by Leonature26** [comment]
> > Ah, thanks for replying. Looks like the pack me and my friends made doesn't have Greg Tech, so we still got some searching to do :p. Thanks!
> 
> Did you ever figure out the cause? Facing similar issue without Greg tech.

Did you also figure it out? It happens on my custom modpack with 300+ mods after pregenerating for a while. I'm guessing there's a problematic mod that breaks the game when generating its structure. All I see in my logs are "IO-Worker" and "JM-texture" on timed_waiting.

**Comment by Techno3d** [comment]
> > > Ah, thanks for replying. Looks like the pack me and my friends made doesn't have Greg Tech, so we still got some searching to do :p. Thanks!
> > 
> > 
> > Did you ever figure out the cause? Facing similar issue without Greg tech.
> 
> Did you also figure it out? It happens on my custom modpack with 300+ mods after pregenerating for a while. I'm guessing there's a problematic mod that breaks the game when generating its structure. All I see in my logs are "IO-Worker" and "JM-texture" on timed_waiting.
> 
> Edit: saw on a reddit post suggesting it might be dungeon crawl causing a cascading worldgen. Tried removing it and pregenerating again, it seems the server doesn't hang anymore.
> 
> Edit2: Nvm server froze even without dungeon crawl. Now I tried to remove overhauled village mod but I'm not sure anymore if it will happen again.

Sadly no. We just had to try teleporting him out of those chunks in the small time frame we had when he joined before the server crashed. That server's been dead for a bit now, so I don't remember that many specifics, but all I remember is that we couldn't find anything in the logs that pointed to anything specific.
