### ISSUE TITLE
[ATM9 - v0.1.0] Allthemodium doesn't spawn

### ISSUE THREAD

**Issue by Voltury** [AllTheMods/ATM-9#382]
I have started a new world with ATM9 v0.1.0 and can not find allthemodium.
Even with x-Ray i can't find it in the deep dark biome, ancient city, mining dimension or the other.
Vibranium and Unobtanium spawn normally.

**Comment by motivo** [comment]
Same for me

**Comment by ImTehCookie** [comment]
Same here, spent 2-3 hours nonstop looking in the deep dark, ancient cities but nothing, never got to the mining dimension because of that so I can't confirm if it spawns/doesn't spawn for me there

**Comment by SkrimanS** [comment]
Is it just me or is the latest version of the allthemodium ore server not generate?
