### ISSUE TITLE
[0.1.0] PneumaticCraft's Sound Bug

### ISSUE THREAD

**Issue by ANZUARIAKE0127** [AllTheMods/ATM-9#384]
As mentioned briefly in the Discord, I am formally reporting the title problem and its solution.

**Description:** Scancode.123(no convert in JIS IME), 46, 48(Volume up/down) keys will sound the minigun spin-down. like this: [video](https://www.youtube.com/watch?v=brE-Wo8RNEE)
**Solution:** update PneumaticCraft to v6.0.7 (pneumaticcraft-repressurized 6.0.7+mc1.20.1) [Changelog](https://github.com/TeamPneumatic/pnc-repressurized/blob/1.20.1/Changelog.md)
v6.0.6 does **NOT** fix this issue in my test.

**Comment by TheBedrockMaster** [comment]
Is this still an issue?
