### ISSUE TITLE
[atm9-0.1.1] Question - Recipe for Supply Ship

### ISSUE THREAD

**Issue by savosdarkran** [AllTheMods/ATM-9#387]
Pack Version: 0.1.1
Prism Launcher: 8.0-develop
Java: 17.0.8.7 Hotspot (Adoptium)

When viewing the recipe of the MineColonies Supply Ship I get red squares instead of boats.

![image](https://github.com/AllTheMods/ATM-9/assets/26523998/b0bae385-1508-4d70-b389-4c332cf80cf6)

When viewing the item, I see that the boats claim to be SGear.

![image](https://github.com/AllTheMods/ATM-9/assets/26523998/ae099d77-85d4-4d51-ba64-60718c639f6b)

The Supply Camp works fine.

![image](https://github.com/AllTheMods/ATM-9/assets/26523998/47dfbe6a-b9c2-4d7a-9967-b834feadca7a)

Just curious if this is by design.

**Comment by TheBedrockMaster** [comment]
Is this still like this?
