### ISSUE TITLE
all the 9 mods crash

### ISSUE THREAD

**Issue by Joannapro92** [AllTheMods/ATM-9#390]
please help me it is giving me exit code 1

**Comment by starlingfire** [comment]
Just a heads up: you aren't going to get any support on an issue with no information on it. No modpack version, no log, no nothing. 

Also, consider reviewing the recent issues because there's a chance your issue has already been raised.

**Comment by Joannapro92** [comment]
modpack:all the 9 mods¨//modpack won't open and shows me exit code 1

**Comment by iQSJoker** [comment]
If you're still having this issue, see this if you have an AMD GPU #211

**Comment by Joannapro92** [comment]
something is wrong with the forge, what should I do, I really want to run after the modpack
