### ISSUE TITLE
FTB essentials isn't respecting config changes.

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-9#393]
defaultconfigs>ftbessentials-server
Changed to enable /back and "Cooldown between /home commands (in seconds)" "cooldown" to 0, 604800, and to 1 nothing changed. Cooldown still 2h 46m.
/back also not working despite being enabled in configs. "Unknown or incomplete command."

**Comment by Mitchell5200** [comment]
`/world/serverconfigs/`, not default configs, stop the server first.
