### ISSUE TITLE
[0.1.1] Allthemodium/Vibranium/Unobtanium Jetpack Refined Storage Pattern

### ISSUE THREAD

**Issue by xBlackPoison357x** [AllTheMods/ATM-9#394]
Creating a pattern for allthemodium, vibranium or unobtanium jetpack gives you an Invalid pattern: Recipe doesn't exist. You can put it into a crafter and it still works however. 

All the Mods 9-0.1.1

![vibranium jetpack](https://github.com/AllTheMods/ATM-9/assets/4401213/164af9aa-4fd6-41a8-926c-c14c494e7b0f)
![unobtanium jetpack](https://github.com/AllTheMods/ATM-9/assets/4401213/dfd58ae0-c21d-49a8-a6cc-0c8d027c735d)
![allthemodium](https://github.com/AllTheMods/ATM-9/assets/4401213/b674027d-f14d-4a65-b548-7b682b9eb0e8)

**Comment by TheBedrockMaster** [comment]
Is this still a problem? Add bug label.
