### ISSUE TITLE
Broken silent gear rewards from quests

### ISSUE THREAD

**Issue by RJE95** [AllTheMods/ATM-9#397]
Rewards for random silent gear items from the quests does not appear to be working. The specific one I encountered was from the Loot Chests quest (under Part 1: Getting Started) and the reward gave the error for an unknown or incomplete command in chat (/sgear_random_gear @p silentgear:pickaxe 2)
I am playing on ATM9 version 0.1.2

**Comment by Amunsul** [comment]
I had the same issue, have experienced it a couple times now. The most recent was from completing the Sophisticated Backpacks quest. In chat it gave the error:

Unknown or incomplete command, see below for error
sgear_random_gear @p silentgear:hammer

The previous time i got the error i dont recall what the quest was but it gave basically the same error except it was hammer 2 instead of hammer 3.

I am also playing on ATM9 1.2

**Comment by WyFryMU** [comment]
Same issue on 0.1.3, what's odd is the command runs if you type it in normally.

**Comment by RJE95** [comment]
> Same issue on 0.1.3, what's odd is the command runs if you type it in normally.

That's interesting, because for me it didn't recognise the command at all when I tried to run it manually. It didn't recognise /sgear_random_gear as a command. Do you play with cheats enabled on your game by any chance?

I will update and test again to see if it is recognised for me on the latest version.

**Comment by RJE95** [comment]
After updating to 0.1.3 and testing, it appears that the silent gear quest rewards only work if cheats are enabled at world creation. The command is also recognised if typed into chat with cheats enabled, but appears unrecognised if cheats are off (which they are by default). I also tested by redeeming the rewards from the quests directly. I'm not sure if there's a way around this without cheats being enabled for everyone, but hopefully this narrows down the issue.

**Comment by contra1337** [comment]
issue still exists on 0.1.11

![image](https://github.com/AllTheMods/ATM-9/assets/9068381/837acd43-6675-4451-b996-91012e5238a5)

**Comment by TheBedrockMaster** [comment]
Is this fixed?

**Comment by ToshibaEC0Microwave** [comment]
This should finally be fixed for next update and soon will be fixed for the other modpacks
