### ISSUE TITLE
[0.1.0] /back shows "Teleportation history is empty!"

### ISSUE THREAD

**Issue by Brother-Blue** [AllTheMods/ATM-9#398]
I've tried using /back in a few different scenarios, both as an operator and a normal player. Each time no matter if it's after /home, /spawn, or after death, it always returns as "Teleportation history is empty". I have the ftbessentials.snbt configured as follows:
```
teleportation: {
    back: {
	cooldown: 10
	enabled: true
	max: 0
	only_on_death: false
	warmup: 0
    }
}
```

I'm currently running version 0.1.0 in case this was addressed in a later version.

**Comment by dramo2002** [comment]
i found the probleme

![Capture d’écran 2023-09-19 170855](https://github.com/AllTheMods/ATM-9/assets/96302150/c316f2ff-d46d-4e81-9961-05dde52ea6d0)

**Comment by Brother-Blue** [comment]
Can't believe I missed that entirely, many thanks!
