### ISSUE TITLE
upgrading from 0.065 to 0.1.3 trashes base

### ISSUE THREAD

**Issue by gzcwnk** [AllTheMods/ATM-9#404]
Can you please make older versions of the server easily findable/available?   I want to try upgrading to 0.1.0 then 0.1.1 then 0.1.2 and finallt 0.1.3 but cant locate these 3 server packs.

**Comment by twothe** [comment]
All servers can be downloaded from CurseForge. They have a record of every version released.

**Comment by gzcwnk** [comment]
I looked, impossible to find.  hence "make easier"

Corruption/loss of chunks happens from 0.65 to 0.1,  or  0.1.1, or 0.1.3.  Chunks seem to be reset to virgin state.

**Comment by Mitchell5200** [comment]
Each server pack is attached to each client release on CF, click on each version and scroll down past the changelog.
As for "trashes base" we did recommend new worlds for users once we did our 0.1.0 release

Files tab, https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files
0.1.0 server pack https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4752160
0.1.1 https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4753674
0.1.2 https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4755774
0.1.3 https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4756123
![Screenshot 2023-09-21 16 28 39](https://github.com/AllTheMods/ATM-9/assets/45913837/a888c90d-0b95-4870-9822-7d192a8a8475)
