### ISSUE TITLE
claiming quest lootbox reward in one quest autoclaims other quest lootboxes

### ISSUE THREAD

**Issue by aofsupporter** [AllTheMods/ATM-9#408]
atm9 version 0.1.3
example case: Powah quest chapter, blazing cable and niotic cable quests

elsewhere in the Powah quest lines, I was rewarded 2 niotic cables.  I had not made any blazing cables at the time, so the niotic cable quest got the grey checkmark like normal as a locked quest.  Later, I went back and crafted some blazing cables which properly completed both quests (green checkmarks).

When I clicked on the blazing cable's lootbox reward, the niotic cable's lootbox claimed at the same time.  I ended up with 2 energized steel ingots via 2 toast announcements, so I guess I got a duplicated roll of the blazing loottable rather than a blazing roll and an empty roll for niotic.

**Comment by alfredggttv** [comment]
I cannot replicate this issue. This might have been fixed in a newer version of the mod.
