### ISSUE TITLE
[Suggestion] Quarryable raw ores? Allthemodium, Vibranium and Unobtainium

### ISSUE THREAD

**Issue by KaranMaia** [AllTheMods/ATM-9#412]
Just a suggestion, I don't know if you guys noticed but the mods added by Allthemods can be quarryed by the ore laser base from industrial foregoing.

If it's intended, just ignore this hahaha

Thanks, nice work with the modpack!

![image](https://github.com/AllTheMods/ATM-9/assets/73917457/efd15961-26f8-4797-973b-142eb6d39583)

**Comment by Mitchell5200** [comment]
that's intentional and was added by Us, and is added via Kubejs, example below
https://github.com/AllTheMods/ATM-9/blob/main/kubejs/data/industrialforegoing/recipes/laser_drill_ore/raw_unobtainium.json
