### ISSUE TITLE
Reliquary tipped saturation arrow crashes the client

### ISSUE THREAD

**Issue by 727Enjoyer** [AllTheMods/ATM-9#415]
Once the lingering saturation potion is combined with the arrows to make tipped ones (which is not doable in the ME system) in a crafting table, the game crashes

**Comment by Philogex** [comment]
i think this is an issue with all condensed potions from reliquary.
i attached my last crash report: [crash-2024-01-14_22.02.23-client.txt](https://github.com/AllTheMods/ATM-9/files/13933147/crash-2024-01-14_22.02.23-client.txt)
