### ISSUE TITLE
Client crash 1.5 cataclysm:bloom_stone_pauldrons

### ISSUE THREAD

**Issue by Janvier123** [AllTheMods/ATM-9#417]
We just loaded the new 1.5 and are unable to login, as soon as we connect, the game (client) crashed

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Registry Object not present: cataclysm:bloom_stone_pauldrons

[crash-2023-09-21_11.34.27-client.txt](https://github.com/AllTheMods/ATM-9/files/12683005/crash-2023-09-21_11.34.27-client.txt)

Fixed by reverting back to 1.3

**Comment by SinisterZinn** [comment]
This issue is still prevalent in patch 1.7 server as well

**Comment by Janvier123** [comment]
> This issue is still prevalent in patch 1.7 server as well

We had the same issue with 1.7.

Long story short, we copied the new files on top of the old files, so mods where loaded twice or bad/old versions first 

_L_Enders_Cataclysm-1.29-1.20.1.jar
L_Enders_Cataclysm-1.34 -1.20.1.jar_

Both where loaded at startup.
**Anyway we fixed by renaming the "mods" folder to "mods_old" and copied the new mods from 1.7, booted server, all fixed!**

As far as i know, issue is fixed
