### ISSUE TITLE
Gregtech recipes broken

### ISSUE THREAD

**Issue by Sargauss** [AllTheMods/ATM-9#423]
After new update no gregtech recipe is valid. All my patterns for it in ae2 system are now broken.

**Comment by Kiccat** [comment]
Try doing /reload I'm pretty sure they mention this in the change log for 1.4; everything mostly works for me.

**Comment by Sargauss** [comment]
Ah, okay. I'm using a server so maybe restarting it will fix it. Will try.

**Comment by teriak47** [comment]
> Try doing /reload I'm pretty sure they mention this in the change log for 1.4; everything mostly works for me.

this didn't work for me.

**Comment by Sargauss** [comment]
Didn't work for me either

**Comment by Sargauss** [comment]
Just gonna go manual on this and get the latest gregtech file see if that works.

**Comment by Sargauss** [comment]
And that fixed it. Download latest file and the machines are working again, recipes back on.

**Comment by Sargauss** [comment]
Had to roll back on version down from latest build in Gregtech due to laser engraver lens recipes not working. Is working now.
