### ISSUE TITLE
[v0.1.6] Empty Mining Dimension

### ISSUE THREAD

**Issue by jonasfuegen** [AllTheMods/ATM-9#428]
When loading up the mining dimension in v0.1.6 it doesn't generate any ores at all.

**Comment by Seb1337** [comment]
Got the same Issue yesterday.
I managed to got ores to generate after i **downgraded** the 
**gtceu-forge-1.20.1-1.0.12.e.jar**  
in the mods folder to
**gtceu-forge-1.20.1-1.0.12.b.jar**
which is present in the version 0.1.5 from the Modpack.
And then deleted the dimension from the world folder, aswell as deleting the folder "libraries" "local" and "modernfix"  from the server.

**Comment by jonasfuegen** [comment]
Fixed in v0.1.7
