### ISSUE TITLE
Iridium seed not seeding

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/ATM-9#431]
I got an iridium seed as a random reward and noticed gregtech had some recipes for it so I thought I'd make a chest full. The result was minimal fertilized essence (a good thing/waste priduct imo) and the rest was iridium essence.
No seed in the entire 500 (after crafting) Iridium chest.
Might want to check the fluorite seed also, I've heard that was given as a random reward also.

**Comment by loving2** [comment]
Fluorite seeds should work in the latest version, and the iridium seed has been removed from the loot table. Thank you for reporting this issue!
