### ISSUE TITLE
0.1.16 Ore Gen issue/ AE2 universal Terminal1

### ISSUE THREAD

**Issue by Jaillhouse** [AllTheMods/ATM-9#432]
Only finding Greg Tech ore in mining Dimension and No coal anywhere looks like it may be all vanilla resources no iron gen overworld or mining dim.  AE2 Wireless Universal Terminal will kick from server until item is removed from inventroy.

**Comment by BFWingsII** [comment]
I can confirm.  No vanilla ores are generating.

**Comment by kuriyna** [comment]
Just came here to see if anyone was running into the same issue.

**Comment by MrTestificate1** [comment]
Is this fixed in 0.1.17?

**Comment by Jaillhouse** [comment]
After 0.1.17 issue was corrected
