### ISSUE TITLE
Gregtech laser engraver chip recipes broken

### ISSUE THREAD

**Issue by Sargauss** [AllTheMods/ATM-9#433]
Had to roll back to c version (currently on e standard package) to get the laser engravers working again, as it no longer recognized the lenses in latest gregtech version.

**Comment by kolan4ick** [comment]
+1

**Comment by Sargauss** [comment]
latest update seems to have fixed this

**Comment by kolan4ick** [comment]
> latest update seems to have fixed this

Which one? I have 0.1.7, but crafts with orange lens and one more (I don't remember) are broken.
