### ISSUE TITLE
Modd suggestion: CalcMod

### ISSUE THREAD

**Issue by shadeydo** [AllTheMods/ATM-9#438]
CalcMod is a calculator in your Minecraft chat with extra features to determine farm rates, generate random numbers, convert between Overworld and Nether coordinates, and a bunch of other nerdy things. CalcMod is more catered to technical Minecraft players, but is useful to all. it's lightweight and unintrusive. It would be a good fit for ATM because very helpful for any minecraft calculations!

Heres a link to the mod page:
[https://www.curseforge.com/minecraft/mc-mods/calcmod](https://www.curseforge.com/minecraft/mc-mods/calcmod)

**Comment by screret** [comment]
post this to #1 please, not a separate issue.
