### ISSUE TITLE
[0.1.7] Dragon Egg doesn't spawn

### ISSUE THREAD

**Issue by Brother-Blue** [AllTheMods/ATM-9#441]
After spawning and defeating the end dragon again with the ritual, there is a structure that spawns where the initial portal back to the overworld was but no dragon egg spawns.

**Comment by AaronFosco** [comment]
I too am having this issue.
The structures are from YUNG's end island mod and More Dragon eggs mod is what should have added a dragon egg for a respawned dragon. However, it looks like More Dragon eggs is overwritten by YUNG's island mod.

**Comment by Mass1milian0** [comment]
this issue is still relevant in version 0.1.11 and 0.1.12 (both were tested)

**Comment by Kevin-Marsh** [comment]
This has been fixed in newer versions.
