### ISSUE TITLE
Potential Fix Found - MineColonies Supply Ship Recipe Does Not Work

### ISSUE THREAD

**Issue by Caprikey** [AllTheMods/ATM-9#442]
Unable to craft the Minecolonies Supply Ship. 

Supply Ship is available in JEI. 

When you click on the Supply Ship in JEI, the crafting recipe menu is opened but the crafting recipe shows 5 red squares with diagonal lines through them. When hovering over the red items, they display the error: "Empty Tag: minecraft:boats".

If you have 5 crafted boats in your inventory, the "Move To Crafting Table" button will show, but you when clicked, it shows "Missing Items" error. 

- I can craft boats with no issue. 
- I can craft Supply Camp item. 
- Placing the boats manually in the crafting table/crafting table on a stick grid in the correct layout shows incorrect recipe (No item shows in result/crafted box). 
- Issue occurs on two computer with different accounts. 
- Issue has occurred with version 0.1.2 and 0.1.6.
- I posted the error on MineColonies github, they advised the bug is on the Modpack's side. 

![MineColonies-SupplyShip-Error](https://github.com/AllTheMods/ATM-9/assets/5361497/85056d92-0311-4155-b7f9-0f293734096e)
![MineColonies-SupplyShip-Error2](https://github.com/AllTheMods/ATM-9/assets/5361497/9828bab2-d7b5-477e-90ba-45578ef8814e)
![MineColonies-SupplyShip-Error3](https://github.com/AllTheMods/ATM-9/assets/5361497/865e2379-db91-4ec0-bf34-9dd2c8a51933)

**Comment by Caprikey** [comment]
Potential Fixed Found. 

I was able to locate a block of code in the tags.js file under the server_scripts folder of the kubejs directory.

The block of code is on lines 81-97, with line 80 being a commented header.  The commented header indicated the following code was being utilized as a temporary fix for boat tag being broken due to the bambooeverything mod version prior to 2.2.4. However, the BambooEverything mod is currently on version 3.0.3, and according to the outdated github changelog, bambooraft was removed as of build 2.3.0. (Thus the need for the fix above).

Commenting out lines, 81-97, in the tags.js file has resolved the issue with the Supply Ship Recipe not working. 

I do not know if said fix has generated any other issues.

**Comment by Caprikey** [comment]
Appears to be have been corrected and committed by @whatthedrunk here: https://github.com/AllTheMods/ATM-9/commit/ed7a9de3b9d4949378162acee5db21e68f54b3fa

If my understanding is correct. You can mark as closed. I don't want to mark it closed, just incase I'm an idiot haha.

**Comment by Mitchell5200** [comment]
Yes, Closing
