### ISSUE TITLE
integrated dynamics storage terminal not working on servers

### ISSUE THREAD

**Issue by immaduck** [AllTheMods/ATM-9#443]

**Comment by MitchellMarx** [comment]
Attempting to open a terminal causes 
<img width="1478" alt="image" src="https://github.com/AllTheMods/ATM-9/assets/761006/706b7ae4-0727-4819-b571-1197b0f824ec">

**Comment by LyraelRayne** [comment]
See https://github.com/CyclopsMC/IntegratedTerminals/issues/112
