### ISSUE TITLE
Entangled Blocks crashing server when player loading them joins.

### ISSUE THREAD

**Issue by Kurunoa** [AllTheMods/ATM-9#45]
When a player joins and has Entangled Blocks in use for say, a quarry, the server can lock up/crash with a watchdog error.

I found a pattern to the crashes.

If you extract items and such from the red entangled block, that is crashy.
If you extract items and such from the real-block the entangled block is linked to, no crashes.
Inserting items works fine for either.

**Comment by fishermedders** [comment]
any updates on this? my world has this issue as well.
