### ISSUE TITLE
Crashing when using building gadgets Copy-paste Gadget - ATM 9-0.1.7

### ISSUE THREAD

**Issue by MortenSkildpadde** [AllTheMods/ATM-9#451]
I tried using building gadgets Copy-Paste Gadget to copy a build including only vanilla items though with things like banners and when i put the gadget into paste mode, my game crashed and has been crashing when i try to load my world since that. I honestly don't know what to do, can i just disable the Building Gadgets mod?
[crash-2023-09-24_22.43.57-client.txt](https://github.com/AllTheMods/ATM-9/files/12709637/crash-2023-09-24_22.43.57-client.txt)

**Comment by metroidboy** [comment]
I have the same exact problem 
This is the crash report [https://mclo.gs/Qtem2bd](url)

**Comment by MortenSkildpadde** [comment]
I have removed the Building Gadgets 2 mod from the modfolder... I can load my world then
