### ISSUE TITLE
ATM9 0.1.7 Forge Missing Tags on Gregtech

### ISSUE THREAD

**Issue by SakiSkai** [AllTheMods/ATM-9#454]
Running the latest server version at the moment. Laser engravers from gregtech require lenses. I had them automated and working before but in the latest update they broke. When I look in JEI for the wafer recipes I get Empty Tag: forge:lenses/brown. I have also tried /reload to no effect if that's relevant. I am providing a screenshot as well: https://prnt.sc/8M9MaH5aBCBV

**Comment by screret** [comment]
Next GT update will fix this.
