### ISSUE TITLE
end ?

### ISSUE THREAD

**Issue by Blackspack** [AllTheMods/ATM-9#459]
idk what is but my end is strange 
![image](https://github.com/AllTheMods/ATM-9/assets/95555897/6b7395ad-7af3-44f7-bcb1-28cde9a9a564)
![image](https://github.com/AllTheMods/ATM-9/assets/95555897/85824149-2c30-4e07-a346-5b65973c4750)
and no egg and portal

**Comment by Blackspack** [comment]
hmm yung end mod have problems 
![image](https://github.com/AllTheMods/ATM-9/assets/95555897/cd602f0d-5b80-4313-87f7-9c4079c08145)

**Comment by Lalilian** [comment]
there is now a way to fix it using the command:
/end_island reset

**Comment by Blackspack** [comment]
yep it works
