### ISSUE TITLE
Dark Utilities missing recipe

### ISSUE THREAD

**Issue by iiJonno** [AllTheMods/ATM-9#46]
problem - dark utilities is missing many recipes 

Solution - update from [16.0.1]( https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/4588226) to [16.0.3](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/4610992)

**Comment by whatthedrunk** [comment]
Thanks... For some reason that dev decided he didn't want to test it against 1.20.1 and add the tag to make it easy to update. I manually did it for next update. So probably tomorrow when 0.0.33 comes out thanks!
