### ISSUE TITLE
Performance Drop, Freezing, Eventual Crash when moving too far North or East

### ISSUE THREAD

**Issue by Cal-f10** [AllTheMods/ATM-9#462]
[Error](url) Code: The game crashed whilst exception ticking world Error: java.lang.OutOfMemoryError: Java heap space

Error Report:
[crash-2023-09-25_19.19.22-server.txt](https://github.com/AllTheMods/ATM-9/files/12720403/crash-2023-09-25_19.19.22-server.txt)

**Comment by djnifos** [comment]
https://mclo.gs/EecVzxP

Here's your log on a website that makes them easier to see.  
Looks like you're allocating 4gb.  The pack needs about double at least to run.
