### ISSUE TITLE
0.1.8 Server Hang

### ISSUE THREAD

**Issue by xBlackPoison357x** [AllTheMods/ATM-9#466]
After updating my server to 0.1.8, I was having issues with it hanging and not booting. As I was preparing to rollback to 0.1.7, the server finally loaded after 1,295 seconds, compared to an average of 60 seconds in 0.1.7. Once it finished I believe I found what caused the issue:

`[26Sep2023 13:27:18.149] [Server thread/INFO] [io.redspace.ironsspellbooks.IronsSpellbooks/]: IronsWorldUpgrader finished REGION_FOLDER after 756061 ms.  chunks updated:6 chunks skipped:2864058 tags fixed:2
[26Sep2023 13:28:05.015] [spark-java-sampler-0-2/WARN] [spark/]: Timed out waiting for world statistics
[26Sep2023 13:28:10.155] [Server thread/INFO] [io.redspace.ironsspellbooks.IronsSpellbooks/]: IronsWorldUpgrader finished ENTITY_FOLDER after 52004 ms.  chunks updated:2 chunks skipped:148468 tags fixed:1`

lastest.log [https://mclo.gs/0AUOO5B](url)

**Comment by zacko27** [comment]
disable world upgrader and itll work

**Comment by HeyHooper** [comment]
Thank you. I found this config inside the World folder, under serverconfigs/irons_spellbooks-server.toml. In the first section there is  spot to turn it from true to false.

**Comment by themadjem** [comment]
I had the same issue updating from 0.1.7 to 0.1.8 and 0.1.9 separately.
I noticed that just before the Updater ran, my server had issues loading config information for the mod and set all of the spells to default values. All of my spells are like the following now 
![image](https://github.com/AllTheMods/ATM-9/assets/17654014/15beef97-c405-489b-80c4-329aa2fe1f4e)

log files from the 0.1.8 update first-start
latest.log: https://mclo.gs/KlSrco9
debug.log: https://mclo.gs/X7CeSAb

**Comment by themadjem** [comment]
Upon further investigation, the 0.1.8 update brought with it version 2.0.0 of Iron's Spells and Spellbooks. In this version, they seem to have transitioned from differentiating spell scrolls using ID numbers in their NBT data to using a string ID. 
My guess is the IronsWorldUpdater is supposed to transition existing scrolls to the new format. Turning the updater off leads to None Scrolls. I was able to just edit the NBT data using FTBLibrary's nbtedit and changed the sid of each scroll I had to be the new string ID.

Irons version 1.2.1:
![image](https://github.com/AllTheMods/ATM-9/assets/17654014/ef8f8a0b-064a-49b6-9103-0d2945931fd8)
Irons version 2.0.0
![image](https://github.com/AllTheMods/ATM-9/assets/17654014/7e6f5122-e379-4b6f-85b0-e52bbdfb8c26)

**Comment by phit** [comment]
Took about 10 min for us, with a ~8gb world file, so the process does work, its just really slow..

**Comment by lab3** [comment]
> to None Scrolls. I was able to just edit the NBT data using FTBLibrary's nbtedit and changed the sid of each scroll I had in my spellbook to be the new string ID.

@phit Is there any chance you would send us a zip of that world we can use for testing?  I could send you a dropbox upload link if so.

**Comment by lab3** [comment]
The upgrader is running slow on large worlds but will complete.  It is a one time process on a world after upgrading.  We are working on fixing the performance issue.  

https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/169

**Comment by themadjem** [comment]
> The upgrader is running slow on large worlds but will complete. It is a one time process on a world after upgrading. We are working on fixing the performance issue.
> 

I tried letting it run initially a few times and kept having fatal JRE errors, which is why I decided to continue without it. I tried it again just now and it completed in about 4 minutes without issue. 🤷🏻‍♂️
