### ISSUE TITLE
[Suggestion] Please add passive shield mod

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-9#475]
One of the major annoyance of having a shield equipped is that it needlessly blocks a big portion of your screen. The mod Passive Shield changes that, so that the shield is only rendered if it is actually in use.

https://www.curseforge.com/minecraft/mc-mods/passive-shield

I would love to see if this mod is added to the pack.

**Comment by Mitchell5200** [comment]
Use #1 For mod suggestions please, not new posts
