### ISSUE TITLE
AE2 Wireless terminal only pulling 32 items at a time

### ISSUE THREAD

**Issue by JpnRndr01** [AllTheMods/ATM-9#481]
This is occurring when the Dimensional Card is being used, without it the terminal can pull 64 at a time

Other users have posted about this problem on r/feedthebeast
https://www.reddit.com/r/feedthebeast/comments/15p2uuf/atm9_wireless_crafting_terminal_can_only_send_or

**Comment by phit** [comment]
caused by https://github.com/Hexeption/AEInfinityBooster/pull/15

**Comment by ZuruZockt010** [comment]
Is there a Fix aviable? Because the items goes in Secondary Hand

**Comment by phit** [comment]
yes, click the link in the previous comment

**Comment by ZuruZockt010** [comment]
but then all Players must use that jar file , right?

**Comment by phit** [comment]
no
