### ISSUE TITLE
Fluid Extractor Bug

### ISSUE THREAD

**Issue by MindOfNasser** [AllTheMods/ATM-9#482]
Hey, so after i put an fluid extractor and finish from it and trying to move it, the block infront of it stuck on breaking action
![1](https://github.com/AllTheMods/ATM-9/assets/45881640/ec033953-2c7e-4abe-bde5-66858632c126)
![2](https://github.com/AllTheMods/ATM-9/assets/45881640/c5cbd2df-98f9-43b9-84fd-4d4551b5bc06)
![3](https://github.com/AllTheMods/ATM-9/assets/45881640/a263fcc1-f4c2-4f4b-9dd8-03e1bab1ad37)

**Comment by MindOfNasser** [comment]
sometimes it has more breaking texture but for now only this show up.

**Comment by djnifos** [comment]
That's a choice by the mod.  There used to be a cheaty way to break and replace the log just before the fluid extractor would do it, so you'd never actually consume the log, and get free latex.  The mod stores the damage some other way now to prevent that.

**Comment by MindOfNasser** [comment]
> That's a choice by the mod. There used to be a cheaty way to break and replace the log just before the fluid extractor would do it, so you'd never actually consume the log, and get free latex. The mod stores the damage some other way now to prevent that.

Thats what i thought, so i let the fluid extractor finish the log but still the same issue i opened this bug issuse because i tried everything i could think of
