### ISSUE TITLE
ore generation in the mining dimension (prosperity, inferium, uraninite)

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/ATM-9#483]
is it intentional that no prosperity, inferium and uraninite ore is generated in the mining dimension?

btw
yes, there is more allthemodium ore in the minig dimension, but I think to say "a lot more common" with 8 ore in 16 chunks (4x4) is a bit exaggerated (fresh start in v 0.1.9) ^^
![grafik](https://github.com/AllTheMods/ATM-9/assets/93662041/afd26e1a-b5b3-46c6-872f-6c02a5d2f269)

**Comment by YukkiPlays** [comment]
What kind of map is this?

**Comment by Schrimpes** [comment]
journey map

**Comment by Schrimpes** [comment]
in my main save, started with v 0.1.7, first entry into the mining dimension with v 0.1.8, there are only 5 allthemodium ores in 16 chunks. In my opinion, the generation should be set a little higher.
![grafik](https://github.com/AllTheMods/ATM-9/assets/93662041/4c004b66-e329-4255-bbc1-3145b69d559d)
