### ISSUE TITLE
No Way to obtain Yellorium Ingot

### ISSUE THREAD

**Issue by Kaldoron** [AllTheMods/ATM-9#484]
The Recipe for Yellorium Ingot is missing, but its needed to craft Fluidizer Casing from Extreme Reactors

**Comment by ShadedPL** [comment]
Yeah can confirm, there is no way to craft the Fluidizer. And without the fluidizer you are unable to craft the ATM Star, at least as far as I know.

**Comment by ShadedPL** [comment]
This can be closed, since Fluidizer is now craftable with Alltheores Uranium Ingot in 0.2.1
