### ISSUE TITLE
Allthemods 9 suddenly crashes when Im playing.

### ISSUE THREAD

**Issue by Sajns** [AllTheMods/ATM-9#487]
Hey! When Im playing allthemods 9 the game can suddenly crash and according to the crash reports Java is going out of memory and I dont know how to fix this so I would be very thankful if I could get some help by someone. 

---- Minecraft Crash Report ----

[crash-2023-09-29_20.07.35-client.txt](https://github.com/AllTheMods/ATM-9/files/12773024/crash-2023-09-29_20.07.35-client.txt)

**Comment by G4ming69** [comment]
unfortunately the same problem! and the discord is unfortunately behind a pay wall! omg

**Comment by Mitchell5200** [comment]
> unfortunately the same problem! and the discord is unfortunately behind a pay wall! omg

No, it's not, read the welcome page properly please

**Comment by Mitchell5200** [comment]
> Hey! When Im playing allthemods 9 the game can suddenly crash and according to the crash reports Java is going out of memory and I dont know how to fix this so I would be very thankful if I could get some help by someone.
> 
> ---- Minecraft Crash Report ----
> 
> [crash-2023-09-29_20.07.35-client.txt](https://github.com/AllTheMods/ATM-9/files/12773024/crash-2023-09-29_20.07.35-client.txt)

@Sajns Try dialing back your RAM allocation to between 7GB and 12GB, and for now disable the texture pack.
Please also report this crash to https://github.com/embeddedt/embeddium/issues

**Comment by Sajns** [comment]
Thanks, I will try that and come back if it doesnt help.

**Comment by Sajns** [comment]
The game crashed again and here is the crash report: 
[hs_err_pid11436.log](https://github.com/AllTheMods/ATM-9/files/12776103/hs_err_pid11436.log)

It seems that it is JAVA as dont have enough memory but I dont know how to fix it.
