### ISSUE TITLE
All the Crashes!

### ISSUE THREAD

**Issue by G4ming69** [AllTheMods/ATM-9#488]
new update and nothing works again!

The game crashed whilst mouseclicked event handler
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[crash-2023-09-30_10.23.04-client.txt](https://github.com/AllTheMods/ATM-9/files/12774251/crash-2023-09-30_10.23.04-client.txt)

**Comment by Mitchell5200** [comment]
oh, HammerLib, remove that and Solarflux reborn, as it's crashing with KubeJS

**Comment by G4ming69** [comment]
ok i test it
