### ISSUE TITLE
ATM 9 0.0.17 Crafting crashes the game

### ISSUE THREAD

**Issue by janzen20** [AllTheMods/ATM-9#49]
OK so I was trying to get terracotta for some botany pots but when I tried to craft the clay balls I had into clay blocks my game crashes or freezes and I don't know why, I have a good gaming pc and 8gbs of ram allocated for this modpack and this is on singleplayer with Complementary Reimagined shaders on if you need any extra info

**Comment by janzen20** [comment]
ok it seems like crafting anything in a crafting table or inventory while dragging the items will crash or freeze your game and it does sometimes delete your items when you restart the modpack

**Comment by janzen20** [comment]
like clicking items in one by one doesnt crash or freeze just when you drag a item around it crashes or freezes

**Comment by janzen20** [comment]
so I downgraded to 0.0.16 and its all good now so something with 0.0.17 is messed up

**Comment by whatthedrunk** [comment]
new versions have this fixed thanks
