### ISSUE TITLE
Twilight Forest - creating Maze Map crashes game

### ISSUE THREAD

**Issue by Johann-00** [AllTheMods/ATM-9#490]
Friend opened the maze map for twilight forest and got kicked from the server. and can't reconnect as long as he has the map in his inventory. 
Seems the game crashes in the process of creating the actual map.
In Single player the game crashes completely.

Steps to reproduce:
- create single player world in creative
- get blank maze map 
- open it (being in the twilight forest not necessary)

**Comment by colelisiongaming** [comment]
I second this behavior on version 0.1.9
