### ISSUE TITLE
Better End Island prevents spawning of Ender Dragon

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-9#491]
When players on my server go to the end, there is no dragon, and the server console constantly spams

```
[15:05:23] [Server thread/INFO] [betterendisland/]: Starting initial dragon fight!
[15:05:23] [Server thread/INFO] [betterendisland/]: Unable to find all 4 summoning crystals. This shouldn't happen!
```

It appears that the Better End Islands mod is broken and fails to properly spawn the Ender Dragon fight. I completely wiped the End to make sure, but that did not solve the problem.

**Comment by iQSJoker** [comment]
This is known to happen when adding BEI to an existing world, see below for fix. This is straight from the BEI mod page.

To use BEI on an existing world, we've provided the /end_island reset command. Using this command while in the End will attempt to reset the dragon fight back to its initial state and replace any previous portal/pillars with our redesigned versions. But this command attempts some major things behind the scenes, so please back up your world before trying! Also note that simply deleting your End dimension files is not suffificient, and you will still need to run the command.

**Comment by twothe** [comment]
ty, I give it a try.

**Comment by twothe** [comment]
It worked.

This mod definitely need a few quest guidelines for players, as it is very unintuitive and literally everyone will wonder how to resummon the dragon now that the exit portal doesn't exist.
