### ISSUE TITLE
[NaturesAura]Severe server bug, destroyed saves

### ISSUE THREAD

**Issue by KuroPeach** [AllTheMods/ATM-9#493]
When using any powder, the archive will be damaged and the corresponding world can only be deleted. My English is not very good. Please give feedback to the author.
I tried editing the save, deleting blocks, chunks, and mca, but the archive couldn't be repaired.
https://paste.ubuntu.com/p/7cTJ3gtHNj/
![image](https://github.com/AllTheMods/ATM-9/assets/19620848/bd16abe0-fe9b-4ee8-9e62-5a002788329f)

**Comment by KuroPeach** [comment]
fix now

**Comment by TLATER** [comment]
I've reproduced this, what does "fix now" mean

**Comment by TLATER** [comment]
In our case, removing the mod, loading the save, and then re-adding the mod at least saved the world, but clearly this mod feature is broken. What did you do to resolve this, @KuroPeach ?

**Comment by TLATER** [comment]
Ah, I see, fixed in Nature's Aura 39.2: https://github.com/Ellpeck/NaturesAura/commit/791c6ada5e4875154c1727fbca3f3742046b9d99
