### ISSUE TITLE
Create mod compatibility issue sophisticated storage

### ISSUE THREAD

**Issue by camoscout** [AllTheMods/ATM-9#496]
Hello! I think I have come across and issue with the Threshold Switch and the Stack upgrade with sophisticated storage. The switch does not seem to calculate the addition of the stack upgrade(s). Using the stack upgrade seem pretty obsolete with this tree farm.

Should I also report this in the create and/or sophisticated storage?

![image](https://github.com/AllTheMods/ATM-9/assets/139405231/bcc520db-1b8d-4551-b4e3-c9dc748e1231)

![image](https://github.com/AllTheMods/ATM-9/assets/139405231/85ae0b5f-7415-47f6-acd8-99c5372b0064)

**Comment by twothe** [comment]
This is most likely an issue with the Create mod, so maybe forward it to them.
