### ISSUE TITLE
AE2 inscriber creating infinite parts.

### ISSUE THREAD

**Issue by Kurunoa** [AllTheMods/ATM-9#5]
I put in 64 diamonds, and it is making more than 64 processor parts, and the 64 in the inscriber does not decrease.

![image](https://github.com/AllTheMods/ATM-9/assets/77598167/3370488b-a10d-4884-bded-15b8413613dd)
![image](https://github.com/AllTheMods/ATM-9/assets/77598167/274b03d8-a669-4efb-b7bd-f87e0515dbc2)

**Comment by quikenb** [comment]
Just to add on to this as well, you cannot remove items from the input GUI. You need to break the inscriber block.

**Comment by FallenPumpking** [comment]
Came to report this issue as well.

**Comment by Nukiloco** [comment]
i think this was fixed in the newest ae2 commit
https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/b7f3df581c7aed9f1934c5d2fde751eaf58079a7

atm has to update the mod to fix it
