### ISSUE TITLE
Server Files for 0.1.11 missing

### ISSUE THREAD

**Issue by YukkiPlays** [AllTheMods/ATM-9#501]
Hello there, i dont know if you aware about this issue but there aren't Serverfiles for the 0.1.11 uploaded yet.

**Comment by Mitchell5200** [comment]
We are aware, they're stuck on CF in Manual review.

Direct file link for CF https://mediafilez.forgecdn.net/files/4776/766/Server-Files-0.1.11.zip

**Comment by Kebin-san** [comment]
Hi,
have downloaded the file from your link, but  i´m missing Pineapple Delight 1.0.6-Fix when i try to connect to my server

**Comment by Mitchell5200** [comment]
because that mod was removed from the pack.
