### ISSUE TITLE
V 0.1.11; Crafting awakened supremium essence consumes all essences

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/ATM-9#503]
Crafting awakened supremium essence consumes all essences from the essence vessel, not just the 10 required. So when the vessels are full with 40 essences, all 40 are used up. Furthermore, the essences in the vessels are displayed in white and not in their color. no additional texture pack or shader is used.

**Comment by themadjem** [comment]
Color issues are likely related to Embeddium/Oculus. I noticed problems with CC: Tweaked color monitors, Flux Networks points and plugs, and Ender Chests and Ender Tanks. Disabling Oculus fixed the color issues for me. Funnily enough, shaders seem to fix the problem, it's only present without a shader enabled.
