### ISSUE TITLE
v0.1.11 Can't load into updated world

### ISSUE THREAD

**Issue by themadjem** [AllTheMods/ATM-9#504]
Anyone who tries to log into my ATM9 server after the 0.1.11 update gets this same error upon Loading Terrain 
![image](https://github.com/AllTheMods/ATM-9/assets/17654014/ec21bf3c-8e41-4c53-8a23-e68e2c79629b)

I tried a combination of restarts for the clients and server and still get the error. 
I tried generating a new world and the issue was not there. 
I couldn't see anything in the logs that called out a specific reason for the disconnection.

**Comment by Kebin-san** [comment]
Same Problem for me, my console on the server says after this:
[20:21:22] [Server thread/ERROR] [sophisticatedcore/]: Item thermal:satchel is set to not be affected by stack upgrade in config, but it does not exist in item registry
[20:21:22] [Server thread/ERROR] [sophisticatedcore/]: Item ars_elemental:caster_bag is set to not be affected by stack upgrade in config, but it does not exist in item registry
[20:21:22] [Server thread/ERROR] [sophisticatedcore/]: Item ars_elemental:curio_bag is set to not be affected by stack upgrade in config, but it does not exist in item registry

**Comment by themadjem** [comment]
client latest.log: https://mclo.gs/BpPZiQS
client debug.log: https://mclo.gs/P6bQlbP

**Comment by sir-vancelot** [comment]
Same for me: https://github.com/AllTheMods/ATM-9/issues/507

**Comment by themadjem** [comment]
> Same for me: #507

Interesting that it's just you, everyone trying to connect to my server has the same error.

**Comment by themadjem** [comment]
On a brand new world on version 0.1.11, craft map, right-click with map, crash. So definitely something to do with maps. But this doesn't explain why I can't load in on the previous world. I checked my inventory in NBTExplorer and I don't have a map on me

**Comment by arsalannisar09** [comment]
on my server one of our players has the item in his base  on a item frame and when anyone goes near that chunk it boots everyone out with that error

**Comment by themadjem** [comment]
> on my server one of our players has the item in his base on a item frame and when anyone goes near that chunk it boots everyone out with that error

I wouldn't even know how to go about searching for something like that. I kind of knew that playing a beta pack might come with these risks though. So not the end of the world if we have to start anew.

**Comment by themadjem** [comment]
I deleted the map data from the world/data/ folder and that seemed to work and allow me to log in
pic from my 0.1.9 just to show the files:
![image](https://github.com/AllTheMods/ATM-9/assets/17654014/9311e701-889d-4ec8-a7d5-35fe8bce19b4)

**Comment by themadjem** [comment]
This was fixed with the 0.1.12 update

**Comment by rmccarthy1504** [comment]
Issue has re-occurred for 0.2.4

**Comment by themadjem** [comment]
@rmccarthy1504 is it the same error as shown before?
