### ISSUE TITLE
v 0.1.11 Treasure Map Bug

### ISSUE THREAD

**Issue by MsVoxxie** [AllTheMods/ATM-9#505]
As of version 0.1.11, Picking up a filled treasure map seems to cause a packet issue which breaks a players data until the map is removed via NBTEditor, The only fix I am currently aware of is doing such with NBTEditor on their inventory. Hopefully this helps narrow down any issues.

![image](https://github.com/AllTheMods/ATM-9/assets/10318911/19351b1a-d2d8-4996-b27d-3d4528a96920)

**Comment by themadjem** [comment]
My issue #504 is the same problem. I and none of the players that have tried logging in have any maps in their inventory. Even a brand new player gets the same error

**Comment by whatthedrunk** [comment]
was fixed last update thanks
