### ISSUE TITLE
ATM 9-0.1.11 Maps and Treasure Maps Client crash

### ISSUE THREAD

**Issue by GamerCH** [AllTheMods/ATM-9#508]
I got this when i created a map or used a Treasure map in my inventory

Temporal Solution on Multiplayer basis:
 A Person with OP need to take it away (/invsee username) from my Inventory (obvius not in his own or he got a crash too) and trowed it on the ground (with backpackmagnet off) or in Trash bin

**Comment by whatthedrunk** [comment]
was fixed last update thanks
