### ISSUE TITLE
Mekanism Ethylene no recipe

### ISSUE THREAD

**Issue by xNoVoSx** [AllTheMods/ATM-9#511]
Hello in the 0.1.12 update is the Ethylene recipe gone from the Pressurized Reaction Chamber and there is no other recipe
![2023-10-02_11 07 37](https://github.com/AllTheMods/ATM-9/assets/88331908/46684db8-d706-435d-8356-b6ef9eb03a54)

**Comment by screret** [comment]
As it should be.

**Comment by Mitchell5200** [comment]
Intentional pack change, Closing
