### ISSUE TITLE
IF Rocket Mycelial Generator broken some point after 0.1.9

### ISSUE THREAD

**Issue by Amunsul** [AllTheMods/ATM-9#517]
Generator no longer shows a tab for accepted items in JEI. They rocket item it used to accept is no longer showing in JEI. Tried fireworks but it wont accept. This was working 0.1.9. My server updated from 0.1.9 directly to 0.1.12 yesterday and now its broken. Please fix :)

**Comment by Amunsul** [comment]
per Mitchell i made a firework star and a firework rocket, neither worked.

**Comment by lukaspkrr** [comment]
@Amunsul Rocket Mycelial Generator needs a rocket with flight duration, the automatic rocket recipe using only 1 gunpowder does not generate rockets with flight duration, change your rocket recipe to 1 paper and 2 gunpowder, this way the automatically created rockets will have 2 flight duration and have already been accepted by the Rocket Mycelial Generator.

**Comment by TheBedrockMaster** [comment]
Did you fix this?
