### ISSUE TITLE
No ethylene recipe

### ISSUE THREAD

**Issue by Paranceanic** [AllTheMods/ATM-9#518]
In the newest version of ATM9 there is no current way to create ethylene.
Normal you would use a pressurized reaction chamber with hydrogen and bio fuel to create ethylene and substrate.
Now when you use the recipe all you get is substrate and no ethylene.

V 0.1.12

**Comment by Lol5kek** [comment]
i think it to delete op melon power plants, you still can do HDPE pellets

**Comment by Paranceanic** [comment]
Can't you just get rid of the melon recipe and that's it?

**Comment by Paranceanic** [comment]
> i think it to delete op melon power plants, you still can do HDPE pellets

Can't they just get rid of the melon recipe and that's it?
Or is there something i am missing?

**Comment by Schrimpes** [comment]
at least you can still use hydrogen in the gas burning generator

**Comment by Paranceanic** [comment]
> at least you can still use hydrogen in the gas burning generator

Well the thing is that when you use hydrogen in the gas burner you actually lose energy so there aren't many practical uses for it.

**Comment by Schrimpes** [comment]
> > at least you can still use hydrogen in the gas burning generator
> 
> Well the thing is that when you use hydrogen in the gas burner you actually lose energy so there aren't many practical uses for it.

I've never worked with hydrogen, so I didn't know that. All I know is that you can use hydrogen. 
then you can at least use it where hydrogen is produced but not consumed. like fissile fuel production, if I'm not mistaken.

**Comment by Paranceanic** [comment]
> > > at least you can still use hydrogen in the gas burning generator
> > 
> > 
> > Well the thing is that when you use hydrogen in the gas burner you actually lose energy so there aren't many practical uses for it.
> 
> I've never worked with hydrogen, so I didn't know that. All I know is that you can use hydrogen. then you can at least use it where hydrogen is produced but not consumed. like fissile fuel production, if I'm not mistaken.

That's true though the amount of energy you would get is quite miniscule.

**Comment by Mitchell5200** [comment]
Recipe Intentionally removed. Closing
