### ISSUE TITLE
[0.1.10] Traveller's Backpacks losing inventory contents 

### ISSUE THREAD

**Issue by Brother-Blue** [AllTheMods/ATM-9#521]
This is similar to an issue from 4 years ago https://github.com/DarkPacks/Crackpack-3/issues/25

When you as a player die in the following ways, the backpack loses its contents:
- Dying with the backpack in your inventory and recovering it from your grave
- Dying in lava
- The other ways mentioned in the aforementioned issue.

**Comment by rekcon** [comment]
I have encountered this, too. I died by drowning with the backpack in my inventory.
