### ISSUE TITLE
Mek Pressurized Reaction Chamber wont accept Plutonium

### ISSUE THREAD

**Issue by Amunsul** [AllTheMods/ATM-9#523]
tried piping it in all six sides, it shows in the pressurized mek pipe but machine wont accept it.
![sideconfigs](https://github.com/AllTheMods/ATM-9/assets/67374500/4bd85a93-afb1-45ec-a35e-b8f1db3386ec)
![empty PRC](https://github.com/AllTheMods/ATM-9/assets/67374500/e2ec5370-43fe-4de8-8581-754e60e4460b)
![Plutonium](https://github.com/AllTheMods/ATM-9/assets/67374500/5a15b61d-6397-46c4-9225-0bf52957b4d8)

**Comment by dan-garvey** [comment]
I've heard mek needs to fix this

**Comment by DerTyp7** [comment]
Did you find a solution?
Having the same problem

**Comment by DerTyp7** [comment]
Running the command `/reload` on the server fixed it for me.

**Comment by minecrafterseppe** [comment]
bump
this issue still persists

**Comment by leikenghou** [comment]
I got the same problem in my server,
ATM9-0.2.60 
mek10.4.6
