### ISSUE TITLE
sgear_random_gear @p silentgear:pickaxe 3

### ISSUE THREAD

**Issue by Exodus89MTG** [AllTheMods/ATM-9#529]
Hi

Sorry if this is an open issue already, got a random reward and got the following message

Unkown or incomplete  command, see below of error
/sgear_random_gear @p silentgear:pickaxe 3

![image](https://github.com/AllTheMods/ATM-9/assets/14543038/2a5c5250-5cd2-4ac1-8321-db868bb15795)

**Comment by TheBedrockMaster** [comment]
Is this still broken?

**Comment by ToshibaEC0Microwave** [comment]
Finally will be fixed!
