### ISSUE TITLE
JEI doesn't load.

### ISSUE THREAD

**Issue by BFWingsII** [AllTheMods/ATM-9#53]
JEI keeps failing to load.  This started in 0.0.18 and persists through the current version of the pack.  I have no other mods installed and have 8+ gigs of RAM allocated.  All that needs to be done to replicate this is to simply start the game. 
[crash-2023-06-30_21.23.01-fml.txt](https://github.com/AllTheMods/ATM-9/files/11923981/crash-2023-06-30_21.23.01-fml.txt)

**Comment by Seegras** [comment]
Can confirm. Impossible to start.
![2023-07-01_09-06](https://github.com/AllTheMods/ATM-9/assets/1655796/1f985591-a721-4140-80b1-7f593dd91330)

It says it's with UtilitiX, but the same versions of that and jei worked with 0.0.18.

**Comment by chady33** [comment]
update to UtilitiX-1.20.1-0.8.1.jar and the pack works fine

**Comment by BFWingsII** [comment]
Thank you.  The game works just fine now.
