### ISSUE TITLE
[0.1.12] Refined Storage Crafter losing patterns

### ISSUE THREAD

**Issue by Johann-00** [AllTheMods/ATM-9#534]
logged in on my server today and find my netherite crafter completely empty.
Yesterday it was full with patterns and even the speed upgrades disappeared.
Had a similar issue before where some patterns would disappear out of other standard crafters but reappear in a barrel that is part of my refined storage system but not directly connected to the crafter.
This time I can't find the lost patterns anywhere.
Not sure if it's a Server issue or not and can't find a way to trigger it on prupose.

**Comment by xenonmb** [comment]
got the same issue, and also mentioned it here on the extrastorage issues https://github.com/Edivad99/ExtraStorage/issues/72

**Comment by Freakyman403** [comment]
> got the same issue, and also mentioned it here on the extrastorage issues [Edivad99/ExtraStorage#72](https://github.com/Edivad99/ExtraStorage/issues/72) i think it happens on server restart/world reload

the vanishing patterns happens at restart/world reload

**Comment by K1kk0m4n** [comment]
Same here. After restart patterns are gone from crafter

**Comment by OSoHexxy7** [comment]
Having the same issue, also a netherite crafter and also had extrastorage recipies in the crafter

**Comment by xenonmb** [comment]
it would seem to me the issue is also dependent on the position of the crafter, when i had the problem i repositioned the crafter and then it didnt occur anymore
