### ISSUE TITLE
ATM9 0.1.12 Game crash when I have drawer in inventory

### ISSUE THREAD

**Issue by KingDs99** [AllTheMods/ATM-9#538]
Hi ! 

So I made some framed drawers with ancient smooth stone when I brake it and try to open my inventory with the drawer inside the game crash, with items or without itmes inside the drawer.

I tried to pickup framed drawers in other material and it don't crash the game.

Crash with items inside drawer:
[crash-2023-10-07_21.28.56-client.txt]

Crash without items inside drawer:
[crash-2023-10-07_21.55.04-client.txt]

**Comment by jmadarg** [comment]
Been trying to find info about these kind of crashes and found this https://github.com/Buuz135/FunctionalStorage/issues/210 not sure if there is any fix :s

**Comment by KingDs99** [comment]
Oh yeah it's very similar to my problem, I see it is not fixed yet because the issue was reported some weeks ago. 
But if it was already reported just to wait and be carreful with that.

Thanks @jmadarg I will see in the next update
