### ISSUE TITLE
JEI crashing on load with 0.0.19

### ISSUE THREAD

**Issue by Kurunoa** [AllTheMods/ATM-9#54]
If you recieve a JEI crash with 0.0.19, containing the following: 'Exception message: java.lang.NullPointerException: Cannot read field "modid" because the return value of "de.melanx.utilitix.UtilitiX.getInstance()" is null', manually update the "UtilitiX" mod to 0.8.1.

https://github.com/MelanX/UtilitiX/commit/0ef5434a01128dfeb091bc77532b159a565f9b17

**Comment by fR3aKonMC** [comment]
update to 0.0.20 or update UtilitiX to fix this issue.
