### ISSUE TITLE
[Suggestion] Remove Greg from the pack.

### ISSUE THREAD

**Issue by cthae** [AllTheMods/ATM-9#540]
While IC2 fitted ATM somewhat and was a nice light mod for fun, greg adds a ton of unneeded ores, recipes and overhead. We're thankful that it isn't required for the ATM star, but really, greg's balance is way off. It just doesn't fit the modpack. 

Very few people ever use greg, and it doesn't actually provide anything useful or essential.

**Comment by mindlessspectre** [comment]
I'm new to this pack but honestly I think Greg is what sets it apart from a ton of other popular packs. No other mod has the rich complexity and usefulness that that Greg does, i think the complexity and lack of direction in a guidebook is what turns people off.  If nothing else its forced progression is going to draw people who are open minded and willing to try something new to play more and spend time in their playthroughs learning, experimenting, and finding results from it.
