### ISSUE TITLE
evil craft big blood chest texturse dont work

### ISSUE THREAD

**Issue by minos-prime-p2-primesoul** [AllTheMods/ATM-9#547]
<img width="1280" alt="Screenshot 2023-10-08 174746" src="https://github.com/AllTheMods/ATM-9/assets/147336505/1ebb41e9-82b7-436e-8ff6-e7807f026989">
thats the screen shot

**Comment by toqueteos** [comment]
Can confirm this is still happening on 0.2.32 (doesn't work with either shaders on or off).

![image](https://github.com/AllTheMods/ATM-9/assets/699969/475a10f2-6adc-433d-97b6-551b5f4fe7fd)
![image](https://github.com/AllTheMods/ATM-9/assets/699969/ff85c28c-9bd3-4814-87e7-b1814bf4cc06)
