### ISSUE TITLE
Electrodynamics and Surrounding Mods

### ISSUE THREAD

**Issue by skiprocks999** [AllTheMods/ATM-9#549]
Hello,

Electrodynamics has been updated to 1.20.1 along with its dependent mods, and I would like to request that they be included in the pack if possible:

Electrodynamics: https://legacy.curseforge.com/minecraft/mc-mods/electrodynamics

Assembly Line: https://www.curseforge.com/minecraft/mc-mods/assembly-lines
Ballistix: https://www.curseforge.com/minecraft/mc-mods/ballistix
Blastcraft: https://www.curseforge.com/minecraft/mc-mods/blast-craft
Dynamic Electricity: https://www.curseforge.com/minecraft/mc-mods/dynamic-electricity
Extended Tools: https://www.curseforge.com/minecraft/mc-mods/extended-tools
Modular Force Field Systems: https://legacy.curseforge.com/minecraft/mc-mods/modular-forcefields
Nuclear Science: https://legacy.curseforge.com/minecraft/mc-mods/nuclear-science

Please let me know if I need to provide any further information.

**Comment by Mitchell5200** [comment]
Use #1 for mod suggestions, not a new issue post.

**Comment by Mitchell5200** [comment]
![Screenshot 2023-10-09 18 18 52](https://github.com/AllTheMods/ATM-9/assets/45913837/a39055ca-257d-47af-93ce-a10b461bdc5f)
Additionally, from the Electrodynamics CF page, they require permission before the mod can be added to a Public pack, which is against CF's rules, the way i understand them.
