### ISSUE TITLE
Very low TPS when a blood moon happens.

### ISSUE THREAD

**Issue by itsSilverlink** [AllTheMods/ATM-9#552]
Hi, 

When a blood moon happens the server TPS dips like mad. It goes down like to 6 - 7 TPS
Normally it sits around 16 - 18 TPS.

I run it on a dedicated piece of hardware that currently only runs the ATM9 Modpack.
Processor: Ryzen 7 7735HS
RAM: 32GB and dedicated 4 - 10GB to ATM9

Blood Moon Happening: https://spark.lucko.me/oDC2gCGqB5
Normal run: https://spark.lucko.me/NToFD7jt8E

**Comment by alfredggttv** [comment]
This is very likely due to the mobs that spawn from it. I suggest on getting something like the mod InControl to control the total amount of mobs that can be spawned at any given time. You can also just remove the mod.
