### ISSUE TITLE
Mekanism Pressureized Reaction Chamber not producing ethylene

### ISSUE THREAD

**Issue by HarjoFamily** [AllTheMods/ATM-9#553]
The pressurized reaction chamber is not producing ethylene. It is producing the pellets but not the gas for the generator to function. I have tried every setup I could to get it to function but nothing is working. The electrolytic seperator is also not accepting enough power to function long term.

**Comment by Schrimpes** [comment]
This was disabled in the current version (0.1.12). There are/were already a few posts before. If you search for "ethylene" using the search function (search all of them, not just the open ones) they should appear and you can read more about why there.

**Comment by HarjoFamily** [comment]
Thank you

**Comment by alfredggttv** [comment]
As said, the production of Ethylene was removed in the current version. Power is currently getting a rebalance and you might see it make a come back in the future.
