### ISSUE TITLE
1x1 Taskbar causing issue for 50m rf quest

### ISSUE THREAD

**Issue by Coni69** [AllTheMods/ATM-9#558]
When i placed it down nothing was wrong but when i selected the quest and clicked confirm it crashed my game and i think i got chunk banned cause when i try to log onto the server again i cant cause it just crashes with this crash log: 

The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m118409()" because "empty" is null

**Comment by alfredggttv** [comment]
This seems to be a current issue with FTBQuests. I'll keep an eye on it.

**Comment by Viking790** [comment]
Works in latest update
![Screenshot_20231012_100556](https://github.com/AllTheMods/ATM-9/assets/102779251/07ecc1f5-14f2-4b58-9c10-ca1789d0e6d9)

**Comment by alfredggttv** [comment]
Glad to hear!
