### ISSUE TITLE
Eccentric Tome not showing 

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/ATM-9#560]
this doesnt show up in JEI  you have to know how to make its not in the quests or anywhere. so if you dont know how to make it its useless to some ppl. see pics tried searching in jei no avial.
 steps to get to screen shot
1. make bookself
2. add bookself and extra book to crafting table
3. press R on result of craft ("Eccentric Tome")
4. this is how i got it to appear in JEI but still not in list
see pic 
![Screenshot_2](https://github.com/AllTheMods/ATM-9/assets/45196448/ac736da5-dd5c-4d2b-a396-f1115e2dc68c)

All the Mods 9-0.1.12

**Comment by themadjem** [comment]
Same issue with Blood Magic's guidebook. You can craft it, but it doesn't show in JEI

**Comment by 345022817** [comment]
same for the "Iron's Guidebook"
