### ISSUE TITLE
Starbuncles cannot be bound to beds or to move from one inventory to the other

### ISSUE THREAD

**Issue by mindlessspectre** [AllTheMods/ATM-9#578]
All they are able to be bound to do is store in an inventory, cant bind them to magebloom beds or to be able to move from one inventory to another (ex: from a chest to the pedestal next to a volcanic or mycelial source link.)

**Comment by Kevin-Marsh** [comment]
This bug should be resolved as of some of the latest updates. Any Ars version post 4.5 should be working according to the Ars nouveau github. https://github.com/baileyholl/Ars-Nouveau/issues/1096
