### ISSUE TITLE
Dragon Egg Essence not Craftable

### ISSUE THREAD

**Issue by alessandrofasse** [AllTheMods/ATM-9#581]
# Description
I have the problem, that I can not create the `Dragon Egg Seeds`. See the following screenshots. First, there is problem in the GUI and the recipe is not shown correctly, i.e. there is no proper icon for the `Dracon Scale`. And second, if I click the button nothing at the altar happens. I checked my setup with other seeds and they do work. (Note that the `Propserity Seed` is placed at the middle altar (as in the recipe) but is hard to see)

Any idea?

![2023-10-11_15 56 40](https://github.com/AllTheMods/ATM-9/assets/38497013/15e7e4b9-717a-464b-a444-6c34f36cea20)
![2023-10-11_15 56 32](https://github.com/AllTheMods/ATM-9/assets/38497013/3f03281c-a3fc-42bd-b288-571f77e9dee1)

**Comment by lahjsldkjamzxnclkna** [comment]
If you zoom in you can see that the dragon scales do have an icon, and you are using the incorrect ones.
