### ISSUE TITLE
Slot gloves - Aether

### ISSUE THREAD

**Issue by petriczech** [AllTheMods/ATM-9#585]
i have few gloves, but i have only 2 slot hands but not gloves (mod @aether)

![image](https://github.com/AllTheMods/ATM-9/assets/5469703/23c31dda-4e98-47d6-ad5b-0c309a1edf4c)

**Comment by Schrimpes** [comment]
The gloves, and other items from the Aether mod have their own place. If you click on the cloud to the right of your shoes, the interface will open

**Comment by petriczech** [comment]
> The gloves, and other items from the Aether mod have their own place. If you click on the cloud to the right of your shoes, the interface will open

thnx. i didn see this icon
![image](https://github.com/AllTheMods/ATM-9/assets/5469703/fe58ce56-bdb1-471d-b240-e053dc1b0c07)
