### ISSUE TITLE
Cannot export mekanism radioactive liquid/gas through ae2

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-9#592]
Hi,
I'm working with "mekanism" trying to make polonium and to do so I need nuclear waste, which I wanted to manage by using my AE2 network, but you can only import it in...
The problem is that you cannot filter this fluid/gas in the export bus (nor making autocraft with it btw). I tried putting it in a chemical tank trough applied but it won't enter it. After that I tried to drag and drop the fluid in the filter slot via JEI but didn't work either. I can't think of an other solution but I belive it should have been possible by one of these methods (especially the JEI method since you can do it with the other fluids)

I'm on the 0.1.12 release so if this is already fixed i'm sorry

thanks.

\Terrazed

**Comment by Kevin-Marsh** [comment]
It is a bug between Applied Mekanistics and Mekanism. It is on the list of things for Mekanism to work on so all we can do is wait. While it isn't a good solution, you can jump to creative and give yourself a chemical tank containing the radioactive substance, set the filter and trash the tank after.

**Comment by Schrimpes** [comment]
Afaik, all radioactive material only goes into the radioactive waste barrel and not into a chemical tank

**Comment by Kevin-Marsh** [comment]
It does except for if you are in creative mode and grab a creative chemical tank containing the material. It is hardly ideal but the only real option for now.
