### ISSUE TITLE
[0.2.1] Gregtech Rubber Ring recipe consumes the knife

### ISSUE THREAD

**Issue by vakus** [AllTheMods/ATM-9#593]
# Expected behaviour

The knife used in crafting takes a durability damage (allows reusing tools but with limited crafts)

# Actual Behaviour

The knife used in crafting is consumed (Tried on Iron and Diamond Tier)

![image](https://github.com/AllTheMods/ATM-9/assets/8487993/e3695fa7-1efa-4f2f-a94a-803999dc4c77)

_Unsure if this is a Gregtech issue or some changed recipe in ATM9_

**Comment by loving2** [comment]
I've posted and referenced this as a bug report on GTCEu-Modern's github, as I don't think this is from ATM9

For now I'd recommend using a GT knife, as those properly lose durability rather than get deleted
