### ISSUE TITLE
apotheosis : Cant modify Spawner with clock's or Sugar

### ISSUE THREAD

**Issue by ZebGasm** [AllTheMods/ATM-9#594]
i cant modify spawners with sugar or clocks

**Comment by jakeb2000** [comment]
the items have changed i noticed

**Comment by jakeb2000** [comment]
Conduit - Ignores Players
Soul Lantern - Ignores Light
Ghast Tear - Max Entities
Piglich Heart - Spawn Count
Wool - Silent
Golden Apple - No AI
Allthemodium Ingot - 10 Min Spawn Delay
Prismarine Crystal - Activation Range
Redstone Comparator - Redstone Control
Unobtainium Ingot - Max Spawn Delay
Dragon Egg - Ignores Conditions
Blaze Rod - Spawn Range
