### ISSUE TITLE
Suggestion : Sophisticated Storage - Better Non-Backpacks

### ISSUE THREAD

**Issue by KaiRoman** [AllTheMods/ATM-9#595]
Id like to see backpacks nerfed a bit and stationary storage buffed, I personally think its kinda BS that a backpack can hold more than a stationary chest/barrel/drawer. I would like to see more slots for the chest/barrels/drawers and maybe a netherite stack upgrade for those too, while on the flipside Id like less slots on the backpacks, and no netherite stack upgrade. 

Just a simple suggestion, I apologize if it was posted in the wrong place.

**Comment by Schrimpes** [comment]
You have the option of not upgrading the backpack. So you can keep with a 27 slot backpack. And if you make a netherite backpack for the quests, you can put it somewhere and use it as a stationary storage. So everyone can play how they want. ^^

**Comment by MooseMan600** [comment]
The balance comes from the fact that the stationary ones are cheaper to make for the same size, and the upgrades modules are cheaper to make as well.

**Comment by KaiRoman** [comment]
Ah I see, alright fair enough

**Comment by aAndrew3030** [comment]
The Sophisticated mods are highly configurable. The first thing I normally do when installing these mods is to go into the configs and max out everything, but you can easily tweak it to your own taste
