### ISSUE TITLE
No 0.2.2 Server Pack

### ISSUE THREAD

**Issue by YukkiPlays** [AllTheMods/ATM-9#597]
Hello there! I noticed that there isn't any Serverpack for the 0.2.2 Version of ATM9. Is it in manual review by curseforge again?

**Comment by YukkiPlays** [comment]
Nevermind, i scraped it off curseforge myself xD
https://mediafilez.forgecdn.net/files/4795/997/Server-Files-0.2.2.zip

**Comment by YukkiPlays** [comment]
The 0.2.3 Serverpack can be found here:
https://mediafilez.forgecdn.net/files/4796/875/Server-Files-0.2.3.zip

**Comment by Forgrim** [comment]
And 0.2.4 is here: https://mediafilez.forgecdn.net/files/4799/153/Server-Files-0.2.4.zip

**Comment by JakeMoe** [comment]
0.2.2 through 0.2.4 have finally been released

**Comment by JakeMoe** [comment]
...just in time for 0.2.5 to be released without a server pack.  Anyone know why the server packs are so delayed these days?

**Comment by YukkiPlays** [comment]
https://mediafilez.forgecdn.net/files/4801/665/Server-Files-0.2.5.zip
Here ya go

**Comment by Mitchell5200** [comment]
0.2.6, just because https://mediafilez.forgecdn.net/files/4803/153/Server-Files-0.2.6.zip
