### ISSUE TITLE
Sushi to go causes crashes to desktop

### ISSUE THREAD

**Issue by cddrury** [AllTheMods/ATM-9#598]
For almost every recipe I've created with Sushi to go, the game has crashed. When I log in, the sushi that I made is in my inventory.

**Comment by Mitchell5200** [comment]
Logs via https://mclo.gs/ please

**Comment by cddrury** [comment]
I posted one log the link you sent me. Should I attach other logs as well to this thread?

**Comment by Mitchell5200** [comment]
yes, and share the link here too

**Comment by cddrury** [comment]
Apologize for not linking the first upload - this is my first bug report/log upload. 

[https://mclo.gs/KnGzxMr]

[https://mclo.gs/6148SRO]

[https://mclo.gs/PJFJKme]

**Comment by cddrury** [comment]
Aaaaand, I don't think I pasted the URL in correctly.

**Comment by cddrury** [comment]
OK, fixed it.

**Comment by Mitchell5200** [comment]
hmm, can you go into your Crash reports folder and grab at least one of those crash reports from when you crashed, i'll go and mention this to the mod devs in the meantime

**Comment by cddrury** [comment]
Crash reports attached.
[crash-2023-10-13_10.07.12-client.txt](https://github.com/AllTheMods/ATM-9/files/12901039/crash-2023-10-13_10.07.12-client.txt)
[crash-2023-10-13_10.14.10-client.txt](https://github.com/AllTheMods/ATM-9/files/12901040/crash-2023-10-13_10.14.10-client.txt)
[crash-2023-10-13_10.19.06-client.txt](https://github.com/AllTheMods/ATM-9/files/12901041/crash-2023-10-13_10.19.06-client.txt)
