### ISSUE TITLE
Refined Storage Receivers not working in ad astra dimensions

### ISSUE THREAD

**Issue by kolivere** [AllTheMods/ATM-9#599]
Network Receivers are working in the nether/end, but don't appear to be working on the moon/mars/etc...

**Comment by aAndrew3030** [comment]
Do you have the areas chunk loaded?

**Comment by Natomik** [comment]
Same problem here, chunk-loading the place  doesn't seem to do anything. The network receiver is dark like it's not connected.
![Minecraft Forge_ 1 20 1 - Multiplayer (3rd-party Server) 27_12_2023 12_07_31](https://github.com/AllTheMods/ATM-9/assets/69772566/d07bff99-b443-43f5-ab4f-63d6fa6db4d8)
![Minecraft Forge_ 1 20 1 - Multiplayer (3rd-party Server) 27_12_2023 12_06_47](https://github.com/AllTheMods/ATM-9/assets/69772566/ae80eb92-249f-4be9-9b87-81c72d263b30)
