### ISSUE TITLE
Silent Gear Items Not Spawning In Loot Chests

### ISSUE THREAD

**Issue by Busch-Matthew** [AllTheMods/ATM-9#60]
Have travelled roughly 50,000 blocks in the nether and haven't found a single netherwood sapling or nether banana. Went into a single player creative world and spawned ~200 loot chests when I noticed _no items_ from silentgear were spawning in chests.  

Tested this against ATM8, where the in 10 chests I saw 7 saplings.

**Comment by LupusTheFallen** [comment]
Can confirm this is still happening in 0.0.63, I checked >50 nether chests (Bastions, Fortresses, Ruined portals...) and got nothing. This is extremely annoying as it is the only way to get netherwood saplings, a possible solution would be to add the sapling (and other materails) to the Market from Farming for Blockheads.
