### ISSUE TITLE
Sorting Inventory causes an error message to appear.

### ISSUE THREAD

**Issue by SuperDMAN122** [AllTheMods/ATM-9#600]
java.lang.IllegalStateException: Unequal before and after item counts

**Comment by aAndrew3030** [comment]
I think the issue is caused by having multiple competing mods that sort chests. You can try disabling the sorting options in Inventory Profiles Next (or removing the mod alltogether). I just use the sort button in Sophisticated storage with no issue

**Comment by Quidney** [comment]
> I think the issue is caused by having multiple competing mods that sort chests. You can try disabling the sorting options in Inventory Profiles Next (or removing the mod alltogether). I just use the sort button in Sophisticated storage with no issue

Might be, but I only have 2 mods binded to the middle mouse button. Sophisticated Backpacks, and Sophisticated Storage. I'd like to guess those two are compatible.
And also pick block is binded to middle button but that's a vanilla feature.

**Comment by DanceStar** [comment]
If i want wo make a storage template (only wrong with the 1024k Storage), the targeted item is the wrong mod item, so i cant us it to make like the infinite storage with one click. screens attached. it goes from the mod "Extra Storage" to "Reborn Storage"
![2023-10-14 13_32_40-Minecraft Forge_ 1 20 1 - Multiplayer (3rd-party Server)](https://github.com/AllTheMods/ATM-9/assets/75915155/35721b24-e8ae-4fc6-8c38-a7240f0f6639)
![2023-10-14 13_32_59-Minecraft Forge_ 1 20 1 - Multiplayer (3rd-party Server)](https://github.com/AllTheMods/ATM-9/assets/75915155/63c26251-737d-4a45-b9bf-44533a84e877)

**Comment by aAndrew3030** [comment]
Inventory Profiles Next also default is the middle mouse, and the keybind can only be changed threw the mod config (r+c to access the config in game)

**Comment by aAndrew3030** [comment]
Turning it off in Inventory Profiles fixes the middle button sort in Sophisticated mods

**Comment by SuperDMAN122** [comment]
Hi, thank you very much for the Info because it was distracting. Now I deleted the mod Inventory Profiles Next and installed inventory sorter, and it is fixed. I'll do that way until the Devs fix it.
