### ISSUE TITLE
[Suggestion] Remove Blood Moon mod

### ISSUE THREAD

**Issue by cthae** [AllTheMods/ATM-9#601]
Nobody likes it. Nobody needs it. Lag.

That's the general sentiment from the atm9-alpha.

Harvest moons and the luck+1 moon are garbage too. But at least it's not as annoying and lag-inducing.

**Comment by aAndrew3030** [comment]
Anyone can remove the mod without breaking anything, so I see no issue leaving it and letting people decide? That said, your critique could be a bit more tactful!

**Comment by cthae** [comment]
When you say anyone, you don't mean players, right? You mean server admins since I believe it's not a client mod.

Following similar logic, you could just add any mod to the pack and leave the admins to choose whether they want those. Similarly, you could just link them to the mods repo instead of making the pack, I guess.

Ye, it could be more tactful. I'm just relaying what I got from our persistent players. I don't mind it personally. It might be a bit annoying early game but after that it's mostly lag that it produces.

**Comment by OArndt** [comment]
+1 for removing it.
@cthae do you know which mod it is? I'd like to remove it from my local game, but can't find it.

**Comment by cthae** [comment]
@OArndt I believe this is it: https://www.curseforge.com/minecraft/mc-mods/bloodmoon Maybe reducing the 5% chance for it about ten times to half a percent chance would make more sense. Blood moon once every 200 days. Maybe.
