### ISSUE TITLE
Refined Storage Auto Crafting 

### ISSUE THREAD

**Issue by Shrekovitch** [AllTheMods/ATM-9#603]
![Screenshot 2023-10-12 170757](https://github.com/AllTheMods/ATM-9/assets/147887338/8a733005-87ac-4074-a633-6378a7fc5a95)

Got a problem with Extra Disks on refine storage. I do all the patterns to get infinite storage and put them in the crafter, then when i go to craft then they change from ED to either Extra Storage and Reborn Storage for some reason. Seem to be a conflict, how do i resolve?

**Comment by themadjem** [comment]
I offered a solution in Issue #565 , You can use the javascript provided saved in the `kubejs/server-scripts` folder to remove the Extra Storage recipes, I will update it to remove the Reborn Storage recipes too.

**Comment by Shrekovitch** [comment]
Sorry new to this. How do I add the script to the folder do I use a program or WordPad?
