### ISSUE TITLE
EnderIO no dark steel anvil

### ISSUE THREAD

**Issue by babyFUNK** [AllTheMods/ATM-9#608]
Not sure if this is a bug or if it was removed on purpose but the recipe for dark steel anvil doesn't work, so I can't use powered spawners. Went to creative and I'm not seeing the item at all.

**Comment by mZ0ckERc** [comment]
EnderIO was only available up to 1.12.2 recently, now there are many people working on porting it to newer versions. It seems as if a complete or at least big part of the mod has to be rewritten.
Unfortunately, not all features of EnderIO have been implemented yet (I have noticed some myself during gameplay). This seems to be one of those. Your best bet is probably to create an issue over at [the EnderIO repository](https://github.com/Team-EnderIO/EnderIO).
