### ISSUE TITLE
Mystical Agriculture Step Assist causing ctd

### ISSUE THREAD

**Issue by Ozimundis** [AllTheMods/ATM-9#61]
MC Ver 1.20.1
Pack version 0.0.21
No additional mods.
1 Additional Datapack added (packing tape able to move spawners)

Freshly crafted step assist augment, installed on supremium boots with frost walker enchant, tried to equip via right clicking boots in hand only to have my single player instance immediately crash to desktop. 

Any further attempts to enter that specific world are resulting in the same ctd. 

Crash report attached. 

With datapack 
[crash-2023-07-03_01.32.20-server.txt](https://github.com/AllTheMods/ATM-9/files/11931902/crash-2023-07-03_01.32.20-server.txt)

Without
[crash-2023-07-03_01.45.34-server.txt](https://github.com/AllTheMods/ATM-9/files/11931909/crash-2023-07-03_01.45.34-server.txt)

Tested in a fresh world, cheating in supremium boots, tinker table and augment, same result. 

[crash-2023-07-03_01.49.07-client.txt](https://github.com/AllTheMods/ATM-9/files/11931920/crash-2023-07-03_01.49.07-client.txt)

**Comment by wraithhawit** [comment]
I made an instance of minecraft with just mystical agriculture and it has the same crash, this is a problem with just the mod

**Comment by MarobsKoco** [comment]
My game dont crashes, but step assist dont work at all.
I gues they are still working on this an put it off for now?
