### ISSUE TITLE
Harvester Pylon destroys silent gear hoe

### ISSUE THREAD

**Issue by Laurent-Mercier** [AllTheMods/ATM-9#610]
Hi, I'm currently running the pack on version 0.2.1 and I've noticed the following bug: when using a silent gear hoe in the harvester pylon, the hoe disappears when it reaches durability 0. As it is a silent gear item, it should be broken but still appearing in the inventory so I can repair it.

**Comment by shortybsd** [comment]
> Hi, I'm currently running the pack on version 0.2.1 and I've noticed the following bug: when using a silent gear hoe in the harvester pylon, the hoe disappears when it reaches durability 0. As it is a silent gear item, it should be broken but still appearing in the inventory so I can repair it.

Same here, 
Silent Gear for 1.20.1 version 3.6.3
All The Mods 9 version 0.2.58
