### ISSUE TITLE
maps crash

### ISSUE THREAD

**Issue by redgoblin88** [AllTheMods/ATM-9#613]
upon trying to use an empty map (or obtain an already made map, such as vanilla treasure maps) i get a crash
this happens on a server so there is no crashlog, it causes a "crashloop" and needs admins to delete the map fromt he player inv

![image](https://github.com/AllTheMods/ATM-9/assets/13396472/a15e322f-f724-4850-b91e-1cdc256e9a29)

**Comment by PaziGamer** [comment]
I can confirm this. Opening any map causes that same crash for me too on my own server, with some variation on the byte count numbers the crash reports.

Also some other players get that same crash at login on my server, but not all of them. And that has led to a revelation that also maps hanged on the wall on item frames cause the same crash on client.

I got this fixed by removing all the map-files from the servers world/data folder. But I guess we better keep our blocky fingers off from the maps for now.

**Comment by Holysweet** [comment]
Had hoped after discovering this crash that the Twilight forest map would behave normally but can confirm that also doesn't work out :) so yes lets all not touch maps ever again :P

**Comment by spiceswag** [comment]
Can reproduce this on my own server.
I thought i had struck some early game loot :sob:

**Comment by WheresMyMtnDew** [comment]
Yes, I just had the same issue on our server as well. Had to delete data file in the world folder in the player data folder to allow player to log back in. Of course this starts them back at the spawn point. Was able to duplicate this crash. Fortunately this is a new server and we did not have any maps on display. Playing 0.2.4- on multiplayer server with no mods added or adjustments made.

**Comment by Wuerfelhusten** [comment]
Have the same issue. I always have to edit the .dat files to remove broken maps. Without I am not even able to join the server again.

**Comment by m-riley04** [comment]
Also having this issue. My recommendation for everyone here is to get NBTExplorer. Here are steps to delete the map item from a player's inventory using NBTExplorer:

1. Stop the server (might work while running, never have tried though)
2. Navigate to your server files, the world folder, then the "playerdata" folder
3. Download/copy the corresponding player data (.DAT) file
4. Drag said copy into NBTExplorer
5. Locate the "Inventory" list dropdown (under Attributes and EnderItems)
6. Go through every entry until you find "minecraft:filled_map" (or another mod's map, I assume)
7. Select it and click the "delete tag" (red 'x')
8. Save within NBTExplorer (Ctrl+S)
9. Drag the .DAT file back into the playerdata folder (overwrite or replace it. **Must be the same name as before.**)
10. Start the server
