### ISSUE TITLE
Mystical Agriculture Quest Reward Table Can Reward Wrong Infusion Crystal

### ISSUE THREAD

**Issue by c0rphan** [AllTheMods/ATM-9#618]
The Tier 1 Seed Bag loot table contains mysticalagriculture:infusion_crystal as a reward, but this item is made obsolete by the mod Mystical Agriculture Tiered Crystals. Probably the table should be granting matc:inferium_crystal instead.

Version 0.2.4

**Comment by alfredggttv** [comment]
Will be fixed in the next update.
