### ISSUE TITLE
Flux networks not taking power from batteries

### ISSUE THREAD

**Issue by TheOnlyGalaxyGaming** [AllTheMods/ATM-9#620]
I have a giant 5EU RFTools battery, and my flux controller won't distribute power throughout the system, however the wireless charging works. 
I just changed the battery out for a Mekanism one, and the same issue persists. It would seem that Flux Networks is the problem

**Comment by Queen4Eternity** [comment]
I'm having the same issue with the powercells from RFTools but I was able to get the Mekanism cubes to work.
