### ISSUE TITLE
Sophisticated Backpacks Inventory Disappearing

### ISSUE THREAD

**Issue by Naoumxx** [AllTheMods/ATM-9#623]
My game had crashed and when I logged back onto my single player world, all items within my sophisticated backpack were gone. Here is an image of the uuid for the backpack
![Screenshot (18)](https://github.com/AllTheMods/ATM-9/assets/113739536/72215c2a-e163-40f6-a5f0-81573b909251)

**Comment by aAndrew3030** [comment]
Sophisticated backpack content is saved to its own file in the data folder of your world. That file likely became corrupted when your game crashed. You could try replacing that file from a backup. If the uuid from the backed up file matches the current uuid (a new one wasnt assigned) your contents should be restored. If the uuid does not match, you would need to edit that in your player data, or replace your world with a pre crash backup
