### ISSUE TITLE
Already existing worlds crash when trying to generate new chunks, can't create new worlds

### ISSUE THREAD

**Issue by Pirovka** [AllTheMods/ATM-9#624]
Hi. 

Every time the game wants to generate new chunks in the overworld it crashes with the below message:

"The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / terralith:snowy_cherry_grove]=net.minecraft.world.level.biome.Biome@226076ae}, Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:lush_savanna]=net.minecraft.world.level.biome.Biome@73198be8}]"

When trying to create a new world i get "Exit Code: -1"

using All the Mods 9-0.2.5

**Comment by Mitchell5200** [comment]
Remove your extra mods, cyclic is the cause here

**Comment by Pirovka** [comment]
You are right i forgot to remove cyclic when checking without my extra mods. Solved the issue thank you!
