### ISSUE TITLE
Integrated Dynamics - Squeezer crash/not working

### ISSUE THREAD

**Issue by thenameisdylan** [AllTheMods/ATM-9#63]
The squeezer does not work and for some recipes it crashes the game.
Tried on both stone and ancient debris, stone didn't yield anything while ancient debris didn't work/crashed.

**Comment by Krutontar** [comment]
Same problem.  I was trying it on menril logs.  Crashes with "Internal Server error" and doesnt take the server down.

**Comment by Krutontar** [comment]
So, when in doubt, and the problem seems to be client side only, I disable shaders.  Now it stops happening.

**Comment by NoMoreStars** [comment]
Might be a different bug but the squeezer seems completely broken on the most recent version. Weirdly enough you can jump on it and it works just fine with no item inside but as soon as an item is placed inside it stops working entirely until you restart the world.
