### ISSUE TITLE
ATM-9-0.2.5 Crash in the nether and random crashes

### ISSUE THREAD

**Issue by Armagedon13** [AllTheMods/ATM-9#630]
Prism launcher 7.2
ATM-9-0.2.5
java Eclipse Adoptium JDK 17.0.8.101 hotspot
ram dedicated 8064 

i don't know why i have this random crashes
[crash log](https://pastebin.com/3ac3QVLc)

another thing is the sort with middle click lag everything 
here is the lastest log maybe you can see the random crashes i have
[lastest log](https://pastes.io/an4yjfpoo6)

**Comment by aAndrew3030** [comment]
To fix the middle click lag, disable Inventory Profiles Next, or go to the config and remove middle click to sort and use Sophisticated Storage to sort chests/barrels/etc. As far as the crash, the report mentions Deeper Darker enchantment, are you using one of the enchantments from that mod?

**Comment by aAndrew3030** [comment]
Also a temporary fix to prevent crashing would be to use the mod Neruina Ticking Entity Fixer (it removes the ticking entity before it can crash the server)
