### ISSUE TITLE
Entangloporter doens't work for Items.

### ISSUE THREAD

**Issue by Croat86** [AllTheMods/ATM-9#633]
I hooked up an Entangloporter on a Digitial Miner which should send me items to the base, als always. But it is somehow bugged

**Comment by john13210** [comment]
you should just use an ender chest for this

**Comment by rmccarthy1504** [comment]
Best to share a screenshot, to ensure it's setup correctly.

While the entangloporter cab share energy and items, the digital miner has separate ports for each.
