### ISSUE TITLE
Minecolonies - teach custom recipe crash game

### ISSUE THREAD

**Issue by petriczech** [AllTheMods/ATM-9#635]
If I click to "select" button, game crash.

![image](https://github.com/AllTheMods/ATM-9/assets/5469703/018991a1-af6a-494d-ada6-17292bf9748c)

[crash-2023-10-17_18.44.38-client.txt](https://github.com/AllTheMods/ATM-9/files/12936733/crash-2023-10-17_18.44.38-client.txt)

**Comment by LucksFavor** [comment]
I and a friend have both ran into this issue. repeatable.

**Comment by Chevron9** [comment]
Tracked by the MC team at https://github.com/ldtteam/minecolonies/issues/9492

**Comment by petriczech** [comment]
bug in minecolonies done, so can close
