### ISSUE TITLE
Issue with .2.X releases onwards - Terralith?

### ISSUE THREAD

**Issue by kybernetic-afk** [AllTheMods/ATM-9#638]
All is fine on 0.1.12, but if I upgrade my server to any of the .2 releases, it crashes with a note in the crash log about terralith biomes.

Having investigated a little further, I noticed that terralith is one of two or three mods that are are version 1.20.2 in the mods folder, whereas everything else is 1.20 or 1.20.1 - thought it might be worth highlighting

**Comment by Mitchell5200** [comment]
Crashlogs via https://mclo.gs/ please, but i suspect that you've added Cyclic and that is causing the issue, as other times a similar issue has occurred, the user had added cyclic.

**Comment by kybernetic-afk** [comment]
> Crashlogs via https://mclo.gs/ please, but i suspect that you've added Cyclic and that is causing the issue, as other times a similar issue has occurred, the user had added cyclic.

Thanks for the response - We do indeed have cyclic on the server, it hasn't been an issue through pretty much all 1.X versions, we started on 1.3 I believe and went through each update to 1.12.

I'll submit the crashlogs when I'm back home, but if cyclic is the believed cause, do we have to remove it? Or is there a workaround?

**Comment by Mitchell5200** [comment]
As we do not intend to add cyclic to the pack, ever, i have not investigated as to the why, only that removing it fixes the issue, someone could report it to the developer and see if they can fix it.

**Comment by kybernetic-afk** [comment]
That's a shame, it is in my opinion a very strong mod, which adds a lot of functionality. But I understand your position too. I'll test it without cyclic when we next attempt an upgrade. Right now we've reverted back to the 1.12 release from last week, as it was solid and worked without issue. I'll try and get those crash logs to you this evening.
