### ISSUE TITLE
Ender combs are not getting processed by any centrifuge

### ISSUE THREAD

**Issue by Goten92x** [AllTheMods/ATM-9#64]
The title says it all. I tested all 3 and they are just clogging up my system. It happenend in the last update (0.0.23).

**Comment by CyberColonel** [comment]
Do you have other centrifuges right next to that one? For some reason the centrifuges push liquids to each other and if an adjacent centrifuge has honey in it, it will push that honey into your ender comb centrifuge and block processing. Vice versa can happen if liquid chorus crosses over.
