### ISSUE TITLE
Game crash when opening certain quests, mostly productive bee quests

### ISSUE THREAD

**Issue by squattingdogger** [AllTheMods/ATM-9#645]
![image](https://github.com/AllTheMods/ATM-9/assets/148501725/a37b7e99-495b-4a87-b498-72d06b7b25ad)

**Comment by loving2** [comment]
which quests in specific are you able to recreate this crash by selecting? I haven't been able to recreate this, and I've gone through and opened every single quest

also would you be able to upload the latest.log after crashing to mclo.gs and share it here?

**Comment by squattingdogger** [comment]
[crash-2023-10-19_21.31.01-client.txt](https://github.com/AllTheMods/ATM-9/files/13049376/crash-2023-10-19_21.31.01-client.txt)

**Comment by squattingdogger** [comment]
[latest.log](https://github.com/AllTheMods/ATM-9/files/13049397/latest.log)
