### ISSUE TITLE
"Ignore Players" on Apotheosis Spawner

### ISSUE THREAD

**Issue by ryennce** [AllTheMods/ATM-9#647]
ATM V: 0.2.6

I made a mobtrap for exp using spawners from apotheosis using the conduit to ignore the player condition. But id doesnt seem to work like that. 

To reproduce it:
- Make a mobtrap using an apotheosis spawner 
- Mine had: redstone crontrol, no AI, Ignore players
-Use something to transfer the xp to somewhere else (ender tank or entangled block) 
-Go far, like 10 thousands blocks away from the mobtrap and tranfer the xp to there.
-Load both chunks

![image](https://github.com/AllTheMods/ATM-9/assets/102876250/f5d849ad-938a-4187-850c-e725816ca23f)

To solve it? 
I used a spawner agitator. 

The error:
The exp wont go up. Because the spawner module that's supposed to ignore players doesnt seem to work even with both chunks loaded.

**Comment by Paisty** [comment]
I had a similar issue; force loading the chunk along with ignores players(conduit) and ignore conditions(dragon egg) would not be enough for ANY mob to spawn at a distance, be it a passive or hostile mob. 

A temporary solution, one that doesn't require a shift to Industrial Foregoing, is to use a spawn agitator.
