### ISSUE TITLE
Tooltip isn't there

### ISSUE THREAD

**Issue by Frevert** [AllTheMods/ATM-9#649]
i have a problem, that the tooltip on top isn't there anymore. It is after i updated to the latest version. 
Is it a configuration problem i have or is an option i don't find? 
Thanks for help

**Comment by aAndrew3030** [comment]
If you are talking about the Jade mod, there are keybinds to turn it on and off. They sometimes get reset when updating the pack. The default is keypad 1 to toggle it, and keypad 0 to change the settings

**Comment by Frevert** [comment]
thank you very much
