### ISSUE TITLE
JEI/refined storage not working as intended

### ISSUE THREAD

**Issue by 1Harsh-Shah** [AllTheMods/ATM-9#65]
![1](https://github.com/AllTheMods/ATM-9/assets/68141954/9badb2d2-e529-467b-88ce-bb7435a83cb0)

![2](https://github.com/AllTheMods/ATM-9/assets/68141954/f742738e-8ef2-4d9f-aa03-3520b7c57010)

**Comment by MBMRMASTAR** [comment]
It's a JEI limitation not a ATM bug

Disclaimer:
I'm not part of the ATM Team I'm just a random dude saying there thoughts.
