### ISSUE TITLE
Vanilla Recipes Book cannot be reopened

### ISSUE THREAD

**Issue by MarcusUA** [AllTheMods/ATM-9#650]
ATM 9 0.2.6
After accidentally closing Vanilla Recipes Book there is no way to re-open it.
No book icon in inventory or crafting menus (only rotate, balance and clear grid buttons are present) and no hot-key for it.   
![photo_2023-10-20_11-46-11](https://github.com/AllTheMods/ATM-9/assets/3418165/fd9ff9f9-a0bd-429b-8c98-9a86f820c11b)

**Comment by screret** [comment]
use JEI?

**Comment by MarcusUA** [comment]
> use JEI?

Yes, but its not convenient, vanilla book shows currently available recipes, while I have to search for required recipe in JEI. Even if I add required recipe to bookmarks it requires clicking different items on different parts of display (I have ultrawide so its very far apart) , instead of SHIFT clicking item in vanilla book.
Recipes that can only make one item at a time are especially painful.

**Comment by aAndrew3030** [comment]
If you go to the config folder the setting to change this is in the "craftingtweaks-common.toml". Change "hidevanillaCraftingGuide" to false

**Comment by aAndrew3030** [comment]
Also if you want to fix the JEI being far apart, the settings for the are in the JEI config folder in "jei-client.ini". You can adjust the number of rows and columns and the part of the screen they align to

**Comment by MarcusUA** [comment]
> If you go to the config folder the setting to change this is in the "craftingtweaks-common.toml". Change "hidevanillaCraftingGuide" to false

This does it!

Is hidden vanilla recipes book by design? If so, we can close this bug.

**Comment by Mitchell5200** [comment]
yes, as it can have performance issues with the massive amount of modded recipes. Will not be enabled in the pack.
