### ISSUE TITLE
Can't partition MEGA radioactive chemical storage cells

### ISSUE THREAD

**Issue by Fraggy99s** [AllTheMods/ATM-9#651]
# Expected behavior

- put MEGA radioactive chemical storage cell into AE2 Cell workbench
- drag and drop the item (in this case the radioactive gas) into the cell workbench to make a partition
- take cell out of workbench
- cell is partitioned and can store the radioactive gasses

# Actual behavior

- put cell into workbench
- can't drag and drop gasses into cell workbench (either can't drag or no impact after drag)
- therefore can't partition mega cell
- therefore can't store radioactive gasses 

tried to partition with chemical tank containing the radioactive gasses from JEI
tried to partition with the blank item from JEI

![issue](https://github.com/AllTheMods/ATM-9/assets/12915958/265ad0fa-c77f-4a3f-8afd-7d2f53a862b9)

**Comment by Fraggy99s** [comment]
playing on version 0.2.5 btw

**Comment by Fraggy99s** [comment]
![mega](https://github.com/AllTheMods/ATM-9/assets/12915958/47b7f215-9c21-4b0f-867d-1b0d41c9e6af)
Managed to set a filter with a cheated creative tank but a CHEMICAL storage cell cant store chemicals (wtf??)

**Comment by 62832** [comment]
The missing JEI drag behaviour is being tracked under https://github.com/AppliedEnergistics/Applied-Mekanistics/issues/42. As for the last screenshot, radioactive cells specifically do not support *Spent* Nuclear Waste for balancing reasons unless you enable it in a config.
