### ISSUE TITLE
[Full] [ATM9 0.2.6] Server Crashing, Looks Like Memory Leak, Lists a Cobblemon Block in Previous Error Logs

### ISSUE THREAD

**Issue by SpaceCowboyJolts** [AllTheMods/ATM-9#654]
I want to preface that ATM9-0.2.6 is working fine for our server, however, we got cocky and added Cobblemon to the server only for it to generate a memory or at least what looks like a memory leak. 

I don't know what information would be most useful to help figure out this issue, however, I've supplied the most recent and relevant crash log. 

The cobblemon mod and the healing block for cobblemon are listed in a previous overnight crash log. Server side it looks like ramping memory, then a crash occurs once it caps out. No in-game issues occur other than the server crash. This only began after adding Cobblemon to our server and doesn't happen once removed. After removing the mod and re-playing for an hour or so we found no issues and no ramping RAM. We'd like to keep the Cobblemon mod in but have no idea where to start on fixing this issue. 

Version: 1.20.1
Cobbelmon Mod Version: 1.4.0
Base Modpack: ATM9-0.2.6

Server Details: 
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.4.0-153-generic
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 33780880 bytes (32 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 72578.80
	Virtual memory used (MB): 75138.80
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 4095.68
	JVM Flags: 2 total; -Xms128M -Xmx12288M

https://pastebin.com/zZqHrX7e

**Comment by Stijnkluiters** [comment]
You are adding custom mods to your server. Maybe you can get help from a different developer. But this is not an issue related to this modpack. You should close this issue.
