### ISSUE TITLE
Looter Chests corrupt player data

### ISSUE THREAD

**Issue by bsylve1996** [AllTheMods/ATM-9#655]
Version I am on is 0.2.4

Sometimes if you open lootr chests on server it will corrupt player data and that player cannot reconnect to the server

![image](https://github.com/AllTheMods/ATM-9/assets/35739125/43ceabce-8fed-4a76-9d0b-f4ea12e79ecd)

**Comment by bsylve1996** [comment]
When players try to join they get the error message I showing above. They cannot reconnect to that server unless the world is reverted back or we delete their player data.

**Comment by Sudoasroot** [comment]
@bsylve1996 this has been fixed already, please update your Server

**Comment by bsylve1996** [comment]
@Sudoasroot which version was this fixed in?

**Comment by Sudoasroot** [comment]
0.2.5 - the latest one is 0.2.6 with some more fixes

**Comment by bsylve1996** [comment]
Alright will update then. Thanks
