### ISSUE TITLE
[ATM9][0.2.6] Low TPS on server with multiple players

### ISSUE THREAD

**Issue by clavierp** [AllTheMods/ATM-9#660]
Hello

I have a small server with ~4 players and when there is over 2 players online, the TPS falls bellow 10. I ran a lot of observable profiler and it seems NPC are taking a lot of ressources.

minecraft:zombie | 11598 us/t (8009 ticks)
minecraft:skeleton | 6909 us/t (4974 ticks)
minecraft:bat | 4832 us/t (4815 ticks)
minecraft:creeper | 4555 us/t (3728 ticks)
minecraft:item | 4109 us/t (14928 ticks)
minecraft:sheep | 3954 us/t (3259 ticks)
minecraft:pig | 3063 us/t (2548 ticks)
artifacts:mimic | 2527 us/t (2342 ticks)
minecraft:cow | 2414 us/t (1831 ticks)
minecraft:chicken | 2304 us/t (1936 ticks)
minecraft:spider | 2076 us/t (1542 ticks)
productivebees:green_carpenter_bee | 1246 us/t (917 ticks)
productivebees:yellow_black_carpenter_bee | 1187 us/t (843 ticks)
minecraft:villager | 1157 us/t (303 ticks)
minecraft:mob_spawner | 1044 us/t (63141 ticks)
minecraft:squid | 1042 us/t (1284 ticks)
minecraft:axolotl | 1002 us/t (480 ticks)

11 ms/t for zombies seems a lot for around 20 zombies serverwide

And adding on top of that the necromancer issue (https://github.com/AllTheMods/ATM-9/issues/350) -> 115 necromencer atm

**Comment by NousYeCuites** [comment]
We have the same problem on a beefy server, cpu isn't really used that much (12% to 14% usage, on 10 threads), ram isn't the problem either, I can upload the Spark dump if it helps, all the lag seems to come from entity ticking. It becomes pretty much unbearable with 6+ players, on fresh server.

**Comment by Nalyd217** [comment]
Have you been able to resolve this at all? Running into similar server lag issues as you.

**Comment by NousYeCuites** [comment]
@Nalyd217 turned the server into peaceful mode and then back to whatever it was before (normal, hard, easy) and it pretty much resolved it. Seems like something in this version created corrupted mobs that couldnt despawn
