### ISSUE TITLE
enderpearl dupe

### ISSUE THREAD

**Issue by MikeyPantsOn** [AllTheMods/ATM-9#665]
ender pearls can be crafted into ender pearl fragments, 9 or 4 fragments depends on the recipe.
meanwhile ender pearls can be crafted with 4 fragments only, meaning u can make an enderpearl into 9 fragments and make 2 out of it.
unsure if its cause of atm or forbidden & arcanus mod but might as well report it.

**Comment by bojantrpe** [comment]
ran into this now and wanted to report it. but found it's already reported here.
