### ISSUE TITLE
[Suggestions] Megatorches block Grave Guardians. They shouldn't.

### ISSUE THREAD

**Issue by cthae** [AllTheMods/ATM-9#666]
Grave Guardians are peaceful mobs and as such, they shouldn't be blocked. Moreover, you can trade with them. That's another important reason not to block them.

**Comment by Stray216** [comment]
Not really a modpack issue.

You can suggest it to the creator of the megatorch here:
https://github.com/Xalcon/TorchMaster/issues

**Comment by cthae** [comment]
Why would a megatorch creator care about an unrelated mod compatibility. Isn't it up to the modpack team to sync mods, solve conflicts where possible.

Megatorch seems simple to me for ATM team to be able to tinker it as they see fit.

**Comment by Stray216** [comment]
You might be right. It also seems like there is a config to override the megatorch/flarelantern to allow or block mobs, so this should indeed be simple enough.
