### ISSUE TITLE
[Bug] Most of non-vanilla pickaxes break ATM ores.

### ISSUE THREAD

**Issue by cthae** [AllTheMods/ATM-9#667]
0.2.6
An example would be a copper pickaxe.

**Comment by Stijnkluiters** [comment]
Can you be more specific? Which pickaxe is breaking which ore and from which mod?
Are you sure you just don't need a higher tier pickaxe? (something like diamond)

**Comment by cthae** [comment]
To my knowledge, there's only one copper pickaxe. I believe it's from Simply Additions or something. There are many more.

It breaks the Allthemodium ore. I believe it breaks the other ATM ores too. 

To break Allthemodium, you're supposed to need a netherite pickaxe, however, copper works just fine, heh.

**Comment by alekthefirst** [comment]
Tested on 0.2.9 and pickaxes from following mods can mine allthemodium:
Create Stuff & Additions (tested copper pickaxe)
Railcraft Reborn (tested steel pickaxe)
The Aether (tested skyroot pickaxe)
The Undergarden (tested cloggrum pickaxe)
Natures Aura (tested botanists pickaxe)
Blue Skies (tested maple wood pickaxe)

Several other mods were also tested but their pickaxes performed as expected
