### ISSUE TITLE
Can't launch ATM9

### ISSUE THREAD

**Issue by Mndb1** [AllTheMods/ATM-9#67]
I'm trying to launch the modpack but not the loading screen appears, it just crashes. The log doesn't say anything, just the crash report. I can launch other modpacks but not ATM9.
Crash report: https://mclo.gs/nX8LlbE
Log: https://mclo.gs/Eh7bZWN
Help needed, please. Thanks.

**Comment by mattpsvreis** [comment]
This seems like the same issue I had, and my fix was uninstalling the current installed video graphics drivers with DDU (Display Driver Uninstaller) and then install the most recent one for my current GPU.

I see from the Crash Report you have integrated graphics, which could be a bit more trickier. Please try and find the most adequate tutorial to fresh re-install the most recent drivers for your specific specs.

**Comment by Mndb1** [comment]
You just made me remember that by default my laptop uses the integrated graphics rather than the dedicated. Simply changed from integrated graphics to the dedicated GPU and it worked. Thanks.

**Comment by mattpsvreis** [comment]
> 

Glad I was of help!
