### ISSUE TITLE
Can't finish refined storage quests

### ISSUE THREAD

**Issue by AHoroszkiewicz** [AllTheMods/ATM-9#672]
Quests "256k Storage Part" and "1024k Storage Part" don't accept items. I forcefully finished 256k quest with editing mode, but 1024k doesn't work either. Maybe its because i crafted it with autocrafting? I tried dropping those items, putting in chests/storage and nothing worked (i waited for 10s each try just to make sure its not lag). Also I tried editing the quests by removing and adding said items, but that didn't help
update: yes, it's problem with refined storage autocrafting. For some reason there are two identical recipes for two identical items from two different mods. When i put "256k Storage Part" from "Extra Disks" recipe into pattern it thinks its the same item but from "Extra Storage". It look the same, functions the same, but quest doesn't recognize it
update2: sometimes i even get recipes from "RebornStorage" instead of what i wanted

**Comment by Xplodin** [comment]
craft the disk and then uncraft it with shift right click to get the correct part

**Comment by bsylve1996** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/35739125/9785a9f1-0517-438b-b122-5bc2abad570c)
Add an image to back this up. I forced the output to be 1014K from extra disks which is what the quest wants but you can see the pattern still went to rebornstorage

**Comment by AHoroszkiewicz** [comment]
Managed to partially fix it by removing recipes with KubeJS, but I need to do /reload and make new patterns every time i load into the world. If anyone needs it open notepad, paste this:
ServerEvents.recipes(event => {
    [
        'extrastorage:storagepart_256k',
        'extrastorage:storagepart_1024k',
        'extrastorage:storagepart_16384k',
        'rebornstorage:small_item_disk_part',
        'rebornstorage:medium_item_disk_part',
        'rebornstorage:large_item_disk_part',
        'rebornstorage:larger_item_disk_part',
        'extrastorage:storagepart_16384k_fluid',
        'extrastorage:storagepart_65536k_fluid',
        'extrastorage:storagepart_262144k_fluid',
        'extrastorage:storagepart_1048m_fluid',
    ].forEach(id => event.remove({output: id}))
});
and save it into ATM9>kubejs>server_scripts as anything.js (for example extraStorage.js)

**Comment by john13210** [comment]
the stupid thing is they added 2 mods with storage parts and they just didnt check which ones you get and which ones are set in the quests

**Comment by AHoroszkiewicz** [comment]
> the stupid thing is they added 2 mods with storage parts and they just didnt check which ones you get and which ones are set in the quests

i counted 3 mods that add the same storage parts ("ExtraDisks","ExtraStorage","RebornStorage") but they also add more than just those parts. Devs probably just didn't noticed they all have their own storage parts
