### ISSUE TITLE
Electrolytic Separator missing recipes for oxygen/hydrogen from water

### ISSUE THREAD

**Issue by munchingchungus** [AllTheMods/ATM-9#673]
I just updated to 0.2.8 from 0.2.6 and the electrolytic separator no longer produces hydrogen or oxygen.
This seems like a strange thing to break, which made me think it was intentional, however I couldn't find anything in the patch notes.

**Comment by Schrimpes** [comment]
I have the same problem. It has also happened that it worked at the beginning and then the error occurred after a dimension change. Restarting the save helped for now.

**Comment by munchingchungus** [comment]
How odd, I ended up downgrading to 0.2.7 which works as a temporary solution I suppose.

**Comment by munchingchungus** [comment]
Looks to be fixed in 0.2.9
