### ISSUE TITLE
Payload problem

### ISSUE THREAD

**Issue by Sayaniku** [AllTheMods/ATM-9#678]
So we had an little problem with refined and their payload, when someone try to make an chest or an jukebox, he has always this message, we are on 0.2.6 ver of the modpack, and that happens a lot of time
![image](https://github.com/AllTheMods/ATM-9/assets/44569441/59895636-ed0a-48aa-96ab-33bcb9b27726)

**Comment by aAndrew3030** [comment]
https://github.com/AllTheMods/ATM-9/issues/688

**Comment by aAndrew3030** [comment]
https://github.com/refinedmods/refinedstorage/issues/3568
