### ISSUE TITLE
Nether Banana and NetherWood Sappling not Spawning in chests

### ISSUE THREAD

**Issue by FResetFrisk** [AllTheMods/ATM-9#68]
as the title says, i have been searching my world for netherwood sapplings and nether bananas from the silent gear mod so that i can get a tier 3 grader catalyst known as glittery dust but have searched about 15 different bastions and several dozen ruined portals and have found none

**Comment by LupusTheFallen** [comment]
Same as #60 - nothing from Silent Gear is spawning in chests. This still happens in 0.0.63.
