### ISSUE TITLE
[Bug] New endermen should be listed in the Megatorch as entities to block

### ISSUE THREAD

**Issue by cthae** [AllTheMods/ATM-9#680]
0.2.9
They spawn in protected areas.
It causes issues. 

For example, a mushroom enderman spawned in our induction matrix and placed a mushroom in it, breaking the multiblock effectively. Here, snapped a photo of it: https://i.imgur.com/nIoCTMi.jpg

**Comment by cthae** [comment]
Oh, I should add that the induction matrix is in a claimed area. Mobs shouldn't be able to take or place blocks in claimed areas. Here's the config of the area: 
https://i.imgur.com/VVovWBi.jpg
As you can see, mob griefing actions are not allowed. And yet, endermen keep placing those bloody mushrooms everywhere.

**Comment by TheLastPaladin** [comment]
I can confirm this.
