### ISSUE TITLE
[Bug] Tool belt key bind won't open radial menu

### ISSUE THREAD

**Issue by daniele-f** [AllTheMods/ATM-9#681]
Version: 0.2.9

Info: Made the tool belt, and inserted the 2 pouches from the quest using an anvil. 
Then tried to use the key bind to activate it, but nothing happens, tried multiple key binds, even key binds that don't conflict with anything else.
I am able to open a menu when right-clicking the item in my hand.

**Comment by Pherex** [comment]
I'm running into the same issue, @daniele-f were you able to find a fix?

**Comment by daniele-f** [comment]
> I'm running into the same issue, @daniele-f were you able to find a fix?

It's been a while since I've played ATM.
I don't think I found a solution, I think I just stopped using the belt.
