### ISSUE TITLE
(Bug) Gregtech ore not show ore name correctly since update.

### ISSUE THREAD

**Issue by Grisabeller** [AllTheMods/ATM-9#682]
![2023-10-27_22 57 43](https://github.com/AllTheMods/ATM-9/assets/137112235/91acea5c-b33b-4516-bf5b-f00996b0c11c)
as shown all ore showing up as tagprefix.ore even after reloading still showing the same

**Comment by aAndrew3030** [comment]
Fixed in GT 1.0.13.e
