### ISSUE TITLE
[Bug] - Cable and questbook doens't work 

### ISSUE THREAD

**Issue by deoguinho** [AllTheMods/ATM-9#683]
Hi Guys! My friends and I always play your modpack and it's amazing, but recently we had some problems
The EnderIO conduit cable does not accept the flux point or the flux plug, much less the refined storage cables, is there a way to fix this? Another problem is that when we exit Minecraft the questbook is being blocked, can you check?

Hail from Brazil!!

**Comment by john13210** [comment]
go tell that to enderio ppl
exit minecraft what do you mean ?
