### ISSUE TITLE
[Bug] - Unable to sleep in Handcrafted's Fancy Beds since Update

### ISSUE THREAD

**Issue by alfieengland** [AllTheMods/ATM-9#684]
Updated dedicated server & client from 0.2.6 to 0.2.9 and now unable to sleep in Fancy Beds.

Have attempted breaking and re-placing beds, doesn't solve issue.

**Comment by SpinHarmony** [comment]
This was due to an update to Handcrafted, there has since been another update that fixed the issue, but the modpack has not been updated to include it yet. I would recommend manually updating Handcrafted until then.
