### ISSUE TITLE
Crash/Disconnect when using JEI to craft with refined storage

### ISSUE THREAD

**Issue by LarryFullSend** [AllTheMods/ATM-9#688]
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

myself and the server owner have tried using 2 different machines and wifi networks and i believe that refined storage mixed with JEI may be corrupted but i cant narrow it down sadly. i don't know how to port my world and start with fresh files either any help would be greatly appreciated

**Comment by aAndrew3030** [comment]
A full crash report or log would be helpful. When your using JEI to craft with RS, are you using the "+" button in JEI, and if so, what are you trying to craft?

**Comment by dstephens1980** [comment]
@aAndrew3030,
I too am seeing this issue but not for everything, I can using the Wireless crafting grid and the Refined Storage crafting grid to pull from storage and build anything and it will be random as to whether or not the "packet crash" happens, except for the Refined Storage "Stone Brick cable cover", that will cause the issue every time.  I am unsure how to get a full crash report as the "crash" doesn't actually crash the server or client.  It simple shows the error and then drops you back to the MC Multiplayer window, now you cannot reconnect immediately back to the server but if you escape back to main MC menu and re-enter multiplayer menu you can rejoin the server just fine.  Please let me know if you need more information.  Thank you!
