### ISSUE TITLE
Mahou Tsukai I Caliburn > Morgan Issue

### ISSUE THREAD

**Issue by TuShaggy** [AllTheMods/ATM-9#689]
Killing an allied wolf with the Caliburn sword does not turn it into the Morgan sword. I have seen that in ATM8 there was a mod called savepets or something like that that made this error occur but I also saw that the solution was to give him a potato poisoned with the caliburn in my hand but did not work any suggestions to solve it? <--- im on a private server

**Comment by Mitchell5200** [comment]
changed to a warden, also Iron's spellbooks ender orbs instead of nether stars

**Comment by TuShaggy** [comment]
ohhh solved!!!

**Comment by ryennce** [comment]
Sorry to ask but how do you raise its damage after being turned to Caliburn ?

**Comment by TuShaggy** [comment]
killing villagers!!! what a think!
