### ISSUE TITLE
Superflat world doesnt generate

### ISSUE THREAD

**Issue by TwistedKindn3ss** [AllTheMods/ATM-9#69]
Was trying to generate a superflat world on a fresh install to do some creative building, but the world generates like a regular world instead of superflat world.

**Comment by taiyoko** [comment]
I am having this same issue -- I tell the game to generate a superflat world and instead I get normal worldgen.
Pack version 0.0.46

**Comment by Perryplatypus05** [comment]
I am having the same issue on version 0.0.50

**Comment by Makinen-Tayler** [comment]
Same issue for me. They should deploy a fix asap

**Comment by ElfQueen86** [comment]
Still not generating a superflat world

- Mod version: 0.0.63
- NeoForge/Forge version: 47.1.3
- Minecraft version: 1.20.1
- Are you playing on a server?: No

Thanks for everything you do :)

**Comment by ImKringle** [comment]
> Still not generating a superflat world
> 
> * Mod version: 0.0.63
> * NeoForge/Forge version: 47.1.3
> * Minecraft version: 1.20.1
> * Are you playing on a server?: No
> 
> Thanks for everything you do :)

This is caused by Terralith, there's no hotfix you just need to remove Terralith from the mods
