### ISSUE TITLE
add mekanism.chemical to Xnet Controller

### ISSUE THREAD

**Issue by JM-command** [AllTheMods/ATM-9#698]
### Description

I would like to request the addition of support for `mekanism.chemical` within the Xnet Controller. This would help in integrating Mekanism's chemical handling capabilities with Xnet's control and routing capabilities.

### Reasons

1. **Integration with Mekanism:** Mekanism is a popular mod that offers a variety of chemical processes. Seamless integration with Xnet can greatly benefit users who utilize both mods.
2. **Advanced Automation Possibilities:** With this feature, players can have more advanced automation setups using the chemicals from Mekanism.
3. **Consistency:** Adding this feature would bring consistency to Xnet's support for various mod integrations.

### Proposed Solution

- Extend the Xnet Controller's API to recognize and handle `mekanism.chemical`.
- Ensure compatibility with Mekanism's latest version and ensure that all chemical types are supported.

### Additional Context

I've noticed several use-cases in my gameplay where this feature would be incredibly beneficial. The community, in various forums, has also shown interest in such an integration.

Thank you for considering this enhancement!

**Comment by Ridog** [comment]
This could potentially be accomplished by adding [Xnet Gasses](https://github.com/Terrails/xnet-gases) to the pack.
