### ISSUE TITLE
9.0.0.24 Crash

### ISSUE THREAD

**Issue by PBnJs87** [AllTheMods/ATM-9#70]
Having an issue where minecraft can not run an event. games crashes upon startup or with 20 seconds of entering the world.

[crash-2023-07-06_11.38.21-client.txt](https://github.com/AllTheMods/ATM-9/files/11964680/crash-2023-07-06_11.38.21-client.txt)
[crash-2023-07-06_11.42.40-server.txt](https://github.com/AllTheMods/ATM-9/files/11964682/crash-2023-07-06_11.42.40-server.txt)
[crash-2023-07-06_11.46.03-server.txt](https://github.com/AllTheMods/ATM-9/files/11964683/crash-2023-07-06_11.46.03-server.txt)

Reverted back to 0.23 with the same save file as the crashed report, no issues.

**Comment by Tomyface9** [comment]
Getting the same issue here.

**Comment by fmohican** [comment]
Same there
[crash-2023-07-06_11.01.40-server.txt](https://github.com/AllTheMods/ATM-9/files/11966035/crash-2023-07-06_11.01.40-server.txt)

**Comment by whatthedrunk** [comment]
Try updating to 0.0.25

**Comment by Tomyface9** [comment]
That worked for me(Updating to 0.0.25
