### ISSUE TITLE
Arsenic Dust from ChemLib has no recipe. 0.2.9

### ISSUE THREAD

**Issue by DyVyNyTy** [AllTheMods/ATM-9#702]
The issue is also posted on the mod creators issues. But I wasn't sure if its possible the recipe got messed up within the pack or it was missed in the actual mod itself. I guess all I can do is create a profile with just Chemlib in it to test this.

**Comment by aAndrew3030** [comment]
Many of the Chemlib recipes are changed by Almost Unified. If you want to revert Chemlib recipes back to default, remove it from "unify.json", although chemlib may or may not unify well with resources from other mods

**Comment by aAndrew3030** [comment]
https://github.com/SmashingMods/ChemLib/issues/61
