### ISSUE TITLE
[0.2.11 & 0.2.12] [MineColonies] Citizen style stuck on 'Nether'

### ISSUE THREAD

**Issue by AlisAquilae** [AllTheMods/ATM-9#712]
Hi there,

With update 0.2.11, I have started experiencing an issue with the mod MineColonies. As of the update, the citizen style selector is set to 'Nether', which changes my citizens into a nether theme. The option is greyed out for me, since I am not a patreon and therefore cannot change it myself
![image](https://github.com/AllTheMods/ATM-9/assets/80721939/85bb0454-a925-49d0-878e-e5b175385f74)
Whenever a new citizen spawns, it changes to a nether-themed skin, then quickly switches to its regular variant. 
![image](https://github.com/AllTheMods/ATM-9/assets/80721939/a3854ee7-1376-4354-9390-692c18f23881)
However, once I assign them a job, they revert back to their nether variant.
![image](https://github.com/AllTheMods/ATM-9/assets/80721939/d1fd8fef-a8d2-4aa9-a976-6b6ada474fa5)

I changed the installation in 2 ways. One is that I added the mod 'Towntalk'. The other is that I added the custom minecolonies style Byzantine 2 by adding the files into the blueprints folder. Both worked perfectly fine on version 0.2.10, where the option mentioned above is set to default. I removed both changes and booted up a new world, and am met with the same issue. 

I have tried deleting the colony and starting a new one in the same world, but that does not help either.

I do not know whether this is an issue on my end or something I have done, but based on what's described above I doubt it. Could this be a bug? Do others have the same issue? 

Of course, if there's anything that I could do to help (e.g. send certain logs, try things out, etc.) I would be happy to do so.

Thanks in advance!

**Comment by Desoroxxx** [comment]
Same here, stuck on nether style, using 1.19.2
