### ISSUE TITLE
Refined storage crafting

### ISSUE THREAD

**Issue by brokenscrub** [AllTheMods/ATM-9#713]
Hello

After updating to 0.2.11
i can't autocraft the void upgrade because of a recipe conflict, i get spruce cupboard instead of the drawers, even though in my crafter i have the spruce drawer pattern it doesn't appear in my craftables but the cupboard does

![image](https://github.com/AllTheMods/ATM-9/assets/49006961/30d1bb49-ef2b-4b8c-a87f-0984259fecf3)
![image](https://github.com/AllTheMods/ATM-9/assets/49006961/d14369bf-b8c8-47f5-83a7-a8c8c743328b)
![image](https://github.com/AllTheMods/ATM-9/assets/49006961/7fd72e23-66e0-4369-9561-922f4dc9810b)

**Comment by Mithi83** [comment]
Same applies to AE2 I guess. Trying to craft an AE2 Certus Quartz Block from 4 Certus Quartz Crystals results in a  Block of Certus Quartz from GregTech, which is rather annoying for my AE2 automation. I‘ve also run into the exact same problem with Functional Storage Oak Drawers (1x1) and the Handcrafted Oak Drawers with AE2.
