### ISSUE TITLE
Progressive Difficulty

### ISSUE THREAD

**Issue by yoiniu** [AllTheMods/ATM-9#714]
The mobs kinda become trivial at a certain stage and even apotheosis mobs become too easy, I think some system of difficulty progression like in Diablo or in Modded minecraft; Roguelike Adventures where when you kill the wither and the ender dragon, you unlock difficulty stages respective to the game stage you are on, making mobs stronger but in return give more rewards would be amazing.

**Comment by cthae** [comment]
To tell the truth, the Other has the hardest dungeons with, of course, a piglich.

I would suggest giving pigliches better weapons.

I thought about suggesting more mobs like pigliches for the late game, but it's hard to give a reason (reward) to kill them. Piglich already feels like a stretch. Adding more on top would be kinda useless.

Maybe adding mods with challenging endgame bosses would be better, but really, there's not many mods ready for 1.20 and, of course, there are not many mods that would be balanced right towards the endgame. In fact, the only mod I know that would add an interesting challenge on top of pigliches would be DE, but DE is not here yet.

For the ATM team to create difficulty levels arching over all mods and providing worthy rewards would be a really complex task. I don't think it's worth it unless there's already mod that does it well enough.

**Comment by yoiniu** [comment]
> To tell the truth, the Other has the hardest dungeons with, of course, a piglich.
> 
> I would suggest giving pigliches better weapons.
> 
> I thought about suggesting more mobs like pigliches for the late game, but it's hard to give a reason (reward) to kill them. Piglich already feels like a stretch. Adding more on top would be kinda useless.
> 
> Maybe adding mods with challenging endgame bosses would be better, but really, there's not many mods ready for 1.20 and, of course, there are not many mods that would be balanced right towards the endgame. In fact, the only mod I know that would add an interesting challenge on top of pigliches would be DE, but DE is not here yet.
> 
> For the ATM team to create difficulty levels arching over all mods and providing worthy rewards would be a really complex task. I don't think it's worth it unless there's already mod that does it well enough.

I don't know if you've tried the Roguelike Adventures 2 (RAD2) modpack but in it, there is a progression system which I referenced above, killing game bosses would advance you to the next difficulty stage, so instead of normal 20 hp zombies, after killing the wither you'd have, iirc around 90 hp zombies with more attack damage as well as apotheotic mobs spawning in higher tiers in overworld. Also, the bosses get progressively harder every time you kill them. I don't know the specific mods used to implement this system other than Apotheosis but I think this system was very fun but RAD2 was more vanilla+, it lacked machines and stuff which I like tinkering with so I prefer mods like ATM where there's tech mods so if ATM also somehow could apply this progression system I think this would be perfect as there would be proper reason to get super OP gear.
