### ISSUE TITLE
Evilcraft - colossal chest no sprite/texture.

### ISSUE THREAD

**Issue by DJJ143** [AllTheMods/ATM-9#726]
When you craft the colossal chest as part of the evilcraft modpack, there is no texture simply a purple/black looking chest. Been this way for many versions.

**Comment by john13210** [comment]
go report it to evilcraft github then

**Comment by DJJ143** [comment]
> go report it to evilcraft github then

No need to be so rude. I have reported it to them as well thanks. Given this is a main mod in the ATM9 modpack I also advised the team. Perhaps if you have nothing helpful to say keep your comments to yourself.
