### ISSUE TITLE
Registry entry not present: gtceu:inert_nether_essence_bucket

### ISSUE THREAD

**Issue by mrsaminus** [AllTheMods/ATM-9#729]
When opening inventory in creative, the game crashes and this error message show

"The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Registry entry not present: gtceu:inert_nether_essence_bucket"

**Comment by mrsaminus** [comment]
reinstalled the server, then i got this

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry entry not present: gtceu:nether_star_bucket

**Comment by Mx772** [comment]
Getting this issues on `0.2.19` - Getting crashes. Looks like several people in the ATM discord as well as some other discords getting it aswell.
CrashReport snippet below.

No reproducibility on my end. Has the following crashes:
- Opening ME System
- Using Wrench on ME wire with import bus
- Randomly in cave

[crashReport.txt](https://github.com/AllTheMods/ATM-9/files/13401258/crashReport.txt)
