### ISSUE TITLE
Recepe issue - Glass

### ISSUE THREAD

**Issue by mrsaminus** [AllTheMods/ATM-9#730]
Need glass to make glass?

<img width="390" alt="image" src="https://github.com/AllTheMods/ATM-9/assets/20222257/18494c45-2e8b-4c40-95d9-5ac184813ab6">

**Comment by john13210** [comment]
the second recipe here scrolls thru a lot of items and some of them are just sand

**Comment by mrsaminus** [comment]
> the second recipe here scrolls thru a lot of items and some of them are just sand

All the different ways to burn/smelt sand : no one accept sand

**Comment by xenonmb** [comment]
ATM9 - 0.2.12
Works as it should on my end. Did you add any mods or changes?

![Screenshot_2023-11-05_19-53-Minecraft_Forge_1 20 1_-_Multiplayer_(3rd-party_Se-Horseshoecrab](https://github.com/AllTheMods/ATM-9/assets/21304246/f2dcfc66-1f90-46a1-b0b6-36781abb5c4f)
![Screenshot_2023-11-05_19-54-Minecraft_Forge_1 20 1_-_Multiplayer_(3rd-party_Se-Fowl](https://github.com/AllTheMods/ATM-9/assets/21304246/f1b688bf-f5f5-4bc9-9b57-43abcb674b6c)

**Comment by mrsaminus** [comment]
no changes other than updating the server to the latest version

**Comment by john13210** [comment]
have you even tried putting the sand in the furnace by hand ? how can you not check it ?

**Comment by mrsaminus** [comment]
> have you even tried putting the sand in the furnace by hand ? how can you not check it ?

Yes, "All the different ways to burn/smelt sand : no one accept sand"

**Comment by xenonmb** [comment]
so, now we just need to find out whats wrong with your server installation... is your other issue with the inventory crash in creative mode also still present? https://github.com/AllTheMods/ATM-9/issues/729 
because this also works normally for me

**Comment by Kevin-Marsh** [comment]
These sorts of issues are cause by not copying the gregtech config file over into your server properly for anyone that finds this issue in the future.
