### ISSUE TITLE
refined storage causing crashing on clients

### ISSUE THREAD

**Issue by Archeangelgaming** [AllTheMods/ATM-9#733]
I tried to use refined storage to craft a bunch of chests using planks and it crashed my client with saying cannot do this because it took 32GB of ram

**Comment by xenonmb** [comment]
It shouldn't be able to allocate 32gb unless you set the launcher to allow this much. How much RAM do you actually have? I'd recoomend setting the launcher to use 8 if you have 16 and a maximum of 10-12 if you have more

**Comment by Archeangelgaming** [comment]
I play on my friends server who has 64 gb allocated but when trying to bulk craft a chest in the crafting grid it kicked me from his server because of ram. I have about 12gb allocated through me client
