### ISSUE TITLE
Nonsymmetrical universe orb

### ISSUE THREAD

**Issue by Tomat777** [AllTheMods/ATM-9#738]
![image](https://github.com/AllTheMods/ATM-9/assets/146892171/7ae1ae0b-4801-4823-8678-e062b36a4286)
Is this supposed to be this way?

**Comment by screret** [comment]
..what?

**Comment by Tomat777** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/146892171/e7b3b4cb-79f2-433d-b873-0e5b0730f599)
Universal orb multiblock nonsymmetrical in this places. Is it supposed to be like it?

**Comment by screret** [comment]
yes? it's symmetrical, those are different layers

**Comment by screret** [comment]
oh waiiit

**Comment by screret** [comment]
I see. will fix.
