### ISSUE TITLE
Typing 'e' in refined storage search bar closes the crafting grid

### ISSUE THREAD

**Issue by snommit2** [AllTheMods/ATM-9#74]
As the title says, when you are in the crafting grid and searching for an item, the crafting grid will close when the letter 'e' is typed. It will close if you are searching in JEI as well. I assume it's because 'e' is used to open and close inventory and the crafting grid is counted as an inventory.

**Comment by zayonarts** [comment]
I can confirm this issue, i have the same problem, in search bar you can't write anything with 'E' because it closes the inventory...

**Comment by whatthedrunk** [comment]
If you have not already update the pack
