### ISSUE TITLE
Mystical Agriculture reward seed for blocked/missing recipe

### ISSUE THREAD

**Issue by FHoulbreque** [AllTheMods/ATM-9#741]
___Symptoms:___ 
You can get the *Mystical Flower Seeds* as a quest reward while this is entirely invisible/hidden in JEI as the screen shows below.

___Expected behaviour:___ 
Either the seed should be removed from the rewards or the missing recipe should be back in.

![Screenshot of the seed and JEI](https://i.imgur.com/Vmjhdn0.png)

**Comment by alfredggttv** [comment]
Will be fixed in the next update.
