### ISSUE TITLE
0.12.12 EnderIO Experience Obelisk

### ISSUE THREAD

**Issue by Rhino1399** [AllTheMods/ATM-9#743]
When retrieving XP from the obelisk, they will be added to the Players XP but not subtracted from the Obelisk -> Unlimited XP and will crash the game on numbers higher then about 20k Lvls

**Comment by killerkitt** [comment]
cannot replicate can you give details and steps on how you do so? and version you are on?

**Comment by Rhino1399** [comment]
Version was 0.2.12 sorry typed it wrong in header. There was no special
treatment. Just when pulling out XP the XP-Status in the Obelisk stays the
same, and won't get less.
