### ISSUE TITLE
Problem with mode mahou tsuki

### ISSUE THREAD

**Issue by VX-02** [AllTheMods/ATM-9#754]
**Mahou tsuki** isnt working properly. There is a problem to create sword **morgan**, i killed with **caliburn** 3dogs and nothing :,( one time with 5k mana, with enchanted smite 5 and one time upgrated. Still nothing.

**Comment by Mitchell5200** [comment]
changed to a warden, in atm9

**Comment by VX-02** [comment]
3poor dogs :'(

**Comment by killerkitt** [comment]
you can use familiar stones to bring the dogs back if you wanted to

**Comment by ryennce** [comment]
You have to kill the Warden to make Morgan
