### ISSUE TITLE
Unable to startup due to KubeJS errors

### ISSUE THREAD

**Issue by AceShadow8** [AllTheMods/ATM-9#755]
Following a crash during gameplay, my game will no longer start, as right before the menu opens there is an error message about KubeJS startup errors. Nothing special about the crash, i was just flying around with the glide from Ars Noveau and OpenJDK platform binary crashed. But once i tryed to reopen the game, this error impedes me to play once again. I've atempted to repair the pack in CurseForge, to no avail. The error is as follows and I'll attach the startup.log:

There were KubeJS startup errors [2]:
1) gtceu/material_modification.js#21: Error in 'GTCEuStartupEvents.registry': java.lang, IllegalStateException
2) Error in 'StartupEvents.registry': java.lang.IllegalStateException

![Error message](https://github.com/AllTheMods/ATM-9/assets/135562954/3e595223-6226-444c-b851-744cdb6e890b)
[startup.log](https://github.com/AllTheMods/ATM-9/files/13298420/startup.log)

**Comment by AceShadow8** [comment]
I've also found the exit code for the initial crash, if that helps at all:
Exit Code: -1073740791

**Comment by aAndrew3030** [comment]
Have you tried deleting and reinstalling (from a fresh download) the entire KubeJS folder?

**Comment by AceShadow8** [comment]
Hmmm, I just checked on reddit, and apparently this KubeJS thing is just something that happens 50% of the time... I tryed running again, and it worked. I deleted the KubeJS folder and reinstalled as you said just to be safe. Anyhow, I keep getting this crash with OpenJDK platform binary every 30min or so...

**Comment by cddrury** [comment]
I am also getting the KubeJS error on startup.
[startup.log](https://github.com/AllTheMods/ATM-9/files/13325869/startup.log)
