### ISSUE TITLE
[Bug] Inventory sorting freezes the client for 5 seconds

### ISSUE THREAD

**Issue by cthae** [AllTheMods/ATM-9#756]
This is either a misconfigured, conflicting or just poorly written mod. Should be fixed. There's absolutely no reason why sorting the inventory should have to take five seconds and freeze the client completely while doing so.

The sorting I talk about is the scroll click sort on the player inventory.

**Comment by killerkitt** [comment]
now is this a consistant freeze each time or is it a freeze once and it goes back to sorting normally because thats how it happens for me just a quick 1-3 second freeze and then every other time i sort even other inventories it is quick less than a second

**Comment by killerkitt** [comment]
ok i think best thing is to test it out on a new pack with just that mod (inventoryprosfilesnext) and test to see if it still does it or not, then if it does report it on their issue tracker and hopefully the developer of the mod will take a look into it?

**Comment by aAndrew3030** [comment]
It is a known mod conflict with the other mods that add sorting behavior

https://github.com/AllTheMods/ATM-9/issues/600
