### ISSUE TITLE
The 4- 5 latest updates doesn't work for me.

### ISSUE THREAD

**Issue by Sajns** [AllTheMods/ATM-9#757]
When I going to log into my world the game gets stuck on loading, it freezes after reading world data and I don't know what to do.

**Comment by Sajns** [comment]
I tried to reinstall the modpack but it didn't helped me.

**Comment by Sajns** [comment]
Here is the latest crash report if that might help solve the problem: 
[crash-2023-11-08_21.42.19-server.txt](https://github.com/AllTheMods/ATM-9/files/13301248/crash-2023-11-08_21.42.19-server.txt)

**Comment by djnifos** [comment]
> Here is the latest crash report if that might help solve the problem: [crash-2023-11-08_21.42.19-server.txt](https://github.com/AllTheMods/ATM-9/files/13301248/crash-2023-11-08_21.42.19-server.txt)

Go inside the `world` folder, inside `serverconfig` folder, delete `utilitarian-server.toml`.  If it continues to happen with different configs, you may need to delete the whole `serverconfig` folder, the game will remake it.

**Comment by Sajns** [comment]
Thank's, that solved the problem.
