### ISSUE TITLE
Fluid Drawers not locking properly 

### ISSUE THREAD

**Issue by Zinnorok** [AllTheMods/ATM-9#762]
Current Version: 9-0.2.14
-When a fluid is fully drained from a fluid drawer, it will no longer accept the same fluid as an input from the linked storage controller even thought it was locked 
         -Issue occurs with fluids from mods and vanilla 

-Not seeing this as an issue on the Functional Storage Github page so possibly a ATM9 issue

Steps to repro:

-Insert fluid into a drawer linked to a controller
-Lock the drawer 
-Drain the fluid from the drawer down to 0 mb
-Attempt to pipe the fluid into the controller

**Comment by aAndrew3030** [comment]
Have you tried those steps with just lava or water? The last I seen on discord, Buuz was trying to determine if it was a pack issue or mod issue

**Comment by Zinnorok** [comment]
I have tested it with vanilla fluids and mod added ones
