### ISSUE TITLE
New mod nomowanderer  pls add ?

### ISSUE THREAD

**Issue by SpartaWarsec** [AllTheMods/ATM-9#767]
https://www.curseforge.com/minecraft/mc-mods/nomowanderer

**Comment by Mitchell5200** [comment]
Use #1 for mod suggestions, 
we have tried this mod before but we're getting some server side issues with it.

**Comment by Graphicscore** [comment]
@Mitchell5200 Apparently the mod author fixed something, maybe it's worth another try?

https://github.com/J-Dill/NoMoWanderer/issues/16

**Comment by J-Dill** [comment]
@Mitchell5200 @Graphicscore Indeed, all issues have now been fixed in regards to the chunk loading issues. Mod has been stable now and is also updated for Forge all the way through 1.20.2.
