### ISSUE TITLE
Crashing consistently in survival mode when clicking the Rechiseled Mod Smooth Stone Connected Texture Block

### ISSUE THREAD

**Issue by docHP** [AllTheMods/ATM-9#777]
https://pastebin.com/KKrctE46

^ Error Log

When you place a Smooth Stone Connected Texture Block in the Mining Dimension and hit it with your M1 it will crash your game with this error log.

Repeatable and did it multiple times.

**Comment by brandonramon** [comment]
To Add to this thread (not a dev) - issue also happens in the regular dimension with Rechiseled Obsidian and Glowstone (multiple pick-axes tried) - I'm on the newest update as well

**Comment by akasia** [comment]
same issee with rechiseled mod but i on overworld with cobblestone piller Connected Texture
