### ISSUE TITLE
0.0.28 Iron Golem Travelers Backpack not opening from back slot

### ISSUE THREAD

**Issue by kuriyna** [AllTheMods/ATM-9#78]
I looted 2 iron golem travelers backpacks from a village and they wont open from the back slot in the curios(?) area.  they do open from inventory.  Also equiping from the ground placement makes them "disappear" and not show up in the curios(?) slots, only way to get access to them is to die.

**Comment by McKitten** [comment]
Using the backpack in the curio slot seems to make it unusable, the bag itself has an equip (person with up arrow bottom left) and unequip (down arrow same spot) which will enable it to be used via keybind (don't remember default, I've bound it to shift b with the other pack type on b). Above this is also the very important ability button.
The Traveller's pack ones are just slightly OP so the extra work is worth it IMO.

**Comment by kuriyna** [comment]
The Keybind is also not working even if equipped that way.  Thus I cannot get to the backpack to put loot in or unequip it as its not there.

**Comment by kuriyna** [comment]
Weird, i put one in my curios slot while the "equip" one is equipped and now the "equip" one wants to respond to the keybind.  Took the curios one back out and now it works.  i dont get this game sometimes!
