### ISSUE TITLE
Gregtech ore Recipe are not set

### ISSUE THREAD

**Issue by zookeper** [AllTheMods/ATM-9#780]
Earlier I was making the progression towards stainless steel and I noticed a problem, The emerald ores are being generated under minecraft name but the Recipe for gregtech requires gregtech ore and as such I can not macerate or forge hammer minecraft emerald ore in order to make the parts needed to progress. Can't cut emerald lens without emerald cut jewel, need emerald cut jewel to make cutter, only way to get this is by macerating/forge hammering emerald ore and then sifting it.

Newest version 0.2.15

**Comment by Graphicscore** [comment]
Possible duplicate https://github.com/AllTheMods/ATM-9/issues/752

**Comment by zookeper** [comment]
Thanks Graphic, was trying to find this yesterday, got the wrong search result.
