### ISSUE TITLE
allthemodium:Dungeon not spawning in the other

### ISSUE THREAD

**Issue by CaptainGusgus** [AllTheMods/ATM-9#787]
as of 0.2.18b allthemodium:Dungeon not spawn in the other, only Ancient Pyramid, Ancient City, Allthemodium:piglin_village. have used the structure compass to search for it but nothing. Keeps Telling me to keep going 10,000 step and i do another search and nothing i repeat another 10.000 and repeat. can it be a bad map gen? if so how do i fix or delete the other?

**Comment by CaptainGusgus** [comment]
had to go over 36k block away from spawner all around and then connect  all four corners , its hard with no flying.

**Comment by G33kman** [comment]
Been looking for that last hour and a half with the mining laser on efficiency 5 and plowing through ancient stone but can't find it anywhere. If it's out that many blocks that's definitely frustrating without flight...
