### ISSUE TITLE
Request: Add versioning or a changelog.md

### ISSUE THREAD

**Issue by Brother-Blue** [AllTheMods/ATM-9#789]
This isn't a huge issue, more of a quality of life feature for the repository. 

I've seen it once so far where "Lots of other changes if you visit github" while in the Curse launcher and going through commits to see what was changed is a bit of a headache. From a end-user perspective it would be great to either have a changelog.md (or as a part of the readme.md) or starting to add versioning/release tags to the repo with a list of changes.

![image](https://github.com/AllTheMods/ATM-9/assets/61142910/b7861dec-12a4-4ce3-910e-32cac58d25be)

**Comment by Brother-Blue** [comment]
As a side note, this is included in previous versions of ATM
https://github.com/AllTheMods/ATM-8/blob/main/Changelog-ATM8-Master.md
https://github.com/AllTheMods/ATM-7/tree/main/changelogs
https://github.com/AllTheMods/ATM-6/tree/master/changelog

**Comment by aAndrew3030** [comment]
Somewhat related, can someone PLEASE close issues when they are fixed! There are 569 open issues, combine that with the changelog and it can be real difficult to know if a issue has been fixed. Simple status labels would work wonders. A "issue acknowledged" would at least let a person know there issue is not being ignored.

**Comment by Brother-Blue** [comment]
Typically issues are closed by those who created them, unless the project has a large amount of contributors who can do that as well. So this isn't really relative to the original request.
