### ISSUE TITLE
breaking ender chests from EnderChests mod is consistently dropping tablets and scrolls from Corail Tombstone

### ISSUE THREAD

**Issue by GL17CH92** [AllTheMods/ATM-9#79]
tool used is a Silent Gear diamond paxel enchanted with fortune 3
pack version 0.0.26

**Comment by 3less** [comment]
Thats not only with EnderChests, the same Problem has Redstone Chests!

**Comment by kohdcilver** [comment]
As well as reinforced chest. Items include scrolls, tablets, poppets, seed pouches, and bundles. Potentially more, but that is what i discovered after about 80 breaks.
