### ISSUE TITLE
server crashing 

### ISSUE THREAD

**Issue by Jaydenpoyser4** [AllTheMods/ATM-9#791]
[crash-2023-11-13_20.59.33-server.txt](https://github.com/AllTheMods/ATM-9/files/13341925/crash-2023-11-13_20.59.33-server.txt)

here's my server logs

**Comment by Jaydenpoyser4** [comment]
someone help with it

**Comment by djnifos** [comment]
that says you have a bunch items on the ground

**Comment by Jaydenpoyser4** [comment]
> that says you have a bunch items on the ground

how do i clear items on the ground

**Comment by Mitchell5200** [comment]
either `/kill @e[type=item]`, or enable item clearing in the Crash utils config in the `/world/serverconfig/` folder
