### ISSUE TITLE
Unable to convert a villager to werewolf + finding them.

### ISSUE THREAD

**Issue by Janvier123** [AllTheMods/ATM-9#794]
Hi,

We are playing ATM9 **0.2.18b** we are trying to get werewolf flesh, but have been unsuccessful. Info on reddit seems not to work. 
Source: https://www.reddit.com/r/allthemods/comments/17h71y2/atm_9_where_to_find_evilcraft_werewolf/

We tried the following:

- Hitting a naturally spawned villager with a lighting sword (The Aether)
- Hitting a naturally spawned villager with a lighting grenade (EvilCraft)
- Hitting a spawned (Mob Duplicator) villager with a lighting sword (The Aether)
- Hitting a spawned (Mob Duplicator) villager with a lighting grenade (EvilCraft)
- Hitting a spawned (Egg) villager with a lighting sword (The Aether)
- Hitting a spawned (Egg) villager with a lighting grenade (EvilCraft)
- Using lightning on villager with a natural lightning
- Using lightning rods nearby villagers with a natural lightning
- Using lightning rods nearby villagers forced natural lightning ("/weather thunder" command)
- All of the above when Full Moon & non-full moons.
- All of the above when daylight

All of them turn into witches! 

We are searching in an out of villages, but are unable to find them.

Greetz

**Comment by HYSPoy** [comment]
If you put a villager into a trader (Easy Villagers) with a Smoker the villager will turn into a werewolvian when placed down will turn into a werewolf

**Comment by peterromfeldhk** [comment]
if i place down werewolvian he turns back into regular villager
