### ISSUE TITLE
Looter crash v.0.0.28

### ISSUE THREAD

**Issue by zombiebush** [AllTheMods/ATM-9#80]
I opened a chest in the nether in a twigs stretcher and that was fine then i found piglin village opened a chest there, crash. tried another one, crash. https://pastebin.com/GgCQxKEJ  I'm on forge v.47.1.0 because I'm checking out enderio. but this doesn't seem to matter i tried reverting to the previous forge version and removing enderio and the same thing happens.  it seems to only happen in new chunks after updating to 0.0.28.

**Comment by whatthedrunk** [comment]
Still having this issue on 0.0.32?

**Comment by zombiebush** [comment]
sorry i didnt answer you back i guess my notifications are turned off
