### ISSUE TITLE
Gateway to Eternity Mod Gate Pearls 

### ISSUE THREAD

**Issue by ReaperCast** [AllTheMods/ATM-9#807]
Medium Gate Peals not craftable and return an error item. Not sure if this is intentional or not. 
![nLCEMvB](https://github.com/AllTheMods/ATM-9/assets/8506731/f43a799d-0209-45c5-9819-aaddfaef1c96)
![WVpG2UA](https://github.com/AllTheMods/ATM-9/assets/8506731/ba2a5f35-47b8-4f44-bca7-d58228ed2ff7)

**Comment by Kevin-Marsh** [comment]
This should be fixed with the gateway rewrite.
