### ISSUE TITLE
Reporting 2 things I've found thus far bug+dupe

### ISSUE THREAD

**Issue by Delta4741** [AllTheMods/ATM-9#809]
Technically a dupe, using the SAG mill with boosted main output can dupe metal, works with gold and iron, not all but those few provided you have a grinding ball/flint that increases main output.

The RAILCRAFT boiler outputs steam as a LIQUID and by doing so it cannot send said liquid into other power generators as a proper GAS 
Even though it is my understanding that said steam forge listed compatible,
As a note i used 3 types of piping to try and send the steam from my RAILCRAFT boiler into storage/Steam turbines from ADVANCED GENERATORS, Ender IO pipes will not dump into the turbines, Whilst pipez will not do the same, mekanism pressurized pipes work, but will not pull steam from the boiler.

**Comment by screret** [comment]
The "proper gas" should be a fluid with the forge api but mek people decided to be dumb and make their own system. Blame them.
