### ISSUE TITLE
MUCH

### ISSUE THREAD

**Issue by HuliosGaming** [AllTheMods/ATM-9#811]
Updates gemacht, server startet nicht mehr mit der alten welt crasht einfach instant weg PERFEKT.

Ist FR ein Scheiß Entwicklerteam machen updates mit irgendeiner dulli scheiße und ficken damit die Server ist ja nicht der erste Report wegen Defekten Updates. Weis nicht ob die ganzen Pimmel keine Ahnung haben wie man Updates macht aber man sollte sie wenigstens Testen bevor man alles zerfickt.
Hab das Modpack seit version 0.2.4 und nach und nach die updates gemacht sprich 0.2.4 auf 0.2.9 dann auf 0.2.10 und jetzt auf 0.2.19 und es geht garnichts mehr.

**Comment by screret** [comment]
> Updates made, server no longer starts with the old world, just crashes immediately PERFECT.
> 
> FR is a shit development team making updates with some stupid shit and fucking with the servers is not the first report about defective updates. I don't know if all the dicks have no idea how to do updates, but you should at least test them before you fuck everything up. I've had the modpack since version 0.2.4 and have gradually made the updates, i.e. 0.2.4 to 0.2.9 then to 0.2.10 and now to 0.2.19 and nothing works anymore.

damn they mad

**Comment by HuliosGaming** [comment]
Yes, I'm fucking pissed in this world was played by 12 players over 10-15 weeks

**Comment by Mitchell5200** [comment]
Raging is not gonna help get any problem solved, post logs either via direct upload, or paste them into https://mclo.gs/ and share the links here

**Comment by HuliosGaming** [comment]
I don't give a shit about this shitty modpack, I'm looking for another modpack for my boys on the "ATM", boys you can't rely on at all

**Comment by Mitchell5200** [comment]
Alright then mate, be that way

**Comment by HuliosGaming** [comment]
This can all read for the Fucking Team with the Name "ATM"
