### ISSUE TITLE
Villages are too spaced apart

### ISSUE THREAD

**Issue by TheMeq** [AllTheMods/ATM-9#813]
I am unable to easily locate any villages on my server. After using /locate structure command, it's because they are all 10's of thousands away from anything, surely villages should be more common then this? 

![image](https://github.com/AllTheMods/ATM-9/assets/7303969/126afc04-69ea-4ec0-8c3a-a22c1cff01ce)

**Comment by aAndrew3030** [comment]
This is caused by the mod "Sparse Structures Reforged". You can adjust the spacing in the mods config, or disable the mod all together to get default spacing
