### ISSUE TITLE
Hoglin, Piglin attack crash game

### ISSUE THREAD

**Issue by HadesDurin** [AllTheMods/ATM-9#815]
When i got attacked by hoglin or piglin my game crashes
[crash-2023-11-16_22.13.04-server.txt](https://github.com/AllTheMods/ATM-9/files/13384391/crash-2023-11-16_22.13.04-server.txt)

**Comment by djnifos** [comment]
Were you wearing a twilight cloak from Reliquary?

**Comment by AceShadow8** [comment]
Holy crap, this bug is so annoying. It is the twilight cloak for sure... I had to revert to a backup to get my save to work again, because it crashes on reopening the save too.
