### ISSUE TITLE
[9-0.2.19] World generation ignores super flat setting

### ISSUE THREAD

**Issue by karikusa** [AllTheMods/ATM-9#823]
I'm trying to find out how my machine works.
I prefer to use the [Redstone Ready] preset for Superflat.
However, the normal world is generated ignoring those settings.

**Comment by djnifos** [comment]
Terralith's worldgen is done via datapacks, and due to a design choice by Mojang superflats still use the regular world's datapacks

**Comment by karikusa** [comment]
I searched quite a bit and couldn't figure out how to disable it.

**Comment by djnifos** [comment]
you'd have to remove the mod

**Comment by JDLanyon** [comment]
It's worth mentioning [this issue on the terralith repo](https://github.com/Stardust-Labs-MC/Terralith/issues/43).
