### ISSUE TITLE
[GregTech] Large Mixing Vessel stopped mixing programmable recipes

### ISSUE THREAD

**Issue by ShadedPL** [AllTheMods/ATM-9#827]
Since 0.2.20 The Large Mixing Vessel stopped mixing any recipe other than not programmed ones. 
Example Niobium Titanium Dust Programmed to 1.
![image](https://github.com/AllTheMods/ATM-9/assets/4216212/aa88cc7b-20f0-42cf-953b-d846cbe8e119)
Or Soldering Alloy Dust Programmed to 3 also not processing.
![image](https://github.com/AllTheMods/ATM-9/assets/4216212/65130519-55ac-44ff-8e47-ae2b1f35cc7a)
But For example Titanium Carbide which does not use a program, was processed just fine
On 0.2.19 this was working correctly, maybe it's something with the addition of Almost Unified.
Trying to use Greg-only dusts also does not work.

The 1-block Mixer programmed recipes work correctly. The problem seems to be only with the Large Mixing Vessel.

**Comment by screret** [comment]
do you by change have distinct buses enabled?

**Comment by screret** [comment]
something might've gone wrong again in those

**Comment by ShadedPL** [comment]
after disabling distinct buses it's processing just fine, thanks! But isn't there a risk then for the wrong recipe being processed? I thought that's what the distinct buses function is for.

**Comment by screret** [comment]
yes, please report this issue to https://github.com/GregTechCEu/GregTech-Modern/issues.

**Comment by ShadedPL** [comment]
https://github.com/GregTechCEu/GregTech-Modern/issues/554 done, closing this one.
