### ISSUE TITLE
gregtech problems

### ISSUE THREAD

**Issue by moosecrazy13** [AllTheMods/ATM-9#832]
cant import biomass from brewery with importer and is there a way to get ethanol without the distillation tower because the distillery recipe went away

**Comment by ShadedPL** [comment]
when it comes to importing/exporting fluids (but also items) I would suggest you use the auto-output function in the Output settings and 'allow fluids input from the output side' and just connect it with the pattern provider that provides the auto-crafting part.
![image](https://github.com/AllTheMods/ATM-9/assets/4216212/1fb44baa-510a-4828-af62-890a84998457)
For Ethanol you can try to go the Pneumaticraft route and produce it with sugar and yeast.
