### ISSUE TITLE
Missing Gregtech Recipes 0.2.20

### ISSUE THREAD

**Issue by MrNoe93** [AllTheMods/ATM-9#838]
Some recipes for Gregtech fluids are missing on server, but available in singleplayer. 

The ones I have noticed are for Benzene and Ethanol.  Serverside benzene only has the heavy fuel recipe in the distillery, while in singleplayer the other recipes, such as wood tar, are present.  Serverside ethanol has no recipes in the distillery.  
Edit:  Looking at this more, on the server, the distillery only has six recipes total while in singleplayer theres over 200.

Have tried reinstalling the pack on the server and replacing the serverside kubejs folder with the one from the singleplayer and no change.

**Comment by Ashsilvara** [comment]
In single player ethanol is only available with Distillation Tower. But you need ethenol to finish out the MV tier to get to the Distillation Tower.......

**Comment by MrNoe93** [comment]
Update:  this appears to be specifically a gregtech issue.  With just jei and gregtech installed, the recipes are missing until doing /reload or leaving and rejoining a world.  Gonna report it on their git.

**Comment by MrNoe93** [comment]
Fixed in the next release of GTCEU
