### ISSUE TITLE
0.2.21; Performance Issue With All the Mods 9; Causing PC to Stutter / Freeze

### ISSUE THREAD

**Issue by MythrodakIV** [AllTheMods/ATM-9#861]
After playing All the Mods 9 on **0.2.21** for roughly 10 hours, suddenly on my next launch of All the Mods 9 yesterday, the performance of the game was poor. Before this issue, I received around 130 ~ 90 frames with shaders on with stable performance, since I had 10GiB RAM allocated with an RTX 3080 / i7-12700KF. Now, I receive 30 ~ 20 frames with shaders disabled, and having All the Mods 9 open is causing my entire PC to stutter/freeze. 
I.E: Windows [OS and Programs] becomes less responsive, trying to open other windows takes longer, mouse cursor freezes and stutters when trying to move the cursor, start menu takes longer to open. . .etc. Closing AtM 9 is a struggle on its own since Task Manager tends to crash when AtM 9 is open.

What's unique is that this performance issue does not occur in any other modpack except in All the Mods 8 and 9, but especially in All the Mods 9; even in another 1.20.1 Forge instance, the game ran normally. In another instance I regularly use that uses 1.20.1 Fabric, the issue still remains non-existent. Additionally, regardless of my choice of launcher, this issue always occurs. Even entire reinstalls of the modpack do not fix the issue, nor reinstalls of the launchers I am using. I've used MultiMC, ATLauncher, and Curseforge's launcher to no avail.  Before this, I had updated my Java, updated my NVidia drivers, and changed my monitor setup by replacing one of my monitors.

ATM 9 **0.2.21** was used.

**Comment by Janvier123** [comment]
Same here, after a few hours of playing the memory of the OS was fully in use. The OS has become unusable.
Java has eaten up all of its allowed memory and even the memory of the OS! It is using 19.9 Gb!!!!

![image](https://github.com/AllTheMods/ATM-9/assets/1528455/0dce5109-3f2f-4994-9e26-57ac2eded107)

![image](https://github.com/AllTheMods/ATM-9/assets/1528455/356a4732-9fe5-484b-ad48-b24f47a14c1c)



Its a VM running on 20gb memory 18gb for java, running win server 2022

**Comment by Janvier123** [comment]
**Update:** Running 2.20 no issues found, dont install 2.21 untill fixed

**Comment by FlowerCinth** [comment]
Having switched to 2.20 of AtM 9 seems to increase the severity of my issue, as now my entire system becomes unresponsive, forcing me to do a hard shutoff by holding my power button. There just seems to be no apparent cause for my issue as far as I know where to look.
