### ISSUE TITLE
[GregTech] Alloy Blast Smelter not accepting Parallel Hatch

### ISSUE THREAD

**Issue by ShadedPL** [AllTheMods/ATM-9#866]
As in the description the Alloy Blast Smelter does not seem to accept any parallel hatch but according to it's description it should:
![image](https://github.com/AllTheMods/ATM-9/assets/4216212/c854e6b3-3f20-4f6e-a1b0-0f5fac8da319)
JEI is not showing the parallel hatch too
![image](https://github.com/AllTheMods/ATM-9/assets/4216212/84c0f7df-594e-4972-b264-92581457417b)

**Comment by Gratisvampier** [comment]
Yeah, that causes really a lot of problems, fix pls
