### ISSUE TITLE
Overflowing Memory since update

### ISSUE THREAD

**Issue by alpha-pvp** [AllTheMods/ATM-9#867]
Since the last update to version 0.2.21 my memory is overflowing within two hours. I have 8 GB allocated and had no issues beforehand. No it slowly overflows and the game starts to stutter and freeze until it crashes.

**Comment by Shawak** [comment]
We ran into the same problem, were you able to fix it?

**Comment by alpha-pvp** [comment]
@Shawak it solved itself after the release of version 0.2.23, so I didn't figure out what was causing it. Haven't played on the newest version yet, so don't know if it occurs again.

**Comment by Shawak** [comment]
Looks like it was fixed in 0.2.35
