### ISSUE TITLE
[ATM 9 - v0.2.22] Functional Storage Issue

### ISSUE THREAD

**Issue by Dracos99** [AllTheMods/ATM-9#871]
After updating my server from v0.2.21 to  v0.2.22, all my storage drawers are not linked. They all sit at the max 12 blocks around my controller. Trying to relink them in place has no effect. Moving them closer to the controller allows them to be linked...but only if 8 blocks or less. Additionally, the controller extension changed to a different block and when i try to remove and replace, i get errors.

https://mclo.gs/XOK7De5

Starting a new Local game does not have the rang limitations and can link out to 12 blocks.

**Comment by aAndrew3030** [comment]
The Functional Storage mod was updated with some major changes to the way linking works. Looks like something with the controller got corrupted. Have you tried placing a new controller?

**Comment by Dracos99** [comment]
yes, tried new controller, new linking card, picking up the drawers and placing them back down...they would only link again if i placed them within 8 blocks instead of 12

**Comment by Dracos99** [comment]
Update: This may be a general server issue with the latest version of functional storage. I removed all other mods as well as all configs and kubejs scripts from my server so that it was only running forge forge-1.20.1-47.1.3, functionalstorage-1.20.1-1.2.5, and titanium-1.20.1-3.8.23 and connected to it...and it still had an 8 block range inside the 12 block holo range. i also didnt see any range upgrade cards that should be able to go into the new controller slots

**Comment by aAndrew3030** [comment]
The upgrades are just the normal stack upgrades. Copper +2 blocks, gold +4 blocks, etc.

**Comment by Dracos99** [comment]
I will give them a try tomorrow, but even if they work, it doesn't change the problem of the range showing 12, but only connecting to 8 on a server. Either the outline should show 8 or they should connect out to 12...they work out to 12 single players.

**Comment by Dracos99** [comment]
After testing, i can confirm that on both [ATM 9 - v0.2.22] and [ATM 9 - v0.2.23], the range of the controller on a server seems to be 8 (not 12) and that adding a pair of copper or a gold card lets you reconnect your drawers at 12 blocks. adding more range does the same expected range (holo box) -4.

**Comment by Dracos99** [comment]
I spoke with the dev on his discord and it looks like it is a disconnect in the configs. 
prior to the latest version, the functionalstorage-common.toml file generated with a line:
 `	#Linking range radius
	DRAWER_CONTROLLER_LINKING_RANGE = 12`
After the latest version, a newly generated config looks like this:
`	#Linking range radius
	DRAWER_CONTROLLER_LINKING_RANGE = 8`
since i always install updates into a new directory and copy my world file over, it generates this file from scratch since the ATM9 pack doesnt have it in the config. Here is where the disconnect is, the local client also has the functionalstorage-common.toml file, but it doenst get changed because it is not cleared out on an upgrade (at least in FTB App launcher) so it still shows 12, while the server defaults to 8.

I think the solution may need to be either a way to clear out the client config file on update so that it matches the new server one, or distribute a config file with the server pack to set it back to 12 instead of the new default of 8.
