### ISSUE TITLE
putting redstone ore in marid crusher gives barrier items

### ISSUE THREAD

**Issue by Matthew-J-json** [AllTheMods/ATM-9#874]
putting any variety of redstone in an Occultism Marid Crusher will cause the Marid crusher to give the player 12 barrier items, rather than  12 redstone dust. Looking at JEI also implies that certus quartz ore, nether quartz ore, and topaz ore will result in the same bug, but I have not tested with these ores

**Comment by aAndrew3030** [comment]
Fixed in version 2.24 of the pack
