### ISSUE TITLE
ATM9 AE2 ME System: Items strangely capped at a certain ammount

### ISSUE THREAD

**Issue by Lupidor** [AllTheMods/ATM-9#880]
Hi,
i saw an issue on a private server on which the item count in the ME-System is somehow limited, but somehow not. here a closer explaination:
for example, i harvest pig essence with a harvester pylon and everything worked fine for a while but now the item count doesn't increase anymore. when i take out a stack, and just put it back into the system, the ammount is less than before even i just took it out and put it back in instantly after, and the ammount is capped by the new ammount.
Same thing for cobblestone which is mined by the builder in the mining dimension. It has no specific limit, it's somewhere around 180k.
If i use them to craft compressed cobblestones, the ammount is less and will raise again to around 180k, but not more. the rest is getting vanished i guess...

For info, i have tons of space and channels left in my system, and a server restart did not help.
Any suggestions?

Ask if something is unclear or if you did not quite understand what i mean.

**Comment by toruPuchuu** [comment]
Might you be capping on total items in a storage cell?

**Comment by Lupidor** [comment]
By the way i have over 100 completely empty 1024k storage cells
