### ISSUE TITLE
found few issues while playing on atm9

### ISSUE THREAD

**Issue by VX-02** [AllTheMods/ATM-9#882]
1. After few processes steam gregtech machines stop working and i need to mine and place them again to work.
2. Every time i try to craft "juke box" in refind storage, my game crashes.
3. and third i forgot sorry :c

**Comment by MarwenX3M** [comment]
The steam machines need an unblocked vent, its on the back of the machine by default but this can be configured with a wrench.

**Comment by dethcalulator** [comment]
Even this considered they suddenly stop working.
