### ISSUE TITLE
Ars Nouveau: Documentation Viewing Error in Worn Notebook

### ISSUE THREAD

**Issue by PoPoGH** [AllTheMods/ATM-9#883]
Hello,

I'm experiencing an issue with the Ars Nouveau mod regarding the documentation section within the Worn Notebook. The mod functions correctly in all other aspects, but when I try to access the documentation, I encounter loading errors. Here are the relevant details:

- **Mod Version**: ars_nouveau-1.20.1-4.7.4-all
- **Forge/Fabric Version**: forge-1.20.1-47.2.0
- **Minecraft Version**: 1.20.1
- **AllTheMods Version**: 0.2.23

**Description of the Issue**:
Accessing the documentation tab in the Ars Nouveau Worn Notebook for the "Summoning Familiars" section results in the following error messages:

- "Error building entry ars_nouveau:familiars/summoning_familiars of book ars_nouveau:worn_notebook"
- "Error while building entry ars_nouveau:familiars/summoning_familiars"
- "Page 3 of book ars_nouveau:worn_notebook"
- "Could not find entry ars_nouveau:rituals/binding"

**Steps to Reproduce**:
1. Open the Ars Nouveau Worn Notebook in-game.
2. Attempt to access the documentation tab.
3. Encounter the loading errors.

**Expected Behavior**:
The documentation tab should display the "Summoning Familiars" information without any errors, allowing for full use of the mod's features.

**Actual Behavior**:
Error messages are shown instead of the actual content when attempting to access the "Summoning Familiars" documentation, preventing me from accessing the information.

**Additional Information**:
![image](https://github.com/AllTheMods/ATM-9/assets/76515395/2b6a41f7-cc4a-4b91-8aef-6d74521c36b2)
![image](https://github.com/AllTheMods/ATM-9/assets/76515395/4b17aae2-8948-4b00-afb2-af9b3d593f04)

I appreciate your time and assistance with this matter.

Best regards,
PoPo

**Comment by NJM1564** [comment]
Oh good it's not just me.

**Comment by NJM1564** [comment]
Ars-Nouveau gethub mentions it being a patchouli error "revert to version 1.20.1-81 and the error will be gone."

**Comment by djnifos** [comment]
Fair warning, you will break botania downgrading patchouli.
