### ISSUE TITLE
[0.2.23] Graphics corruption and severe stuttering.

### ISSUE THREAD

**Issue by stephen-smith** [AllTheMods/ATM-9#885]
Linux, Debian, X11, PrismLauncher (Flatpak).

Doing nothing, game still obviously freezes every 5-10 seconds for 1-3 seconds each.  This would be sufficient to render the game unplayable.

However, I'm also see "floating" sprite sheets:

![2023-11-26_09 56 24](https://github.com/AllTheMods/ATM-9/assets/283443/2ec1fee5-eb22-4b9e-a226-f8c4ece51d2c)

which indicates to me that some shader is crashing or at least passing incorrect data around, and it might be that the freezes are the graphics stack attempting to recover.

In addition, *after existing Minecraft*, my desktop process (plasmashell) is constantly busy and refuses to re-render my desktop background, widgets, taskbar/tray, or application ("start") menu.  The old textures/bitmaps redraw if a mouse or another window passes over them, but icons/entries for exited applications persist and newly start applications don't show up.  The application menu takes up space, but doesn't draw anything.  Hover pop-ups for some things still trigger, but the contents of them are just random graphics trash, not the expected text (?).

**Comment by stephen-smith** [comment]
[latest.log](https://github.com/AllTheMods/ATM-9/files/13467391/latest.log) -- Client logs, in case they might help. :(

**Comment by aAndrew3030** [comment]
There was a issue with a older version of AMD drivers, and it looks like your using a outdated version according to your log?

**Comment by stephen-smith** [comment]
I upgraded to the latest versions available for my OS, and the issues persist:

```
bss@monster % apt-cache policy xserver-xorg-video-amdgpu
xserver-xorg-video-amdgpu:
  Installed: 23.0.0-1
  Candidate: 23.0.0-1
  Version table:
 *** 23.0.0-1 900
        900 http://deb.debian.org/debian stable/main amd64 Packages
        700 http://deb.debian.org/debian testing/main amd64 Packages
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
bss@monster % apt-cache policy libdrm-amdgpu1
libdrm-amdgpu1:
  Installed: 2.4.117-1
  Candidate: 2.4.117-1
  Version table:
 *** 2.4.117-1 700
        700 http://deb.debian.org/debian testing/main amd64 Packages
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.114-1+b1 900
        900 http://deb.debian.org/debian stable/main amd64 Packages
bss@monster % apt-cache policy firmware-amd-graphics
firmware-amd-graphics:
  Installed: 20230515-4
  Candidate: 20230515-4
  Version table:
 *** 20230515-4 300
        300 http://deb.debian.org/debian experimental/non-free-firmware amd64 Packages
        300 http://deb.debian.org/debian experimental/non-free-firmware i386 Packages
        100 /var/lib/dpkg/status
     20230515-3 700
        700 http://deb.debian.org/debian testing/non-free-firmware amd64 Packages
        700 http://deb.debian.org/debian testing/non-free-firmware i386 Packages
        500 http://deb.debian.org/debian sid/non-free-firmware amd64 Packages
        500 http://deb.debian.org/debian sid/non-free-firmware i386 Packages
```

Can you tell me what version(s) of (and part(s) of) the AMD graphic stack are affected, so I can open a issue with my OS vendor?

**Comment by stephen-smith** [comment]
Updating the kernel helped.  There's still some stuttering, but I think it could be worldgen (relatively new server) or network (I'm on a higher latency connection than I'd like) chunk loading lag, since it primarily happens as I explore / fly now.

```
bss@monster % apt-cache policy linux-image-amd64
linux-image-amd64:
  Installed: 6.5.10-1
  Candidate: 6.5.10-1
  Version table:
 *** 6.5.10-1 700
        700 http://deb.debian.org/debian testing/main amd64 Packages
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
     6.5.3-1~bpo12+1 800
        800 http://deb.debian.org/debian bookworm-backports/main amd64 Packages
     6.1.55-1 900
        900 http://deb.debian.org/debian stable/main amd64 Packages
     6.1.52-1 900
        900 http://deb.debian.org/debian-security stable-security/main amd64 Packages
```

I am now on 6.5.10-1 / 6.5.0-4, and didn't see the graphical errors.  The graphical errors were present on 6.1.55-1 / 6.1.0-13.

Oddly enough it did still hang plasmashell and crash discord, but I suppose that could be an issue with those programs.

New logs: 
[latest.log](https://github.com/AllTheMods/ATM-9/files/13476749/latest.log)

**Comment by stephen-smith** [comment]
The graphical errors are back, even with the 6.5.10-1 kernel.  I don't have anything newer available from my OS vendor.

![2023-11-27_23 13 56](https://github.com/AllTheMods/ATM-9/assets/283443/fa854883-7d1e-4848-901d-6d21186caeaf)

Logs, of course: [latest.log](https://github.com/AllTheMods/ATM-9/files/13483792/latest.log)

**Comment by stephen-smith** [comment]
Removing Oculus prevents the crazy, mistextured triangles in the sky and significantly reduces freezes.

**Comment by aAndrew3030** [comment]
The pack just updated with forge version 47.2.8. This version of forge includes some graphics fixes that may or may not help. Also of note, Rubidium Extra was replaced with Embedium++
