### ISSUE TITLE
Fission reactor recipe issue?

### ISSUE THREAD

**Issue by Queen4Eternity** [AllTheMods/ATM-9#892]
My fission reactor won't let me put a radioactive bee spawn egg into it and I therefore can't get the protactinium bee spawn egg.

**Comment by GothBoyUK** [comment]
Neither of the reactors will accept bee eggs. If you try to force it, by shift clicking, the fusion reactor will actual wipe the egg's NBT data and make it blank! I've lost hours of work to it. 🙄
