### ISSUE TITLE
Solo/Shared FTBQuest progression

### ISSUE THREAD

**Issue by kalmantoth** [AllTheMods/ATM-9#895]
In a FTBTeams party the FTBQuest progression is shared so the quests cant be solo progressed by the invidual team members.
It would be nice if there was an option to set the quest progression to be **Solo** or **Team** based.

**Comment by alfredggttv** [comment]
This can be changed in the settings menu for the team, or in the config.

**Comment by dsf3449** [comment]
@alfredggttv where is the setting? I don't see it in

**Comment by elKevaso** [comment]
there aren't settings for change it
