### ISSUE TITLE
Piglich ticking entity crash

### ISSUE THREAD

**Issue by bigtruckin78** [AllTheMods/ATM-9#898]
I spawned some piglich's using an enderIO powered spawner in a hyperbox. I was using a Industrial Forgoing mob crusher and it was killing them as soon as they spawned and there was no problem. The issue occurred when I turned the mob crusher off and the piglich were free to rome about. All of a sudden my game crashed. It crashes every time I try to load into it giving the same ticking entity error. The only other thing I recently changed was, made a piglich charm from Apotheosis and was wearing it. I've attached a copy of the crash report. [](url)  
[crash-2023-11-27_23.53.25-server.txt](https://github.com/AllTheMods/ATM-9/files/13483699/crash-2023-11-27_23.53.25-server.txt)

**Comment by Ozzymud** [comment]
Apr 2, 2024 - reliquary-1.20.1-2.0.39.1211.jar - Fixed mob charms and twilight cloak to not crash with some of the entities
