### ISSUE TITLE
Question about "The Beyond" or this might be a bug?

### ISSUE THREAD

**Issue by yutoe** [AllTheMods/ATM-9#901]
Is the Beyond supposed to be all black for the sky and slightly glitchy when the sun is setting? Playing on 0.2.23
![2023-11-28_05 49 36](https://github.com/AllTheMods/ATM-9/assets/1342774/717c7ad1-6f08-44a2-8d4c-a514b3be6417)
![2023-11-27_20 21 37](https://github.com/AllTheMods/ATM-9/assets/1342774/a38dec19-7b9a-4343-9b56-df1dfb94f394)
![2023-11-27_20 21 39](https://github.com/AllTheMods/ATM-9/assets/1342774/a1f185f9-7d9c-4823-be7c-79380ebbd780)

**Comment by aAndrew3030** [comment]
Do you have fog turned off?

**Comment by yutoe** [comment]
So the "Sky Colors" under "Details" in the "Video settings" is enabled and when disabling it, Fixes everything, SOOO much better
![image](https://github.com/AllTheMods/ATM-9/assets/1342774/9c8fd67d-6620-4a66-b554-b71f382fa6de)

**Comment by yutoe** [comment]
So the "Sky Colors" under "Details" in the "Video settings" is enabled and when disabling it, Fixes everything, SOOO much better
![image](https://github.com/AllTheMods/ATM-9/assets/1342774/9c8fd67d-6620-4a66-b554-b71f382fa6de)

**Comment by Shroomich** [comment]
hi. What do you mean by "under details" in the video settings? i cant find and change the setting like u did

**Comment by Trold220704** [comment]
So how did you fix it?

**Comment by thevortex** [comment]
answer to OP question is yes, that is how its supposed to look

**Comment by Trold220704** [comment]
Ah damn okay. Guess i'll try and find a shader that can cover it up then :/
