### ISSUE TITLE
Gregtech's Certus Quartz not usable in Inscriber.

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/ATM-9#903]
Currently running ATM ver 0.2.23

The Gregtech version of quartz works fine in a crafting grid but will not be accepted by the inscriber.

I go through 6+ stacks per operation so i thought blocking them was wise but now I can't use it for calculation processors / dust.

Any chance you can clamp down on all the outputs for gregtech & railcraft reborn? It's causing additional stress.

**Comment by Captn138** [comment]
Hey, I have the same problem. Did you find anything about that ? A workaround maybe ?

**Comment by Kevin-Marsh** [comment]
Gt certus and AE certus are different items with the same name. These are not compatible.
