### ISSUE TITLE
Keybind issue after update.

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-9#908]
In version 0.2.22 I had:
Open Super Wireless Grid set to Tab
And 
Switch Super Wierless Grid Mode set to Shift+Tab
And it worked perfectly Switching mode with Shift tab and opening it with just tab.
With the upgrade to 0.2.23 and now with 0.2.24 shift tab switches and opens it at the same time forcing me to close it to go to the next setting. Preventing me from rapidly switching through them. Any idea how I can fix this?

**Comment by aAndrew3030** [comment]
This was fixed in forge version 47.2.14

**Comment by aAndrew3030** [comment]
Fixed in version 2.25 of the pack
