### ISSUE TITLE
Destruction Gadget can bypass claims

### ISSUE THREAD

**Issue by DigBatt** [AllTheMods/ATM-9#909]
The destruction gadget from building gadgets 2 is able to bypass claims.

**Comment by aAndrew3030** [comment]
I believe this is known... claims cant (and wont) protect against all modded items. You can remove the destruction gadget recipe with kubejs (and delete them all with commands)

kubejs>server_scripts>mods>buidlinggadgets>recipes.js and duplicate the event.remove line and change the id to reflect the destruction gadget
