### ISSUE TITLE
Problem with loading Save

### ISSUE THREAD

**Issue by Egos90** [AllTheMods/ATM-9#910]
I've problem with starting my world. Loading screen stop at 100% and freeze. To run the game i've to restore some backup. Sometimes it's realy old one. About 2-3 hours earlier. In these time only things I do is about Minecolony.

Here is some log:

[latest.log](https://github.com/AllTheMods/ATM-9/files/13512840/latest.log)

**Comment by BroPayton** [comment]
idk maybe you will find some luck at https://github.com/AllTheMods/ATM-9/issues/1014
