### ISSUE TITLE
Conflict between Inventory Essentials and Mouse Tweaks/Inventory Profiles Next

### ISSUE THREAD

**Issue by FilGoodInc** [AllTheMods/ATM-9#912]
**Infos:**
- ATM9 Version 0.2.24
- Inventory Essentials (8.2.1) - Feature name is _Hold shift click and move over items_
- Mouse Tweaks (2.25) - Feature name is _LMB Tweak_
- Inventory Profiles Next (1.10.9) - Feature name is _Swipe Moving Items From the Container_

**Problem:**
All three mod conflict with each others when it comes to the feature:

> Hold shift click and move over items to quick-move them without having to click each individually

It simply stop working if Inventory Essentials is installed (no matter if you disable the feature from the other 2 mods or not).

**Fix:**
Uninstalling only Inventory Essentials on the client fixes the problem.
Can also uninstall both other mods but they have more features.

**Comment by aAndrew3030** [comment]
This was a forge bug that was fixed in forge version 47.2.14

**Comment by aAndrew3030** [comment]
Should be fixed in version 2.25 of the pack
