### ISSUE TITLE
beekeeper in JEI texture is missing

### ISSUE THREAD

**Issue by Jarrettmitchener** [AllTheMods/ATM-9#913]
entity.minecraft.villager.beekeeper has a missing texture inside JEI. Texture is still seen on in game villager, so seems possibly relating to JEI
version 0.2.25
![image](https://github.com/AllTheMods/ATM-9/assets/77806941/ba25e065-14f8-4dfc-ad43-71edbb10e696)

**Comment by robinfrt** [comment]
Same problem here. Playing Create Haven modpack

**Comment by Kevin-Marsh** [comment]
This bug is no longer present.

**Comment by darthvader45** [comment]
Found this again in 1.20.1, using Forge 47.3.1 and JEI 15.3.0.8 for 1.20.1.  Happens for all villager professions, doesn't happen for wandering trader.
