### ISSUE TITLE
Laser io shader 

### ISSUE THREAD

**Issue by Powermania321** [AllTheMods/ATM-9#921]
Laser from laser Io is too bright with shaders
![2023-12-02_13 47 39](https://github.com/AllTheMods/ATM-9/assets/125279479/b954595f-d6ba-4bf8-8347-c79c77e0d47b)

**Comment by ninjassassin911** [comment]
I totally agree. It's so bright that it's unusable.

**Comment by derekmurawsky** [comment]
This also happens with mining gadgets. It's an upstream issue w/ the shader, I think. At least, I've seen this issue reported in many areas with little on a real solution. 
https://github.com/Asek3/Oculus/issues/393 - Not sure if this pack uses Oculus, but this is an example. 
Suggestions are basically disable bloom, lower light intensity settings where possible (like with mining gadget), etc.

**Comment by Lord-Volkner** [comment]
The mining gadget is worse. The green glow fills about 2/3rd of the screen, making it pretty much unusable.

The only way to fix it is to turn shaders off.

**Comment by djnifos** [comment]
turn bloom off
