### ISSUE TITLE
[ATM 9} 0.2.25 

### ISSUE THREAD

**Issue by GiGDDragon** [AllTheMods/ATM-9#929]
Blue Skies Everdawn dimension loads excessively slow on my server. Any other dimensions load fine. Havent tried the other Blue skies dimension yet.

**Comment by MaxxQc** [comment]
they're pretty laggy too, I just stopped exploring them
Maybe just blue skies issues

**Comment by kurbar** [comment]
Same problem with both Blue Skies dims - Everdawn and Everbright
