### ISSUE TITLE
Mob Yoinker Necromancer Crash 

### ISSUE THREAD

**Issue by x9Eclipse** [AllTheMods/ATM-9#931]
So i found out if you Pick up a Necromancer from Iron Spells and Spellbooks in a Mobyoinker and try to release it, to put it into a Containment Jar ( Ars). It will crash the game. It works fine if you lure the necromancer there so im guessing it has something to do with the mob yoinker.

Game version is 0.2.25

**Comment by DiggityMan420** [comment]
All the Mods 9-0.2.28 still crashes

**Comment by TheBedrockMaster** [comment]
Does this still happen now? Add crash label.

**Comment by TheBedrockMaster** [comment]
Yep, just happened to me, add crash label.
