### ISSUE TITLE
Hydrofluoric acid uses a random amount of sulfiric acid

### ISSUE THREAD

**Issue by cooljacob204** [AllTheMods/ATM-9#932]
I'm using auto crafting to produce Hydrofluoric acid and it appears to use a random amount between .088-.1b of sulfuric acid. This results in a random amount of sulfuric acid slowly building up in my machine.

![image](https://github.com/AllTheMods/ATM-9/assets/1229589/b0ac0706-76fd-48f4-b577-194cee149177)
![image](https://github.com/AllTheMods/ATM-9/assets/1229589/e7452575-6c81-4b4f-bca4-ee3eb50b30ea)

**Comment by Burkino** [comment]
This is intended by Mekanism. I know it's really stupid and annoying. The solution is probably to just constantly export sulfuric acid with a crafting upgrade, then have the crafting pattern just be fluorite.
