### ISSUE TITLE
FTB xmod compat needs an update

### ISSUE THREAD

**Issue by DillPickle31** [AllTheMods/ATM-9#933]
With the 0.2.25 update, FTB Chunks broke on my server. I use FTB Ranks and playtime to grant players ranks that give them more chunks and force loaded chunks. For many players, their claims will be shown, but will show its out of 0, example below. But while individuals have this issue, teams can still claim their chunks normally

Example: Claimed (121/0)

FTB Chunks as of today got an update
[https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/4925796](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/4925796)

![claims](https://github.com/AllTheMods/ATM-9/assets/95327650/bb22f5a2-8eb9-41db-8358-1ec2c1fedc4f)

**Comment by TheBedrockMaster** [comment]
Fixed?
