### ISSUE TITLE
ATM9 v0.2.27 Snorkel not working

### ISSUE THREAD

**Issue by Natomik** [AllTheMods/ATM-9#948]
Hello, 
I am currently playing ATM9 v0.2.27 on a server and apparently, the Snorkel is not working.
The water breathing works for only 15 sec (the initial time given by the snorkel).
Can you please fix it or change the desc?
Thank you in advance !

**Comment by KiprasJ** [comment]
Still not working as of today

**Comment by thehebrewhand** [comment]
Still only a temporary 15 seconds as of the newest release (0.2.37)

**Comment by Kevin-Marsh** [comment]
I have requested that the dev amend the tooltip. This is now over to them and I am closing this issue.
