### ISSUE TITLE
Iron's Spells n Spellbooks Necromancer high spawn rate

### ISSUE THREAD

**Issue by ZymmiR** [AllTheMods/ATM-9#95]
Been playing on a survival world, and have noticed an unusually large spawn rate of the necromancer from iron's spells n spellbooks. I have a command set to kill them every few minutes, and it consistently kills 50+ mobs. I can go outside of my house in the middle of the minecraft night and find like 3 or 4 around me. Wouldnt be an issue if they werent really strong and healed. 

Also they continue to spawn when I change the difficulty to peaceful, but just wont attack me.

**Comment by john13210** [comment]
not only they spawn like crazy but also lag the server for some reason
