### ISSUE TITLE
Version 1.20.1-1.1 - ATM9 - Dank not keeping filtering options when emptied

### ISSUE THREAD

**Issue by GoddessTT** [AllTheMods/ATM-9#950]
Issue: When you mouse + ctrl over a slot that has items in it, then empty the dank it in theory it is suppose to when filled again, putting whatever was there before back in that spot. When filled the dank is just putting random items in the the slots slated for specific items. This has been confirmed by several people on our server. It doesn't matter if it is manual or using the dank cradle, it literally sucks everything out.

The image with all the items filtered and nothing it, was just ran through the dank dock and emptied. When attempting to receive items into it, it just randomly put it somewhere, i.e. the enderpearl x3. The very last pic with the enderpearl in the very first row near end where it is to be, was a manual me dropping it and picking it up after it being docked and NOT emptied (there was nothing to empty). I did it again, put something in it, docked it, emptied it, and again it would not follow the filtering rules. The filtering rules are being broken when it is put on the dock and emptied. This has been repro'd multiple times on a variety of machines but all running the same version 1.20.1-1.1 - ATM9.

![image](https://github.com/AllTheMods/ATM-9/assets/40719616/e3e64967-83b7-46b5-81b8-b48db4cc81cd)

![image](https://github.com/AllTheMods/ATM-9/assets/40719616/7e7e5ee7-1831-4bd2-9e0e-3d0f47f5fe0a)

![image](https://github.com/AllTheMods/ATM-9/assets/40719616/6d1f1b99-472d-4935-9b29-f526a18a09b3)

**Comment by Cybersnowfox** [comment]
Yeah i also have issues with it

**Comment by GoddessTT** [comment]
> Yeah i also have issues with it

Still? If so, open a ticket and reference this one.
