### ISSUE TITLE
Ender Dragon and Wither Data Models missing/broken

### ISSUE THREAD

**Issue by BrettMoan** [AllTheMods/ATM-9#962]
It seems that somewhere between 0.2.24 and 0.2.28 the data models for the ender dragon and wither have been corrupted. Not sure if these were intentionally removed as i didn't see mention of it in the patch notes, so just in case its a bug I'm raising the issue.

**Comment by TheDude1134** [comment]
Can confirm, already made dragon and wither models are now broken

**Comment by KE7FNS** [comment]
There are a few more than just the two you reported.  I had 7 broken data models in my storage system.  Not sure which ones exactly they all are, but I suspect its related to the recent changes.

**Comment by TheDude1134** [comment]
Yeah it seems quite a few of the models are now missing from JEI as well as corrupted in game.

**Comment by BrettMoan** [comment]
creating a new world seems to also have the same issue, so it doesn't seem to be related to updating

**Comment by slimeinacloak** [comment]
Happened for me too, seems to the 7 models defined in /kubejs/data/hostilenetworks/data_models, so ender dragon, evoker, skeleton, warden, wither, wither skeleton and zombie.

**Comment by Mitchell5200** [comment]
Corrected in PR https://github.com/AllTheMods/ATM-9/pull/959 will be in the next pack update

**Comment by TheDude1134** [comment]
Thanks for the quick fix!

**Comment by slimeinacloak** [comment]
Updated my save using the changes made in the PR and all the models returned to normal :)

**Comment by Jophire** [comment]
Running
/hostilenetworks datafix_all
and replacing the files with the newly generated files also fixes the issue if you don't want to update to the pr.
