### ISSUE TITLE
[0.2.28] Mekanism metallurgic infuser / GregTech obsidian dust bug

### ISSUE THREAD

**Issue by HypexsparkyzZ** [AllTheMods/ATM-9#969]
When attempting to input GregTech obsidian dust into a Mekanism metallurgic infuser (with enriched diamond) it proceeds to bug back into inventory.

**Comment by johnholton0** [comment]
I wonder if this is related to the other bugs with mek machines. I've seen infusers and PRCs stop accepting materials so far. Did you discover a workaround?

**Comment by cnnrshd** [comment]
Experiencing this issue in 0.2.57 with GregTech obsidian dust.
![image](https://github.com/AllTheMods/ATM-9/assets/35985695/5bfe10a4-75bf-40b0-aadf-ebfff4f9a8bf)
