### ISSUE TITLE
[0.2.28] Server-Pack is Missing

### ISSUE THREAD

**Issue by tekook** [AllTheMods/ATM-9#970]
The Server Pack for 0.2.28 is missing, any chance to upload it? <3

**Comment by Mitchell5200** [comment]
not missing, just stuck in CF approvals, we have a manual link in discord (#atm9-help, in the pins), but i'll post it here as well
https://mediafilez.forgecdn.net/files/4938/147/Server-Files-0.2.28.zip

**Comment by tekook** [comment]
Awesome, thank u very much. It is now also approved I think. 

Kind regards
