### ISSUE TITLE
Sugarcane WHAT????

### ISSUE THREAD

**Issue by DiggityMan420** [AllTheMods/ATM-9#973]
plant sugar cane under water and it grows see pics no crash log latest version All the Mods 9-0.2.28

![Screenshot_6](https://github.com/AllTheMods/ATM-9/assets/45196448/d6929fe3-97b7-4484-8e55-98db8e41fba6)
![Screenshot_7](https://github.com/AllTheMods/ATM-9/assets/45196448/666ca0b3-d503-4df2-a37e-6d875fa02cba)

**Comment by DiggityMan420** [comment]
an checked on later it grows see pic 
![Screenshot_8](https://github.com/AllTheMods/ATM-9/assets/45196448/62372c54-bedd-4905-a234-7de4f9d118c0)

**Comment by DiggityMan420** [comment]
acting like a door i can breath in it too 
![Screenshot_9](https://github.com/AllTheMods/ATM-9/assets/45196448/421f5c22-8d34-490e-ba0f-9a8eac24108c)

**Comment by LupusSmoth** [comment]
@DiggityMan420 
![obraz_2023-12-11_114824317](https://github.com/AllTheMods/ATM-9/assets/109044881/f0960118-9e9e-48fe-8c55-2b76be966dd9)
Sorry mate but this is just normal vanilla Minecraft mechanics
