### ISSUE TITLE
[ATM9 v0.2.28] Unnecessary Ore Type Duplicates

### ISSUE THREAD

**Issue by ZilophosGH** [AllTheMods/ATM-9#974]
There are several mods which add their own unique versions of ore types already included via AllTheOres. These feel unnecessary and only serve to further add to the concern of item and world generation bloat. Do note that these unique versions will not show up in the JEI menu, but are present in the world gen.

Problem Mods:
Immersive Engineering, Eidolon Repraised

Immersive Engineering:
Lead Ore, Raw Lead
Silver Ore, Raw Silver
Bauxite Ore, Raw Bauxite (aluminum)

Eidolon Repraised:
Lead Ore, Raw Lead
Silver Ore, Raw Silver

**Comment by ProfessorBiddle** [comment]
Issue still persists in latest version as of 1/31/24
