### ISSUE TITLE
[ATM9 v0.2.28]  no mob drops 

### ISSUE THREAD

**Issue by henkoe** [AllTheMods/ATM-9#976]
after testing i found out mobs are not droping items because of deap learner from Hostile Neural Networks had broke data models 

![broken data model](https://github.com/AllTheMods/ATM-9/assets/1676268/a60b2af9-4b18-49d9-b9ed-d51ad7396f75)

**Comment by lvictor215** [comment]
The same here, Wither and dragon are broken.

**Comment by Jophire** [comment]
If you run /hostilenetworks datafix_all there is a difference in how color is represented which might be causing the issue:

New: "name_color": "#05343F",
Old: "name_color": "0x05343F",

Gonna try replacing the kubejs files with the generated outputs and see if that fixes it.

**Comment by Chifilly** [comment]
Just thought I'd mention that #962 mentioned the fix, which is in PR #959 and I can confirm that making the changes to the files in `kubejs/data/hostilenetworks/data_models` fixes the issue
