### ISSUE TITLE
Strange Water Texture Flicker

### ISSUE THREAD

**Issue by SumRando1994** [AllTheMods/ATM-9#978]
When used in conjunction with Complementary Shaders Unbound, water texture glitches. Appears to be related to angle of viewing and the wave action of the water (water seems to move like a strobe light).
![2023-12-10_12 00 28](https://github.com/AllTheMods/ATM-9/assets/46729322/0d9629b0-a1c3-41f8-b769-2338aa240890)

**Comment by DragonsKeep89** [comment]
This also happens with Reimagined

**Comment by TheOneLazyFox** [comment]
Apparently people on Reddit found this to be a clash between oculus and nature's aura because you can see it with shaders off as well

**Comment by dixonj2022** [comment]
https://github.com/AllTheMods/ATM-9/assets/19805611/3e20c39e-4304-48dc-93ef-1f358825541a

Here's it happening without shaders.

**Comment by Danwo0** [comment]
Is there an update on this issue? Still seeing this issue.

**Comment by roboboredom** [comment]
This is happening for me at certain random times and angles when facing the water. Latest pack version as of 3/7/2024. Standard graphics, shaders off, MIPMAP LEVEL 4. Nvidia GPU.

**Comment by roboboredom** [comment]
Lets goo!! :)

**Comment by erdopfi** [comment]
![2024-05-09_13 44 39](https://github.com/AllTheMods/ATM-9/assets/66178444/9d8d8f8b-2517-467d-8fe3-940cf1698f91)
Still existing in the newest version
