### ISSUE TITLE
[0.2.28] Seaweed does not generate, blocking almost all of Sushi Go Crafting.

### ISSUE THREAD

**Issue by AHAuwuOK** [AllTheMods/ATM-9#979]
**Steps to reproduce:**
1. Launch a world on All the Mods 9 version 0.2.28.
2. Attempt to gather seaweed in any ocean biome.

**Results:**
Seaweed cannot be found anywhere on the map or in JEI. Since nori made by crushing seaweed is required for all sushi recipes, the issue blocks almost all functionality of the mod. Dried kelp blocks cannot be used as a substitute.

**Comment by ninjassassin911** [comment]
0.2.27 has plenty of seaweed generating.

**Comment by karikusa** [comment]
You can make seaweed from Cellulose with a mod called Alchemistry!

**Comment by Kevin-Marsh** [comment]
It appears that sushigocrafting changed to use kelp that is squished in world to produce nori sheets. The Manual explains it for anyone that finds this issue.
