### ISSUE TITLE
Mystical Agriculture Seeds Disappear After Some Time

### ISSUE THREAD

**Issue by pickleheadjr** [AllTheMods/ATM-9#985]
I have a mystical agriculture farm on insanium farmland surrounded by lily pads of fertility and a harvester pylon in the middle. After some time more then half of them disappear. After the seeds disappear I can no longer place seeds in the spots without seeds anymore. (Its not a graphical issue because when I break the block where seeds used to be nothing drops besides the farmland.) Issue just started today. I'm currently on modpack version  0.2.28.

**Comment by myKrins** [comment]
Hi,
I ran into this issue too. Detected today that all my inferium seeds that were planted on insanium farmland are gone. Can't place new seeds on the farmland. I even have the issue that I can't plant some of the other seeds (e.g. pig seeds) on insanium farmland.
Setup was was waterlogged stairs and lillypads. Version 0.2.34

**Comment by myKrins** [comment]
For me it was a lightning problem. Placed a few glowstones and now I can place all the seeds.

**Comment by ShadowRL76** [comment]
Thanks, Playing atm10 and my seeds would break If I got close with a harvester pylon and lighting fixed it!
