### ISSUE TITLE
Refined Iron ingot

### ISSUE THREAD

**Issue by Merithor** [AllTheMods/ATM-9#986]
In JEI, there is no Refined Iron Ingot, as I have a Silent Gear hammer made from it (Quest Reward), but cannot repair it as it does not have a recipe, an item associated with it, and does not show up in Creative menu either.

SS of the tool.
https://imgur.com/a/aLvsdIX

**Comment by prescar** [comment]
You can repair silent gear tools with metals of the same tier, doesn't have to be the same ingot
