### ISSUE TITLE
Warp plates not generating attuned shards.

### ISSUE THREAD

**Issue by fit-dran** [AllTheMods/ATM-9#988]
First time I place a warp plate it generates the shard any other warp plate placed after that stays as a flint. Downgrading to 0.2.28 fixes it.
Tested in single player and server.

Version: 0.2.29

**Comment by andreas-k-beckman** [comment]
If you add more warp dust manually around it again, it will generate.

But any warpplate, newly made this way OR old, for me simply says the shard has lost it's attunement when I try to use them, so while you can technically get it to generate a shard it wont really help you :S

**Comment by FHoulbreque** [comment]
I can confirm this bug, experienced it. All my warp plates has gone unattuned.
