### ISSUE TITLE
[0.2.29] Enriched Iron Mekanism Bug

### ISSUE THREAD

**Issue by HypexsparkyzZ** [AllTheMods/ATM-9#990]
When trying to input enriched iron into a metallurgic infuser with carbon in it. It refuses to accept the item and puts it back into player's inventory.

**Comment by aobrem** [comment]
I have this issue too. It happens with or without carbon. Enriched iron doesn't go in, nor can it be piped in.

**Comment by Hirsu** [comment]
Here to give this a +1. Enriched iron is pushed straight back to player inventory.

**Comment by johnholton0** [comment]
I'm also encountering this issue in my ATM9 world. Alloying iron in any version of an infuser simply stopped working. Items will go in, but nothing is made. In addition, my PRC stopped functioning while making plutonium. This happened after I logged out and came back to it. Machine that had previously been working simply stopped accepting inputs. Fluorite dust gets kicked back to user inventory.

**Comment by aobrem** [comment]
This issue is fixed for me in version 0.2.32.

**Comment by johnholton0** [comment]
> This issue is fixed for me in version 0.2.32.

@aobrem Our server patched up to .32 and my machines started working as well. No specific fix mentioned in patch notes, so we'll see if they stay fixed.

**Comment by Daschi1** [comment]
I have the same problem on modpack version 0.2.34, the metallurgic infuser won't accept the Enriched Iron.

**Comment by Bultjer** [comment]
1.20.1 - 0.2.34
The Metallurgic Infuser refuses Infused Alloy with Diamonds as extra, to craft Reinforced Alloy.
When inserting the Infused Alloy per cursor action, it places the Infused Alloy in the machine and immediately back to the curser.
When inserting the Infused Alloy per shift + left click, it puts the Infused Alloy in the right slot in the Metallurgic Infuser and then immediately puts it back into the inventory.

Reloading (/reload) crashed the server, everything worked as intended afterwards.

**Comment by Daschi1** [comment]
> I have the same problem on modpack version 0.2.34, the metallurgic infuser won't accept the Enriched Iron.

I have since restarted the server, and it works again.
