### ISSUE TITLE
Magentite Bee spawn egg don´t converte to Ridiculite Bee spawn egg

### ISSUE THREAD

**Issue by Arnaen** [AllTheMods/ATM-9#992]
Mode version 0.2.28 (server) (no changes)

my Magentite Bee spawn egg don't converte to Ridiculite Bee spawn egg by a Ludicrite Bee.

![grafik](https://github.com/AllTheMods/ATM-9/assets/30075335/c3d8405d-e1e1-4770-95a3-a44bcf6eae0a)

![grafik](https://github.com/AllTheMods/ATM-9/assets/30075335/02d0f60f-14c4-4dfd-80b9-1cf99776ab82)

![grafik](https://github.com/AllTheMods/ATM-9/assets/30075335/499dcc92-119e-457f-9a87-f403c4022220)

![grafik](https://github.com/AllTheMods/ATM-9/assets/30075335/b848ae99-540f-4699-b230-1835ff9ccd5e)

the previous conversions have worked well.

thanks for your help

**Comment by Queen4Eternity** [comment]
Maybe try temporarily taking out the other block so the bees have no other choice but to convert the spawn egg rather than pollinate the block?

**Comment by Arnaen** [comment]
I have tried everything possible.
With and without a block. In and outside the hive, directly in the world without a hive. Throwing the eggs in the world onto the block and much more, nothing worked.

**Comment by GothBoyUK** [comment]
Have you also tried without any simulation or productivity upgrades in the hive? When I was converting other eggs the bees needed to leave the hive and dance over the egg (in a feeding slab) until the new converted egg popped out. I used a modular router with a vacuum augment to pick up the new egg. 

What I also observed is that there remains a 'ghost egg' in the feeding slab after conversion occurs. It doesn't really exist, so unless I had been close to the hive and with a magnet switched on the new egg would have despawned. I wouldn't have known conversion had already happened and couldn't happen again as the original egg no longer existed. If you haven't already tried using the method I suggested it may be worth a go. Good luck.

**Comment by Arnaen** [comment]
Thank you, I have already tried the method and even after 10 minutes in the open air the bee was not interested in the spawegg or the slap.
but i will try it again.

**Comment by Arnaen** [comment]
Everything works again after the update to 0.2.31.
Thanks for the help

**Comment by LB1177** [comment]
I'm also having trouble with the same thing. I've tried everything mentioned in the earlier comments and no matter what I do, the bees won't even show any interest in the egg/feeding slab unless the ludicrite block is on it but then they still don't convert the egg into ridiculite so idk if it's bugged again but I can't seem to figure it out
